{
 "title": "Kubernetes Cluster Autoscaler (via Prometheus)",
 "description": "Super simple dashboard showing an overview of kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to prometheus.\r\n\r\nhttps://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_namespace_created, source_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{source_cluster=~\"$cluster\"})\n"
    }
   ]
  },
  {
   "title": "Nodes available",
   "type": "singlestat",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\", source_cluster=~\"$cluster\"})/sum(cluster_autoscaler_nodes_count{source_cluster=~\"$cluster\"})*100"
    }
   ]
  },
  {
   "title": "Is cluster safe to scale?",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale{source_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of unscheduled pods",
   "type": "singlestat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{source_cluster=~\"$cluster\"})",
     "legendFormat": " pods"
    }
   ]
  },
  {
   "title": "Last scaleDown activity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"scaleDown\", source_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Last autoscale activity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"autoscaling\", source_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pod activity",
   "type": "graph",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Num Pods" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{source_cluster=~\"$cluster\"})",
     "legendFormat": "unscheduled pods"
    }
   ]
  },
  {
   "title": "Failed scale up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(cluster_autoscaler_failed_scale_ups_total{source_cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Num nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{source_cluster=~\"$cluster\"})",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{source_cluster=~\"$cluster\"})\n",
     "legendFormat": "total nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\", source_cluster=~\"$cluster\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"unready\", source_cluster=~\"$cluster\"})",
     "legendFormat": "unready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"notStarted\", source_cluster=~\"$cluster\"})",
     "legendFormat": "not started"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_kops_k8s_io_instancegroup=~\".*master.*\", source_cluster=~\"$cluster\"}) by (label_beta_kubernetes_io_instance_type)"
    },
    {
     "expr": "count(kube_node_labels{label_kops_k8s_io_instancegroup=~\".*spot.*\", source_cluster=~\"$cluster\"}) by (label_beta_kubernetes_io_instance_type,label_kops_k8s_io_instancegroup)"
    },
    {
     "expr": "count(kube_node_labels{label_kops_k8s_io_instancegroup!~\".*spot.*|.*master.*\", source_cluster=~\"$cluster\"}) by (label_beta_kubernetes_io_instance_type,label_kops_k8s_io_instancegroup)"
    }
   ]
  }
 ]
}