{
 "title": "Trino Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Deployment Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Counts",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\", namespace=\"data-platform\", pod=~\"trino-coordinator.*\"})",
       "legendFormat": "Coordinator Ready Count "
      },
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\", namespace=\"data-platform\", pod=~\"trino-worker-.*\"})",
       "legendFormat": "Worker Ready Count "
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coordinator CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"data-platform\", container=\"trino-coordinator\", container!=\"POD\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "topk(1, kube_pod_container_resource_limits_cpu_cores{namespace=\"data-platform\", container=\"trino-coordinator\"})",
       "legendFormat": "CPU Limit"
      }
     ]
    },
    {
     "title": "Worker CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"data-platform\", container=\"trino-worker\", container!=\"POD\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "topk(1, kube_pod_container_resource_limits_cpu_cores{namespace=\"data-platform\", container=\"trino-worker\"})",
       "legendFormat": "CPU Limit"
      }
     ]
    },
    {
     "title": "Coordinator Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=\"data-platform\", container=\"trino-coordinator\", container!=\"POD\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "topk(1, kube_pod_container_resource_limits_memory_bytes{namespace=\"data-platform\", container=\"trino-coordinator\", container!=\"POD\"})",
       "legendFormat": "Memory Limit"
      }
     ]
    },
    {
     "title": "Worker Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=\"data-platform\", container=\"trino-worker\", container!=\"POD\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "topk(1, kube_pod_container_resource_limits_memory_bytes{namespace=\"data-platform\", container=\"trino-worker\", container!=\"POD\"})",
       "legendFormat": "Memory Limit"
      }
     ]
    }
   ]
  }
 ]
}