{
 "title": "hotstar-rename-http-metric",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Lag",
   "type": "timeseries",
   "description": "Pending Bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(http_requests_duration_milliseconds_bucket{program=~\"leve.*\", per=~\"write.*|publish.*\",l9cluster=~\"b290d3f4-3464-466f-ab8b-da902620aea7\"}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(http_requests_duration_milliseconds_bucket{program=~\"leve.*\",per=~\"query.*\",l9cluster=~\"b290d3f4-3464-466f-ab8b-da902620aea7\"}[1m])) by (le)) / 1000",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(http_requests_duration_milliseconds_bucket{program=~\"leve.*\",per=~\"query.*\",l9cluster=~\"b290d3f4-3464-466f-ab8b-da902620aea7\"}[1m])) by (le)) / 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(http_requests_duration_milliseconds_bucket{program=~\"leve.*\",per=~\"query.*\",l9cluster=~\"b290d3f4-3464-466f-ab8b-da902620aea7\"}[1m])) by (le)) / 1000",
     "legendFormat": "p90"
    }
   ]
  },
  { "title": "hotstar vmagent prod metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "hotstar vmagent remote write saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n  rate(vmagent_remotewrite_send_duration_seconds_total{job=~\".*\", instance=~\".*\", source_cluster=~\".*\", url=\"2:secret-url\"}[4m0s])\n  /\n  vmagent_remotewrite_queues{job=~\".*\", instance=~\".*\", source_cluster=~\".*\", url=\"2:secret-url\"}\n) by(job, url, source_cluster)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hotstar vmagent remote write queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(\n  vmagent_remotewrite_queues{job=~\".*\", instance=~\".*\", source_cluster=~\".*\", url=\"2:secret-url\"}\n) by(job, url, source_cluster)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hotstar vmagent memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    max_over_time(process_resident_memory_bytes{job=~\".*\", instance=~\".*\",source_cluster=~\".*\"}[4m0s])\n    /\n    vm_available_memory_bytes{job=~\".*\", instance=~\".*\",source_cluster=~\".*\"}\n) by(job, source_cluster)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hotstar vmagent cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    rate(process_cpu_seconds_total{job=~\".*\", instance=~\".*\", source_cluster=~\".*\"}[4m0s])\n    /\n    vm_available_cpu_cores{job=~\".*\", instance=~\".*\", source_cluster=~\".*\"}\n) by(job, source_cluster)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "current cardinality: bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "http_server_requests_seconds_bucket",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(http_server_requests_seconds_bucket{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get_page_http_server_requests_seconds_bucket",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(get_page_http_server_requests_seconds_bucket{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "page_comp_http_server_requests_seconds_bucket",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_http_server_requests_seconds_bucket{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get_widget_http_server_requests_seconds_bucket",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(get_widget_http_server_requests_seconds_bucket{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "start_http_server_requests_seconds_bucket",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(start_http_server_requests_seconds_bucket{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "page_comp_gql_resolver_latency_bucket",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_gql_resolver_latency_bucket{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "current cardinality: sum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "http_server_requests_seconds_sum",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(http_server_requests_seconds_sum{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get_page_http_server_requests_seconds_sum",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(get_page_http_server_requests_seconds_sum{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "page_comp_http_server_requests_seconds_sum",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_http_server_requests_seconds_sum{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get_widget_http_server_requests_seconds_sum",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(get_widget_http_server_requests_seconds_sum{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "start_http_server_requests_seconds_bucket",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(start_http_server_requests_seconds_sum{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "page_comp_gql_resolver_latency_sum",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_gql_resolver_latency_sum{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "current cardinalaity: count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "http_server_requests_seconds_count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(http_server_requests_seconds_count{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get_page_http_server_requests_seconds_count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(get_page_http_server_requests_seconds_count{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "page_comp_http_server_requests_seconds_count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_http_server_requests_seconds_count{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get_widget_http_server_requests_seconds_count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(get_widget_http_server_requests_seconds_count{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "start_http_server_requests_seconds_count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(start_http_server_requests_seconds_count{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "page_comp_gql_resolver_latency_count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_gql_resolver_latency_count{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get_page_*",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "get_page_http_server_requests_seconds_bucket_overall",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "count(last_over_time(get_page_http_server_requests_seconds_bucket{}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "get_page_http_server_requests_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "count(last_over_time(get_page_http_server_requests_seconds_bucket{}[1m])) by (service, source_cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "get_page_http_server_requests_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "count(last_over_time(get_page_http_server_requests_seconds_sum{}[1m])) by (service, source_cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "get_page_http_server_requests_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "count(last_over_time(get_page_http_server_requests_seconds_count{}[1m])) by (service, source_cluster)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "get_widget_*", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "get_widget_http_server_requests_seconds_bucket_overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "count(last_over_time(get_widget_http_server_requests_seconds_bucket{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get_widget_http_server_requests_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "count(last_over_time(get_widget_http_server_requests_seconds_bucket{}[60m])) by (service, source_cluster)",
     "legendFormat": "last- {{service}}, {{source_cluster}}"
    }
   ]
  },
  {
   "title": "get_widget_http_server_requests_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "count(last_over_time(get_widget_http_server_requests_seconds_count{}[1m])) by (service, source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get_widget_http_server_requests_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "count(last_over_time(get_widget_http_server_requests_seconds_sum{}[1m])) by (service, source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "page_comp_*", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "page_comp_http_server_requests_seconds_bucket_overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_http_server_requests_seconds_bucket{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "page_comp_http_server_requests_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_http_server_requests_seconds_bucket{}[1m])) by (service, source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "page_comp_http_server_requests_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_http_server_requests_seconds_count{}[1m])) by (service, source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "page_comp_http_server_requests_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "count(last_over_time(page_comp_http_server_requests_seconds_sum{}[1m])) by (service, source_cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_* overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "range_per_service_http_server_requests_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "count(last_over_time(http_server_requests_seconds_bucket{}[1m])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "instant_per_service_http_server_requests_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "count(last_over_time(http_server_requests_seconds_bucket{}[1m])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "overall_http_server_requests_seconds_bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "count(last_over_time(http_server_requests_seconds_bucket{}[15m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "instant_per_service_http_server_requests_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "count(last_over_time(http_server_requests_seconds_count{}[1m])) by (service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "overall_http_server_requests_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "count(last_over_time(http_server_requests_seconds_count{}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}