{
 "title": "EKS Node Utilisation - DC Level V1",
 "description": "Provisioned cluster capacity",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "datacenter",
    "label": "datacenter",
    "query": {
     "query": "label_values(kube_node_info, datacenter)"
    }
   },
   { "name": "max_usage", "label": "max_usage", "query": "95,90,85,80,75,70,60,50" }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"})"
    }
   ]
  },
  {
   "title": "Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", condition=\"Ready\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Not Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"}) - count(kube_node_status_condition{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", condition=\"Ready\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Allocated CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1))"
    }
   ]
  },
  {
   "title": "Used CPU %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) * 100) / sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"}) / (1024 * 1024 * 1024)"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) / (1024 * 1024 * 1024), 0.1)"
    }
   ]
  },
  {
   "title": "Used Memory %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) / (1024 * 1024 * 1024), 0.1) * 100) / (sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"}) / (1024 * 1024 * 1024))"
    }
   ]
  },
  {
   "title": "Karpenter Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Karpenter Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"}) by (node))"
    }
   ]
  },
  {
   "title": "Karpenter Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", condition=\"Ready\", status=\"true\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"})"
    }
   ]
  },
  {
   "title": "Karpenter Not Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"}) by (node)) - count(kube_node_status_condition{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", condition=\"Ready\", status=\"true\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"})"
    }
   ]
  },
  {
   "title": "Karpenter Allocated CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"})"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1) and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"})"
    }
   ]
  },
  {
   "title": "Used CPU %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1) and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"}) * 100) / sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"})"
    }
   ]
  },
  {
   "title": "Karpenter Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"}) / (1024 * 1024 * 1024)"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1) and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"}) / (1024 * 1024 * 1024), 0.1)"
    }
   ]
  },
  {
   "title": "Used Memory %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1) and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"}) / (1024 * 1024 * 1024), 0.1) * 100) / (sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_karpenter_sh_nodepool!=\"\"}) / (1024 * 1024 * 1024))"
    }
   ]
  },
  {
   "title": "EKS Node Group Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Group Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"}) by (node))"
    }
   ]
  },
  {
   "title": "Node Group Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", condition=\"Ready\", status=\"true\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"})"
    }
   ]
  },
  {
   "title": "Node Group Not Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"}) by (node)) - count(kube_node_status_condition{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", condition=\"Ready\", status=\"true\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"})"
    }
   ]
  },
  {
   "title": "Node Group Allocated CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"})"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1) and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"})"
    }
   ]
  },
  {
   "title": "Used CPU %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1) and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"}) * 100) / sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"})"
    }
   ]
  },
  {
   "title": "Node Group Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"}) / (1024 * 1024 * 1024)"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1) and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"}) / (1024 * 1024 * 1024), 0.1)"
    }
   ]
  },
  {
   "title": "Used Memory %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1) and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"}) / (1024 * 1024 * 1024), 0.1) * 100) / (sum(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(node) kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", label_eks_amazonaws_com_nodegroup!=\"\"}) / (1024 * 1024 * 1024))"
    }
   ]
  },
  {
   "title": "Resource Usage Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU and Memory Underutilization < $max_usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} and on(node) (((sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} < $max_usage) and on(node) (sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} < $max_usage)"
    },
    {
     "expr": "kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(node) (((sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} < $max_usage) and on(node) (sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} < $max_usage)"
    },
    {
     "expr": "round(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} / (1024 * 1024 * 1024), 0.1) and on(node) (((sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} < $max_usage) and on(node) (sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} < $max_usage)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) and on(node) (((sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} < $max_usage) and on(node) (sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} < $max_usage)"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) / (1024 * 1024 * 1024), 0.1) and on(node) (((sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} < $max_usage) and on(node) (sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} < $max_usage)"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(node) (((sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} < $max_usage) and on(node) (sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} < $max_usage)"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) / (1024 * 1024 * 1024), 0.1) * 100 / on(node) group_left() (kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} / (1024 * 1024 * 1024)) and on(node) (((sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} < $max_usage) and on(node) (sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} < $max_usage)"
    }
   ]
  },
  {
   "title": "Node Usage - Resource Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"}"
    },
    {
     "expr": "kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"}"
    },
    {
     "expr": "round(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} / (1024 * 1024 * 1024), 0.1)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node)"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) / (1024 * 1024 * 1024), 0.1)"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"}"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) / (1024 * 1024 * 1024), 0.1) * 100 / on(node) group_left() (kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} / (1024 * 1024 * 1024))"
    }
   ]
  },
  {
   "title": "Node Usage - Resource Limits",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"}"
    },
    {
     "expr": "kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"}"
    },
    {
     "expr": "round(kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} / (1024 * 1024 * 1024), 0.1)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node)"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_limits{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) / (1024 * 1024 * 1024), 0.1)"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"}"
    },
    {
     "expr": "round(sum(kube_pod_container_resource_limits{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) / (1024 * 1024 * 1024), 0.1) * 100 / on(node) group_left() (kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} / (1024 * 1024 * 1024))"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Group by Zone",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "count(kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"}) by (label_topology_kubernetes_io_zone)",
     "legendFormat": "{{ label_beta_kubernetes_io_instance_type }}"
    }
   ]
  },
  {
   "title": "Group by Instance Type",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "count(kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"}) by (label_beta_kubernetes_io_instance_type)",
     "legendFormat": "{{ label_beta_kubernetes_io_instance_type }}"
    }
   ]
  },
  {
   "title": "Group by Nodepool",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "count(kube_node_labels{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"}) by (label_karpenter_sh_nodepool)",
     "legendFormat": "{{ label_beta_kubernetes_io_instance_type }}"
    }
   ]
  },
  {
   "title": "Pod Density",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "count(kube_pod_info{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"}) by (node)"
    }
   ]
  },
  {
   "title": "Pod Density [w/o DaemonSet]",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "count(kube_pod_info{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", created_by_kind!=\"DaemonSet\"}) by (node)"
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "karpenter_nodes_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource_type=\"cpu\"}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node CPU Utilization [Pod Requests]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) * 100) / on(node) group_left() kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"cpu\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization [Pod Requests]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(kube_pod_container_resource_requests{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} and on(pod) (kube_pod_container_status_running{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\"} == 1)) by (node) / (1024 * 1024 * 1024), 0.1) * 100 / on(node) group_left() (kube_node_status_allocatable{datacenter=\"$datacenter\", source_cluster=~\"hs-eks.*\", resource=\"memory\"} / (1024 * 1024 * 1024))",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}