{
 "title": "Load Shedder Build Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "MetricPrefix", "label": "MetricPrefix", "query": { "query": "label_values(__name__)" } },
   {
    "name": "datacenter",
    "label": "datacenter",
    "query": {
     "query": "label_values(${MetricPrefix}_loadshedder_limit, datacenter)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(${MetricPrefix}_loadshedder_limit{datacenter=~\"${datacenter}\"}, service)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(${MetricPrefix}_loadshedder_limit{service=\"${service}\",datacenter=~\"${datacenter}\"}, pod)"
    }
   },
   {
    "name": "Partition",
    "label": "Partition",
    "query": {
     "query": "label_values(${MetricPrefix}_loadshedder_limit{service=\"${service}\",datacenter=~\"${datacenter}\"}, partition)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Metrics By Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall Rejections-${MetricPrefix}",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call_total{status=~\"rejected\"}[$__rate_interval])) by (service) ",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call{status=~\"rejected\"}[$__rate_interval])) by (service) ",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Load Shedder Global Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Global Request Status Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(${MetricPrefix}_loadshedder_limit{pod_name=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call_total{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\"}[$__range])) by (status)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "max(${MetricPrefix}_loadshedder_limit{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"global\"})",
     "legendFormat": "Limit[Go]"
    },
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"global\"}[$__range])) by (status)",
     "legendFormat": "{{status}}[Go]"
    }
   ]
  },
  {
   "title": "Global Request Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call_total{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\"}[$__rate_interval])) by (status) ",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"global\"}[$__rate_interval])) by (status) ",
     "legendFormat": "{{status}}[Go]"
    }
   ]
  },
  {
   "title": "Global Request Count ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(${MetricPrefix}_loadshedder_limit{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(${MetricPrefix}_loadshedder_inflight{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"\"})",
     "legendFormat": "InFlight"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\", uri!=\"/health\"}[$__rate_interval]))",
     "legendFormat": "Total Load"
    },
    {
     "expr": "max(${MetricPrefix}_loadshedder_limit{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"global\"})",
     "legendFormat": "Limit[Go]"
    },
    {
     "expr": "sum(${MetricPrefix}_loadshedder_inflight{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"global\"})",
     "legendFormat": "InFlight[Go]"
    }
   ]
  },
  {
   "title": "Global Metrics By Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rejected Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call_total{pod=~\"$Pod\",datacenter=~\"$datacenter\",status=\"rejected\",service=\"$service\"}[$__rate_interval])) by (pod) ",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",status=\"rejected\",partition=\"global\"}[$__rate_interval])) by (pod) ",
     "legendFormat": "{{pod}}[Go]"
    }
   ]
  },
  {
   "title": "Success Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call_total{pod=~\"$Pod\",datacenter=~\"$datacenter\",status=\"success\",service=\"$service\"}[$__rate_interval])) by (pod) ",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",status=\"success\",partition=\"global\"}[$__rate_interval])) by (pod) ",
     "legendFormat": "{{pod}}[Go]"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call_total{pod=~\"$Pod\",datacenter=~\"$datacenter\",status=\"failure\",service=\"$service\"}[$__rate_interval])) by (pod) ",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(increase(${MetricPrefix}_loadshedder_call{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",status=\"failure\",partition=\"global\"}[$__rate_interval])) by (pod) ",
     "legendFormat": "{{pod}}[Go]"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${MetricPrefix}_loadshedder_inflight{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(${MetricPrefix}_loadshedder_inflight{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"global\"}) by (pod)",
     "legendFormat": "{{pod}}[Go]"
    }
   ]
  },
  {
   "title": "Global Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(${MetricPrefix}_loadshedder_limit{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(${MetricPrefix}_loadshedder_limit{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=\"global\"}) by (pod)",
     "legendFormat": "{{pod}}[Go]"
    }
   ]
  },
  {
   "title": "Total Load [Java Only]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\", uri!=\"/health\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Load Shedder Partition Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Status Count By Partition",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(${MetricPrefix}_loadshedder_partition_limit{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"})",
       "legendFormat": "{{partition}}_limit"
      },
      {
       "expr": "sum(increase(${MetricPrefix}_loadshedder_partition_call_total{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"}[$__range])) by (status, partition)",
       "legendFormat": "{{partition}}_{{status}}"
      },
      {
       "expr": "sum(increase(${MetricPrefix}_loadshedder_call{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"}[$__range])) by (status, partition)",
       "legendFormat": "{{partition}}_{{status}}[Go]"
      },
      {
       "expr": "max(${MetricPrefix}_loadshedder_limit{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"})",
       "legendFormat": "{{partition}}_limit"
      }
     ]
    },
    {
     "title": "Request Status By Partition",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(${MetricPrefix}_loadshedder_partition_call_total{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"}[$__rate_interval])) by (status, partition) ",
       "legendFormat": "{{partition}}_{{status}}"
      },
      {
       "expr": "sum(increase(${MetricPrefix}_loadshedder_call{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"}[$__rate_interval])) by (status, partition) ",
       "legendFormat": "{{partition}}_{{status}}"
      }
     ]
    },
    {
     "title": "Request Count  by Partition",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(${MetricPrefix}_loadshedder_partition_limit{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"})",
       "legendFormat": "{{partition}}_limit"
      },
      {
       "expr": "sum(${MetricPrefix}_loadshedder_partition_inflight{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"}) by (partition)",
       "legendFormat": "{{partition}}_Inflight"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\", uri!=\"/health\"}[$__rate_interval]))",
       "legendFormat": "Total Load"
      },
      {
       "expr": "max(${MetricPrefix}_loadshedder_limit{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"})",
       "legendFormat": "{{partition}}_limit"
      },
      {
       "expr": "sum(${MetricPrefix}_loadshedder_inflight{pod=~\"$Pod\",datacenter=~\"$datacenter\",service=\"$service\",partition=~\"$Partition\"}) by (partition)",
       "legendFormat": "{{partition}}_Inflight"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"$service-[^-]+-[^-]+\",datacenter=~\"$datacenter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage Per Core",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"$service-[^-]+-[^-]+\",datacenter=~\"$datacenter\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"$service-[^-]+-[^-]+\",datacenter=~\"$datacenter\"}[$__rate_interval]) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod=~\"$service-[^-]+-[^-]+\",datacenter=~\"$datacenter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}