{
 "title": "Broker Performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "P0 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg CPU IO Wait %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" }
     ]
    }
   ]
  },
  {
   "title": "Mean CPU uage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") + mean(\"usage_system\") FROM \"cpu\" WHERE (\"application\" = 'knol-broker') AND $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_user\") + mean(\"usage_system\") FROM \"cpu\" WHERE (\"application\" = 'knol-broker') AND $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "bytes_sent/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "bytes_recv/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" }
     ]
    }
   ]
  },
  {
   "title": "Network Processor Avg Utilisation %",
   "type": "graph",
   "description": "1 minus Avg Network Avg Idle %",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "SocketServer",
     "query": "SELECT 1- mean(\"Value\") FROM \"SocketServer\" WHERE (\"name\" = 'NetworkProcessorAvgIdlePercent') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NetworkProcessorAvgIdlePercent" }
     ]
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "RequestHandlerAvgIdlePercent",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"OneMinuteRate\") FROM \"RequestHandlerAvgIdlePercent\" WHERE $timeFilter GROUP BY time(1m), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes In Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "GlobalBrokerTopicMetrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesInPerSec" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"OneMinuteRate\") FROM \"RequestHandlerAvgIdlePercent\" WHERE $timeFilter GROUP BY time(1m), \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Out Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "GlobalBrokerTopicMetrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesOutPerSec" }
     ]
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "RequestChannel",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "RequestQueueSize" }
     ]
    }
   ]
  },
  {
   "title": "Response Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "RequestChannel",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ResponseQueueSize" }
     ]
    }
   ]
  },
  {
   "title": "Avg Bytes In",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "BrokerTopicMetrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesInPerSec" }
     ]
    }
   ]
  },
  {
   "title": "Avg Bytes Out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "BrokerTopicMetrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesOutPerSec" }
     ]
    }
   ]
  },
  {
   "title": "Max Bytes In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "BrokerTopicMetrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesInPerSec" }
     ]
    }
   ]
  },
  {
   "title": " Max Bytes Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "BrokerTopicMetrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesOutPerSec" }
     ]
    }
   ]
  },
  {
   "title": "Failed Produce Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_topic -> $tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BrokerTopicMetrics",
     "query": "SELECT sum(\"OneMinuteRate\") FROM \"BrokerTopicMetrics\" WHERE (\"name\" = 'FailedProduceRequestsPerSec') AND $timeFilter AND \"OneMinuteRate\" > 0.01 and topic !~ /_confluent.*/ GROUP BY time($__interval), \"hostname\", \"topic\" fill(null)",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "FailedProduceRequestsPerSec" }
     ]
    }
   ]
  },
  {
   "title": "Global Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Controller",
   "type": "graph",
   "description": "Active Controller",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "controllerMetrics",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ActiveControllerCount" }
     ]
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "controllerMetrics",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "GlobalTopicCount" }
     ]
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "controllerMetrics",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "OfflinePartitionsCount" }
     ]
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "controllerMetrics",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "GlobalPartitionCount" }
     ]
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "PartitionCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leader Count",
   "type": "graph",
   "description": "Leaders across Brokers",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "LeaderCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "graph",
   "description": "Partitions across brokers",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "PartitionCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "UnderReplicatedPartitions",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fetch Consumer Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "RequestMetrics",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "TotalTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "FetchConsumer" }
     ]
    }
   ]
  },
  {
   "title": "Produce Request Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "RequestMetrics",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "TotalTimeMs" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "Produce" }
     ]
    }
   ]
  },
  {
   "title": "Fetch Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname - Failed Fetch",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "BrokerTopicMetrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "FailedFetchRequestsPerSec" }
     ]
    },
    {
     "alias": "$tag_hostname - Fetch",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "BrokerTopicMetrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "TotalFetchRequestsPerSec" }
     ]
    }
   ]
  },
  {
   "title": "Produce Requests Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname - Failed Produce",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "BrokerTopicMetrics",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "FailedProduceRequestsPerSec" }
     ]
    },
    {
     "alias": "$tag_hostname - Produce",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "BrokerTopicMetrics",
     "query": "SELECT sum(\"OneMinuteRate\") FROM \"BrokerTopicMetrics\" WHERE (\"name\" = 'TotalProduceRequestsPerSec') AND $timeFilter GROUP BY time(1m), \"hostname\"",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "TotalProduceRequestsPerSec" }
     ]
    }
   ]
  },
  {
   "title": "Disk metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"autogen\".\"disk\" WHERE (\"application\" = 'knol-broker' AND \"device\" != 'xvda1' AND \"device\" != 'xvdh') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" },
      { "condition": "AND", "key": "device", "operator": "!=", "value": "xvda1" },
      { "condition": "AND", "key": "device", "operator": "!=", "value": "xvdh" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"autogen\".\"disk\" WHERE (\"application\" = 'knol-broker' AND \"device\" != 'xvda1' AND \"device\" != 'xvdh') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Disk usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"autogen\".\"disk\" WHERE (\"application\" = 'knol-broker' AND \"device\" != 'xvda1' AND \"device\" != 'xvdh') AND $timeFilter GROUP BY time($__interval), \"device\", \"host\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" },
      { "condition": "AND", "key": "device", "operator": "!=", "value": "xvda1" },
      { "condition": "AND", "key": "device", "operator": "!=", "value": "xvdh" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"autogen\".\"disk\" WHERE (\"application\" = 'knol-broker' AND \"device\" != 'xvda1' AND \"device\" != 'xvdh') AND $timeFilter GROUP BY time($__interval), \"device\", \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Flush Rate Time ms",
   "type": "graph",
   "description": "Time to flush log files to broker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "LogFlushRateAndTimeMs",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Flush Rate Time ms",
   "type": "graph",
   "description": "Time to flush log files to broker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "LogFlushRateAndTimeMs",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Disk Usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "xvdh" }
     ]
    }
   ]
  },
  {
   "title": "Root Disk Usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "xvda1" }
     ]
    }
   ]
  },
  {
   "title": "Iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "reads/s" ], "type": "alias" }
      ],
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "writes/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "xvda" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "xvda1" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "xvdh" }
     ]
    }
   ]
  },
  {
   "title": "Read/write time/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "write_time/s" ], "type": "alias" }
      ],
      [
       { "params": [ "read_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "read_time/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "xvdh" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "xvda1" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "xvda" }
     ]
    }
   ]
  },
  {
   "title": "Mean Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "write_bytes/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "read_bytes/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "xvda1" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "xvda" }
     ]
    }
   ]
  },
  {
   "title": "Host level metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Collection Time Non-Negative Difference",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "GarbageCollector",
     "select": [
      [
       { "params": [ "CollectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" }
     ]
    }
   ]
  },
  {
   "title": "TCP socket states",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netstat",
     "select": [
      [
       { "params": [ "tcp_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_established" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" }
     ]
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "GarbageCollector",
     "select": [
      [
       { "params": [ "LastGcInfo_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "knol-broker" }
     ]
    }
   ]
  }
 ]
}