{
 "title": "OBR",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Head Room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Head room",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(platform_onboarding_ladder{datacenter=~\"sgp\", job=\"ladder-selector-alb-0\", source_datacenter=~\"sgp\"} - ((sum(increase(http_server_start_api_requests_total{datacenter=\"sgp\", container=\"main\", action=~\"\"}[1m])), 0) + (sum(increase(start_degradation_request_count_total{datacenter=\"sgp\"}[1m])), 0) ) )/ ((sum(increase(http_server_start_api_requests_total{datacenter=\"sgp\", container=\"main\", action=~\"\"}[1m])), 0) + (sum(increase(start_degradation_request_count_total{datacenter=\"sgp\"}[1m])), 0) ) * 100",
     "legendFormat": "head_room"
    },
    {
     "expr": "(sum(increase(http_server_start_api_requests_total{datacenter=\"sgp\", container=\"main\", action=~\"\"}[1m])), 0) + (sum(increase(start_degradation_request_count_total{datacenter=\"sgp\"}[1m])), 0) ",
     "legendFormat": "actual_obr"
    },
    {
     "expr": "platform_onboarding_ladder{datacenter=~\"sgp\", job=\"ladder-selector-alb-0\", source_datacenter=~\"sgp\"}",
     "legendFormat": "platform_obr"
    }
   ]
  },
  { "title": "Actual OBR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Actual OBR on product",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(sum(increase(http_server_start_api_requests_total{datacenter=\"sgp\", container=\"main\", action=~\"\"}[1m])), 0) + (sum(increase(start_degradation_request_count_total{datacenter=\"sgp\"}[1m])), 0) ",
     "legendFormat": "Actual OBR on product"
    }
   ]
  },
  {
   "title": "Platform OBR (Predicted Manually)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Platform OBR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "platform_onboarding_ladder{datacenter=~\"sgp\", job=\"ladder-selector-alb-0\", source_datacenter=~\"sgp\"}",
     "legendFormat": "Platform OBR"
    }
   ]
  }
 ]
}