{
 "title": "Observe_dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, source_cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{source_cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod_regex",
    "query": ".*(refinery|collector|fluentd|filebeat|vmagent).*"
   },
   { "name": "node_regex", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "CPU> 50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container!=\"POD\", source_cluster=~\".*eks.*\", pod=~\"$pod_regex\",  image!=\"\", container!=\"\"}[1m])) by (pod, source_cluster) / max(kube_pod_container_resource_limits_cpu_cores{ source_cluster=~\".*eks.*\", pod=~\"$pod_regex\"}) by (pod, source_cluster) * 100 > 69",
     "legendFormat": "{{pod}}({{source_cluster}})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container!=\"POD\", source_cluster=~\".*eks.*\", pod=~\"$pod_regex\",  image!=\"\", container!=\"\"}[1m])) by (pod, source_cluster) / max(kube_pod_container_resource_limits_cpu_cores{ source_cluster=~\".*eks.*\", pod=~\"$pod_regex\"}) by (pod, source_cluster) * 100",
     "legendFormat": "{{pod}}({{source_cluster}})"
    }
   ]
  },
  {
   "title": "max memory (in %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container!=\"POD\", source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod_regex\",  image!=\"\", container!=\"\"}[1m]) by (pod, node) / max(kube_pod_container_resource_limits_memory_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod_regex\"}) by (pod, node) * 100",
     "legendFormat": "{{node}}({{pod}})"
    }
   ]
  },
  {
   "title": " Memory > 60 %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container!=\"POD\", source_cluster=~\".*eks.*\", pod=~\"$pod_regex\", image!=\"\", container!=\"\"}[1m]) by (pod, source_cluster) / max(kube_pod_container_resource_limits_memory_bytes{ source_cluster=~\".*eks.*\", pod=~\"$pod_regex\"}) by (pod, source_cluster) * 100 > 60",
     "legendFormat": "{{pod}}({{source_cluster}})"
    }
   ]
  },
  {
   "title": "POD count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod_regex\"}) by (phase)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "max cpu (in %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container!=\"POD\", source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod_regex\",  image!=\"\", container!=\"\"}[1m])) by (pod, node) / max(kube_pod_container_resource_limits_cpu_cores{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod_regex\"}) by (pod, node) * 100",
     "legendFormat": "{{node}}({{pod}})"
    }
   ]
  }
 ]
}