{
 "title": "Kubernetes Fleet Utilisation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "datacenter",
    "query": {
     "query": "label_values(live_event_in_progress, datacenter)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info{datacenter=\"$datacenter\"}, source_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Per Nodepool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"common-workloads-c.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"common-workloads-c.*\"})",
     "legendFormat": "Common workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"monitoring-workload.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"monitoring-workload.*\"})",
     "legendFormat": "Monitoring workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"ssai-common-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"ssai-common-workloads.*\"})",
     "legendFormat": "SSAI Common workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"cpu-affinity-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"cpu-affinity-workloads.*\"})",
     "legendFormat": "CPU Affinity Workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"memory-optimized-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"memory-optimized-workloads.*\"})",
     "legendFormat": "Memory Optimized workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"flink-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"flink-workloads.*\"})",
     "legendFormat": "Flink workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"ceph-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"ceph-workloads.*\"})",
     "legendFormat": "Ceph workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"graviton-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"graviton-workloads.*\"})",
     "legendFormat": "Graviton workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"stable-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"stable-workloads.*\"})",
     "legendFormat": "Stable workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"common-workloads-spot.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"cpu\", nodepool=~\"common-workloads-spot.*\"})",
     "legendFormat": "Spot Common workloads"
    }
   ]
  },
  {
   "title": "Memory Usage Per Nodepool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"common-workloads-c.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"common-workloads-c.*\"})",
     "legendFormat": "Common workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"monitoring-workload.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"monitoring-workload.*\"})",
     "legendFormat": "Monitoring workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"ssai-common-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"ssai-common-workloads.*\"})",
     "legendFormat": "SSAI Common workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"cpu-affinity-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"cpu-affinity-workloads.*\"})",
     "legendFormat": "CPU Affinity Workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"memory-optimized-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"memory-optimized-workloads.*\"})",
     "legendFormat": "Memory Optimized workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"flink-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"flink-workloads.*\"})",
     "legendFormat": "Flink workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"ceph-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"ceph-workloads.*\"})",
     "legendFormat": "Ceph workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"graviton-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"graviton-workloads.*\"})",
     "legendFormat": "Graviton workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"stable-workloads.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"stable-workloads.*\"})",
     "legendFormat": "Stable workloads"
    },
    {
     "expr": "sum(karpenter_nodepools_usage{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"common-workloads-spot.*\"}) * 100 / sum(karpenter_nodepools_limit{source_cluster=\"$cluster\", resource_type=\"memory\", nodepool=~\"common-workloads-spot.*\"})",
     "legendFormat": "Spot Common workloads"
    }
   ]
  },
  {
   "title": "Underutilized Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "karpenter_voluntary_disruption_eligible_nodes{source_cluster=\"$cluster\", reason=\"underutilized\"}",
     "legendFormat": "Underutilized nodes"
    }
   ]
  },
  {
   "title": "Cloud Provider errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(karpenter_cloudprovider_errors_total{source_cluster=\"$cluster\", datacenter=\"$datacenter\"}[$__interval])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}