{
 "title": "Layout Service",
 "tags": [
  "HotstarX",
  "Backend",
  "Core"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_cluster",
    "label": "source_cluster",
    "query": "hs-eks-prod-api-apse1,hs-eks-prod-api-euw1,hs-eks-load1-api-apse1,hs-eks-dev-api-aps1,hs-eks-qa-api-aps1,hs-eks-nonprod-api-aps1"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Http Server (PComp facing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "Overall Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\", container=\"main\", job=\"layout-service-default\"}[$__rate_interval])*60) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Latency by url",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (le, url))",
     "legendFormat": "p99 {{url}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (le, url))",
     "legendFormat": "p95 {{url}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (le, url))",
     "legendFormat": "p90 {{url}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (le, url))",
     "legendFormat": "p50 {{url}}"
    }
   ]
  },
  {
   "title": "Get Page",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(get_page_count_total{source_cluster=\"$source_cluster\", service=\"layout-service\", container=\"main\"}[$__rate_interval])*60) by (page_name, platform, cohort_id, filters, proto_version, partner_type)",
     "legendFormat": "{{page_name}}-{{platform}}-{{cohort_id}}-{{filters}}-{{proto_version}}-{{partner_type}}"
    }
   ]
  },
  {
   "title": "Overall Throughput by pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\", container=\"main\", job=\"layout-service-default\"}[$__rate_interval])*60) by (status_code, pod)",
     "legendFormat": "{{status_code}}-{{pod}}"
    }
   ]
  },
  {
   "title": "API 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\", url=~\"/v2/.*\",source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (status_code, url)",
     "legendFormat": "{{status_code}}-{{url}}"
    }
   ]
  },
  {
   "title": "API 4xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{url=~\"/v2/.*\",source_cluster=\"$source_cluster\", status_code=~\"4..\", service=\"layout-service\", container=\"main\"}[$__rate_interval])) by (status_code, url)",
     "legendFormat": "{{status_code}}-{{url}}"
    }
   ]
  },
  {
   "title": "Latency alert panel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"hs-eks-prod-api-euw1\", service=\"layout-service\"}[1m])) by (le, source_cluster))",
     "legendFormat": "p99-{{source_cluster}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_bucket{url=~\"/v2/.*\",source_cluster=\"hs-eks-prod-api-apse1\", service=\"layout-service\"}[1m])) by (le, source_cluster))",
     "legendFormat": "p99-{{source_cluster}}"
    }
   ]
  },
  {
   "title": "5XX % throughput alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (sum(rate(http_requests_total{url=~\"/v2/.*\", status_code=~\"5..\",source_cluster=\"hs-eks-prod-api-euw1\", service=\"layout-service\"}[1m])*60) by (source_cluster) / sum(rate(http_requests_total{url=~\"/v2/.*\",source_cluster=\"hs-eks-prod-api-euw1\", service=\"layout-service\"}[1m])*60) by (source_cluster))",
     "legendFormat": "5xx %- {{source_cluster}}"
    },
    {
     "expr": "100 * (sum(rate(http_requests_total{url=~\"/v2/.*\", status_code=~\"5..\",source_cluster=\"hs-eks-prod-api-apse1\", service=\"layout-service\"}[1m])*60) by (source_cluster) / sum(rate(http_requests_total{url=~\"/v2/.*\",source_cluster=\"hs-eks-prod-api-apse1\", service=\"layout-service\"}[1m])*60) by (source_cluster))",
     "legendFormat": "5xx %- {{source_cluster}}"
    }
   ]
  },
  {
   "title": "LS Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Layout service Instances",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{source_cluster=\"$source_cluster\", namespace=\"hs-core\", pod!~\"layout-service-nginx-.*\", pod=~\"layout-service.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Overall CPU utilisation",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "min(rate(container_cpu_usage_seconds_total{namespace=\"hs-core\",container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\", source_cluster=\"$source_cluster\"}[$__rate_interval])) / avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"hs-core\",container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\", source_cluster=\"$source_cluster\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"hs-core\",container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\", source_cluster=\"$source_cluster\"}[$__rate_interval])) / avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"hs-core\",container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\", source_cluster=\"$source_cluster\"})",
       "legendFormat": "avg"
      },
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"hs-core\",container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\", source_cluster=\"$source_cluster\"}[$__rate_interval])) / avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"hs-core\",container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\", source_cluster=\"$source_cluster\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Overall Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "min(sum(container_memory_rss{namespace=\"hs-core\", source_cluster=~\"$source_cluster\", container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\"}) by (pod)/sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"hs-core\", source_cluster=~\"$source_cluster\", container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\"}) by (pod))",
       "legendFormat": "min"
      },
      {
       "expr": "avg(sum(container_memory_rss{namespace=\"hs-core\", source_cluster=~\"$source_cluster\", container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\"}) by (pod)/sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"hs-core\", source_cluster=~\"$source_cluster\", container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\"}) by (pod))",
       "legendFormat": "avg"
      },
      {
       "expr": "max(sum(container_memory_rss{namespace=\"hs-core\", source_cluster=~\"$source_cluster\", container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\"}) by (pod)/sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"hs-core\", source_cluster=~\"$source_cluster\", container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\"}) by (pod))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Per Pod CPU utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"hs-core\", container=\"main\", pod!~\"layout-service-nginx-.*\", pod=~\"layout-service.*\", source_cluster=~\"$source_cluster\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Per pod memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{namespace=\"hs-core\", container=\"main\", pod=~\"layout-service.*\", pod!~\"layout-service-nginx.*\", source_cluster=\"$source_cluster\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Go routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_goroutines{namespace=\"hs-core\", pod!~\"layout-service-nginx-.*\", pod=~\"layout-service.*\", source_cluster=\"$source_cluster\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Idle connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(db_stats_connections_idle{db_name=\"hs_core_layout_service_db\", source_cluster=\"$source_cluster\", service=\"layout-service\", container=\"main\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "In use connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(db_stats_connections_in_use{db_name=\"hs_core_layout_service_db\", source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval]) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Open connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(db_stats_connections_open{db_name=\"hs_core_layout_service_db\", source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Max open connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(db_stats_connections_max_open{db_name=\"hs_core_layout_service_db\", source_cluster=\"$source_cluster\", service=\"layout-service\", container=\"main\"}[$__rate_interval])",
       "legendFormat": "{{pod}}-{{instance_type}}"
      }
     ]
    },
    {
     "title": "DB connection wait time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(db_stats_connections_blocked_seconds_total{db_name=\"hs_core_layout_service_db\", source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Idle connections closed because of max idle connection count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(db_stats_connections_closed_max_idle_total{db_name=\"hs_core_layout_service_db\", source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Connections closed because of max connection idle time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(db_stats_connections_closed_max_idle_time_total{db_name=\"hs_core_layout_service_db\", source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(increase(db_stats_connections_closed_max_lifetime_total{db_name=\"db\",service=\"layout-service\",source_cluster=\"$source_cluster\"}[1m]))",
       "legendFormat": "closed connections because of limit on max lifetime of a connection"
      },
      {
       "expr": "sum(increase(db_stats_connections_waited_for_total{db_name=\"db\",service=\"layout-service\",source_cluster=\"$source_cluster\"}[1m]))",
       "legendFormat": "connections waited for"
      }
     ]
    },
    {
     "title": "Connections closed because of max connection life time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(db_stats_connections_closed_max_lifetime_total{db_name=\"hs_core_layout_service_db\", source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "count of connections waited for",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(db_stats_connections_waited_for_total{db_name=\"hs_core_layout_service_db\", source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EagleEye View on Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Get Page Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(get_page_error_count_total{source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (page_name, platform, country, proto_version, partner_type, error_message)",
       "legendFormat": "{{page_name}}-{{platform}}-{{country}}-{{proto_version}}-{{partner_type}}-{{error_message}}"
      }
     ]
    },
    {
     "title": "Get Page Instance Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(get_page_instance_error_count_total{source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (page_name, platform, country, proto_version, partner_type, error_message)",
       "legendFormat": "{{page_name}}-{{platform}}-{{country}}-{{proto_version}}-{{partner_type}}-{{error_message}}"
      }
     ]
    },
    {
     "title": "Get Widget Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(get_widget_error_count_total{source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])) by (page_id, space_id, widget_id, platform, proto_version, error_message)",
       "legendFormat": "{{page_id}}-{{space_id}}-{{widget_id}}-{{platform}}-{{proto_version}}-{{error_message}}"
      }
     ]
    },
    {
     "title": "Get Widget Type Instance Info Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(get_widget_type_instance_info_error_count_total{source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (widget_type_instance_name, platform, proto_version, error_message)",
       "legendFormat": "{{widget_type_instance_name}}-{{platform}}-{{proto_version}}-{{error_message}}"
      }
     ]
    },
    {
     "title": "Get Space Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(get_space_error_count_total{source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (page_id, space_id, platform, proto_version, filter_key, filter_value, next_offset, next_size, error_message)",
       "legendFormat": "{{page_id}}-{{space_id}}-{{platform}}-{{proto_version}}-{{filter_key}}-{{filter_value}}-{{next_offset}}-{{next_size}}-{{error_message}}"
      }
     ]
    },
    {
     "title": "Get Widget Info Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(get_widget_info_error_count_total{source_cluster=\"$source_cluster\", service=\"layout-service\"}[$__rate_interval])*60) by (widget_type_instance_name, platform, proto_version, error_message)",
       "legendFormat": "{{widget_type_instance_name}}-{{platform}}-{{proto_version}}-{{error_message}}"
      }
     ]
    }
   ]
  }
 ]
}