{
 "title": "Prometheus Agent",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(scrape_samples_scraped, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(3, sum by (instance) (rate(process_cpu_seconds_total{job=~\"$job\"}[1m])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total scrapes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(3, sum by (instance) (increase(scrape_samples_scraped{job=~\"$job\"}[1m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(3, avg by (instance) (process_resident_memory_bytes{job=~\"$job\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(3, sum by (instance) (scrape_duration_seconds{job=~\"$job\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Scrape Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(3, sum by (instance) (increase(scrape_samples_post_metric_relabeling{job=~\"$job\"}[1m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Series Added",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk(3, sum by (instance) (increase(scrape_series_added{job=~\"$job\"}[1m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "scrape timeout",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "topk(3, sum by (instance) (increase(scrape_timeout_seconds\t{job=~\"$job\"}[1m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}