{
 "title": "Debugging Streaming Aggregation Spikes 2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "window",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(http_server_requests_seconds_without_instance_and_pod_and_pod_name_bucket, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "$service request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=\"$service\", datacenter=\"sgp\"}[$window]))",
     "legendFormat": "orig"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_without_instance_and_pod_and_pod_name_count{service=\"$service\", datacenter=\"sgp\"}[$window]))",
     "legendFormat": "lau"
    }
   ]
  },
  {
   "title": "$service request count: diff ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=\"$service\", datacenter=\"sgp\"}[$window])) - sum(increase(http_server_requests_seconds_without_instance_and_pod_and_pod_name_count{service=\"$service\", datacenter=\"sgp\"}[$window]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$service request P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(http_server_requests_seconds_bucket{service=\"$service\", datacenter=\"sgp\"}[$window])) by (le))",
     "legendFormat": "orig"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(http_server_requests_seconds_without_instance_and_pod_and_pod_name_bucket{service=\"$service\", datacenter=\"sgp\"}[$window])) by (le))",
     "legendFormat": "lau"
    }
   ]
  },
  {
   "title": "$service request P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(http_server_requests_seconds_bucket{service=\"$service\", datacenter=\"sgp\"}[$window])) by (le)) - histogram_quantile(0.95, sum(increase(http_server_requests_seconds_without_instance_and_pod_and_pod_name_bucket{service=\"$service\", datacenter=\"sgp\"}[$window])) by (le))",
     "legendFormat": "orig"
    }
   ]
  }
 ]
}