{
 "title": "Core utilization cluster-wise",
 "time": { "from": "2024-05-31T18:30:00.000Z", "to": "2024-06-15T18:29:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "dc",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas,datacenter)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas, source_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Vmagent Calculations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{datacenter=\"$dc\", pod=~\".*vmagent.*\"})"
    }
   ]
  },
  {
   "title": "Cluster core utlization - DC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{datacenter=~\"$dc\"})",
     "legendFormat": "Core utilized Total"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{datacenter=~\"$dc\"})",
     "legendFormat": "Core allocatable Total"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{datacenter=~\"$dc\"}) by (source_cluster)",
     "legendFormat": "Core utilized - {{source_cluster}}"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{datacenter=~\"$dc\"}) by (source_cluster)",
     "legendFormat": "Core allocatable - {{source_cluster}}"
    }
   ]
  },
  {
   "title": "Cluster core utlization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{source_cluster=~\"$cluster\"})",
     "legendFormat": "Core utlized"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{source_cluster=~\"$cluster\"})",
     "legendFormat": "Core allocatable"
    }
   ]
  },
  {
   "title": "Per node core wastage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{source_cluster=\"$cluster\"}) by (node) - sum(kube_pod_container_resource_limits_cpu_cores{source_cluster=\"$cluster\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Core utlization per namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{source_cluster=~\"$cluster\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Per node memory wastage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_memory_bytes{source_cluster=\"$cluster\"}) by (node) - sum(kube_pod_container_resource_limits_memory_bytes{source_cluster=\"$cluster\"}) by (node))/(1024 * 1024 * 1024)",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}