{
 "title": "LAST9-Appstartuptime-IN-Updated",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "PLATFORM_ANDROID",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l9_quantile_app_startuptime(app_startup_time_avg{platform=\"PLATFORM_ANDROID\",country=\"IN\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLATFORM_ANDROIDTV",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l9_quantile_app_startuptime(app_startup_time_avg{platform=\"PLATFORM_ANDROIDTV\",country=\"IN\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLATFORM_FIRETV",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l9_quantile_app_startuptime(app_startup_time_avg{platform=\"PLATFORM_FIRETV\",country=\"IN\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLATFORM_IOS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l9_quantile_app_startuptime(app_startup_time_avg{platform=\"PLATFORM_IOS\",country=\"IN\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLATFORM_WEBOS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l9_quantile_app_startuptime(app_startup_time_avg{platform=\"PLATFORM_WEBOS\",country=\"IN\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLATFORM_TIZENTV",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l9_quantile_app_startuptime(app_startup_time_avg{platform=\"PLATFORM_TIZENTV\",country=\"IN\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLATFORM_APPLETV",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l9_quantile_app_startuptime(app_startup_time_avg{platform=\"PLATFORM_APPLETV\",country=\"IN\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLATFORM_CHROMECAST",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l9_quantile_app_startuptime(app_startup_time_avg{platform=\"PLATFORM_CHROMECAST\",country=\"IN\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLATFORM_WEB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l9_quantile_app_startuptime(app_startup_time_avg{platform=\"PLATFORM_WEB\",country=\"IN\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}