{
 "title": "Copy - Debugging Stream Aggregation",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Demo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "stragg definition",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "```\n- promql: 'sum2 without (instance, pod, pod_name) (http_server_requests_seconds_count{}[1m])'\n  as: http_server_requests_seconds_without_instance_and_pod_and_pod_name_lau_count\n  cluster_id: b290d3f4-3464-466f-ab8b-da902620aea7\n```"
   }
  },
  {
   "title": "stragg definition",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "```\n- promql: 'sum2 by (service, pod, pod_name, le) (http_server_requests_seconds_bucket{}[1m])'\n  as: http_server_requests_seconds_with_service_and_pod_and_pod_name_lau_bucket\n  cluster_id: b290d3f4-3464-466f-ab8b-da902620aea7\n```"
   }
  },
  {
   "title": "Without pod: actual vs stragg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_requests_seconds_without_instance_and_pod_and_pod_name_lau_bucket\n{service=~'.*messenger.*', le=~\"0.1|0.04|0.02\", source_cluster=\"hs-eks-prod4-api-apse1\"}))",
     "legendFormat": "stragg_{{le}}"
    },
    {
     "expr": "sum by (le) (increase(sum without (instance, pod, pod_name)(http_server_requests_seconds_bucket\n{ service=~'.*messenger.*', le=~\"0.1|0.04|0.02\",source_cluster=\"hs-eks-prod4-api-apse1\"})))",
     "legendFormat": "raw_{{le}}"
    }
   ]
  },
  {
   "title": "With pod: actual vs stragg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_requests_seconds_with_service_and_pod_and_pod_name_lau_bucket\n{service=~'.*messenger.*', pod=~\".*\",le=~\"0.1|0.04|0.02\"}))",
     "legendFormat": "stragg_{{le}}"
    },
    {
     "expr": "sum by (le) (increase(sum by (instance, pod, pod_name, le)(http_server_requests_seconds_bucket\n{ service=~'.*messenger.*', le=~\"0.1|0.04|0.02\",source_cluster=\"hs-eks-prod4-api-apse1\"})))",
     "legendFormat": "raw_{{le}}"
    }
   ]
  },
  { "title": "Stream-aggr accuracy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "LAU - RAW (histogram INF)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(\n    sum (increase(http_server_requests_seconds_without_instance_and_pod_and_pod_name_bucket\n{uri=~'/messenger/api/v1/:country/notification/:event|in-prod-hspay-messenger-scheduler-ingestion-queue|/health|/metrics', source_cluster=~'hs-eks-prod4-api-apse1', service=~'.*messenger.*', le=\"+Inf\", l9shard=\"10.50.156.58\", datacenter=\"sgp\"}))\n)\n-\n\n(\n    sum (increase(sum without (instance, pod, pod_name)(http_server_requests_seconds_bucket\n{uri=~'/messenger/api/v1/:country/notification/:event|in-prod-hspay-messenger-scheduler-ingestion-queue|/health|/metrics', source_cluster=~'hs-eks-prod4-api-apse1', service=~'.*messenger.*', le=\"+Inf\", datacenter=\"sgp\"})))\n)",
     "legendFormat": "agg_{{le}}"
    }
   ]
  },
  {
   "title": "LAU - RAW (sum)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n    sum (increase(http_server_requests_seconds_without_instance_and_pod_and_pod_name_sum\n{source_cluster=~'hs-eks-prod4-api-apse1',l9shard=\"10.50.156.58\"}))\n)\n-\n\n(\n    sum (increase(sum without (instance, pod, pod_name)(http_server_requests_seconds_sum\n{source_cluster=~'hs-eks-prod4-api-apse1'})))\n)",
     "legendFormat": "agg_{{le}}"
    }
   ]
  },
  {
   "title": "LAU - RAW count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "(\n    sum (increase(http_server_requests_seconds_without_instance_and_pod_and_pod_name_count\n{uri=~'/messenger/api/v1/:country/notification/:event|in-prod-hspay-messenger-scheduler-ingestion-queue|/health|/metrics', source_cluster=~'hs-eks-prod4-api-apse1', service=~'.*messenger.*', l9shard=\"10.50.156.58\", datacenter=\"sgp\"}))\n)\n-\n\n(\n    sum (increase(sum without (instance, pod, pod_name)(http_server_requests_seconds_count\n{uri=~'/messenger/api/v1/:country/notification/:event|in-prod-hspay-messenger-scheduler-ingestion-queue|/health|/metrics', source_cluster=~'hs-eks-prod4-api-apse1', service=~'.*messenger.*', datacenter=\"sgp\"})))\n)",
     "legendFormat": "agg_{{le}}"
    }
   ]
  },
  {
   "title": "RAW (INF)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "(\n    sum (increase(sum without (instance, pod, pod_name)(http_server_requests_seconds_bucket\n{uri=~'/messenger/api/v1/:country/notification/:event|in-prod-hspay-messenger-scheduler-ingestion-queue|/health|/metrics', source_cluster=~'hs-eks-prod4-api-apse1', service=~'.*messenger.*', le=\"+Inf\", datacenter=\"sgp\"})))\n)",
     "legendFormat": "agg_{{le}}"
    }
   ]
  },
  {
   "title": "RAW (sum)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n    sum (increase(sum without (instance, pod, pod_name)(http_server_requests_seconds_sum\n{uri=~'/messenger/api/v1/:country/notification/:event|in-prod-hspay-messenger-scheduler-ingestion-queue|/health|/metrics', source_cluster=~'hs-eks-prod4-api-apse1', service=~'.*messenger.*', datacenter=\"sgp\"})))\n)",
     "legendFormat": "agg_{{le}}"
    }
   ]
  },
  {
   "title": "RAW count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 22 },
   "targets": [
    {
     "expr": "(\n    sum (increase(sum without (instance, pod, pod_name)(http_server_requests_seconds_count\n{uri=~'/messenger/api/v1/:country/notification/:event|in-prod-hspay-messenger-scheduler-ingestion-queue|/health|/metrics', source_cluster=~'hs-eks-prod4-api-apse1', service=~'.*messenger.*', datacenter=\"sgp\"})))\n)",
     "legendFormat": "agg_{{le}}"
    }
   ]
  }
 ]
}