{
 "title": "Last9 PFR Alerts (ZA, ID, PH, MY, TH)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "ZA-Android",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROID', country=~'ZA'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ZA', platform=~'PLATFORM_ANDROID', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ZA', platform=~'PLATFORM_ANDROID', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ZA', platform=~'PLATFORM_ANDROID'}) by (platform)),450,5,4,0.85)",
     "legendFormat": "__auto"
    },
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROID', country=~'ZA'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ZA', platform=~'PLATFORM_ANDROID', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ZA', platform=~'PLATFORM_ANDROID', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ZA', platform=~'PLATFORM_ANDROID'}) by (platform)),450,5,4,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ID-Android",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROID', country=~'ID'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ID', platform=~'PLATFORM_ANDROID', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ID', platform=~'PLATFORM_ANDROID', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ID', platform=~'PLATFORM_ANDROID'}) by (platform)),40,5,5,0.85)",
     "legendFormat": "__auto"
    },
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROID', country=~'ID'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ID', platform=~'PLATFORM_ANDROID', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ID', platform=~'PLATFORM_ANDROID', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ID', platform=~'PLATFORM_ANDROID'}) by (platform)),40,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH-PLATFORM_ANDROID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROID', country=~'PH'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'PH', platform=~'PLATFORM_ANDROID', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'PH', platform=~'PLATFORM_ANDROID', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'PH', platform=~'PLATFORM_ANDROID'}) by (platform)),60,5,5,0.85)",
     "legendFormat": "__auto"
    },
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROID', country=~'PH'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'PH', platform=~'PLATFORM_ANDROID', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'PH', platform=~'PLATFORM_ANDROID', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'PH', platform=~'PLATFORM_ANDROID'}) by (platform)),60,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MY-PLATFORM_ANDROID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROID', country=~'MY'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'MY', platform=~'PLATFORM_ANDROID', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'MY', platform=~'PLATFORM_ANDROID', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'MY', platform=~'PLATFORM_ANDROID'}) by (platform)),20,5,5,0.75)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TH-PLATFORM_ANDROID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROID', country=~'TH'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'TH', platform=~'PLATFORM_ANDROID', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'TH', platform=~'PLATFORM_ANDROID', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'TH', platform=~'PLATFORM_ANDROID'}) by (platform)),20,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZA-PLATFORM_ANDROIDTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROIDTV', country=~'ZA'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ZA', platform=~'PLATFORM_ANDROIDTV', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ZA', platform=~'PLATFORM_ANDROIDTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ZA', platform=~'PLATFORM_ANDROIDTV'}) by (platform)),450,5,5,0.75)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH-PLATFORM_ANDROIDTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROIDTV', country=~'PH'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'PH', platform=~'PLATFORM_ANDROIDTV', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'PH', platform=~'PLATFORM_ANDROIDTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'PH', platform=~'PLATFORM_ANDROIDTV'}) by (platform)),50,8,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ID-PLATFORM_ANDROIDTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROIDTV', country=~'ID'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ID', platform=~'PLATFORM_ANDROIDTV', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ID', platform=~'PLATFORM_ANDROIDTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ID', platform=~'PLATFORM_ANDROIDTV'}) by (platform)),50,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TH-PLATFORM_ANDROIDTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROIDTV', country=~'TH'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'TH', platform=~'PLATFORM_ANDROIDTV', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'TH', platform=~'PLATFORM_ANDROIDTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'TH', platform=~'PLATFORM_ANDROIDTV'}) by (platform)),45,5,5,0.75)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MY-PLATFORM_ANDROIDTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432',platform=~'PLATFORM_ANDROIDTV', country=~'MY'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'MY', platform=~'PLATFORM_ANDROIDTV', newtork_type!='NETWORK_TYPE_OFFLINE'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'MY', platform=~'PLATFORM_ANDROIDTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'MY', platform=~'PLATFORM_ANDROIDTV'}) by (platform)),40,8,4,0.75)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ID-PLATFORM_IOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ID', platform=~'PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ID', platform=~'PLATFORM_IOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ID', platform=~'PLATFORM_IOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1|PL-1004\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ID', platform=~'PLATFORM_IOS'}) by (platform)),25,5,3,0.7)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZA-PLATFORM_IOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ZA', platform=~'PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ZA', platform=~'PLATFORM_IOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ZA', platform=~'PLATFORM_IOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1|PL-1004\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ZA', platform=~'PLATFORM_IOS'}) by (platform)),250,5,5,0.65)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MY-PLATFORM_IOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'MY', platform=~'PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'MY', platform=~'PLATFORM_IOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'MY', platform=~'PLATFORM_IOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1|PL-1004\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'MY', platform=~'PLATFORM_IOS'}) by (platform)),25,5,5,0.75)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH-PLATFORM_IOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'PH', platform=~'PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'PH', platform=~'PLATFORM_IOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'PH', platform=~'PLATFORM_IOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1|PL-1004\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'PH', platform=~'PLATFORM_IOS'}) by (platform)),50,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZA-PLATFORM_WEB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ZA', platform=~'PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ZA', platform=~'PLATFORM_WEB', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ZA', platform=~'PLATFORM_WEB', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ZA', platform=~'PLATFORM_WEB'}) by (platform)),200,5,3,0.65)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TH-PLATFORM_IOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'TH', platform=~'PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'TH', platform=~'PLATFORM_IOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_IOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'TH', platform=~'PLATFORM_IOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1|PL-1004\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'TH', platform=~'PLATFORM_IOS'}) by (platform)),50,5,5,0.8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZA-PLATFORM_WEBOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ZA', platform=~'PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ZA', platform=~'PLATFORM_WEBOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ZA', platform=~'PLATFORM_WEBOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ZA', platform=~'PLATFORM_WEBOS'}) by (platform)),150,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH-PLATFORM_WEB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'PH', platform=~'PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'PH', platform=~'PLATFORM_WEB', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'PH', platform=~'PLATFORM_WEB', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'PH', platform=~'PLATFORM_WEB'}) by (platform)),25,5,3,0.5)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZA-PLATFORM_TIZENTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ZA', platform=~'PLATFORM_TIZENTV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ZA', platform=~'PLATFORM_TIZENTV', newtork_type!='NETWORK_TYPE_OFFLINE',platform='PLATFORM_TIZENTV' }) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ZA', platform=~'PLATFORM_TIZENTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ZA', platform=~'PLATFORM_TIZENTV'}) by (platform)),200,5,3,0.5)",
     "legendFormat": "__auto"
    },
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ZA', platform=~'PLATFORM_TIZENTV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ZA', platform=~'PLATFORM_TIZENTV', newtork_type!='NETWORK_TYPE_OFFLINE',platform='PLATFORM_TIZENTV' }) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ZA', platform=~'PLATFORM_TIZENTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ZA', platform=~'PLATFORM_TIZENTV'}) by (platform)),200,5,3,0.5)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TH-PLATFORM_WEB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'TH', platform=~'PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'TH', platform=~'PLATFORM_WEB', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'TH', platform=~'PLATFORM_WEB', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'TH', platform=~'PLATFORM_WEB'}) by (platform)),25,5,2,0.4)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ID-PLATFORM_WEB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ID', platform=~'PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ID', platform=~'PLATFORM_WEB', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ID', platform=~'PLATFORM_WEB', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ID', platform=~'PLATFORM_WEB'}) by (platform)),20,5,3,0.75)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ID-PLATFORM_WEBOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ID', platform=~'PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ID', platform=~'PLATFORM_WEBOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ID', platform=~'PLATFORM_WEBOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ID', platform=~'PLATFORM_WEBOS'}) by (platform)),15,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MY-PLATFORM_WEB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'MY', platform=~'PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'MY', platform=~'PLATFORM_WEB', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEB'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'MY', platform=~'PLATFORM_WEB', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'MY', platform=~'PLATFORM_WEB'}) by (platform)),20,5,3,0.65)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MY-PLATFORM_WEBOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'MY', platform=~'PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'MY', platform=~'PLATFORM_WEBOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'MY', platform=~'PLATFORM_WEBOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'MY', platform=~'PLATFORM_WEBOS'}) by (platform)),25,5,5,0.85)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'MY', platform=~'PLATFORM_WEBOS'}) by (platform))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH-PLATFORM_WEBOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'PH', platform=~'PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'PH', platform=~'PLATFORM_WEBOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'PH', platform=~'PLATFORM_WEBOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'PH', platform=~'PLATFORM_WEBOS'}) by (platform)),15,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ID-PLATFORM_TIZENTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'PH', platform=~'PLATFORM_TIZENTV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'PH', platform=~'PLATFORM_TIZENTV', newtork_type!='NETWORK_TYPE_OFFLINE',platform='PLATFORM_TIZENTV' }) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'PH', platform=~'PLATFORM_TIZENTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'PH', platform=~'PLATFORM_TIZENTV'}) by (platform)),20,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH-PLATFORM_TIZENTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'PH', platform=~'PLATFORM_TIZENTV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'PH', platform=~'PLATFORM_TIZENTV', newtork_type!='NETWORK_TYPE_OFFLINE',platform='PLATFORM_TIZENTV' }) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'PH', platform=~'PLATFORM_TIZENTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'PH', platform=~'PLATFORM_TIZENTV'}) by (platform)),20,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZA-PLATFORM_FIRETV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ZA', platform=~'PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ZA', platform=~'PLATFORM_FIRETV', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ZA', platform=~'PLATFORM_FIRETV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ZA', platform=~'PLATFORM_FIRETV'}) by (platform)),20,5,2,0.65)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TH-PLATFORM_TIZENTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'TH', platform=~'PLATFORM_TIZENTV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'TH', platform=~'PLATFORM_TIZENTV', newtork_type!='NETWORK_TYPE_OFFLINE',platform='PLATFORM_TIZENTV' }) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'TH', platform=~'PLATFORM_TIZENTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'TH', platform=~'PLATFORM_TIZENTV'}) by (platform)),15,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MY-PLATFORM_TIZENTV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'MY', platform=~'PLATFORM_TIZENTV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'MY', platform=~'PLATFORM_TIZENTV', newtork_type!='NETWORK_TYPE_OFFLINE',platform='PLATFORM_TIZENTV' }) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'MY', platform=~'PLATFORM_TIZENTV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'MY', platform=~'PLATFORM_TIZENTV'}) by (platform)),200,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TH-PLATFORM_WEBOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'TH', platform=~'PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'TH', platform=~'PLATFORM_WEBOS', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_WEBOS'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'TH', platform=~'PLATFORM_WEBOS', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'TH', platform=~'PLATFORM_WEBOS'}) by (platform)),150,5,5,0.85)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MY-PLATFORM_FIRETV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'MY', platform=~'PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'MY', platform=~'PLATFORM_FIRETV', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'MY', platform=~'PLATFORM_FIRETV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'MY', platform=~'PLATFORM_FIRETV'}) by (platform)),20,5,2,0.65)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ID-PLATFORM_FIRETV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'ID', platform=~'PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'ID', platform=~'PLATFORM_FIRETV', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'ID', platform=~'PLATFORM_FIRETV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'ID', platform=~'PLATFORM_FIRETV'}) by (platform)),20,5,2,0.65)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH-PLATFORM_FIRETV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'PH', platform=~'PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'PH', platform=~'PLATFORM_FIRETV', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'PH', platform=~'PLATFORM_FIRETV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'PH', platform=~'PLATFORM_FIRETV'}) by (platform)),20,5,2,0.65)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TH-PLATFORM_FIRETV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "explain_level_increase(((((sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code!~'ERR_PB_1405|ERR_PB_1411|ERR_PB_1410|ERR_PB_1424|ERR_PB_1415|ERR_PB_1426|Unknown|NET_100|NET_101|HTTP_404|NET_103|NET_104|NET_201|NET_301|PB_IOS_NM-1002|PB_IOS_NM-1005|PB_TVOS_NM-1005|NET_102|ERR_CON_041|ERR_PB_1419|ERR_PB_1430|HTTP_475|BFF_FAILED_HTTP_475|475|NET_105|NET_107|NET_106|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104|ERR_PB_1431|ERR_PB_1432', country=~'TH', platform=~'PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_playback_api_total_without_content_id{play_type=\"watch_page\", error_code=~'NET_100|NET_101|NET_102|NET_103|NET_104|NET_301|NET_201|NET_105|NET_106|NET_107|NET_108|BFF_FAILED_NET_102|BFF_FAILED_NET_103|BFF_FAILED_NET_104', country=~'TH', platform=~'PLATFORM_FIRETV', newtork_type!='NETWORK_TYPE_OFFLINE', platform='PLATFORM_FIRETV'}) by (platform) or on () vector(0) + sum(failed_video_total_without_content_id{country=~'TH', platform=~'PLATFORM_FIRETV', play_type='PLAY_TYPE_WATCH_PAGE',error_code!~\"NM-1002_X|NM-4740|NM-1000|NM-4290|NM-4031|NM-4730|CE-1008|CE-16845|NM-1002|NM-1002_1\"}) by(platform))) or on () vector(0))),(sum(watch_attempt_total_without_content_id{play_type=\"watch_page\",country=~'TH', platform=~'PLATFORM_FIRETV'}) by (platform)),20,5,2,0.65)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}