{
 "title": "Business KPI's Country Wise",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "country",
    "query": {
     "query": "label_values(app_opened_total,country)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Login conversion rate platform-wise (P0)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(logged_in_total{country=~\"$country\"}) by (platform) or on() vector(0))*100/(sum(submitted_phone_number_total{country=~\"$country\"}) by (platform) or on() vector(1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAU Country level platform wise (P0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(app_opened_total{country=~\"$country\"}) by (platform)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Success Rate Platform-wise (P0)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "((sum(purchased_subscription_total{country=~\"$country\"}) by (platform) or on() vector(0))/((sum(payment_initiated_total{country=~\"$country\"}) by (platform))or on() vector(1)))*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}