{
 "title": "Relative Failed Video Country Wise",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "country",
    "query": {
     "query": "label_values(failed_video_total,country)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate of Failed Video",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (platform) (rate(failed_video_total{country=~\"$country\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed video",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(failed_video_total{country=~\"$country\"}) by (platform) > 10 or 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Video (Relative Last 7 days)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum(failed_video_total{country=~\"$country\"}) by (platform)- (sum(failed_video_total{country=~\"$country\"}) by (platform) offset 7d))*100/(sum(failed_video_total{country=~\"$country\"}) by (platform) offset 7d)) > 10",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}