{
 "title": "Adtech Fuse Cohosted",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{service=\"adtech-blaze-fuse-cohosted\"}, source_cluster)"
    }
   },
   {
    "name": "country",
    "label": "country",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{service=\"adtech-blaze-fuse-cohosted\"}, country)"
    }
   },
   { "name": "service", "label": "service", "query": "adtech-blaze-fuse-cohosted" },
   { "name": "container", "label": "container", "query": "adtech-fuse" }
  ]
 },
 "panels": [
  {
   "title": "High Level Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri!=\"/health\", uri!=\"/metrics\"})[$__rate_interval]*60)",
       "legendFormat": "RPM"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri!=\"/health\", uri!=\"/metrics\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Throughput by Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri!=\"/health\", uri!=\"/metrics\"})[$__rate_interval] * 60) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Latency by URI, Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri!=\"/health\", uri!=\"/metrics\"}[$__rate_interval])) by (le, uri, status))",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg CPU Usage %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{source_cluster=~\"$cluster\",container=~\"$container\", pod=~\"adtech-blaze-fuse.*\"}[$__rate_interval]))/ avg(kube_pod_container_resource_requests_cpu_cores{source_cluster=~\"$cluster\",container=~\"$container\", pod=~\"adtech-blaze-fuse.*\"})",
       "legendFormat": "% CPU"
      }
     ]
    },
    {
     "title": "Avg Memory Usage %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{source_cluster=~\"$cluster\",container=\"$container\", pod=~\"adtech-blaze-fuse.*\"}[$__rate_interval])/ avg(kube_pod_container_resource_requests_memory_bytes{source_cluster=~\"$cluster\",container=\"$container\", pod=~\"adtech-blaze-fuse.*\"})",
       "legendFormat": "% Mem"
      }
     ]
    },
    {
     "title": "Max CPU Usage %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{source_cluster=~\"$cluster\",container=~\"$container\", pod=~\"adtech-blaze-fuse.*\"}[$__rate_interval]))/ max(kube_pod_container_resource_requests_cpu_cores{source_cluster=~\"$cluster\",container=~\"$container\", pod=~\"adtech-blaze-fuse.*\"})",
       "legendFormat": "% CPU"
      }
     ]
    },
    {
     "title": "Max Memory Usage %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{source_cluster=~\"$cluster\",container=\"$container\", pod=~\"adtech-blaze-fuse.*\"}[$__rate_interval])/ max(kube_pod_container_resource_requests_memory_bytes{source_cluster=~\"$cluster\",container=\"$container\", pod=~\"adtech-blaze-fuse.*\"})",
       "legendFormat": "% Mem"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{source_cluster=~\"$cluster\", pod=~\"adtech-blaze-fuse.*\", container=~\"$container\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{source_cluster=~\"$cluster\", pod =~\"adtech-blaze-fuse.*\", container=~\"$container\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", source_cluster=~\"$cluster\",deployment=~\".*blaze-fuse.*\"}) by (deployment)",
       "legendFormat": "{{deployment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "P0 APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postings V2 Throughput by Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri=\"/fuse/api/v2/:country/postings\"})[$__rate_interval] * 60) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Postings V2 Latency by Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri=\"/fuse/api/v2/:country/postings\"}[$__rate_interval])) by (le, status))",
       "legendFormat": "{{{status}}"
      }
     ]
    },
    {
     "title": "Postings Throughput by Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri=\"/fuse/api/v1/:country/postings\"})[$__rate_interval] * 60) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Postings Latency by Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri=\"/fuse/api/v1/:country/postings\"}[$__rate_interval])) by (le, status))",
       "legendFormat": "{{{status}}"
      }
     ]
    },
    {
     "title": "Fetch Ads Throughput by Status [DEPRECATED]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri=\"/fuse/api/v1/:country/fetch_ads\"})[$__rate_interval] * 60) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Fetch Ads Latency by Status [DEPRECATED]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri=\"/fuse/api/v1/:country/fetch_ads\"}[$__rate_interval])) by (le, status))",
       "legendFormat": "{{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "P0 Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(fuse_events_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  event_type=\"fuse_errors\"})[$__rate_interval]) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Info Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(fuse_events_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  event_type=\"fuse_info\"})[$__rate_interval]) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Method throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(method_duration_seconds_count{source_cluster=~\"$cluster\", service=~\"$service\"})[$__rate_interval] * 60) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Method Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(method_duration_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\"}[$__rate_interval])) by (le, method))",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Creative Prefetch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prefetch Creatives Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  uri=\"/fuse/api/v1/:country/prefetch_creatives\"})[$__rate_interval]) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Prefetch Creatives Events",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(fuse_events_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  event_type=\"creative_prefetch\"})[$__rate_interval]) by (event, status)",
       "legendFormat": "{{event}} - {{status}}"
      },
      {
       "expr": "sum(increase(fuse_events_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  event_type=\"creative_harvesting_consumer\"})[$__rate_interval]) by (event, status)",
       "legendFormat": "{{event}}-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval] * 60) by (client, code)",
       "legendFormat": "{{client}} {{code}} "
      }
     ]
    },
    {
     "title": "HTTP client latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])) by (le, client, method))",
       "legendFormat": "{{client}} - {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound HTTP Drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_client_event_seconds_count{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"conn_start\"}[$__rate_interval] * 60)) by (client)",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "Put Idle Conns",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_client_event_seconds_count{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"put_idle_conn\"}[$__rate_interval] * 60)) by (client)",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "DNS Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"dns_done\"}[$__rate_interval])) by (le, client)) - histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"dns_start\"}[$__rate_interval])) by (le, client))",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "TLS Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"tls_handshake_done\"}[$__rate_interval])) by (le, client)) - histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"tls_handshake_start\"}[$__rate_interval])) by (le, client))",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "Connection acquisition from pool Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"got_conn\"}[$__rate_interval])) by (le, client)) - histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", event=\"get_conn\"}[$__rate_interval])) by (le, client))",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "TCP Connection latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"conn_done\"}[$__rate_interval])) by (le, client)) - histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"conn_start\"}[$__rate_interval])) by (le, client))",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "HTTP Server Processing latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"got_first_resp_byte\"}[$__rate_interval])) by (le, client)) - histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"got_conn\"}[$__rate_interval])) by (le, client))",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "HTTP Request write latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"wrote_request\"}[$__rate_interval])) by (le, client)) - histogram_quantile(0.99, sum(rate(http_client_event_seconds_bucket{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", event=\"got_conn\"}[$__rate_interval])) by (le, client))",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "In flight requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_client_inflight_requests_current{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}) by (client)",
       "legendFormat": "{{client}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GO/GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Duration - Max",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", quantile=\"1\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC Duration - P75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\", quantile=\"0.75\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{source_cluster=~\"$cluster\", service=\"$service\", container=~\"$container\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Stats - Hit Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  metric=\"hit_count\"})[$__rate_interval]) by (store) / (sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  metric=\"hit_count\"})[$__rate_interval]) by (store) + sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  metric=\"miss_count\"})[$__rate_interval]) by (store))",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Cache Stats - Miss Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  metric=\"miss_count\"})[$__rate_interval]) by (store) / (sum(increase(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  metric=\"hit_count\"})[$__rate_interval]) by (store) + sum(increase(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  metric=\"miss_count\"})[$__rate_interval]) by (store))",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Redis Cache Stats - Master Manifest",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  store=\"redis-master_manifest\"})[$__rate_interval] * 60) by (store, metric)",
       "legendFormat": "{{store}} - {{metric}}"
      }
     ]
    },
    {
     "title": "Redis Cache Stats - Child Manifest",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  store=\"redis-child_manifest\"})[$__rate_interval] * 60) by (store, metric)",
       "legendFormat": "{{store}} - {{metric}}"
      }
     ]
    },
    {
     "title": "Inmem Cache Stats - Master Manifest",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  store=\"inmem-master_manifest\"})[$__rate_interval] * 60) by (store, metric)",
       "legendFormat": "{{store}} - {{metric}}"
      }
     ]
    },
    {
     "title": "Inmem Cache Stats - Child Manifest",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  store=\"inmem-child_manifest\"})[$__rate_interval] * 60) by (store, metric)",
       "legendFormat": "{{store}} - {{metric}}"
      }
     ]
    },
    {
     "title": "Inmem Cache Stats - Ad segments",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  store=\"inmem-ad_segments\"})[$__rate_interval] * 60) by (store, metric)",
       "legendFormat": "{{store}} - {{metric}}"
      }
     ]
    },
    {
     "title": "Redis Cache Stats - Ad segments",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  store=\"redis-ad_segments\"})[$__rate_interval] * 60) by (store, metric)",
       "legendFormat": "{{store}} - {{metric}}"
      }
     ]
    },
    {
     "title": "Redis Cache Stats - Blaze [DEPRECATED]",
     "type": "graph",
     "description": "Only applicable for V1 (Cohort based decisioning)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  store=\"blaze\"})[$__rate_interval] * 60) by (store, metric)",
       "legendFormat": "{{store}} - {{metric}}"
      }
     ]
    },
    {
     "title": "Redis Cache Stats - Fuse Response [DEPRECATED]",
     "type": "graph",
     "description": "Only applicable for V1 (Cohort based decisioning)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\",  store=\"redis-fuse_response\"})[$__rate_interval] * 60) by (store, metric)",
       "legendFormat": "{{store}} - {{metric}}"
      }
     ]
    },
    {
     "title": "Redis Latency - P99",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(redis_client_requests_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])) by (le, store, operation))",
       "legendFormat": "{{store}} - {{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis CP - Hit Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(adtech_fuse_pool_hit_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval]) / (sum(rate(adtech_fuse_pool_hit_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval]) + sum(rate(adtech_fuse_pool_miss_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval]))",
       "legendFormat": "% Hit Rate"
      }
     ]
    },
    {
     "title": "Redis CP - Timeout",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(adtech_fuse_pool_timeout_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval] * 60)",
       "legendFormat": "RPM"
      }
     ]
    },
    {
     "title": "Redis Connection Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(adtech_fuse_pool_conn_total_current{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(adtech_fuse_pool_conn_idle_current{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Redis CP - Stale Conn Removed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(adtech_fuse_pool_conn_stale_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval] * 60)",
       "legendFormat": "RPM"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilisation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_ElastiCache_EngineCPUUtilization_sum{CacheClusterId=~\"adtech-fuse-in-.*\", CacheNodeId=\"0001\"}) / sum(amazonaws_com_AWS_ElastiCache_EngineCPUUtilization_count{CacheClusterId=~\"adtech-fuse-in-.*\", CacheNodeId=\"0001\"})",
       "legendFormat": "% CPU"
      }
     ]
    },
    {
     "title": "Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_ElastiCache_DatabaseMemoryUsagePercentage_sum{CacheClusterId=~\"adtech-fuse-in-.*\", CacheNodeId=\"0001\"}) / sum(amazonaws_com_AWS_ElastiCache_DatabaseMemoryUsagePercentage_count{CacheClusterId=~\"adtech-fuse-in-.*\", CacheNodeId=\"0001\"})",
       "legendFormat": "% Mem"
      }
     ]
    },
    {
     "title": "Cache hit rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "min(amazonaws_com_AWS_ElastiCache_CacheHitRate_sum{CacheClusterId=~\"adtech-fuse-in-.*\", CacheNodeId=\"0001\"})",
       "legendFormat": "% hit"
      }
     ]
    }
   ]
  },
  {
   "title": "SQS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Visible messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_SQS_ApproximateNumberOfMessagesVisible_sum{QueueName=~\"adtech-fuse-in-.*\"}) by (QueueName)",
       "legendFormat": "{{QueueName}}"
      }
     ]
    },
    {
     "title": "Approx age oldest message",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_SQS_ApproximateAgeOfOldestMessage_sum{QueueName=~\"adtech-fuse-in-.*\", quantile=\"1\"}) by (QueueName)",
       "legendFormat": "{{QueueName}}"
      }
     ]
    },
    {
     "title": "Published messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_SQS_NumberOfMessagesSent_sum{QueueName=~\"adtech-fuse-in-.*\"}) by (QueueName)",
       "legendFormat": "{{QueueName}}"
      }
     ]
    },
    {
     "title": "Polled messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_SQS_NumberOfMessagesReceived_sum{QueueName=~\"adtech-fuse-in-.*\"}) by (QueueName)",
       "legendFormat": "{{QueueName}}"
      }
     ]
    },
    {
     "title": "Deleted messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(amazonaws_com_AWS_SQS_NumberOfMessagesDeleted_sum{QueueName=~\"adtech-fuse-in-.*\"}) by (QueueName)",
       "legendFormat": "{{QueueName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Circuit Opened",
     "type": "graph",
     "description": "Total of circuit transitions from closed to opened",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(circuit_opened_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval]) by (name)",
       "legendFormat": "RPM {{name}}"
      }
     ]
    },
    {
     "title": "Circuit Closed",
     "type": "graph",
     "description": "Total of circuit transitions from open to closed",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(circuit_closed_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval]) by (name)",
       "legendFormat": "RPM {{name}}"
      }
     ]
    },
    {
     "title": "Concurrency Rejections",
     "type": "graph",
     "description": "Total reject requests for reach concurrency limit",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(circuit_concurrency_reject_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval]) by (name, func)",
       "legendFormat": "RPM {{name}} {{func}}"
      }
     ]
    },
    {
     "title": "Short Circuit Rejections",
     "type": "graph",
     "description": "Total of runFunc is not called because the circuit was open",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(circuit_short_circuit_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval]) by (name)",
       "legendFormat": "RPM {{name}}"
      }
     ]
    },
    {
     "title": "Latency - Successful Run",
     "type": "graph",
     "description": "Duration of successful func run",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(circuit_success_duration_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])) by (le, name, func))",
       "legendFormat": "P99 - {{name}} - {{func}}"
      }
     ]
    },
    {
     "title": "Latency - Failure Run",
     "type": "graph",
     "description": "Duration of successful func run",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(circuit_failure_duration_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])) by (le, name, func))",
       "legendFormat": "P99 - {{name}} - {{func}}"
      }
     ]
    },
    {
     "title": "Latency - Timeout",
     "type": "graph",
     "description": "Duration of timeout func run",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(circuit_timeout_duration_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])) by (le, name))",
       "legendFormat": "P99 - {{name}}"
      }
     ]
    },
    {
     "title": "Latency - Bad Request",
     "type": "graph",
     "description": "Duration of bad request request",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(circuit_bad_request_duration_seconds_bucket{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])) by (le, name))",
       "legendFormat": "P99 - {{name}}"
      }
     ]
    },
    {
     "title": "Open Circuits",
     "type": "gauge",
     "description": "The status of a circuit, 1 opened, 0 closed",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(circuit_opened{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Shedder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "LS Request status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(adtech_fuse_loadshedder_requests_total{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"})[$__rate_interval]) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "LS Inflight Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(adtech_fuse_loadshedder_inflight_requests_current{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "sum(adtech_fuse_loadshedder_limit{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "LS Threshold",
     "type": "gauge",
     "description": "LS Threshold per pod",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(adtech_fuse_loadshedder_limit{source_cluster=~\"$cluster\", service=~\"$service\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "Threshold"
      }
     ]
    }
   ]
  }
 ]
}