{
 "title": "Kiam",
 "description": "Kiam cache, response & health metrics",
 "tags": [
  "Kubernetes",
  "Kiam"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_namespace_created, source_cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kiam_metadata_responses_total{source_cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of successful responses from a handler",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, handler) (delta(kiam_metadata_success_total{source_cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "{{handler}} - {{pod}} "
    }
   ]
  },
  {
   "title": "Responses from mocked out metadata handlers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code, pod) (delta(kiam_metadata_responses_total{source_cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "{{code}} {{pod}}"
    }
   ]
  },
  {
   "title": "Number of empty roles returned",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (delta(kiam_metadata_empty_role_total{source_cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of errors finding the role for a pod",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler, pod) (delta(kiam_metadata_find_role_errors_total{source_cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "{{handler}} {{pod}}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "Number of errors fetching the credentials for a pod",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler, pod) (delta(kiam_metadata_credential_fetch_errors_total{source_cluster=~\"$cluster\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Number of errors issuing credentials(STS)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (delta(kiam_sts_issuing_errors_total{source_cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of dropped pods because of full buffer",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kiam_k8s_dropped_pods_total{source_cluster=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of assume role calls currently executing",
   "type": "graph",
   "description": "Number of assume role calls currently executing",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kiam_sts_assumerole_current{source_cluster=~\"$cluster\"})",
     "legendFormat": "{{pod}}",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Number of cache hits to the metadata cache",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (delta(kiam_sts_cache_hit_total{source_cluster=~\"$cluster\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of cache misses to the metadata cache",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (delta(kiam_sts_cache_miss_total{source_cluster=~\"$cluster\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "assumerole timing (in secs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kiam_sts_assumerole_timing_seconds_sum{service=\"kiam-server\", source_cluster=~\"$cluster\"}[1m])) by (pod)/sum(rate(kiam_sts_assumerole_timing_seconds_count{service=\"kiam-server\", source_cluster=~\"$cluster\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "metadata handler latency (in secs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kiam_metadata_handler_latency_seconds_bucket{source_cluster=~\"$cluster\"}[1m])) by (le))",
     "legendFormat": "metadata handler latency "
    }
   ]
  },
  {
   "title": "Credentials responsetime",
   "type": "heatmap",
   "description": "Bucketed histogram of handler timings. Tagged by handler",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(kiam_metadata_handler_latency_seconds_bucket{handler=\"credentials\", source_cluster=~\"$cluster\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Replicas",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(kube_daemonset_status_number_available{namespace=\"$namespace\",daemonset=~\".*kiam-server\", source_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 10, "x": 2, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\".*kiam-server.*\", source_cluster=~\"$cluster\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Network traffic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\".*kiam-server-.*\", source_cluster=~\"$cluster\"}[$interval])) by (pod)",
       "legendFormat": "In {{pod}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\".*kiam-server-.*\", source_cluster=~\"$cluster\"}[$interval])) by (pod)",
       "legendFormat": "Out {{pod}}"
      }
     ]
    },
    {
     "title": "Desired Replicas",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(kube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\",daemonset=~\".*kiam-server\", source_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 10, "x": 2, "y": 28 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\".*kiam-server-.*\", source_cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 2, "y": 24 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\".*kiam-agent-.*\", source_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "roleHandler responsetime",
   "type": "heatmap",
   "description": "Bucketed histogram of handler timings. Tagged by handler",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(kiam_metadata_handler_latency_seconds_bucket{handler=\"roleName\", source_cluster=~\"$cluster\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(kube_daemonset_status_number_available{namespace=\"$namespace\",daemonset=~\".*kiam-agent\", source_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 2, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\".*kiam-agent.*\", source_cluster=~\"$cluster\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\".*kiam-agent-.*\", source_cluster=~\"$cluster\"}[$interval])) by (pod)",
     "legendFormat": "In {{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\".*kiam-agent-.*\", source_cluster=~\"$cluster\"}[$interval])) by (pod)",
     "legendFormat": "Out {{pod}}"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\",daemonset=~\".*kiam-agent\", source_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Grpc server stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc server handled total",
     "type": "graph",
     "description": "Total number of RPCs completed on the server, regardless of success or failure.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(grpc_server_handled_total{namespace=\"$namespace\",pod=~\".*kiam-.*\", source_cluster=~\"$cluster\"}[$interval])) by (grpc_code, grpc_method, pod)",
       "legendFormat": "{{grpc_method}} {{grpc_code}} {{pod}}"
      }
     ]
    },
    {
     "title": "grpc server started total",
     "type": "graph",
     "description": "Total number of RPCs started on the server.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(grpc_server_started_total{namespace=\"$namespace\",pod=~\".*kiam-server-.*\", source_cluster=~\"$cluster\"}[$interval])) by (grpc_method, pod)",
       "legendFormat": "{{grpc_method}} {{pod}}"
      }
     ]
    },
    {
     "title": "grpc server msg received total",
     "type": "graph",
     "description": "Total number of RPC stream messages received on the server.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(grpc_server_msg_received_total{namespace=\"$namespace\",pod=~\".*kiam-.*\", source_cluster=~\"$cluster\"}[$interval])) by (grpc_method, pod)",
       "legendFormat": "{{grpc_method}} {{pod}}"
      }
     ]
    },
    {
     "title": "grpc server msg sent total",
     "type": "graph",
     "description": "Total number of gRPC stream messages sent by the server.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(grpc_server_msg_sent_total{namespace=\"$namespace\",pod=~\".*kiam-.*\", source_cluster=~\"$cluster\"}[$interval])) by (grpc_method, pod)",
       "legendFormat": "{{grpc_method}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc client stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc client handled total",
     "type": "graph",
     "description": "Total number of RPCs completed by the client, regardless of success or failure.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(grpc_client_handled_total{namespace=\"$namespace\",pod=~\".*kiam-.*\", source_cluster=~\"$cluster\"}[$interval])) by (grpc_code, grpc_method, pod)",
       "legendFormat": "{{grpc_method}} {{grpc_code}} {{pod}}"
      }
     ]
    },
    {
     "title": "grpc client started total",
     "type": "graph",
     "description": "Total number of RPCs started on the client.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(grpc_client_started_total{namespace=\"$namespace\",pod=~\".*kiam-.*\", source_cluster=~\"$cluster\"}[$interval])) by (grpc_method, pod)",
       "legendFormat": "{{grpc_method}} {{pod}}"
      }
     ]
    },
    {
     "title": "grpc client msg received total",
     "type": "graph",
     "description": "Total number of RPC stream messages received on the client.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(grpc_client_msg_received_total{namespace=\"$namespace\",pod=~\".*kiam-.*\", source_cluster=~\"$cluster\"}[$interval])) by (grpc_method, pod)",
       "legendFormat": "{{grpc_method}} {{pod}}"
      }
     ]
    },
    {
     "title": "grpc client msg sent total",
     "type": "graph",
     "description": "Total number of gRPC stream messages sent by the client.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(grpc_client_msg_sent_total{namespace=\"$namespace\",pod=~\".*kiam-.*\", source_cluster=~\"$cluster\"}[$interval])) by (grpc_method, pod)",
       "legendFormat": "{{grpc_method}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "assumeRole timings",
   "type": "heatmap",
   "description": "Bucketed histogram of assumeRole timings",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(kiam_sts_assumerole_timing_seconds_bucket{source_cluster=~\"$cluster\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}