{
 "title": "Editorial Tray I18N",
 "tags": [
  "P13N",
  "RECO"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_namespace_created, source_cluster)"
    }
   },
   {
    "name": "service",
    "query": "editorial-tray-svc-apse1-0,discovery-editorial-tray,discovery-editorial-tray-apse1-0"
   },
   {
    "name": "tfServingContainer",
    "query": "tf-serving-apse1-0,tf-serving-apse1-1,tf-serving-apse1-2,tf-serving-euw1-0,discovery-tf-serving"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**[Editorial Tray Service](https://hotstar.atlassian.net/wiki/spaces/HP2/pages/3603857439/Ranking+collection+editorial+trays)** is ranking the contents in editorial tray. It shares the algo code with tpfy svc.\n\n\nThe config of the dashboard is [editorial-tray-i18n.json](https://github.com/hotstar/kube-grafana/blob/master/grafana-dashboards/p13n/editorial-tray-i18n.json). The metrics below are queried from Prometheus. The data are from [persona-reco-service](https://github.com/hotstar/persona-reco-service)."
   }
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "CPU usage percentage" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$service.*\", source_cluster=\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes", "label": "memory usage percentage" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$service.*\", source_cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])",
       "legendFormat": "{{pod}} ({{gc}})"
      }
     ]
    },
    {
     "title": "Container Error Count (stacked) [Alert]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none", "label": "number of error" }
     ],
     "targets": [
      {
       "expr": "sum by (reason) (increase(kube_pod_container_status_terminated_reason{namespace=\"$namespace\", pod=~\"$service.*\", source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "terminated - {{reason}}"
      },
      {
       "expr": "sum(increase(kube_pod_container_status_terminated_reason{namespace=\"personalisation\", pod=~\"discovery-editorial-tray.*\", source_cluster=\"hs-eks-prod6-api-apse1\"}[1m]))",
       "legendFormat": "terminated - total"
      }
     ]
    },
    {
     "title": "Average RPM For Each Core (stacked)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "rpm", "label": "request count per minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(p13n_reco_request_latency_ms_count{namespace=\"$namespace\", pod=~\"$service.*\"}[1m])) / sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$service.*\"}[1m]))",
       "legendFormat": "RPM"
      }
     ]
    }
   ]
  },
  {
   "title": "TF Serving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "number of cores" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$tfServingContainer\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes", "label": "memory usage percentage" }
     ],
     "targets": [
      {
       "expr": "container_memory_max_usage_bytes{namespace=\"$namespace\",container=\"$tfServingContainer\", source_cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rank Volume (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "rpm", "label": "prediction count per minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(p13n_reco_tensorflow_predict_time_ms_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (status, model)",
       "legendFormat": "{{model}} ({{status}})"
      }
     ]
    },
    {
     "title": "Rank Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "ms", "label": "rank latency time" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(p13n_reco_tensorflow_predict_time_ms_bucket{namespace=\"$namespace\", service=\"$service\"}[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(p13n_reco_tensorflow_predict_time_ms_bucket{namespace=\"$namespace\", service=\"$service\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(p13n_reco_tensorflow_predict_time_ms_bucket{namespace=\"$namespace\", service=\"$service\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Pod Request Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tensorflow_serving_service_predict_time_ms_count{namespace=\"$namespace\", service=\"$tfServingContainer\", source_cluster=\"$cluster\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Model Request Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tensorflow_serving_service_predict_time_ms_count{namespace=\"$namespace\", service=\"$tfServingContainer\"}[1m])) by (model, status)",
       "legendFormat": "{{model}}:{{status}}"
      }
     ]
    },
    {
     "title": "Predict API latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(tensorflow_serving_service_predict_time_ms_bucket{namespace=\"$namespace\",service=\"$tfServingContainer\",source_cluster=\"$cluster\"}[1m])) by (le, model))",
       "legendFormat": "{{model}}-p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tensorflow_serving_service_predict_time_ms_bucket{namespace=\"$namespace\",service=\"$tfServingContainer\",source_cluster=\"$cluster\"}[1m])) by (le, model))",
       "legendFormat": "{{model}}-p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tensorflow_serving_service_predict_time_ms_bucket{namespace=\"$namespace\",service=\"$tfServingContainer\",source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Fetch Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cache_status) (increase(p13n_reco_mget_fetch_cache_count_total{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{cache_status}}"
      }
     ]
    },
    {
     "title": "Cache Save Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(p13n_reco_mget_save_count_total{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "sum"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_ec_cache_hits_average{dimension_CacheClusterId=~\"p13n-editorial-tray.*\"}",
       "legendFormat": "{{dimension_CacheClusterId}}  Hits"
      },
      {
       "expr": "aws_ec_cache_misses_average{dimension_CacheClusterId=~\"p13n-editorial-tray.*\"}",
       "legendFormat": "{{dimension_CacheClusterId}} miss"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "aws_ec_curr_connections_average{dimension_CacheClusterId=~\"p13n-editorial-tray.*\"}",
       "legendFormat": "{{dimension_CacheClusterId}}  Hits"
      }
     ]
    },
    {
     "title": "Engine CPU utilization ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "aws_ec_engine_cpuutilization_average{dimension_CacheClusterId=~\"p13n-editorial-tray.*\"}",
       "legendFormat": "{{dimension_CacheClusterId}}"
      }
     ]
    },
    {
     "title": "CPU utilization ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "aws_ec_cpuutilization_average{dimension_CacheClusterId=~\"p13n-editorial-tray.*\"}",
       "legendFormat": "{{dimension_CacheClusterId}}"
      }
     ]
    },
    {
     "title": "Freeable memory average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "aws_ec_freeable_memory_average{dimension_CacheClusterId=~\"p13n-editorial-tray.*\"}",
       "legendFormat": "{{dimension_CacheClusterId}}"
      }
     ]
    },
    {
     "title": "Bytes Used For Cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_ec_bytes_used_for_cache_average{dimension_CacheClusterId=~\"p13n-editorial-tray.*\"}",
       "legendFormat": "{{dimension_CacheClusterId}}"
      }
     ]
    },
    {
     "title": "Evictions ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_ec_evictions_average{dimension_CacheClusterId=~\"p13n-editorial-tray.*\"}",
       "legendFormat": "{{dimension_CacheClusterId}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Throttler Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throttler Volume (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "number of throttle result" }
     ],
     "targets": [
      {
       "expr": "sum(increase(throttler_request_total{namespace=\"$namespace\",  service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (throttle)",
       "legendFormat": "{{throttle}}"
      }
     ]
    },
    {
     "title": "AB Degradation Volume (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "number of throttle result" }
     ],
     "targets": [
      {
       "expr": "sum(increase(throttle_ab_degradation_result_total{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (throttle)",
       "legendFormat": "ab-{{throttle}}"
      }
     ]
    },
    {
     "title": "Throttle Concurrency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "concurrency of throttler" }
     ],
     "targets": [
      {
       "expr": "throttler_concurrency{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Throttler Possibility",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "percent", "label": "throttle probability " }
     ],
     "targets": [
      {
       "expr": "throttler_possibility_percentage{namespace=\"$namespace\",  service=\"$service\", source_cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cohort ID",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (id) (increase(p13n_reco_cohort_id_count_total{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Subs Type (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "number of user" }
     ],
     "targets": [
      {
       "expr": "sum(increase(throttler_request_total{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (user)",
       "legendFormat": "{{user}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Volume [Alert]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "rpm", "label": "request count per minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(p13n_reco_request_latency_ms_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (status)",
       "legendFormat": "request-{{status}}"
      }
     ]
    },
    {
     "title": "RPC Latency [Alert]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(p13n_reco_request_latency_ms_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "p9999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(p13n_reco_request_latency_ms_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(p13n_reco_request_latency_ms_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "RPC Server Step Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "rpm", "label": "count per minute" }
     ],
     "targets": [
      {
       "displayType": "Regular",
       "expr": "sum(increase(p13n_reco_step_latency_ms_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (step)",
       "legendFormat": "{{step}}",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Latency Breakdown",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(p13n_reco_step_latency_ms_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le, step))",
       "legendFormat": "{{step}}-p99"
      }
     ]
    },
    {
     "title": "External Service Request Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(circuit_breaker_latency_milliseconds_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (name, success)",
       "legendFormat": "{{name}}-{{success}}"
      }
     ]
    },
    {
     "title": "External Service Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(circuit_breaker_latency_milliseconds_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le, name))",
       "legendFormat": "{{name}}-p99"
      }
     ]
    },
    {
     "title": "Editorial Tray Service Circuit Open (stacked) [Alert]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "number of errors" }
     ],
     "targets": [
      {
       "expr": "sum(circuit_breaker_open_status{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Controller Exception Count (stacked) [Alert]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "number of exceptions" }
     ],
     "targets": [
      {
       "expr": "sum by (name, component) (increase(controller_exception_count_total{job=~\"$service.*\",namespace=\"$namespace\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{component}}-{{name}}"
      }
     ]
    },
    {
     "title": "Step Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(p13n_reco_tpfy_tensorflow_algorithm_predict_time_ms_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le, stage))",
       "legendFormat": "P50-{{stage}}"
      }
     ]
    },
    {
     "title": "AB Experiment(stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (exp) (increase(p13n_reco_ab_hit_count_total{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{exp}}"
      }
     ]
    },
    {
     "title": "Pods Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"personalisation\", pod=~\"discovery-editorial-tray.*\", source_cluster=\"hs-eks-prod6-api-apse1\"}) by (source_cluster)",
       "legendFormat": "apse1-0"
      }
     ]
    }
   ]
  },
  {
   "title": "External Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "AB Request Volume (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "rpm", "label": "request count per minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(circuit_breaker_latency_milliseconds_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", name=\"ab\"}[1m])) by (success)",
       "legendFormat": "ab-{{success}}"
      }
     ]
    },
    {
     "title": "AB Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(circuit_breaker_latency_milliseconds_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", name=\"ab\"}[1m])) by (le))",
       "legendFormat": "ab-p99"
      }
     ]
    },
    {
     "title": "Watch History Request Volume (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "rpm", "label": "request count per minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(circuit_breaker_latency_milliseconds_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", name=\"feature_store_client\"}[1m])) by (success)",
       "legendFormat": "feature-store-{{success}}"
      }
     ]
    },
    {
     "title": "Feature Store Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(circuit_breaker_latency_milliseconds_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", name=\"feature_store_client\"}[1m])) by (le))",
       "legendFormat": "feature-store-p99"
      }
     ]
    },
    {
     "title": "Redis Request Volume (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "rpm", "label": "request count per minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(circuit_breaker_latency_milliseconds_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", name=\"redis\"}[1m])) by (success)",
       "legendFormat": "redis-{{success}}"
      }
     ]
    },
    {
     "title": "Redis Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(circuit_breaker_latency_milliseconds_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", name=\"redis\"}[1m])) by (le))",
       "legendFormat": "redis-p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Steps Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch AB Volume (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "rpm", "label": "request count per minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(p13n_reco_step_latency_ms_count{namespace=\"$namespace\", service=\"$service\", step=\"fetch_ab\"}[1m])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Fetch AB Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(p13n_reco_step_latency_ms_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", step=\"fetch_ab\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(p13n_reco_step_latency_ms_bucket{namespace=\"$namespace\", service=\"editorial-tray-svc-$tenant\", source_cluster=\"$cluster\", step=\"fetch_ab\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(p13n_reco_step_latency_ms_bucket{namespace=\"$namespace\", service=\"editorial-tray-svc-$tenant\", source_cluster=\"$cluster\", step=\"fetch_ab\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Fetch Feature Volume (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "rpm", "label": "request count per minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(p13n_reco_step_latency_ms_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", step=\"fetch_feature\"}[1m])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Fetch Feature Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(p13n_reco_step_latency_ms_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", step=\"fetch_feature\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(p13n_reco_step_latency_ms_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", step=\"fetch_feature\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(p13n_reco_step_latency_ms_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", step=\"fetch_feature\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  },
  {
   "title": "Algorithms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Algorithm Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "number of prediction" }
     ],
     "targets": [
      {
       "expr": "sum(increase(p13n_reco_algorithm_predict_total{namespace=\"$namespace\",  service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (algo_type)",
       "legendFormat": "{{algo_type}}"
      }
     ]
    },
    {
     "title": "Algorithm Result Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "status of algorithm result" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (increase(p13n_reco_editorial_tray_algorithm_result_count_total{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Watch History Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "length of watch history" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(p13n_reco_external_service_items_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", name=\"watch.history\"}[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(p13n_reco_external_service_items_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", name=\"watch.history\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.9999, sum(rate(p13n_reco_external_service_items_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\", name=\"watch.history\"}[1m])) by (le))",
       "legendFormat": "p9999"
      }
     ]
    },
    {
     "title": "Simple Reco Algorithm Volume Breakdown",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "rpm", "label": "prediction per minute" }
     ],
     "targets": [
      {
       "expr": "sum(increase(p13n_reco_tpfy_tensorflow_algorithm_predict_time_ms_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Transformed request volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "requests transformed / min" }
     ],
     "targets": [
      {
       "expr": "sum(increase(p13n_reco_impr_deranker_deranked_candidate_count_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "deranker"
      },
      {
       "expr": "sum(increase(p13n_reco_impr_discounter_discounted_candidate_count_count{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "discounter"
      }
     ]
    },
    {
     "title": "Transformed candidate volume",
     "type": "graph",
     "description": "Number of candidates transformed within each tray",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      {
       "format": "short",
       "label": "candidates transformed / request"
      }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(p13n_reco_impr_deranker_deranked_candidate_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "[P90] deranked"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(p13n_reco_impr_deranker_deranked_candidate_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "[P95] deranked"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(p13n_reco_impr_deranker_deranked_candidate_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "[P99] deranked"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(p13n_reco_impr_deranker_deranked_candidate_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "[P999] deranked"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(p13n_reco_impr_discounter_discounted_candidate_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "[P90] discounted"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(p13n_reco_impr_discounter_discounted_candidate_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "[P95] discounted"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(p13n_reco_impr_discounter_discounted_candidate_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "[P99] discounted"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(p13n_reco_impr_discounter_discounted_candidate_count_bucket{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m])) by (le))",
       "legendFormat": "[P999] discounted"
      }
     ]
    },
    {
     "title": "boosting candidate volume",
     "type": "graph",
     "description": "Number of candidates transformed within each tray",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      {
       "format": "short",
       "label": "candidates transformed / request"
      }
     ],
     "targets": [
      {
       "expr": "sum by (country, trayId, count) (increase(p13n_reco_editorial_tray_boosting_candidates_total{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{country}}, {{trayId}}, count"
      }
     ]
    }
   ]
  },
  {
   "title": "Algorithms 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missed Fids",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (model, slot_id) (increase(p13n_reco_tpfy_missed_fids{namespace=\"$namespace\", service=\"$service\", source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{model}}-{{slot_id}}"
      }
     ]
    }
   ]
  }
 ]
}