{
 "title": "AB Testing Service",
 "tags": [ "ab-testing" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas, source_cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AB Service API latency alert - MENA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "API latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod-api-euw1\",service =~ \"ab-service\", url = \"/api/experiment/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99-/api/experiment/all"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod-api-euw1\",service =~ \"ab-service\", url = \"/api/filter/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99-/api/filter/all"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod-api-euw1\",service =~ \"ab-service\", url = \"/api/targetgroup/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99-/api/targetgroup/all"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod-api-euw1\",service =~ \"ab-service\", url = \"/graphql\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99-/graphql"
      }
     ]
    }
   ]
  },
  {
   "title": "AB Service API latency alert - SGP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "API latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod4-api-apse1\",service =~ \"ab-service\", url = \"/api/experiment/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99-/api/experiment/all"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod4-api-apse1\",service =~ \"ab-service\", url = \"/api/filter/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99-/api/filter/all"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod4-api-apse1\",service =~ \"ab-service\", url = \"/api/targetgroup/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99-/api/targetgroup/all"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod4-api-apse1\",service =~ \"ab-service\", url = \"/graphql\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99-/graphql"
      }
     ]
    }
   ]
  },
  {
   "title": "AB Ingestor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "AB-IngestorThroughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service =~\"ab-ingestor\", url = \"/log/upload\",source_cluster=\"$cluster\"}[$__rate_interval])*60)",
       "legendFormat": "/log/upload"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service =~\"ab-ingestor\", url = \"/allocation/upload\",source_cluster=\"$cluster\"}[$__rate_interval])*60)",
       "legendFormat": "/allocation/upload"
      }
     ]
    },
    {
     "title": "Per pod CPU usage of ab-ingestor",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ab-ingestor-.*\",source_cluster=\"$cluster\"}[1m])) by (pod) / sum(container_spec_cpu_quota{pod=~\"ab-ingestor-.*\",source_cluster=\"$cluster\"}/container_spec_cpu_period{pod=~\"ab-ingestor-.*\",source_cluster=\"$cluster\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_deployment_spec_replicas{deployment=~\"ab-ingestor.*$\", namespace=\"$namespace\",source_cluster=\"$cluster\", deployment!~\".*canary\"})",
       "legendFormat": "Service"
      }
     ]
    },
    {
     "title": "Per pod Memory usage of ab-ingestor",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{pod=~\"ab-ingestor-.*\", source_cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "AB ingestor allocation upload latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-ingestor\", url = \"/allocation/upload\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-ingestor\", url = \"/allocation/upload\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-ingestor\", url = \"/allocation/upload\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-ingestor\", url = \"/allocation/upload\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "kafka msg sent RPM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ab_ingestor_msg_sent_counter_total{service=~\"ab-ingestor\",source_cluster=\"$cluster\"}[1m]) * 60)",
       "legendFormat": "kafka msg sent RPM"
      }
     ]
    },
    {
     "title": "Caller RPM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (caller, version, channel) (rate(ab_ingestor_caller_counter_total{service=~\"ab-ingestor\",source_cluster=\"$cluster\",url=\"/allocation/upload\"}[1m]) * 60)"
      }
     ]
    },
    {
     "title": "prod.ab.bucketing.results bytes-in per min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(BrokerTopicMetrics_OneMinuteRate{name=\"BytesInPerSec\", application=\"kafka-analytics\",env=\"prod\",topic=\"prod.ab.bucketing.results\"}[1m]*60)",
       "legendFormat": "bytes-in"
      }
     ]
    },
    {
     "title": "Log upload RPM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (caller, version, channel, tag, err_info) (rate(ab_ingestor_log_upload_counter_total{service=~\"ab-ingestor\",source_cluster=\"$cluster\"}[1m]) * 60)"
      }
     ]
    },
    {
     "title": "prod.mena.ab.bucketing.results bytes-In per sec",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "BrokerTopicMetrics",
       "query": "SELECT sum(\"OneMinuteRate\") FROM \"BrokerTopicMetrics\" WHERE (\"typeName\" =~ /type=BrokerTopicMetrics,name=BytesInPerSec,topic=$topic/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "OneMinuteRate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "BytesInPerSec" },
        { "condition": "AND", "key": "topic", "operator": "=", "value": "prod.mena.ab.bucketing.results" }
       ]
      }
     ]
    },
    {
     "title": "Kafka msg send fail RPM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (cause) (rate(ab_ingestor_msg_send_fail_counter_total{service=~\"ab-ingestor\",source_cluster=\"$cluster\"}[1m]) * 60)"
      }
     ]
    },
    {
     "title": "Kafka msg processing RPM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status, exp_name) (rate(ab_ingestor_msg_processing_counter_total{service=~\"ab-ingestor\",source_cluster=\"$cluster\"}[1m]) * 60)"
      }
     ]
    },
    {
     "title": "Api error RPM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (url, error, caller) (rate(ab_ingestor_api_err_counter_total{service=~\"ab-ingestor\",source_cluster=\"$cluster\"}[1m]) * 60)"
      }
     ]
    }
   ]
  },
  {
   "title": "AB Sevice eks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "AB-Service Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service =~ \"ab-service\",url!=\"/health\",source_cluster=\"$cluster\"}[$__rate_interval])*60)",
       "legendFormat": "Service-throughput"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service =~\"ab-service\", source_cluster=\"$cluster\"}[$__rate_interval])*60) by (url)",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": "AB service experiment sync latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/experiment/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/experiment/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/experiment/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/experiment/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "AB service graphql latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/graphql\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/graphql\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/graphql\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/graphql\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "AB service filter sync latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/filter/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/filter/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/filter/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/filter/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Per pod Memory usage of ab-service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{pod=~\"ab-service-.*\", source_cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "AB service targetgroup sync latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/targetgroup/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/targetgroup/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/targetgroup/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/targetgroup/all\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Pod count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_deployment_spec_replicas{deployment=~\"ab-service.*$\", namespace=\"$namespace\",source_cluster=\"$cluster\", deployment!~\".*canary\"})",
       "legendFormat": "Service"
      }
     ]
    },
    {
     "title": "AB service user/groups/v2 latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/user/groups/v2\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/user/groups/v2\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/user/groups/v2\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\",service =~ \"ab-service\", url = \"/api/user/groups/v2\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Api error RPM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (url, error, caller) (rate(ab_testing_service_api_counter_total{service=~\"ab-service\",source_cluster=\"$cluster\"}[1m]) * 60)"
      }
     ]
    },
    {
     "title": "Per pod CPU usage of ab-service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ab-service-.*\",source_cluster=\"$cluster\"}[1m])) by (pod) / sum(container_spec_cpu_quota{pod=~\"ab-service-.*\",source_cluster=\"$cluster\"}/container_spec_cpu_period{pod=~\"ab-service-.*\",source_cluster=\"$cluster\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AB Portal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ambassador AB-Portal Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"cluster_ab_portal.*\"}[$__rate_interval])*60) by (envoy_cluster_name)",
       "legendFormat": "Ambassador-throughput"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service =~ \"ab-portal\",url!=\"/health\",source_cluster=\"$cluster\"}[$__rate_interval])*60)",
       "legendFormat": "Service-throughput"
      }
     ]
    },
    {
     "title": "AB portal latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{service =~ \"ab-portal\", url != \"/health\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "{{url}}_p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{service =~ \"ab-portal\", url != \"/health\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "{{url}}_p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{service =~ \"ab-portal\", url != \"/health\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "{{url}}_p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{service =~ \"ab-portal\", url != \"/health\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (le, url))",
       "legendFormat": "{{url}}_p50"
      }
     ]
    },
    {
     "title": "Per pod Memory usage of ab-portal",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{pod=~\"ab-portal-.*\",source_cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Per pod CPU usage of ab-portal",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ab-portal-.*\",source_cluster=\"$cluster\"}[1m])) by (pod) / sum(container_spec_cpu_quota{pod=~\"ab-portal-.*\",source_cluster=\"$cluster\"}/container_spec_cpu_period{pod=~\"ab-portal-.*\",source_cluster=\"$cluster\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(kube_deployment_spec_replicas{deployment=~\"ab-portal.*$\", namespace=\"$namespace\",source_cluster=\"$cluster\", deployment!~\".*canary\"})",
       "legendFormat": "Portal"
      }
     ]
    }
   ]
  },
  {
   "title": "Gorm SDK and Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gorm SDK Stats - Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(gorm_dbstats_idle{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_dbstats_idle"
      },
      {
       "expr": "max(gorm_dbstats_in_use{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_dbstats_in_use"
      },
      {
       "expr": "max(gorm_dbstats_max_idle_closed{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_dbstats_max_idle_closed"
      },
      {
       "expr": "max(gorm_dbstats_max_idletime_closed{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_dbstats_max_idletime_closed"
      },
      {
       "expr": "max(gorm_dbstats_max_lifetime_closed{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_dbstats_max_lifetime_closed"
      },
      {
       "expr": "max(gorm_dbstats_max_open_connections{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_dbstats_max_open_connections"
      },
      {
       "expr": "max(gorm_dbstats_open_connections{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_dbstats_open_connections"
      }
     ]
    },
    {
     "title": "MYSQL DB Stats - Client info",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(gorm_status_Aborted_clients{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_status_Aborted_clients"
      },
      {
       "expr": "max(gorm_status_Aborted_connects{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_status_Aborted_connects"
      }
     ]
    },
    {
     "title": "Gorm SDK Stats - Connection wait",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(gorm_dbstats_wait_duration{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_dbstats_wait_duration"
      },
      {
       "expr": "max(gorm_dbstats_wait_count{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_dbstats_wait_count"
      }
     ]
    },
    {
     "title": "MYSQL DB Stats - Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(gorm_status_Connection_errors_accept{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_status_Connection_errors_accept"
      },
      {
       "expr": "max(gorm_status_Connection_errors_internal{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_status_Connection_errors_internal"
      },
      {
       "expr": "max(gorm_status_Connection_errors_max_connections{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_status_Connection_errors_max_connections"
      },
      {
       "expr": "max(gorm_status_Connection_errors_peer_address{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_status_Connection_errors_peer_address"
      },
      {
       "expr": "max(gorm_status_Connection_errors_select{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_status_Connection_errors_select"
      },
      {
       "expr": "max(gorm_status_Connection_errors_tcpwrap{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_status_Connection_errors_tcpwrap"
      },
      {
       "expr": "max(gorm_status_Connections{service =~\"ab-service\",source_cluster=\"$cluster\"}[$__interval])",
       "legendFormat": "gorm_status_Connections(Total Connection Attempts so far on SQL)"
      }
     ]
    },
    {
     "title": "MYSQL DB Stats - network info",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(gorm_status_Bytes_sent{service =~\"ab-service\",source_cluster=\"$cluster\"}[1m])",
       "legendFormat": "gorm_status_Bytes_sent"
      },
      {
       "expr": "sum(gorm_status_Bytes_received{service =~\"ab-service\",source_cluster=\"$cluster\"}[1m])",
       "legendFormat": "gorm_status_Bytes_received"
      }
     ]
    }
   ]
  },
  {
   "title": "In-Memory Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Items",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(ab_testing_in_mem_cache_item_count{source_cluster=~'$cluster', service='ab-service'}[$__interval])",
       "legendFormat": "Cache Items"
      }
     ]
    },
    {
     "title": "Cache Hit/Miss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(ab_testing_in_mem_cache_counter_total{source_cluster=~'$cluster', service='ab-service'}[$__interval])) by (cacheOperation, status)",
       "legendFormat": "Cache - {{cacheOperation}} - {{status}}"
      }
     ]
    }
   ]
  }
 ]
}