{
 "title": "AP Timer Turner",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "data_source", "query": "prometheus" },
   { "name": "service_name", "label": "service_name", "query": "timer-turner" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_labels{label_app=~\"$service_name\", datacenter=~\"$data_center\"}, source_cluster)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(http_timer_turner_req_count{service=\"$service_name\", source_cluster=~\"${cluster}\"}, pod)"
    }
   },
   {
    "name": "data_center",
    "query": {
     "query": "label_values(kube_pod_labels{label_app=~\"$service_name\"}, datacenter)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Total Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_labels{label_app=\"$service_name\", source_cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Pod Avg Cpu",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{service=\"$service_name\", datacenter=\"$data_center\"}[1m]) / 8"
      }
     ]
    },
    {
     "title": "RPM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_timer_turner_req_count{service=\"$service_name\", datacenter=\"$data_center\", req=\"/api/v1/delay\"}[1m])) by (req)",
       "legendFormat": "register"
      }
     ]
    },
    {
     "title": "Scan Speed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mysql_timer_turner_fetch_count{service=\"$service_name\", datacenter=~\"$data_center\", source_cluster=~\"$cluster\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "fetch"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_timer_turner_req_count{service=\"$service_name\", req=\"/api/v1/delay\", pod=~\"$pod\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}[1m])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "response time pxx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_timer_turner_req_time_hist_bucket{service=\"$service_name\", source_cluster=\"$cluster\", datacenter=\"$data_center\", req=\"/api/v1/delay\"}[1m])) by (le))",
       "legendFormat": "response-time-p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_timer_turner_req_time_hist_bucket{service=\"$service_name\", source_cluster=\"$cluster\", datacenter=\"$data_center\", req=\"/api/v1/delay\"}[1m])) by (le))",
       "legendFormat": "response-time-p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_timer_turner_req_time_hist_bucket{service=\"$service_name\", source_cluster=\"$cluster\", datacenter=\"$data_center\", req=\"/api/v1/delay\"}[1m])) by (le))",
       "legendFormat": "response-time-p90"
      }
     ]
    },
    {
     "title": "Scan Speed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mysql_timer_turner_fetch_count{service=\"$service_name\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}[1m])) by (table, target_topic, status)",
       "legendFormat": "{{table}}-{{target_topic}}-{{status}}"
      }
     ]
    },
    {
     "title": "scan delay time pxx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(mysql_timer_turner_delay_time_hist_bucket{service=\"$service_name\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}[1m])) by (le))",
       "legendFormat": "response-time-p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(mysql_timer_turner_delay_time_hist_bucket{service=\"$service_name\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}[1m])) by (le))",
       "legendFormat": "response-time-p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(mysql_timer_turner_delay_time_hist_bucket{service=\"$service_name\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}[1m])) by (le))",
       "legendFormat": "response-time-p90"
      }
     ]
    }
   ]
  },
  {
   "title": "System Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "process cpu usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{service=\"$service_name\", pod=~\"$pod\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}[1m]/8)) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{service=\"$service_name\", pod=~\"$pod\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "open file descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{service=\"$service_name\", pod=~\"$pod\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OS threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{service=\"$service_name\", pod=~\"$pod\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}"
      }
     ]
    },
    {
     "title": "memory alloc",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes_total{datacenter=\"$data_center\",pod=~\"$pod\",service=\"$service_name\",source_cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "heap in use memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{service=\"$service_name\", pod=~\"$pod\", source_cluster=\"$cluster\", datacenter=\"$data_center\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}