{
 "title": "Frontier Zplay Admin",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_namespace_created, source_cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{source_cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "QoS Module Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "QoS Module Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hotstar_zplay_admin_qos_module_enabled\n",
       "legendFormat": "in"
      }
     ]
    }
   ]
  },
  {
   "title": "Routing Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_routing_manager_requests_total{source_cluster=\"$cluster\", namespace=\"$namespace\", service=\"frontier-zplay-v2-admin-app\"})[1m])",
       "legendFormat": "RM - Total Requests"
      }
     ]
    },
    {
     "title": "Routing Manager Conversion Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(hotstar_zplay_admin_dcs_scheduler_processing_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(hotstar_zplay_admin_dcs_scheduler_processing_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hotstar_zplay_admin_dcs_scheduler_processing_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hotstar_zplay_admin_dcs_scheduler_processing_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Routing Manager Weight Update Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(hotstar_zplay_admin_dcs_scheduler_weight_update_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(hotstar_zplay_admin_dcs_scheduler_weight_update_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hotstar_zplay_admin_dcs_scheduler_weight_update_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hotstar_zplay_admin_dcs_scheduler_weight_update_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Total Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_routing_manager_failures_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "failures"
      }
     ]
    },
    {
     "title": "Incorrect Input weights",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_routing_manager_incorrect_input_weights_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "incorrect input weights"
      }
     ]
    },
    {
     "title": "Output Validation Success",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(sum(hotstar_zplay_admin_routing_manager_output_validation_success_total{source_cluster=\"$cluster\", namespace=\"$namespace\"})[1m])",
       "legendFormat": "success"
      }
     ]
    },
    {
     "title": "Primary Adj > Allowed Dev",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_routing_manager_primary_adj_grtr_than_allowed_dev_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "RPM"
      }
     ]
    },
    {
     "title": "Output Validation Failed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_routing_manager_output_validation_failures_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "failures"
      }
     ]
    },
    {
     "title": "Infinite Loops Detected",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_routing_manager_infinite_loop_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "infinite loops"
      }
     ]
    }
   ]
  },
  {
   "title": "QoS Module ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_qos_requests_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "RPM - {{country}}"
      }
     ]
    },
    {
     "title": "QoS Module Requests Success",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_qos_requests_success_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "RPM - {{country}}"
      }
     ]
    },
    {
     "title": "QoS Api Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(hotstar_zplay_admin_qos_module_response_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(hotstar_zplay_admin_qos_module_response_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hotstar_zplay_admin_qos_module_response_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hotstar_zplay_admin_qos_module_response_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "HTTP Error Status Code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_qos_requests_error_http_status_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country, status)",
       "legendFormat": "{{country}}-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Redis Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_reads_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}:reads"
      },
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_write_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}:writes"
      }
     ]
    },
    {
     "title": "Total Redis Read/Write Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_read_failures_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}-redis-reads"
      },
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_write_failures_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}-redis-writes"
      }
     ]
    },
    {
     "title": "Redis Connection Success",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_connection_request_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "Total Connection Requests - {{country}}"
      }
     ]
    },
    {
     "title": "Redis Connection Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_connection_error_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "Redis Key Not Found",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_key_not_found_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "Redis Lock",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_lock_acquired_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}} - Lock Acquired"
      },
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_lock_acquisition_failed_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}} - Lock Acquisition Failed"
      },
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_lock_release_failed_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}} - Lock Release Failed"
      }
     ]
    },
    {
     "title": "Redis Data Parsing Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_data_parsing_error_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "Redis Cohort Key Created ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_redis_cohort_key_created_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}} - {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Python Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Collections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(python_gc_collections_total{source_cluster=\"$cluster\", namespace=\"$namespace\", service=\"frontier-zplay-v2-admin-app\"})[1m]) by (generation)"
      }
     ]
    },
    {
     "title": "GC Objects Collected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(python_gc_objects_collected_total{source_cluster=\"$cluster\", namespace=\"$namespace\", service=\"frontier-zplay-v2-admin-app\"})[1m]) by (generation)"
      }
     ]
    },
    {
     "title": "GC Objects Uncollectable",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(python_gc_objects_uncollectable_total{source_cluster=\"$cluster\", namespace=\"$namespace\", service=\"frontier-zplay-v2-admin-app\"})[1m]) by (generation)"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_virtual_memory_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", service=\"frontier-zplay-v2-admin-app\"}) ",
       "legendFormat": "Virtual"
      },
      {
       "expr": "sum(process_resident_memory_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", service=\"frontier-zplay-v2-admin-app\"}) ",
       "legendFormat": "Resident"
      }
     ]
    }
   ]
  },
  {
   "title": "DynamoDb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "DynamoDb Saves",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_ddb_save_success_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}:saves"
      }
     ]
    },
    {
     "title": "Supply Map Not found",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_supply_map_not_found_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}:saves"
      }
     ]
    }
   ]
  },
  {
   "title": "DCS Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "DCS Scheduler Run Counts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_scheduler_run_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "Totals"
      }
     ]
    },
    {
     "title": "DCS Scheduler Run Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_scheduler_start_error_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "Totals"
      }
     ]
    },
    {
     "title": "No Allowed Cohorts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_scheduler_no_allowed_cohorts_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "DCS scheduler Supply Map fetch success",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_scheduler_supply_map_fetch_success_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "DCS scheduler Supply Map fetch failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_scheduler_supply_map_fetch_failed_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country,cohort)",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "Cdn Score Not found",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_scheduler_cdn_score_not_found_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country, cohort)",
       "legendFormat": "{{country}} - {{cohort}}"
      }
     ]
    },
    {
     "title": "Invalid Input",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_scheduler_invalid_input_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "Precondition Not Met",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_scheduler_precondition_not_met_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country)",
       "legendFormat": "{{country}} "
      }
     ]
    },
    {
     "title": "DCS State Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_state_update_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country, state, cohort)",
       "legendFormat": "{{country}} - {{cohort}} - {{state}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Argus Fetches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Argus Api Requests by Status Code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_collector_argus_metrics_fetches_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country, status_code, metric)",
       "legendFormat": "Totals"
      }
     ]
    },
    {
     "title": "Argus Api - Response Times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(hotstar_zplay_admin_dcs_scheduler_argus_api_response_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(hotstar_zplay_admin_dcs_scheduler_argus_api_response_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hotstar_zplay_admin_dcs_scheduler_argus_api_response_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hotstar_zplay_admin_dcs_scheduler_argus_api_response_time_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Argus Api Response Data Value Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_collector_argus_data_value_error_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country, metric)",
       "legendFormat": "Totals"
      }
     ]
    },
    {
     "title": "Argus Api Retries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_collector_argus_metrics_fetch_retry_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country, metric)",
       "legendFormat": "Totals"
      }
     ]
    },
    {
     "title": "Argus Api Max Retries exceeded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hotstar_zplay_admin_dcs_collector_argus_metrics_fetch_max_retry_total{source_cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (country, metric)",
       "legendFormat": "Totals"
      }
     ]
    }
   ]
  }
 ]
}