{
 "title": "Adtech Shifu RDS",
 "tags": [ "shifu" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "svc_name",
    "query": {
     "query": "label_values(aws_rds_info, tag_kubernetes_io_service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$svc_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "svc_name",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_cpuutilization_average{dimension_DBClusterIdentifier!=\"\", dimension_Role=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_DBClusterIdentifier}}"
      }
     ]
    },
    {
     "title": "Database Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_database_connections_average{dimension_Role!=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_Role}}"
      }
     ]
    },
    {
     "title": "Freeable Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_freeable_memory_average{dimension_DBInstanceIdentifier!=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_DBInstanceIdentifier}}"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "aws_rds_write_latency_average{dimension_Role=\"WRITER\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "write latency"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "aws_rds_read_latency_average{dimension_Role!=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_Role}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$svc_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_cpuutilization_average{dimension_DBClusterIdentifier!=\"\", dimension_Role=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_DBClusterIdentifier}}"
      }
     ]
    },
    {
     "title": "Database Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_database_connections_average{dimension_Role!=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_Role}}"
      }
     ]
    },
    {
     "title": "Freeable Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_freeable_memory_average{dimension_DBInstanceIdentifier!=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_DBInstanceIdentifier}}"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "aws_rds_write_latency_average{dimension_Role=\"WRITER\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "write latency"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "aws_rds_read_latency_average{dimension_Role!=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_Role}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$svc_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_cpuutilization_average{dimension_DBClusterIdentifier!=\"\", dimension_Role=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_DBClusterIdentifier}}"
      }
     ]
    },
    {
     "title": "Database Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_database_connections_average{dimension_Role!=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_Role}}"
      }
     ]
    },
    {
     "title": "Freeable Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_freeable_memory_average{dimension_DBInstanceIdentifier!=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_DBInstanceIdentifier}}"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "aws_rds_write_latency_average{dimension_Role=\"WRITER\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "write latency"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "aws_rds_read_latency_average{dimension_Role!=\"\"} and on (name) aws_rds_info{tag_kubernetes_io_service_name=\"$svc_name\"}",
       "legendFormat": "{{dimension_Role}}"
      }
     ]
    }
   ]
  }
 ]
}