{
 "title": "Tray Management Portal Copy",
 "tags": [
  "P13N",
  "RECO"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load Failure [alert]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (p13n_tray_portal_load_failure{namespace=\"$namespace\"})",
     "legendFormat": "{{type}}-load-failure"
    }
   ]
  },
  {
   "title": "Load Item Failure [alert]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (increase(p13n_tray_portal_load_item_failure_total{namespace=\"$namespace\"})[1m])",
     "legendFormat": "{{type}}-item-load-failure"
    }
   ]
  },
  {
   "title": "Update Failure [alert]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (update_task) (increase(p13n_reco_update_failure_total{namespace=\"$namespace\",service=\"tray-management-portal\"}[1m]))",
     "legendFormat": "{{update_task}}"
    }
   ]
  }
 ]
}