{
 "title": "Argus Clickhouse",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instances",
    "query": {
     "query": "label_values(ClickHouseProfileEvents_UserTimeMicroseconds{external_source=~\".*argus.*\", service=\"external-prometheus\"}, external_source)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Cores)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_OSCPUVirtualTimeMicroseconds_total{external_source=~\"$instances\", service=\"external-prometheus\"} / 1000000)) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "CPU Wait",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_OSCPUWaitMicroseconds_total{external_source=~\"$instances\", service=\"external-prometheus\"} / 1000000)) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "IO Wait",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_OSIOWaitMicroseconds{external_source=~\"$instances\", service=\"external-prometheus\"} / 1000000)) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(ClickHouseAsyncMetrics_DiskUsed_default{external_source=~\"$instances\"} / ClickHouseAsyncMetrics_DiskTotal_default{external_source=~\"$instances\"}) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Read Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_OSReadBytes{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Write Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_OSWriteBytes{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(ClickHouseMetrics_MemoryTracking{external_source=~\"$instances\", service=\"external-prometheus\"}) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Network In",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_NetworkReceiveBytes{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Network Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_NetworkSendBytes{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Insert Queries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_InsertQuery_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Select Queries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_SelectQuery_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Running Queries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseMetrics_Query{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Running Merges",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(ClickHouseMetrics_Merge{external_source=~\"$instances\", service=\"external-prometheus\"}) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Insert Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_InsertQueryTimeMicroseconds_total{external_source=~\"$instances\", service=\"external-prometheus\"}) / rate(ClickHouseProfileEvents_InsertQuery_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Insert Failure",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_FailedInsertQuery_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Inserted Rows",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_InsertedRows_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Inserted Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_InsertedBytes_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Select Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_SelectQueryTimeMicroseconds_total{external_source=~\"$instances\", service=\"external-prometheus\"}) / rate(ClickHouseProfileEvents_SelectQuery_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Select Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_FailedSelectQuery_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Selected Rows",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_SelectedRows_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Selected Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_SelectedBytes_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Merge Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_MergeTotalMilliseconds{external_source=~\"$instances\", service=\"external-prometheus\"}) / rate(ClickHouseProfileEvents_Merge{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Merge Failures",
     "type": "text",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
     "options": { "content": "No failure metrics for merges" },
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_FailedSelectQuery_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Merge Rows",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_MergedRows_total{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Merge Bytes (Uncompressed)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(rate(ClickHouseProfileEvents_MergedUncompressedBytes{external_source=~\"$instances\", service=\"external-prometheus\"})) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(ClickHouseMetrics_TCPConnection{external_source=~\"$instances\", service=\"external-prometheus\"}) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "HTTP Connection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(ClickHouseMetrics_HTTPConnection{external_source=~\"$instances\", service=\"external-prometheus\"}) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    },
    {
     "title": "Global Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(ClickHouseMetrics_GlobalThread{external_source=~\"$instances\", service=\"external-prometheus\"}) by (external_source)",
       "legendFormat": "{{external_source}}"
      }
     ]
    }
   ]
  }
 ]
}