{
 "title": "Rails application monitoring",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "title": "Puma",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Puma overload",
   "type": "graph",
   "description": "percentage showing how busy puma web server loads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": " (1.0 - sum(puma_pool_capacity) / sum(puma_max_threads)) * 100",
     "legendFormat": "App Busy"
    }
   ]
  },
  {
   "title": "Puma Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(puma_max_threads)", "legendFormat": "Max threads" },
    { "expr": "sum(puma_running)", "legendFormat": "Running threads" },
    { "expr": "sum(puma_pool_capacity)", "legendFormat": "Capacity" }
   ]
  },
  {
   "title": "Rails",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total[1m]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Rails average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_sum[1m]))\n/\nsum(rate(rails_request_duration_seconds_count[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(rails_db_runtime_seconds_sum[1m]))\n/\nsum(rate(rails_db_runtime_seconds_count[1m]))",
     "legendFormat": "Active record"
    },
    {
     "expr": "sum(rate(rails_view_runtime_seconds_sum[1m]))\n/\nsum(rate(rails_view_runtime_seconds_count[1m]))",
     "legendFormat": "View"
    }
   ]
  },
  {
   "title": "Rails throughput per endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total[1m])) by (controller, action)",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Rails 95% response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rails_request_duration_seconds_bucket[1m])) by (le,controller,action)) * 1000 ",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  }
 ]
}