{
 "title": "Adtech Shifu DB Proxy",
 "tags": [ "shifu" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info, source_cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{source_cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_deployment_labels{source_cluster=\"$cluster\", namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "envoy_cluster_name",
    "label": "Ambassador Cluster Name",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_total{source_cluster=\"$cluster\"}, envoy_cluster_name)"
    }
   },
   {
    "name": "tag_Name",
    "label": "ALB Tag Name",
    "query": {
     "query": "label_values(aws_alb_info{source_cluster=\"$cluster\"}, tag_Name)"
    }
   },
   {
    "name": "dc",
    "query": {
     "query": "label_values(kube_node_info, datacenter)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service-[^-]+-[^-]+\", container_id!=\"\"})",
     "legendFormat": "pod count"
    }
   ]
  },
  {
   "title": "Pod Container CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$service-[^-]+-[^-]+\", source_cluster=\"$cluster\",container!=\"\"}[1m])) / avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$service-[^-]+-[^-]+\", source_cluster=\"$cluster\",container!=\"\"})",
     "legendFormat": "avg pod container cpu usage"
    }
   ]
  },
  {
   "title": "Pod Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service-[^-]+-[^-]+\",container!=\"\"})\n/ avg(kube_pod_container_resource_requests_memory_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service-[^-]+-[^-]+\",container!=\"\"})",
     "legendFormat": "avg pod container cpu usage"
    }
   ]
  },
  {
   "title": "Dashboard Alerts",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Server RPM",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"}[1m]) * 60)",
     "legendFormat": "HTTP Server RPM"
    }
   ]
  },
  {
   "title": "Current Ladder",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(current_ladder{datacenter=\"$dc\"})",
     "legendFormat": "current ladder"
    }
   ]
  },
  {
   "title": "Onboarding Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((live_onboarding_rate{datacenter=\"$dc\"} * live_event_in_progress{datacenter=\"$dc\"}) + onboarding_rate{datacenter=\"$dc\"} * (1 - live_event_in_progress)) / 1000000",
     "legendFormat": "{{source_cluster}}"
    },
    {
     "expr": "platform_onboarding_ladder{datacenter=~\"$dc\"}/1000000",
     "legendFormat": "platform onboarding ladder"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "options": {
    "content": "[Ad Server Runbook](https://hotstar.atlassian.net/wiki/spaces/HP2/pages/2542502094/Ad+Server+Runbook)\n\n[Shifu Panic Mode](https://hotstar.atlassian.net/wiki/spaces/HP2/pages/1825243303/Shifu+Panic+Mode)\n\n[Current Shifu Architecture](https://hotstar.atlassian.net/wiki/spaces/HP2/pages/1255505924/Current+Shifu+Architecture)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Server RPM by Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", uri!~\"(/health)|(/actuator.*)\"}[1m]) * 60) by (status)",
       "legendFormat": "HTTP response [{{status}}]"
      }
     ]
    },
    {
     "title": "HTTP Server RPM by Uri",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", uri!~\"(/health)|(/actuator.*)\"}[1m]) * 60) by (uri)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "HTTP Server Latency P90/P99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", uri!~\"(/health)|(/actuator.*)\"}[1m])) by (le, uri))",
       "legendFormat": "[P99] {{uri}}"
      },
      {
       "expr": "histogram_quantile(0.95, avg(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", uri!~\"(/health)|(/actuator.*)\"}[1m])) by (le, uri))",
       "legendFormat": "[P95] {{uri}}"
      },
      {
       "expr": "histogram_quantile(0.999, avg(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", uri!~\"(/health)|(/actuator.*)\"}[1m])) by (le, uri))",
       "legendFormat": "[P999] {{uri}}"
      }
     ]
    },
    {
     "title": "HTTP Server Latency P50/mean",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", uri!~\"(/health)|(/actuator.*)\"}[1m])) by (uri) / sum(rate(http_server_requests_seconds_count{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", uri!~\"(/health)|(/actuator.*)\"}[1m])) by (uri)",
       "legendFormat": "[mean] {{uri}}"
      },
      {
       "expr": "histogram_quantile(0.5, avg(rate(http_server_requests_seconds_bucket{source_cluster=\"$cluster\", namespace=\"$namespace\", job=\"$service\",  uri!~\"(/health)|(/actuator.*)\"}[1m])) by (le, uri))",
       "legendFormat": "[P50] {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Balancer Ambassador",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ambassador Request Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_total{source_cluster=\"$cluster\", envoy_cluster_name=\"$envoy_cluster_name\"}[1m]) * 60)",
       "legendFormat": "ambassador request RPM"
      }
     ]
    },
    {
     "title": "Ambassador Latency P90/P99",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{source_cluster=\"$cluster\", envoy_cluster_name=\"$envoy_cluster_name\"}[1m])) by (le))",
       "legendFormat": "[P99] response time"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{source_cluster=\"$cluster\", envoy_cluster_name=\"$envoy_cluster_name\"}[1m])) by (le))",
       "legendFormat": "[P95] response time"
      }
     ]
    },
    {
     "title": "Ambassador Latency P50",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{source_cluster=\"$cluster\", envoy_cluster_name=\"$envoy_cluster_name\"}[1m])) by (le))",
       "legendFormat": "[P50] response time"
      }
     ]
    },
    {
     "title": "Ambassador Connection Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(envoy_cluster_upstream_cx_active{source_cluster=\"$cluster\", envoy_cluster_name=\"$envoy_cluster_name\"})",
       "legendFormat": "active connection"
      }
     ]
    },
    {
     "title": "Backend 5xx",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_5xx_total{envoy_cluster_name=\"$envoy_cluster_name\",source_cluster=\"$cluster\"}[1m]) * 60)",
       "legendFormat": "backend 5xx"
      }
     ]
    },
    {
     "title": "Backend 4xx",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_4xx_total{envoy_cluster_name=\"$envoy_cluster_name\",source_cluster=\"$cluster\"}[1m]) * 60)",
       "legendFormat": "backend 4xx"
      }
     ]
    },
    {
     "title": "Ambassador Connection Fail Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_connect_fail_total{envoy_cluster_name=\"$envoy_cluster_name\",source_cluster=\"$cluster\"}[1m]) * 60)",
       "legendFormat": "ambassador connection fail"
      }
     ]
    }
   ]
  },
  {
   "title": "Business P0 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "load beacon registryshifuid ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(shifu_db_proxy_load_campaign_registryshifuid_size_sum{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])*60) by (pod_name)/sum(rate(shifu_db_proxy_load_campaign_registryshifuid_size_count{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])*60) by (pod_name)",
       "legendFormat": "campaign: {{pod_name}}"
      },
      {
       "expr": "sum(rate(shifu_db_proxy_load_adset_registryshifuid_size_sum{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])*60) by (pod_name)/sum(rate(shifu_db_proxy_load_adset_registryshifuid_size_count{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])*60) by (pod_name)",
       "legendFormat": "adset: {{pod_name}}"
      },
      {
       "expr": "sum(rate(shifu_db_proxy_load_ad_registryshifuid_size_sum{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])*60) by (pod_name)/sum(rate(shifu_db_proxy_load_ad_registryshifuid_size_count{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])*60) by (pod_name)",
       "legendFormat": "ad: {{pod_name}}"
      }
     ]
    },
    {
     "title": "load redirection entity and url",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(shifu_db_proxy_load_redirection_entities_size_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load entity size: {{pod_name}}"
      },
      {
       "expr": "sum(increase(shifu_db_proxy_load_redirection_url_size_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load url size: {{pod_name}}"
      }
     ]
    },
    {
     "title": "counter unarchived adset",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(shifu_db_proxy_load_unarchived_adset_size_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "unarchived adset: {{pod_name}}"
      },
      {
       "expr": "sum(increase(shifu_db_proxy_load_in_schedule_adset_size_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "in schedule adset: {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Business P1 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loading beacon success",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(shifu_db_proxy_load_registryshifuid_success_total{job=~\"$service.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load beacon registryshifuid success : {{pod_name}}"
      },
      {
       "expr": "sum(increase(shifu_db_proxy_load_registryshifuid_fail_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load beacon registryshifuid fail : {{pod_name}}"
      }
     ]
    },
    {
     "title": "Loading redirection success",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(shifu_db_proxy_load_redirection_success_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load redirection success"
      },
      {
       "expr": "sum(increase(shifu_db_proxy_load_redirection_fail_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load redirection fail"
      }
     ]
    },
    {
     "title": "Loading counter success",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(shifu_db_proxy_load_unarchived_adset_success_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load unarchived success: {{pod_name}}"
      },
      {
       "expr": "sum(increase(shifu_db_proxy_load_unarchived_adset_fail_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load unarchived fail :{{pod_name}}"
      },
      {
       "expr": "sum(increase(shifu_db_proxy_load_in_schedule_adset_success_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load in schedule success: {{pod_name}}"
      },
      {
       "expr": "sum(increase(shifu_db_proxy_load_in_schedule_adset_fail_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"$cluster\"}[1m])) by (pod_name)",
       "legendFormat": "load in schedule fail :{{pod_name}}"
      }
     ]
    },
    {
     "title": "Load RegistryShifuId Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(shifu_db_proxy_load_registryshifuid_time_seconds_sum{source_cluster=\"$cluster\",pod=~\"$service.*\"}[1m])) by (pod_name)/ sum(rate(shifu_db_proxy_load_registryshifuid_time_seconds_count{source_cluster=\"$cluster\", pod=~\"$service.*\"}[1m])) by (pod_name)",
       "legendFormat": "load registryshifuid time : {{pod_name}}"
      }
     ]
    },
    {
     "title": "Load Redirection Entity and Url Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(shifu_db_proxy_load_redirection_time_seconds_sum{source_cluster=\"$cluster\",pod=~\"$service.*\"}[1m])) by (pod_name)/ sum(rate(shifu_db_proxy_load_redirection_time_seconds_count{source_cluster=\"$cluster\", pod=~\"$service.*\"}[1m])) by (pod_name)",
       "legendFormat": "load redirection time: {{pod_name}}"
      }
     ]
    },
    {
     "title": "Load Counter Unarchived Adset Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(shifu_db_proxy_load_unarchived_adset_time_seconds_sum{source_cluster=\"$cluster\",pod=~\"$service.*\"}[1m])) by (pod_name)/ sum(rate(shifu_db_proxy_load_unarchived_adset_time_seconds_count{source_cluster=\"$cluster\", pod=~\"$service.*\"}[1m])) by (pod_name)",
       "legendFormat": "load unarchived adset :{{pod_name}}"
      },
      {
       "expr": "sum(rate(shifu_db_proxy_load_in_schedule_adset_time_seconds_sum{source_cluster=\"$cluster\",pod=~\"$service.*\"}[1m])) by (pod_name)/ sum(rate(shifu_db_proxy_load_in_schedule_adset_time_seconds_count{source_cluster=\"$cluster\", pod=~\"$service.*\"}[1m])) by (pod_name)",
       "legendFormat": "load in schedule adset :{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Business P2 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Config Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tomcat_threads_config_max_threads{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"})"
      }
     ]
    },
    {
     "title": "Connection Config Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tomcat_connections_config_max_connections{source_cluster=\"$cluster\", namespace=\"$namespace\", job=\"$service\"})"
      }
     ]
    },
    {
     "title": "Active Sessions Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tomcat_sessions_active_max_sessions{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"})",
       "legendFormat": "total active sessions"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(tomcat_threads_busy_threads{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"})",
       "legendFormat": "busy thread"
      }
     ]
    },
    {
     "title": "Current Thread Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(tomcat_threads_current_threads{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"})"
      }
     ]
    },
    {
     "title": "Current Connection Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(tomcat_connections_current_connections{source_cluster=\"$cluster\", namespace=\"$namespace\", job=\"$service\"})"
      }
     ]
    },
    {
     "title": "Current Active Sessions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tomcat_sessions_active_current_sessions{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"})",
       "legendFormat": "total active sessions"
      }
     ]
    },
    {
     "title": "Tomcat Request Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tomcat_global_request_seconds_count{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"}[1m]) * 60)",
       "legendFormat": "request count"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tomcat_global_request_seconds_sum{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"}[1m]))\n/ sum(rate(tomcat_global_request_seconds_count{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"}[1m]))",
       "legendFormat": "avg latency"
      }
     ]
    }
   ]
  },
  {
   "title": "ElastiCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
     "options": {
      "content": "<br/>\n\n[Shifu ElastiCache Dashboard](https://grafana.hotstar.com/d/NH0-EvF4k/adtech-shifu-elasticache)"
     },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "RDS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
     "options": {
      "content": "<br/>\n\n[Shifu RDS Dashboard](https://grafana.hotstar.com/d/0G0yoEK4k/adtech-shifu-rds)"
     },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", area=\"heap\"})\n/ sum(jvm_memory_max_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", area=\"nonheap\"})\n/ sum(jvm_memory_max_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "G1 Eden Space (heap)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"G1 Eden Space\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"G1 Eden Space\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"G1 Eden Space\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "G1 Old Gen (heap)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"G1 Old Gen\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"G1 Old Gen\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"G1 Old Gen\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "G1 Survivor Space (heap)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"G1 Survivor Space\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"G1 Survivor Space\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"G1 Survivor Space\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Code Cache (non-heap)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"Code Cache\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"Code Cache\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"Code Cache\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Compressed Class Space (non-heap)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"Compressed Class Space\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"Compressed Class Space\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"Compressed Class Space\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Metaspace (nonheap)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"Metaspace\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"Metaspace\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"Metaspace\"})",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count per Minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(increase(jvm_gc_pause_seconds_count{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"}[1m])) by (action, cause)",
       "legendFormat": "{{action}} [{{cause}}] per minute"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(jvm_gc_pause_seconds_sum{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"}[1m])) by (action, cause)",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Memory Allocate/Promote",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(rate(jvm_gc_memory_allocated_bytes_total{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"}[1m]))",
       "legendFormat": "allocated"
      },
      {
       "expr": "avg(rate(jvm_gc_memory_promoted_bytes_total{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"}[1m]))",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads/ClassLoad/Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes Loaded",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(jvm_classes_loaded_classes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"})",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_threads_daemon_threads{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"})",
       "legendFormat": "Daemon"
      },
      {
       "expr": "avg(jvm_threads_live_threads{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"})",
       "legendFormat": "Live"
      },
      {
       "expr": "avg(jvm_threads_peak_threads{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"})",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(jvm_classes_unloaded_classes_total{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\"}[1m]))",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_buffer_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"direct\"})",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "avg(jvm_buffer_total_capacity_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"direct\"})",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(jvm_buffer_memory_used_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"mapped\"})",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "avg(jvm_buffer_total_capacity_bytes{source_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", id=\"mapped\"})",
       "legendFormat": "Capacity Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Container Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{source_cluster=\"hs-eks-prod7-api-apse1\", namespace=\"adtech\", pod=~\"adtech-shifu-db-proxy.*\"})\n/ avg(kube_pod_container_resource_requests_memory_bytes{source_cluster=\"hs-eks-prod7-api-apse1\", namespace=\"adtech\", pod=~\"adtech-shifu-db-proxy.*\"})",
       "legendFormat": "avg pod container cpu usage"
      }
     ]
    },
    {
     "title": "Pod Container CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"adtech\", pod=~\"adtech-shifu-db-proxy.*\", source_cluster=\"hs-eks-prod7-api-apse1\"}[1m])) / avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"adtech\", pod=~\"adtech-shifu-db-proxy.*\", source_cluster=\"hs-eks-prod7-api-apse1\"})",
       "legendFormat": "avg pod container cpu usage"
      }
     ]
    },
    {
     "title": "HTTP Server Latency P95/P99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod7-api-apse1\", namespace=\"adtech\", service=~\"adtech-shifu-db-proxy.*\", uri!~\"(/health)|(/actuator.*)\"}[1m])) by (le, uri))",
       "legendFormat": "[P99] {{uri}}"
      },
      {
       "expr": "histogram_quantile(0.95, avg(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod7-api-apse1\", namespace=\"adtech\", service=~\"adtech-shifu-db-proxy.*\", uri!~\"(/health)|(/actuator.*)\"}[1m])) by (le, uri))",
       "legendFormat": "[P95] {{uri}}"
      },
      {
       "expr": "histogram_quantile(0.999, avg(rate(http_server_requests_seconds_bucket{source_cluster=\"hs-eks-prod7-api-apse1\", namespace=\"adtech\", service=~\"adtech-shifu-db-proxy.*\", uri!~\"(/health)|(/actuator.*)\"}[1m])) by (le, uri))",
       "legendFormat": "[P999] {{uri}}"
      }
     ]
    },
    {
     "title": "Backend 5xx",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_5xx_total{envoy_cluster_name=~\"adtech_shifu_db_proxy.*\",source_cluster=\"hs-eks-prod7-api-apse1\"}[1m]) * 60)",
       "legendFormat": "backend 5xx"
      }
     ]
    },
    {
     "title": "Backend 4xx",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_4xx_total{envoy_cluster_name=~\"adtech_shifu_db_proxy.*\",source_cluster=\"hs-eks-prod7-api-apse1\"}[1m]) * 60)",
       "legendFormat": "backend 4xx"
      }
     ]
    },
    {
     "title": "Loading counter failed",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(shifu_db_proxy_load_unarchived_adset_fail_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"hs-eks-prod7-api-apse1\"}[1m])) by (pod_name)",
       "legendFormat": "load unarchived fail :{{pod_name}}"
      }
     ]
    },
    {
     "title": "Loading beacon failed",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(shifu_db_proxy_load_registryshifuid_fail_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"hs-eks-prod7-api-apse1\"}[1m])) by (pod_name)",
       "legendFormat": "load beacon registryshifuid fail : {{pod_name}}"
      }
     ]
    },
    {
     "title": "Loading redirection failed",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(shifu_db_proxy_load_redirection_fail_total{job=~\"adtech-shifu-db-proxy.*\", source_cluster=\"hs-eks-prod7-api-apse1\"}[1m])) by (pod_name)",
       "legendFormat": "load redirection fail"
      }
     ]
    }
   ]
  }
 ]
}