{
 "title": "Game Day",
 "description": "Overall Service monitoring",
 "tags": [
  "gameday",
  "overall"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_namespace_created, source_cluster)"
   },
   {
    "name": "Service",
    "label": "Service",
    "query": "label_values(aws_elb_info{source_cluster=~\"$cluster\"}, tag_kubernetes_io_service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "ELB Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "aws_elb_request_count_sum{} + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$Service\", source_cluster=~\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_elb_latency_average{source_cluster=~\"$cluster\"} + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$Service\", source_cluster=~\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "ELB 5XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_elb_5_xx_sum{source_cluster=~\"$cluster\"} + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$Service\", source_cluster=~\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Backend 5XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_backend_5_xx_sum{source_cluster=~\"$cluster\"} + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$Service\", source_cluster=~\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Spill Over Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_spillover_count_sum{source_cluster=~\"$cluster\"} + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$Service\", source_cluster=~\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Surge queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_surge_queue_length_maximum{source_cluster=~\"$cluster\"} + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$Service\", source_cluster=~\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Backend 4XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_backend_4_xx_sum{source_cluster=~\"$cluster\"} + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$Service\", source_cluster=~\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Deployment Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Deployment Replicas",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", source_cluster=~\"$cluster\"}) by (deployment, namespace)"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", source_cluster=~\"$cluster\"}) by (deployment, namespace)"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", source_cluster=~\"$cluster\"}) by (deployment, namespace)"
    }
   ]
  }
 ]
}