{
 "title": "CMS Services Dashboard - (Tenant Segregation)",
 "description": "Overall Service monitoring",
 "tags": [
  "gameday",
  "overall",
  "cms"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(cms_http_server_requests_service_duration_seconds, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(cms_http_server_requests_service_duration_seconds{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(cms_http_server_requests_service_duration_seconds{namespace=\"$namespace\",service=\"$service\"}, pod)"
   },
   {
    "name": "Country",
    "query": "label_values(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\"}, country)"
   },
   {
    "name": "cluster",
    "query": "label_values(service_requests, source_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Monitor (aggregated for all pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\", country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (country)",
       "legendFormat": "{{country}}"
      },
      { "expr": "max(heart_beat_concurrency)", "legendFormat": "Platform Concurrency" },
      { "expr": "current_ladder", "legendFormat": "Infra ladder" }
     ]
    },
    {
     "title": "HTTP Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{status=~\"200\",namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "200 "
      },
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{status=~\"4.*\",namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "4xx "
      },
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{status=~\"5.*\",namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "5xx "
      },
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{status=~\"200\",namespace=\"$namespace\",service=\"$service\", country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (country)",
       "legendFormat": "{{country}} 200"
      },
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{status=~\"4.*\",namespace=\"$namespace\",service=\"$service\", country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (country)",
       "legendFormat": "{{country}} 4XX"
      },
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{status=~\"5.*\",namespace=\"$namespace\",service=\"$service\", country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (country)",
       "legendFormat": "{{country}} 5XX"
      }
     ]
    },
    {
     "title": "Traffic relation with concurrency ladder",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m])) / max(heart_beat_concurrency)",
       "legendFormat": "Traffic on service"
      },
      { "expr": "max(heart_beat_concurrency)", "legendFormat": "Hearbeat Concurrency " }
     ]
    },
    {
     "title": "Overall Service Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_service_duration_seconds_sum{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m])) / sum(delta(cms_http_server_requests_service_duration_seconds_count{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(cms_http_server_requests_service_duration_seconds{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\",quantile=\"0.99\"})",
       "legendFormat": "p99"
      },
      {
       "expr": "max(cms_http_server_requests_service_duration_seconds{namespace=\"$namespace\",service=\"$service\",quantile=\"0.95\"})",
       "legendFormat": "p95"
      },
      {
       "expr": "max(cms_http_server_requests_service_duration_seconds{namespace=\"$namespace\",service=\"$service\",quantile=\"0.75\"})",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Latencies in Country ($Country)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_tenant_duration_seconds_sum{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (country) / sum(delta(cms_http_server_requests_tenant_duration_seconds_count{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (country)",
       "legendFormat": "{{country}} - Avg"
      },
      {
       "expr": "avg(cms_http_server_requests_tenant_duration_seconds{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\",quantile=\"0.99\"}) by (country)",
       "legendFormat": "{{country}} - p99"
      },
      {
       "expr": "avg(cms_http_server_requests_tenant_duration_seconds{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\",quantile=\"0.95\"}) by (country)",
       "legendFormat": "{{country}} - p95"
      },
      {
       "expr": "avg(cms_http_server_requests_tenant_duration_seconds{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\",quantile=\"0.75\"}) by (country)",
       "legendFormat": "{{country}} - p75"
      }
     ]
    },
    {
     "title": "Success Percent",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{status=\"200\",namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))/sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\"}[1m]))"
      }
     ]
    },
    {
     "title": "Available Pod count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\",namespace=\"$namespace\",source_cluster=\"$cluster\"}) by (deployment, namespace)",
       "legendFormat": "Available Replica count"
      }
     ]
    },
    {
     "title": "Service CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{container=~\"$service.*\",namespace=\"$namespace\",source_cluster=\"$cluster\"}[1m])) / avg(kube_pod_container_resource_requests_cpu_cores{container=~\"$service.*\",namespace=\"$namespace\",source_cluster=\"$cluster\"}) by (container)"
      }
     ]
    },
    {
     "title": "Service Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 10, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container=~\"$service.*\",namespace=\"$namespace\",source_cluster=\"$cluster\"}) by (container) / avg(kube_pod_container_resource_requests_memory_bytes{container=~\"$service.*\",namespace=\"$namespace\",source_cluster=\"$cluster\"}) by (container)",
       "legendFormat": "Memory - {{ container }}"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\",namespace=\"$namespace\",source_cluster=\"$cluster\"}) by (deployment, namespace)",
       "legendFormat": "Pods - {{deployment}}"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{namespace=\"$namespace\",job=\"$service\",source_cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Monitor (Aggregated for all pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Traffic (RPM)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Country wise API Traffic (RPM)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri, country)",
       "legendFormat": "{{country}} {{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API Latency (Avg)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_time_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri) / sum(delta(cms_http_server_requests_api_counter_total{service=\"$service\",namespace=\"$namespace\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri) ",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Country wise API Latency (Avg)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_time_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri, country) / sum(delta(cms_http_server_requests_api_counter_total{service=\"$service\",namespace=\"$namespace\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri, country) ",
       "legendFormat": "{{country}} {{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API - HTTP 200 Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",status=\"200\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API - HTTP 4xx Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",status=~\"4.*\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API - HTTP 5xx Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",status=~\"5.*\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API Usage and Error rate",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri) / scalar(sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])))"
      },
      {
       "expr": "((sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri)) - \n(sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",status=\"200\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (uri))) / scalar(sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m]))) "
      }
     ]
    },
    {
     "title": "Pod level - Traffic Distribution",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (pod) / scalar(sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])))",
       "legendFormat": "{{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Pod level - HTTP 200 Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",status=~\"200\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (pod)",
       "legendFormat": "pod_id - {{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Pod level - HTTP 4XX Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",status=~\"4.*\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (pod)",
       "legendFormat": "pod_id - {{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Pod level - HTTP 5xx Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",status=~\"5.*\",country=~\"$Country\",source_cluster=\"$cluster\"}[1m])) by (pod)",
       "legendFormat": "pod_id - {{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  { "title": "Load balancers stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "aws_elb_request_count_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "ELB - {{ tag_kubernetes_io_service_name}}"
    },
    {
     "expr": "aws_alb_request_count_sum + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_ingress_name)",
     "legendFormat": "ALB - {{ tag_kubernetes_io_ingress_name }}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_elb_latency_average + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
    },
    {
     "expr": "aws_alb_target_response_time_average + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_ingress_name)",
     "legendFormat": "ALB - {{ tag_kubernetes_io_ingress_name}}"
    }
   ]
  },
  {
   "title": "ELB 5XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_elb_5_xx_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
    },
    {
     "expr": "aws_alb_httpcode_elb_5_xx_count_sum + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_ingress_name)",
     "legendFormat": "ALB - {{ tag_kubernetes_io_ingress_name}}"
    }
   ]
  },
  {
   "title": "Backend 5XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_backend_5_xx_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
    },
    {
     "expr": "aws_alb_tg_httpcode_target_5_xx_count_sum + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_ingress_name)",
     "legendFormat": "ALB - {{tag_kubernetes_io_ingress_name}}"
    }
   ]
  },
  {
   "title": "Spill Over Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_spillover_count_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Surge queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_surge_queue_length_maximum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Backend 4XX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_backend_4_xx_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_service_name)",
     "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
    },
    {
     "expr": "aws_alb_tg_httpcode_target_4_xx_count_sum + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\",source_cluster=\"$cluster\"}) by(name,tag_kubernetes_io_ingress_name)",
     "legendFormat": "ALB - {{ tag_kubernetes_io_ingress_name}}"
    }
   ]
  },
  { "title": "Pod Monitor for pod - $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 20 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", source_cluster=\"$cluster\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"heap\",source_cluster=\"$cluster\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"heap\", source_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", area=\"nonheap\",source_cluster=\"$cluster\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"nonheap\",source_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_threads_live{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"} or jvm_threads_live_threads{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Daemon Threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"} or jvm_threads_daemon_threads{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Peak Threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_threads_peak{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"} or jvm_threads_peak_threads{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pod Memory status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=~\"$service.*\", pod=\"$pod\",source_cluster=\"$cluster\"}",
     "legendFormat": "Container - Total memory"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container_name=~\"$service.*\",pod=\"$pod\",source_cluster=\"$cluster\"} ",
     "legendFormat": "Container - Used memory"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"})",
     "legendFormat": "JVM - Max allowed memory"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"})",
     "legendFormat": "JVM - Comitted memory"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"})",
     "legendFormat": "JVM - Used memory (Heap & Non-Heap)"
    }
   ]
  },
  {
   "title": "JVM Used Memory - Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", area=\"heap\",source_cluster=\"$cluster\"}",
     "legendFormat": "Heap - {{id}}"
    },
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", area=\"nonheap\",source_cluster=\"$cluster\"}",
     "legendFormat": "Non Heap - {{id}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name=~\"$service.*\",namespace=\"$namespace\",pod_name=\"$pod\",source_cluster=\"$cluster\"},\"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / \nsum(kube_pod_container_resource_requests_cpu_cores{container=~\"$service.*\",namespace=\"$namespace\",pod=\"$pod\",source_cluster=\"$cluster\"}) by (pod)",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "fds per pod <> total pods count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}",
     "legendFormat": "Open fds"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\",namespace=\"$namespace\",source_cluster=\"$cluster\"}) by (deployment, namespace)",
     "legendFormat": "Open Fd"
    }
   ]
  },
  {
   "title": "JVM Buffers ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_total_capacity{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}",
     "legendFormat": "{{id}} buffer - capacity"
    },
    {
     "expr": "jvm_buffer_memory_used{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"} / jvm_buffer_total_capacity{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}",
     "legendFormat": "{{id}} buffer - used"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}",
     "legendFormat": "Load Average 1m"
    }
   ]
  },
  {
   "title": "Pod Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(cms_http_server_requests_api_counter_total{namespace=\"$namespace\",service=\"$service\",pod = \"$pod\",source_cluster=\"$cluster\"}[1m])) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_duration_seconds_count{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Garbage Collection - Pause Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_duration_seconds_sum{namespace=\"$namespace\",service=\"$service\",source_cluster=\"$cluster\",pod=\"$pod\"}[1m])/rate(jvm_gc_pause_duration_seconds_count{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_duration_seconds_max{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",source_cluster=\"$cluster\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  }
 ]
}