{
 "title": "P0 CMS Services Dashboard (Tenant Segregation) [DC Migrated]",
 "description": "Overall Service monitoring",
 "tags": [
  "gameday",
  "overall",
  "cms"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, namespace)"
    }
   },
   {
    "name": "service",
    "query": "multi-get,persona-get,geccomp,drools,catalog-processor,cdc-processor"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}, pod)"
    }
   },
   {
    "name": "datacenter",
    "query": {
     "query": "label_values(node_cpu_seconds_total, datacenter)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Monitor (aggregated for all pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60)",
       "legendFormat": "Overall"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\", datacenter=\"$datacenter\"}[1m])*60) by (country) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\", datacenter=\"$datacenter\"}[1m])*60) by (country)",
       "legendFormat": "{{country}}"
      },
      { "expr": "max(heart_beat_concurrency)", "legendFormat": "Platform Concurrency" },
      {
       "expr": "max(current_ladder{datacenter=\"$datacenter\"})",
       "legendFormat": "Infra ladder"
      }
     ]
    },
    {
     "title": "HTTP Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{status=~\"2.*\",namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60) or sum(rate(cms_http_server_requests_seconds_count{status=~\"2.*\",namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60)",
       "legendFormat": "200 "
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4.*\",namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60) or sum(rate(cms_http_server_requests_seconds_count{status=~\"4.*\",namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60)",
       "legendFormat": "4xx "
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5.*\",namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60) or sum(rate(cms_http_server_requests_seconds_count{status=~\"5.*\",namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60)",
       "legendFormat": "5xx "
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{status=~\"2.*\",namespace=\"$namespace\",service=\"$service\", datacenter=\"$datacenter\"}[1m])*60) by (country) or sum(rate(cms_http_server_requests_seconds_count{status=~\"2.*\",namespace=\"$namespace\",service=\"$service\", datacenter=\"$datacenter\"}[1m])*60) by (country)",
       "legendFormat": "{{country}} 200"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4.*\",namespace=\"$namespace\",service=\"$service\", datacenter=\"$datacenter\"}[1m])*60) by (country) or sum(rate(cms_http_server_requests_seconds_count{status=~\"4.*\",namespace=\"$namespace\",service=\"$service\", datacenter=\"$datacenter\"}[1m])*60) by (country)",
       "legendFormat": "{{country}} 4XX"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5.*\",namespace=\"$namespace\",service=\"$service\", datacenter=\"$datacenter\"}[1m])*60) by (country) or sum(rate({status=~\"5.*\",namespace=\"$namespace\",service=\"$service\", datacenter=\"$datacenter\"}[1m])*60) by (country)",
       "legendFormat": "{{country}} 5XX"
      }
     ]
    },
    {
     "title": "Ladders",
     "type": "gauge",
     "description": "Actual Onboarding is fetched from : https://grafana.hotstar.com/d/KfM5im04k/page-compositor-side-car-fleet?viewPanel=348&orgId=1\n\nhttps://hotstar.slack.com/archives/C04D0C8MZAL/p1693828380769849",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(platform_onboarding_ladder{datacenter=~\"$datacenter\"})",
       "legendFormat": "Onboarding ladder"
      },
      {
       "expr": "sum(rate(http_server_start_api_requests_total{action=~\"\",container=\"main\",datacenter=\"$datacenter\"}[1m]) * 60) + sum(rate(start_degradation_request_count_total{datacenter=\"$datacenter\"}[1m]) * 60)",
       "legendFormat": "Actual Onboarding"
      },
      {
       "expr": "max(current_ladder{datacenter=\"$datacenter\"})",
       "legendFormat": "Concurrency Ladder"
      },
      { "expr": "max(heart_beat_concurrency)", "legendFormat": "Actual Concurrency " }
     ]
    },
    {
     "title": "Overall Service Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le)) or histogram_quantile(0.999, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le)) or histogram_quantile(0.99, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le)) or histogram_quantile(0.95, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Latencies in Country",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le, country)) or histogram_quantile(0.99, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le, country))",
       "legendFormat": "{{country}} - p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le, country)) or histogram_quantile(0.95, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le, country))",
       "legendFormat": "{{country}} - p95"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le, country)) or histogram_quantile(0.75, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le, country))",
       "legendFormat": "{{country}} - p75"
      }
     ]
    },
    {
     "title": "Success Percent",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{status=\"200\",namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60)/sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60) or sum(rate(cms_http_server_requests_seconds_count{status=\"200\",namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60)/sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60)"
      }
     ]
    },
    {
     "title": "Pod count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\",namespace=\"$namespace\",datacenter=\"$datacenter\"}) by (deployment, namespace)",
       "legendFormat": "Available Replica count"
      }
     ]
    },
    {
     "title": "Core/Pod",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"$service.*\",namespace=\"$namespace\",datacenter=\"$datacenter\"})",
       "legendFormat": "Core/Pod"
      }
     ]
    },
    {
     "title": "Service CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"$service.*\",namespace=\"$namespace\",datacenter=\"$datacenter\"}[1m])) by (pod) / avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"$service.*\",namespace=\"$namespace\",datacenter=\"$datacenter\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Service Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{pod=~\"$service.*\",namespace=\"$namespace\",datacenter=\"$datacenter\"}) by(pod)/ avg(kube_pod_container_resource_requests_memory_bytes{pod=~\"$service.*\",namespace=\"$namespace\",datacenter=\"$datacenter\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\",namespace=\"$namespace\",datacenter=\"$datacenter\"}) by (deployment, namespace)",
       "legendFormat": "Pods - {{deployment}}"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service-canary\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\",namespace=\"$namespace\",datacenter=\"$datacenter\"}) by (deployment, namespace)",
       "legendFormat": "Canary Pods - {{deployment}}"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_current_connection_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"} or cms_tomcat_current_connection_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Accept Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(executor_active_threads{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Executor Pool",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(executor_pool_core_threads{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"})",
       "legendFormat": "Core Threads"
      },
      {
       "expr": "sum(executor_pool_max_threads{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"})",
       "legendFormat": "Max Threads"
      }
     ]
    },
    {
     "title": "Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(executor_queued_tasks{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Monitor (Aggregated for all pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Traffic (RPM)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Country wise API Traffic (RPM)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri, country) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri, country)",
       "legendFormat": "{{country}} - {{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API Latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])) by (le, uri)) or \nhistogram_quantile(0.99, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])) by (le, uri))",
       "legendFormat": "p99 - {{uri}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])) by (le, uri)) or histogram_quantile(0.95, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])) by (le, uri))",
       "legendFormat": "p95 - {{uri}}"
      }
     ]
    },
    {
     "title": "Country wise API Latency ",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])) by (le, uri, country)) or histogram_quantile(0.99, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])) by (le, uri, country))",
       "legendFormat": "p99 - {{country}} {{uri}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])) by (le, uri, country)) or histogram_quantile(0.95, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])) by (le, uri, country))",
       "legendFormat": "p95 - {{country}} {{uri}}"
      }
     ]
    },
    {
     "title": "API - HTTP 200 Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"2.*\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"2.*\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API - HTTP 4xx Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"4.*\",datacenter=\"$datacenter\"}[1m])*60) by (uri) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"4.*\",datacenter=\"$datacenter\"}[1m])*60) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API - HTTP 5xx Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"5.*\",datacenter=\"$datacenter\"}[1m])*60) by (uri) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"5.*\",datacenter=\"$datacenter\"}[1m])*60) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API Usage and Error rate",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri) / scalar(sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60)) or \nsum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri) / scalar(sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60))"
      },
      {
       "expr": "((sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri)) - \n(sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"2.*\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri))) / scalar(sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60)) or ((sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri)) - \n(sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"2.*\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60) by (uri))) / scalar(sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\", uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\", uri!=\"/slow/start/check\"}[1m])*60))  "
      }
     ]
    },
    {
     "title": "Pod level - Traffic Distribution",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60) by (pod) / scalar(sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60)) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60) by (pod) / scalar(sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60))\n",
       "legendFormat": "{{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Pod level - HTTP 200 Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"2.*\",datacenter=\"$datacenter\"}[1m])*60) by (pod) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"2.*\",datacenter=\"$datacenter\"}[1m])*60) by (pod) ",
       "legendFormat": "pod_id - {{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Pod level - HTTP 4XX Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"4.*\",datacenter=\"$datacenter\"}[1m])*60) by (pod) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"4.*\",datacenter=\"$datacenter\"}[1m])*60) by (pod) ",
       "legendFormat": "pod_id - {{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Pod level - HTTP 5xx Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"5.*\",datacenter=\"$datacenter\"}[1m])*60) by (pod) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"5.*\",datacenter=\"$datacenter\"}[1m])*60) by (pod) ",
       "legendFormat": "pod_id - {{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "Downstream Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cms_downstream_service_seconds_count{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])*60)",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "DAX Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(cms_downstream_service_seconds{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\",quantile=\"0.99\", downstream_type=\"dynamo_db\"}) or histogram_quantile(0.99, sum(rate(cms_downstream_service_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "max(cms_downstream_service_seconds{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\",quantile=\"0.95\", downstream_type=\"dynamo_db\"}) or histogram_quantile(0.90, sum(rate(cms_downstream_service_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "max(cms_downstream_service_seconds{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\",quantile=\"0.50\", downstream_type=\"dynamo_db\"}) or histogram_quantile(0.50, sum(rate(cms_downstream_service_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Function wise DAX Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(cms_downstream_service_seconds{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\",quantile=\"0.99\", downstream_type=\"dynamo_db\"}) by (cms_function) or histogram_quantile(0.99, sum(rate(cms_downstream_service_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le, cms_function))",
       "legendFormat": "p99 - {{cms_function}}"
      },
      {
       "expr": "max(cms_downstream_service_seconds{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\",quantile=\"0.95\", downstream_type=\"dynamo_db\"}) by (cms_function) or histogram_quantile(0.90, sum(rate(cms_downstream_service_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le, cms_function))",
       "legendFormat": "p90 - {{cms_function}}"
      },
      {
       "expr": "max(cms_downstream_service_seconds{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\",quantile=\"0.50\", downstream_type=\"dynamo_db\"}) by (cms_function) or histogram_quantile(0.50, sum(rate(cms_downstream_service_seconds_bucket{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"}[1m])) by (le, cms_function))",
       "legendFormat": "p50 - {{cms_function}}"
      }
     ]
    },
    {
     "title": "Core Thread",
     "type": "graph",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(executor_pool_core_threads{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"})",
       "legendFormat": "Max Threads {{pod}}"
      },
      {}
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 3, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(executor_active_threads{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\"})",
       "legendFormat": "Active Threads"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Monitor for pod - $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Thread States",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max(jvm_threads_states_threads{datacenter=\"$datacenter\", namespace=\"$namespace\", service=~\"$service\", pod=\"$pod\"}) by (state) or max(cms_jvm_threads_states_threads{datacenter=\"$datacenter\", namespace=\"$namespace\", service=~\"$service\", pod=\"$pod\"}) by (state)",
       "legendFormat": "{{state}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"heap\",datacenter=\"$datacenter\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"heap\", datacenter=\"$datacenter\"}) or sum(cms_jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"heap\",datacenter=\"$datacenter\"})*100/sum(cms_jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"heap\", datacenter=\"$datacenter\"})"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 2, "x": 12, "y": 4 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_process_uptime_seconds{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{pod=\"$pod\",namespace=\"$namespace\",datacenter=\"$datacenter\"}[1m]))/ avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\",namespace=\"$namespace\",datacenter=\"$datacenter\"})",
       "legendFormat": "CPU Utilization"
      }
     ]
    },
    {
     "title": "Pod Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",pod = \"$pod\",datacenter=\"$datacenter\"}[1m])*60) by (pod) or sum(rate(cms_http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",pod = \"$pod\",datacenter=\"$datacenter\"}[1m])*60) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", area=\"nonheap\",datacenter=\"$datacenter\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"nonheap\",datacenter=\"$datacenter\"}) or sum(cms_jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", area=\"nonheap\",datacenter=\"$datacenter\"})*100/sum(cms_jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", area=\"nonheap\",datacenter=\"$datacenter\"})"
      }
     ]
    },
    {
     "title": "Live Threads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_threads_live{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or jvm_threads_live_threads{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_jvm_threads_live{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_jvm_threads_live_threads{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}"
      }
     ]
    },
    {
     "title": "Daemon Threads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_threads_daemon{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or jvm_threads_daemon_threads{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_jvm_threads_daemon{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_jvm_threads_daemon_threads{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}"
      }
     ]
    },
    {
     "title": "Peak Threads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_threads_peak{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or jvm_threads_peak_threads{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_jvm_threads_peak{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_jvm_threads_peak_threads{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}"
      }
     ]
    },
    {
     "title": "Pod Memory status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=~\"$service.*\", pod=\"$pod\",datacenter=\"$datacenter\"}",
       "legendFormat": "Container - Total memory"
      },
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container_name=~\"$service.*\",pod=\"$pod\",datacenter=\"$datacenter\"} ",
       "legendFormat": "Container - Used memory"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}) or sum(cms_jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"})",
       "legendFormat": "JVM - Max allowed memory"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}) or sum(cms_jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"})",
       "legendFormat": "JVM - Comitted memory"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}) or sum(cms_jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"})",
       "legendFormat": "JVM - Used memory (Heap & Non-Heap)"
      }
     ]
    },
    {
     "title": "JVM Used Memory - Distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", area=\"heap\",datacenter=\"$datacenter\"} or cms_jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", area=\"heap\",datacenter=\"$datacenter\"}",
       "legendFormat": "Heap - {{id}}"
      },
      {
       "expr": "jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", area=\"nonheap\",datacenter=\"$datacenter\"} or cms_jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\", area=\"nonheap\",datacenter=\"$datacenter\"}",
       "legendFormat": "Non Heap - {{id}}"
      }
     ]
    },
    {
     "title": "JVM Buffers ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_jvm_buffer_total_capacity_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}",
       "legendFormat": "{{id}} buffer - capacity"
      },
      {
       "expr": "jvm_buffer_count_buffers{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} / jvm_buffer_total_capacity_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_jvm_buffer_count_buffers{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} / cms_jvm_buffer_total_capacity_bytes{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}",
       "legendFormat": "{{id}} buffer - used"
      }
     ]
    },
    {
     "title": "fds per pod <> total pods count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_process_open_fds{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}",
       "legendFormat": "Open fds"
      }
     ]
    },
    {
     "title": "Garbage Collections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}[1m]) or rate(cms_jvm_gc_pause_seconds_count{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Garbage Collection - Pause Durations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\",pod=\"$pod\"}[1m])/rate(jvm_gc_pause_seconds_count{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}[1m]) or rate(cms_jvm_gc_pause_seconds_sum{namespace=\"$namespace\",service=\"$service\",datacenter=\"$datacenter\",pod=\"$pod\"}[1m])/rate(cms_jvm_gc_pause_seconds_count{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"} or cms_jvm_gc_pause_seconds_max{namespace=\"$namespace\",service=\"$service\", pod=\"$pod\",datacenter=\"$datacenter\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    }
   ]
  },
  {
   "title": "General Infra Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Emitted Metrics ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(scrape_samples_scraped{datacenter=\"$datacenter\", namespace=\"$namespace\", service=\"$service\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "CMS Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "GEC p99 Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"cms\",service=\"geccomp\",datacenter=\"sgp\"}[1m])) by (le)) or histogram_quantile(0.99, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"cms\",service=\"geccomp\",datacenter=\"sgp\"}[1m])) by (le))",
     "legendFormat": "GEC 99"
    }
   ]
  },
  {
   "title": "Persona Get p99 Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"cms\",service=\"persona-get\",datacenter=\"sgp\"}[1m])) by (le)) or histogram_quantile(0.99, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"cms\",service=\"persona-get\",datacenter=\"sgp\"}[1m])) by (le))",
     "legendFormat": "Persona Get 99"
    }
   ]
  },
  {
   "title": "Multi Get p99 Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"cms\",service=\"multi-get\",datacenter=\"sgp\"}[1m])) by (le)) or histogram_quantile(0.99, sum(rate(cms_http_server_requests_seconds_bucket{namespace=\"cms\",service=\"multi-get\",datacenter=\"sgp\"}[1m])) by (le))",
     "legendFormat": "Persona Get 99"
    }
   ]
  },
  {
   "title": "GEC Success % Critical Low Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"200\",namespace=\"cms\",service=\"geccomp\",datacenter=\"sgp\"}[1m])*60)/sum(rate(http_server_requests_seconds_count{namespace=\"cms\",service=\"geccomp\",datacenter=\"sgp\"}[1m])*60) or sum(rate(cms_http_server_requests_seconds_count{status=\"200\",namespace=\"cms\",service=\"geccomp\",datacenter=\"sgp\"}[1m])*60)/sum(rate(cms_http_server_requests_seconds_count{namespace=\"cms\",service=\"geccomp\",datacenter=\"sgp\"}[1m])*60)",
     "legendFormat": "GEC Success % Critical Low Alert"
    }
   ]
  },
  {
   "title": "Persona-Get Success %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"200\",namespace=\"cms\",service=\"persona-get\",datacenter=\"sgp\"}[1m])*60)/sum(rate(http_server_requests_seconds_count{namespace=\"cms\",service=\"persona-get\",datacenter=\"sgp\"}[1m])*60) or sum(rate(cms_http_server_requests_seconds_count{status=\"200\",namespace=\"cms\",service=\"persona-get\",datacenter=\"sgp\"}[1m])*60)/sum(rate(cms_http_server_requests_seconds_count{namespace=\"cms\",service=\"persona-get\",datacenter=\"sgp\"}[1m])*60)",
     "legendFormat": "Persona-Get Success %"
    }
   ]
  },
  {
   "title": "Multi-Get Success %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"200\",namespace=\"cms\",service=\"multi-get\",datacenter=\"sgp\"}[1m])*60)/sum(rate(http_server_requests_seconds_count{namespace=\"cms\",service=\"multi-get\",datacenter=\"sgp\"}[1m])*60) or sum(rate(cms_http_server_requests_seconds_count{status=\"200\",namespace=\"cms\",service=\"multi-get\",datacenter=\"sgp\"}[1m])*60)/sum(rate(cms_http_server_requests_seconds_count{namespace=\"cms\",service=\"multi-get\",datacenter=\"sgp\"}[1m])*60)",
     "legendFormat": "Multi-Get Success %"
    }
   ]
  },
  {
   "title": "Multi Get Queue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(executor_queued_tasks{namespace=\"cms\",service=\"multi-get\",datacenter=\"sgp\"})",
     "legendFormat": "Queued Tasks"
    }
   ]
  }
 ]
}