{
 "title": "Playback HPlay dashboard",
 "description": "Overall Service monitoring",
 "tags": [
  "gameday",
  "overall"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cms_http_server_requests_duration_seconds)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(cms_http_server_requests_duration_seconds, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(cms_http_server_requests_duration_seconds{service=\"$service\"}, pod)"
    }
   },
   { "name": "percentile", "label": "API Latency percentile", "query": "0.99,0.95,0.75" }
  ]
 },
 "panels": [
  {
   "title": "Service Monitor (aggregated for all pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m]))",
       "legendFormat": "service-rpm"
      }
     ]
    },
    {
     "title": "HTTP Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{status=~\"200\",service=\"$service\"}[1m]))",
       "legendFormat": "200 "
      },
      {
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{status=~\"4.*\",service=\"$service\"}[1m]))",
       "legendFormat": "4xx "
      },
      {
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{status=~\"5.*\",service=\"$service\"}[1m]))",
       "legendFormat": "5xx "
      }
     ]
    },
    {
     "title": "Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(cms_http_server_requests_duration_seconds_sum{service=\"$service\"}[1m])) / sum(rate(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m])))*1000",
       "legendFormat": "Avg"
      },
      {
       "expr": "sum(cms_http_server_requests_duration_seconds{service=\"$service\",status=\"200\",quantile=\"0.99\"} > 0) / count(cms_http_server_requests_duration_seconds{service=\"$service\",status=\"200\",quantile=\"0.99\"} > 0) * 1000",
       "legendFormat": "p99"
      },
      {
       "expr": "sum(cms_http_server_requests_duration_seconds{service=\"$service\",status=\"200\",quantile=\"0.95\"} > 0) / count(cms_http_server_requests_duration_seconds{service=\"$service\",status=\"200\",quantile=\"0.95\"} > 0) * 1000",
       "legendFormat": "p95"
      },
      {
       "expr": "sum(cms_http_server_requests_duration_seconds{service=\"$service\",status=\"200\",quantile=\"0.75\"} > 0) / count(cms_http_server_requests_duration_seconds{service=\"$service\",status=\"200\",quantile=\"0.75\"} > 0) * 1000",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Average latency by status code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(cms_http_server_requests_duration_seconds_sum{service=\"$service\",status=\"200\"}[1m])) / sum(rate(cms_http_server_requests_duration_seconds_count{ service=\"$service\",status=\"200\"}[1m])))*1000",
       "legendFormat": "200"
      },
      {
       "expr": "(sum(rate(cms_http_server_requests_duration_seconds_sum{service=\"$service\",status=~\"4.*\"}[1m])) / sum(rate(cms_http_server_requests_duration_seconds_count{ service=\"$service\",status=~\"4.*\"}[1m])))*1000",
       "legendFormat": "4xx"
      },
      {
       "expr": "(sum(rate(cms_http_server_requests_duration_seconds_sum{service=\"$service\",status=~\"5.*\"}[1m])) / sum(rate(cms_http_server_requests_duration_seconds_count{ service=\"$service\",status=~\"5.*\"}[1m])))*1000",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Success Percent",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{status=~\"200\",service=\"$service\"}[1m]))/sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m]))"
      }
     ]
    },
    {
     "title": "Available Pod count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\"}) by (deployment)",
       "legendFormat": "Available Replica count"
      }
     ]
    },
    {
     "title": "Service CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"$service.*\"}[1m])) by (pod) / avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"$service.*\"})",
       "legendFormat": "CPU Percent - {{pod}}"
      }
     ]
    },
    {
     "title": "Service Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 10, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{pod=~\"$service.*\"}) by (pod)",
       "legendFormat": "Memory - {{ container }}"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\"}) by (deployment)",
       "legendFormat": "Pods - {{deployment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Monitor (Aggregated for all pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Traffic RPM",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m])) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API Latency - Percentile $percentile",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(cms_http_server_requests_duration_seconds{service=\"$service\",status=\"200\",quantile=~\"$percentile\"}) by (uri,quantile) / scalar(sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\"})) * 1000",
       "legendFormat": "{{uri}} - p{{quantile}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API - HTTP 200 Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\",status=\"200\"}[1m])) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API - HTTP 4xx Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\",status=~\"4.*\"}[1m])) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API - HTTP 5xx Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\",status=~\"5.*\"}[1m])) by (uri)",
       "legendFormat": "{{uri}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API Usage and Error rate",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m])) by (uri) / scalar(sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m])))"
      },
      {
       "expr": "((sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m])) by (uri)) - \n(sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\",status=\"200\"}[1m])) by (uri))) / scalar(sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m]))) "
      }
     ]
    },
    {
     "title": "Pod level - Traffic Distribution",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m])) by (pod) / scalar(sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\"}[1m])))",
       "legendFormat": "{{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Pod level - HTTP 200 Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\",status=~\"200\"}[1m])) by (pod)",
       "legendFormat": "pod_id - {{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Pod level - HTTP 4XX Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\",status=~\"4.*\"}[1m])) by (pod)",
       "legendFormat": "pod_id - {{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Pod level - HTTP 5xx Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(delta(cms_http_server_requests_duration_seconds_count{service=\"$service\",status=~\"5.*\"}[1m])) by (pod)",
       "legendFormat": "pod_id - {{pod}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "Load balancers stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "aws_elb_request_count_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
      },
      {
       "expr": "aws_alb_request_count_sum + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\"}) by(name,tag_kubernetes_io_ingress_name)",
       "legendFormat": "ALB - {{ tag_kubernetes_io_ingress_name }}"
      }
     ]
    },
    {
     "title": "Avg Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "aws_elb_latency_average + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
      },
      {
       "expr": "aws_alb_target_response_time_average + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\"}) by(name,tag_kubernetes_io_ingress_name)",
       "legendFormat": "ALB - {{ tag_kubernetes_io_ingress_name}}"
      }
     ]
    },
    {
     "title": "ELB 5XX",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 78 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aws_elb_httpcode_elb_5_xx_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
      },
      {
       "expr": "aws_alb_httpcode_elb_5_xx_count_sum + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\"}) by(name,tag_kubernetes_io_ingress_name)",
       "legendFormat": "ALB - {{ tag_kubernetes_io_ingress_name}}"
      }
     ]
    },
    {
     "title": "Backend 5XX",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 78 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aws_elb_httpcode_backend_5_xx_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
      },
      {
       "expr": "aws_alb_tg_httpcode_target_5_xx_count_sum + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\"}) by(name,tag_kubernetes_io_ingress_name)",
       "legendFormat": "ALB - {{tag_kubernetes_io_ingress_name}}"
      }
     ]
    },
    {
     "title": "Spill Over Count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aws_elb_spillover_count_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
      }
     ]
    },
    {
     "title": "Surge queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 83 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aws_elb_surge_queue_length_maximum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
      }
     ]
    },
    {
     "title": "Backend 4XX",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 83 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "aws_elb_httpcode_backend_4_xx_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"$namespace/$service\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "ELB - {{ tag_kubernetes_io_service_name }}"
      },
      {
       "expr": "aws_alb_tg_httpcode_target_4_xx_count_sum + on (name)  group_left(tag_kubernetes_io_ingress_name) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_Name=~\"$namespace/$service.*\"}) by(name,tag_kubernetes_io_ingress_name)",
       "legendFormat": "ALB - {{ tag_kubernetes_io_ingress_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Monitor for pod - $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{service=\"$service\", pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 4, "y": 4 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{service=\"$service\", pod=\"$pod\"}*1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{service=\"$service\",pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{service=\"$service\",pod=\"$pod\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{service=\"$service\",pod=\"$pod\", area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "Live Threads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_threads_live{service=\"$service\", pod=\"$pod\"} or jvm_threads_live_threads{service=\"$service\", pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Daemon Threads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_threads_daemon{service=\"$service\", pod=\"$pod\"} or jvm_threads_daemon_threads{service=\"$service\", pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Peak Threads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_threads_peak{service=\"$service\", pod=\"$pod\"} or jvm_threads_peak_threads{service=\"$service\", pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Pod Memory status",
     "type": "graph",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{ container=~\"$service.*\", pod=\"$pod\"}",
       "legendFormat": "Container - Total memory"
      },
      {
       "expr": "container_memory_usage_bytes{ container_name=~\"$service.*\",pod=\"$pod\"} ",
       "legendFormat": "Container - Used memory"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\"})",
       "legendFormat": "JVM - Max allowed memory"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\"})",
       "legendFormat": "JVM - Comitted memory"
      },
      {
       "expr": "sum(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\"})",
       "legendFormat": "JVM - Used memory (Heap & Non-Heap)"
      }
     ]
    },
    {
     "title": "JVM Used Memory - Distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"heap\"}",
       "legendFormat": "Heap - {{id}}"
      },
      {
       "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"nonheap\"}",
       "legendFormat": "Non Heap - {{id}}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name=~\"$service.*\",pod_name=\"$pod\"},\"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / \nsum(kube_pod_container_resource_requests_cpu_cores{container=~\"$service.*\",pod=\"$pod\"}) by (pod)",
       "legendFormat": "CPU Utilization"
      }
     ]
    },
    {
     "title": "JVM Buffers ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "{{id}} buffer - capacity"
      },
      {
       "expr": "jvm_buffer_memory_used{service=\"$service\", pod=\"$pod\"} / jvm_buffer_total_capacity{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "{{id}} buffer - used"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "Load Average 1m"
      }
     ]
    },
    {
     "title": "Garbage Collections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_duration_seconds_count{service=\"$service\", pod=\"$pod\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Garbage Collection - Pause Durations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_duration_seconds_sum{service=\"$service\", pod=\"$pod\"}[1m])/rate(jvm_gc_pause_duration_seconds_count{service=\"$service\", pod=\"$pod\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_duration_seconds_max{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    }
   ]
  }
 ]
}