{
 "title": "Payments & Subscriptions - Health",
 "description": "Payments & Subscriptions - Health",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "User funnel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Paywall throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(increase(paywall_subs_dds_http_status_code_total{namespace=\"hspay\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[1m]))",
       "legendFormat": "Paywall Traffic"
      }
     ]
    },
    {
     "title": "Payments Page throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dds_query_execution_time_count{source_cluster=~\"hs-eks-prod4-api-apse1\",pod=~\".*pay-dds.*\",query=\"GetBillingDetails\"}[1m]))",
       "legendFormat": "Payments page calls"
      }
     ]
    },
    {
     "title": "Subs Webhook throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hspay_thread_pool_based_sqs_consumer_metrics_total{consumer=\"OmsNotifyEventHandler\",source_cluster=\"hs-eks-prod4-api-apse1\"}[1m]) * 60)",
       "legendFormat": "Webhook traffic"
      }
     ]
    },
    {
     "title": "Payment INIT RPM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hspay_subscriptions_init_metrics_total{country_code=\"IN\",is_async_init=\"true\",payment_mode!=\"partner\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[1m])) + sum(rate(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_bucket{le=\"+Inf\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[1m]) * 60)",
       "legendFormat": "INIT traffic - RPM"
      }
     ]
    }
   ]
  },
  {
   "title": "Payment Gateway Funnel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Success Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent", "label": "Success rate (%)" }
     ],
     "targets": [
      {
       "expr": "100 * sum((delta(hspay_payments_success_metrics_total{acquisition_type=\"fresh_purchase\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m]))) / sum((delta(hspay_payments_init_metrics_total{acquisition_type=\"fresh_purchase\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m])))",
       "legendFormat": "Overall SR"
      }
     ]
    },
    {
     "title": "PhonePe PG Success Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (payment_mode, payment_processor) (delta(hspay_payments_success_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"PHONEPE\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m])) / sum by (payment_mode, payment_processor) (delta(hspay_payments_init_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"PHONEPE\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m]))",
       "legendFormat": "{{payment_mode}} / {{payment_processor}}"
      }
     ]
    },
    {
     "title": "RAZOR PG Success Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (payment_mode, payment_processor) (delta(hspay_payments_success_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"RAZOR\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m])) / sum by (payment_mode, payment_processor) (delta(hspay_payments_init_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"RAZOR\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m]))",
       "legendFormat": "{{payment_mode}} / {{payment_processor}}"
      }
     ]
    },
    {
     "title": "PAYTM PG Success Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (payment_mode, payment_processor) (delta(hspay_payments_success_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"PAYTM\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m])) / sum by (payment_mode, payment_processor) (delta(hspay_payments_init_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"PAYTM\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m]))",
       "legendFormat": "{{payment_mode}} / {{payment_processor}}"
      }
     ]
    },
    {
     "title": "BillDESK PG Success Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (payment_mode) (delta(hspay_payments_success_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"BILLDESK\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m])) / sum by (payment_mode) (delta(hspay_payments_init_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"BILLDESK\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m]))",
       "legendFormat": "{{payment_mode}} / {{payment_processor}}"
      }
     ]
    },
    {
     "title": "PAYU PG Success Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (payment_mode) (delta(hspay_payments_success_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"PAYU\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m])) / sum by (payment_mode) (delta(hspay_payments_init_metrics_total{acquisition_type=\"fresh_purchase\",gateway_name=\"PAYU\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[10m]))",
       "legendFormat": "{{payment_mode}} / {{payment_processor}}"
      }
     ]
    },
    {
     "title": "Initiate by PG",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum by (gateway_name) ((delta(hspay_payments_init_metrics_total{acquisition_type=\"fresh_purchase\",country=\"in\",source_cluster=~\"hs-eks-prod4-api-apse1\"}[1m])))",
       "legendFormat": "Traffic - {{gateway_name}}"
      }
     ]
    }
   ]
  }
 ]
}