{
 "title": "[Shifu] Predict Service Overview",
 "tags": [ "shifu" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "adtech-in-dev-aps1,adtech-in-pp-aps1,adtech-in-qa-aps1"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods Total Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{pod=~\"adtech-shifu-vod-perf-ads-service.*\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Avg RPM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(sum(increase(shifu_performance_ads_prediction_service_prediction_feature_build_time_seconds_count{job=\"adtech-shifu-vod-perf-ads-ambassador\", namespace=\"$namespace\"}[1m])) by  (instance))"
    }
   ]
  },
  {
   "title": "Pod Avg CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"adtech-shifu-vod-perf-ads-service.*\",namespace=\"$namespace\"}[1m])/8)"
    }
   ]
  },
  {
   "title": "Request RPM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_performance_ads_prediction_service_prediction_feature_build_time_seconds_count{job=\"adtech-shifu-vod-perf-ads-ambassador\", namespace=\"$namespace\"}[1m])) ",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "Decision service predict time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(shifu_decision_service_get_prediction_time_seconds_bucket{service=\"adtech-shifu-ad-decision-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "p999"
    },
    {
     "expr": "histogram_quantile(0.995, sum(rate(shifu_decision_service_get_prediction_time_seconds_bucket{service=\"adtech-shifu-ad-decision-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "p995"
    },
    {
     "expr": "histogram_quantile(0.990, sum(rate(shifu_decision_service_get_prediction_time_seconds_bucket{service=\"adtech-shifu-ad-decision-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "p990"
    }
   ]
  },
  {
   "title": "total prediction time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(shifu_performance_ads_prediction_service_prediction_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "total time 99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(shifu_performance_ads_prediction_service_prediction_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "total time 95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(shifu_performance_ads_prediction_service_prediction_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "total time 50%"
    }
   ]
  },
  {
   "title": "performance ads selection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_request_count_total{service=\"adtech-shifu-ad-decision-service\", selection_stage=\"SELECT_PERFORMANCE\"}[1m])) - sum(increase(shifu_decision_service_request_count_total{service=\"adtech-shifu-ad-decision-service\", selection_stage=\"SELECT_HOUSE\"}[1m])) "
    }
   ]
  },
  {
   "title": "request count by selection stage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_request_count_total{job=\"adtech-shifu-ad-decision-service\"}[1m])) by (selection_stage)",
     "legendFormat": "{{selection_stage}}"
    }
   ]
  },
  {
   "title": "prediction_call_back",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_prediction_response_total{job=\"adtech-shifu-ad-decision-service\",namespace=\"$namespace\"}[1m]))by(http_return_code)",
     "legendFormat": "{{http_return_code}}"
    }
   ]
  },
  {
   "title": "Decision_service_perf_ads_circuit_breaker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_circuit_breaker_exception_total{namespace=\"$namespace\"}[1m])) by(circuit_breaker_exception_type)"
    }
   ]
  },
  {
   "title": "gc pause",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(jvm_gc_pause_seconds_sum{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m]))by (cause)"
    }
   ]
  },
  {
   "title": "load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(system_load_average_1m{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m]))/8"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jvm_memory_used_bytes{job=\"adtech-shifu-vod-perf-ads-ambassador\", namespace=\"$namespace\"}) by (instance, id)) by(id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"adtech-shifu-vod-perf-ads-service.*\",namespace=\"$namespace\"}[1m])/8)"
    }
   ]
  },
  {
   "title": "empty feature count from redis",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_performance_ads_prediction_service_empty_feature_from_redis_exception_total{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m]))by(feature_type)"
    }
   ]
  },
  {
   "title": "feature build",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(shifu_performance_ads_prediction_service_prediction_feature_build_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "feature build 99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(shifu_performance_ads_prediction_service_prediction_feature_build_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "feature build 95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(shifu_performance_ads_prediction_service_prediction_feature_build_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "feature build 50%"
    }
   ]
  },
  {
   "title": "redis",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(shifu_performance_ads_prediction_service_prediction_redis_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "redis 99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(shifu_performance_ads_prediction_service_prediction_redis_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "redis 95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(shifu_performance_ads_prediction_service_prediction_redis_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "redis 50%"
    }
   ]
  },
  {
   "title": "XGB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(shifu_performance_ads_prediction_service_prediction_xgb_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "xgb 95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(shifu_performance_ads_prediction_service_prediction_xgb_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "xgb 50%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(shifu_performance_ads_prediction_service_prediction_xgb_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "xgb 99%"
    }
   ]
  },
  {
   "title": "LR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(shifu_performance_ads_prediction_service_prediction_lr_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "lr 95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(shifu_performance_ads_prediction_service_prediction_lr_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "lr 50%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(shifu_performance_ads_prediction_service_prediction_lr_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "lr 99%"
    }
   ]
  },
  {
   "title": "transform",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(shifu_performance_ads_prediction_service_prediction_transform_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\"}[1m])) by (le))\n",
     "legendFormat": "transform 99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(shifu_performance_ads_prediction_service_prediction_transform_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "transform 95%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(shifu_performance_ads_prediction_service_prediction_transform_time_seconds_bucket{service=\"adtech-shifu-vod-perf-ads-service\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "transform 50%"
    }
   ]
  }
 ]
}