{
 "title": "DP > Kafka > Cluster Level Metrics - Levitate",
 "tags": [
  "dp",
  "kafka"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(BrokerTopicMetrics_OneMinuteRate,env)"
    }
   },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(BrokerTopicMetrics_OneMinuteRate{env=\"$env\"},application)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(mem_used_percent{application=\"$application\",env=\"$env\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Kafka Degradation SOP : \nhttps://hotstar.atlassian.net/wiki/spaces/HP2/pages/3898343832/Data+Platform+DP+Runbook+Degradation+SOP+for+WC#Degradation-for-Kafka"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "P0 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU IO Wait %",
     "type": "graph",
     "description": "iowait shows the percentage of time that the CPU was idle during which the system had an outstanding disk I/O request",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_iowait{env=\"$env\", application=\"$application\", host=~\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "description": "Avg User + System CPU Usage",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_user{env=\"$env\", application=\"$application\", host=~\"$host\", cpu=\"cpu-total\"} + cpu_usage_system{env=\"$env\", application=\"$application\", host=~\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Network Processor Utilisation %",
     "type": "graph",
     "description": "1 minus Avg Network Avg Idle %",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - SocketServer_Value{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"NetworkProcessorAvgIdlePercent\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Request Handler Idle",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "RequestHandlerAvgIdlePercent_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Request Queue Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "RequestChannel_Value{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"RequestQueueSize\"}",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Response Queue Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "RequestChannel_Value{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"ResponseQueueSize\"}",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(controllerMetrics_Value{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"OfflinePartitionsCount\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(UnderReplicatedPartitions_Value{env=\"$env\", application=\"$application\", hostname=~\"$host\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Peak Throughput per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(diskio_read_bytes_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"}) + max_over_time(diskio_write_bytes_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Peak IOPS per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(diskio_reads_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"}) + max_over_time(diskio_writes_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Data Disk Usage",
     "type": "graph",
     "description": "Max used percentage across all data disks. Max is used because we want to track the least free disk.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(disk_used_percent{env=\"$env\", application=\"$application\", host=~\"$host\", path=~\"/mnt/vol.*\"}) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Disks Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peak Write Throughput per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(diskio_write_bytes_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Peak Read Throughput per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(diskio_read_bytes_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Peak Write IOPS per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(diskio_writes_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Peak Read IOPS per Broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(diskio_reads_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Peak Write I/O Wait Time per Broker per Data Disk",
     "type": "graph",
     "description": "These values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max_over_time(diskio_write_time_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})",
       "legendFormat": "{{host}} - {{name}}"
      }
     ]
    },
    {
     "title": "Peak Read I/O Wait Time per Broker per Data Disk",
     "type": "graph",
     "description": "These values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max_over_time(diskio_read_time_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})",
       "legendFormat": "{{host}} - {{name}}"
      }
     ]
    },
    {
     "title": "Peak IO Queued Time per Broker per Data Disk",
     "type": "graph",
     "description": "This value counts the number of milliseconds during which the device has had I/O requests queued.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max_over_time(diskio_io_time_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})",
       "legendFormat": "{{host}} - {{name}}"
      }
     ]
    },
    {
     "title": "IOPS In Progress",
     "type": "graph",
     "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed.\nSum of iops in progress aggregated across all data disks per broker",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(diskio_iops_in_progress{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})",
       "legendFormat": "{{host}} - {{name}}"
      }
     ]
    },
    {
     "title": "Merged Writes per Broker per Disk",
     "type": "graph",
     "description": "Writes which are adjacent to each other may be merged for efficiency",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(diskio_merged_writes_rate{env=\"$env\", application=\"$application\", host=~\"$host\", name=~\"nvme[1-9].*\"})",
       "legendFormat": "{{host}} - {{name}}"
      }
     ]
    },
    {
     "title": "Log Disk Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(disk_used_percent{env=\"$env\", application=\"$application\", host=~\"$host\", path = \"/mnt/log\"}) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Root Disk Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(disk_used_percent{env=\"$env\", application=\"$application\", host=~\"$host\", path = \"/\"}) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Global Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages In",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(GlobalBrokerTopicMetrics_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"MessagesInPerSec\"})",
       "legendFormat": "{{hostname}}"
      },
      {
       "expr": "sum_over_time(GlobalBrokerTopicMetrics_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"MessagesInPerSec\"})*60",
       "legendFormat": "{{hostname}} - rpm"
      }
     ]
    },
    {
     "title": "Active Controller",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "controllerMetrics_Value{env=\"$env\", application=\"$application\", name=\"ActiveControllerCount\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Produce Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(BrokerTopicMetrics_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"TotalProduceRequestsPerSec\"}) by (hostname)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Fetch Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(BrokerTopicMetrics_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"TotalFetchRequestsPerSec\"}) by (hostname)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Produce Request Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "RequestMetrics_Mean{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"TotalTimeMs\", request=\"Produce\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Fetch Consumer Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "RequestMetrics_Mean{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"TotalTimeMs\", request=\"FetchConsumer\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Failed Produce Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(BrokerTopicMetrics_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"FailedProduceRequestsPerSec\"}) by (hostname, topic)",
       "legendFormat": "{{hostname}} - {{topic}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(BrokerTopicMetrics_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"FailedFetchRequestsPerSec\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Log Flush Time",
     "type": "graph",
     "description": "The rate at which log data is written to disk",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "LogFlushRateAndTimeMs_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Brokers Count",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(GlobalBrokerTopicMetrics_OneMinuteRate{env=\"$env\", application=\"$application\", name=\"MessagesInPerSec\"})"
      }
     ]
    },
    {
     "title": "Topics Count",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 15, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(controllerMetrics_Value{name='GlobalTopicCount' , application=\"$application\" , env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Partitions Count",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max(controllerMetrics_Value{name='GlobalPartitionCount', application=\"$application\", env=\"$env\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker Bytes In",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "GlobalBrokerTopicMetrics_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"BytesInPerSec\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Broker Bytes Out",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 139 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "GlobalBrokerTopicMetrics_OneMinuteRate{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=\"BytesOutPerSec\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Instance Bytes In",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 148 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_recv{env=\"$env\", application=\"$application\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Instance Bytes Out",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{env=\"$env\", application=\"$application\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "GarbageCollector_LastGcInfo_duration{env=\"$env\", application=\"$application\", hostname=~\"$host\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "GC Collection Time Per Sec",
     "type": "graph",
     "description": "Time spent in G1 Young Generation GC per second",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(GarbageCollector_CollectionTime{env=\"$env\", application=\"$application\", hostname=~\"$host\", name=~\".*Young.*\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "TCP Established Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(netstat_tcp_established{env=\"$env\", application=\"$application\", host=~\"$host\"})",
       "legendFormat": "{{host}} - established"
      }
     ]
    },
    {
     "title": "TCP Time Wait Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(netstat_tcp_time_wait{env=\"$env\", application=\"$application\", host=~\"$host\"})",
       "legendFormat": "{{host}} - time_wait"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Used memory doesn't include buffers or cached data, actual RSS usage by all processes",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(mem_used_percent{env=\"$env\", application=\"$application\", host=~\"$host\"})",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Pages In & Out of Disk",
     "type": "graph",
     "description": "pgpgin - KBs system paged in from the disk to memory.\npgpgout = KBs system paged out from memory to disk.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(kernel_vmstat_pgpgout_rate{env=\"$env\", application=\"$application\", host=~\"$host\"})",
       "legendFormat": "{{host}} - pgpgout (disk writes)"
      },
      {
       "expr": "sum_over_time(kernel_vmstat_pgpgin_rate{env=\"$env\", application=\"$application\", host=~\"$host\"})",
       "legendFormat": "{{host}} - pgpgin (disk reads)"
      }
     ]
    }
   ]
  },
  {
   "title": "Partition Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Under Min ISR Partitions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(UnderMinIsrPartitionCount_Value{env=\"$env\", application=\"$application\", hostname=~\"$host\"}) by (hostname)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Leader Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(LeaderCount_Value{env=\"$env\", application=\"$application\", hostname=~\"$host\"}) by (hostname)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Partition count per broker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(PartitionCount_Value{env=\"$env\", application=\"$application\", hostname=~\"$host\"}) by (hostname)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Brokers Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(GlobalBrokerTopicMetrics_OneMinuteRate{env=\"prod\", application=~\"kafka.*\", name=\"MessagesInPerSec\"}) by (application)",
       "legendFormat": "{{application}}"
      }
     ]
    }
   ]
  }
 ]
}