{
 "title": "Subs and Pay Integrated",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "NAMESPACE",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, namespace)"
    }
   },
   {
    "name": "SERVICE",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, job)"
    }
   },
   {
    "name": "API_STATUS",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", deployment=\"subscription-service\"})",
       "legendFormat": "subs pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", deployment=\"payment-service\"})",
       "legendFormat": "pay pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", deployment=\"subscription-service-read\"})",
       "legendFormat": "subs read pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", deployment=\"subscription-service-worker\"})",
       "legendFormat": "subs worker pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", deployment=\"payment-service-worker\"})",
       "legendFormat": "pay worker pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Subs - 2XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (api_name, response_code, http_status) (delta(hspay_subscriptions_api_response_metrics_total{http_status=~\"2.*\"}[1m]))",
       "legendFormat": "{{api_name}}, {{response_code}}, {{http_status}}"
      }
     ]
    },
    {
     "title": "Subs - Overall response throughput by codes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (http_status) (delta(hspay_subscriptions_api_response_metrics_total[1m]))",
       "legendFormat": "{{http_status}}"
      }
     ]
    },
    {
     "title": "Subs API Level Metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$NAMESPACE\", service=~\"$SERVICE\", status=~\"$API_STATUS\"}[1m])) by (uri, status) > 0 ",
       "legendFormat": "{{uri}} {{status}}"
      }
     ]
    },
    {
     "title": "Pay - 2XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (api_name, response_code, http_status) (delta(hspay_payments_api_response_metrics_total{http_status=~\"2.*\"}[1m]))",
       "legendFormat": "{{api_name}}, {{response_code}}, {{http_status}}"
      }
     ]
    },
    {
     "title": "Subs - 4XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (api_name, response_code, http_status) (delta(hspay_subscriptions_api_response_metrics_total{http_status=~\"4.*\"}[1m]))",
       "legendFormat": "{{api_name}}, {{response_code}}, {{http_status}}"
      }
     ]
    },
    {
     "title": "Initiate 5XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_5XX_counter[1m]))",
       "legendFormat": "Subs"
      },
      {
       "expr": "sum(increase(http_custom_server_requests_seconds_count{namespace=\"hspay-in-load-apse1\", service=~\"payment-service.*\", uri=\"/payments/{apiVersion:v1|v2|v3}/charge\", status=~\"5..\"}[1m]))",
       "legendFormat": "Pay"
      }
     ]
    },
    {
     "title": "Pay - 4XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (api_name, response_code, http_status) (delta(hspay_payments_api_response_metrics_total{http_status=~\"4.*\"}[1m]))",
       "legendFormat": "{{api_name}}, {{response_code}}, {{http_status}}"
      }
     ]
    },
    {
     "title": "Subs - Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name, method) (increase(hspay_subscriptions_error_metrics_total[30s]))",
       "legendFormat": "Errors: {{service_name}}, {{method}}"
      }
     ]
    },
    {
     "title": "Subs Redis metrics | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_redis_metrics_bucket[1m])) by (le, method))"
      }
     ]
    },
    {
     "title": "Pay/Kafka - Producer metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(hspay_payments_service_kafka_producer_bucket[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_payments_service_kafka_producer_bucket[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_service_kafka_producer_bucket[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "sum(delta(hspay_payments_service_kafka_producer_bucket{le=\"+Inf\"}[1m]))",
       "legendFormat": "Throughput"
      }
     ]
    }
   ]
  },
  {
   "title": "Major APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Initiate throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_bucket{le=\"+Inf\"}[1m]))",
       "legendFormat": "Subs"
      },
      {
       "expr": "sum(delta(hspay_payments_service_ChargeService_initiate_bucket{le=\"+Inf\"}[1m]))",
       "legendFormat": "Pay"
      }
     ]
    },
    {
     "title": "Subs - Initiate latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_bucket[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_bucket[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_bucket[1m])) by (le))",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Get subs throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"0\", le=\"+Inf\"}[1m]))",
       "legendFormat": "verbose 0"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"1\", le=\"+Inf\"}[1m]))",
       "legendFormat": "verbose 1"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"2\", le=\"+Inf\"}[1m]))",
       "legendFormat": "verbose 2"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"3\", le=\"+Inf\"}[1m]))",
       "legendFormat": "verbose 3"
      }
     ]
    },
    {
     "title": "Get Subs Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket[1m])) by (le))",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Get subs latency | verbose 0",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"0\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"0\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"0\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Payment client - Initiate latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(hspay_subscriptions_http_client_metrics_bucket[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_http_client_metrics_bucket[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_http_client_metrics_bucket[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "max(rate(hspay_subscriptions_http_client_metrics_bucket[1m]))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Get subs latency | verbose 1",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"1\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"1\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"1\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Get subs latency | verbose 2",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"2\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"2\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"2\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Get subs latency | verbose 3",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"3\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"3\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"3\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "PayU - Initiate latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(hspay_payments_service_PayUGateway_initiateCharge_bucket[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_payments_service_PayUGateway_initiateCharge_bucket[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_service_PayUGateway_initiateCharge_bucket[1m])) by (le))",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Partner - Create Subs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_PartnerService_createSubscription_bucket[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_PartnerService_createSubscription_bucket[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_PartnerService_createSubscription_bucket{le=\"+Inf\"}[1m]))",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "Partner - Update Subs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_PartnerService_updateSubscription_bucket[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_PartnerService_updateSubscription_bucket[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_PartnerService_updateSubscription_bucket{le=\"+Inf\"}[1m]))",
       "legendFormat": "throughput"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Consumer Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_worker_metrics_bucket{le=\"+Inf\"}[1m])) by (queue_name)",
       "legendFormat": "{{queue_name}}"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_consumer_metrics_bucket{le=\"+Inf\"}[1m])) by (consumer)",
       "legendFormat": "{{consumer}}"
      }
     ]
    },
    {
     "title": "Worker Consumer Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_worker_metrics_bucket[1m])) by (queue_name,le))",
       "legendFormat": "{{queue_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_consumer_metrics_bucket[1m])) by (consumer,le))",
       "legendFormat": "{{consumer}}"
      }
     ]
    },
    {
     "title": "Partner worker recur events success count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hspay_subscriptions_partner_worker_metrics_total{is_success=\"true\"})) by (partner)",
       "legendFormat": "success count - {{partner}}"
      },
      { "legendFormat": "failure count - {{partner}}" },
      {
       "expr": "sum(increase(hspay_subscriptions_partner_worker_metrics_total{is_success=\"false\"}))",
       "legendFormat": "failure count - total"
      }
     ]
    }
   ]
  },
  {
   "title": "Partner Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "OK",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"OK\"}[1m])) by (api_name)",
       "legendFormat": "{{api_name}}"
      }
     ]
    },
    {
     "title": "Traffic by partner",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{}[1m])) by (partner)",
       "legendFormat": "{{partner}}"
      }
     ]
    },
    {
     "title": "USER_SUBSCRIPTION_SUBSCRIPTION_NOT_FOUND",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"USER_SUBSCRIPTION_SUBSCRIPTION_NOT_FOUND\"}[1m])) by (api_name)",
       "legendFormat": "{{api_name}}"
      }
     ]
    },
    {
     "title": "INTERNAL_SERVER_ERROR",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"INTERNAL_SERVER_ERROR\"}[1m])) by (api_name)",
       "legendFormat": "{{api_name}}"
      }
     ]
    },
    {
     "title": "PARTNER_SUBSCRIPTION_CONFLICT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"PARTNER_SUBSCRIPTION_CONFLICT\"}[1m])) by (partner)",
       "legendFormat": "{{partner}}"
      }
     ]
    },
    {
     "title": "EVENT_NOT_ACCEPTABLE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"EVENT_NOT_ACCEPTABLE\"}[1m])) by (api_name)",
       "legendFormat": "{{api_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat server metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat busy threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_threads_busy_threads{job=\"subscription-service\"})",
       "legendFormat": "Subs busy threads"
      },
      {
       "expr": "sum(tomcat_threads_busy_threads{job =~ \"payment-service.*\"})",
       "legendFormat": "Pay busy threads"
      },
      {
       "expr": "sum(tomcat_threads_busy_threads{job=\"subscription-service-read\"})",
       "legendFormat": "Subs read busy threads"
      }
     ]
    }
   ]
  },
  {
   "title": "Database metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pay - Charges | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_db_metrics_bucket{entity=\"charge\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Pay - Webhook notification Log | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_db_metrics_bucket{entity=\"webhook_notification_log\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Pay - PayU Charges | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_db_metrics_bucket{entity=\"payu_charge\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Subscription Table | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_db_metrics_bucket{entity=\"subscription\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Subscription Logs Table | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_db_metrics_bucket{entity=\"subscription_log\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Orders Table | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_db_metrics_bucket{entity=\"order\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Subs Redis metrics | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_redis_metrics_bucket[1m])) by (le, method))"
      }
     ]
    },
    {
     "title": "Switch transition Logs Table | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_db_metrics_bucket{entity=\"switch_transition_meta\"}[1m])) by (le, entity, method))"
      }
     ]
    }
   ]
  }
 ]
}