{
 "title": "HS-CORE-CONFIG-STORE",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service_name", "label": "service_name", "query": "hs-core-config-store" },
   { "name": "platform", "query": "android,web,ios,others" },
   {
    "name": "cluster",
    "query": "hs-eks-prod-api-apse1,hs-eks-prod-api-euw1,hs-eks-load1-api-apse1,hs-eks-dev-api-aps1,hs-eks-qa-api-aps1,hs-eks-nonprod-api-aps1"
   }
  ]
 },
 "panels": [
  {
   "title": "Config Service POD Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall CPU utilisation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"main\", source_cluster=\"$cluster\",pod=~\"hs-core-config-store.*\"}) by (pod)/sum(kube_pod_container_resource_requests_cpu_cores{container=\"main\",source_cluster=\"$cluster\", pod=~\"hs-core-config-store.*\"}) by (pod))",
       "legendFormat": "Average"
      },
      {
       "expr": "max(sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container=\"main\", source_cluster=\"$cluster\",pod=~\"hs-core-config-store.*\"}) by (pod)/sum(kube_pod_container_resource_requests_cpu_cores{container=\"main\",source_cluster=\"$cluster\", pod=~\"hs-core-config-store.*\"}) by (pod))",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "Overall Memory utilisation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(sum(container_memory_rss{namespace=\"hs-core\", source_cluster=~\"$cluster\", container=\"main\", pod=~\"hs-core-config-store.*\"}) by (pod)/sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"hs-core\", source_cluster=~\"$cluster\", container=\"main\", pod=~\"hs-core-config-store.*\"}) by (pod))",
       "legendFormat": "Average"
      },
      {
       "expr": "max(sum(container_memory_rss{namespace=\"hs-core\", source_cluster=~\"$cluster\", container=\"main\", pod=~\"hs-core-config-store.*\"}) by (pod)/sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"hs-core\", source_cluster=~\"$cluster\", container=\"main\", pod=~\"hs-core-config-store.*\"}) by (pod))",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "Config Service Instances",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{container=\"main\", pod=~\"hs-core-config-store-.*\", source_cluster=\"$cluster\"})",
       "legendFormat": "Instances"
      }
     ]
    },
    {
     "title": "Config Service Cores",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container=\"main\", pod=~\"hs-core-config-store-.*\",source_cluster=\"$cluster\"})",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Number of OS threads",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(go_threads{service =~ \"$service_name\",source_cluster=\"$cluster\"}[1m])",
       "legendFormat": "Go Threads"
      }
     ]
    },
    {
     "title": "Config Service CPU usage Per Pod",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"hs-core\", container=\"main\", pod=~\"${service_name}.*\", source_cluster=~\"$cluster\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Config Service Memory usage Per Pod",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{namespace=\"hs-core\", container=\"main\", pod=~\"${service_name}.*\", source_cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Config Service Go Routines Per Pod",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(go_goroutines{service =~ \"$service_name\", source_cluster=\"$cluster\"}[10m]) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Launch Darkly Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Launch Darkly Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hs_core_config_store_ld_latency_count{service =~ \"$service_name\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (type)",
       "legendFormat": "\"{{type}}\" Throughput"
      }
     ]
    },
    {
     "title": "Launch Darkly Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hs_core_config_store_ld_latency_sum{service =~ \"$service_name\",source_cluster=\"$cluster\"}[$__rate_interval])) by (type)/\nsum(rate(hs_core_config_store_ld_latency_count{service =~ \"$service_name\",source_cluster=\"$cluster\"}[$__rate_interval])) by (type)",
       "legendFormat": "launchdarkly {{ type }}"
      }
     ]
    },
    {
     "title": "LaunchDarkly P0 latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(hs_core_config_store_ld_latency_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hs_core_config_store_ld_latency_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hs_core_config_store_ld_latency_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(hs_core_config_store_ld_latency_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hs_core_config_store_ld_latency_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  },
  {
   "title": "Config Service metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service =~ \"$service_name\", source_cluster=\"$cluster\", platform=~\"$platform\", code=~\"2..\",url!=\"/health\"}[$__rate_interval])*60)",
       "legendFormat": "2XX"
      },
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\",code=~\"4..\"}[$__rate_interval])*60)",
       "legendFormat": "4XX"
      },
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\",code=~\"5..\"}[$__rate_interval])*60)",
       "legendFormat": "5XX"
      }
     ]
    },
    {
     "title": "Overall Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(config_store_http_server_requests_seconds_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(config_store_http_server_requests_seconds_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(config_store_http_server_requests_seconds_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(config_store_http_server_requests_seconds_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(config_store_http_server_requests_seconds_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\"}[$__rate_interval])*60) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "API 2XX",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\", code =~\"2..\"}[$__rate_interval])*60) by (url)",
       "legendFormat": "2xx"
      }
     ]
    },
    {
     "title": "API 5XX",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\",code=~\"5..\"}[$__rate_interval])*60) by (url)",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "API 4XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\",code=~\"4..\"}[$__rate_interval])*60) by (url)",
       "legendFormat": "4XX"
      }
     ]
    },
    {
     "title": "Config Store API Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(config_store_http_server_requests_seconds_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\"}[$__rate_interval])*60) by (le,url))",
       "legendFormat": "{{url}} p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(config_store_http_server_requests_seconds_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\"}[$__rate_interval])*60) by (le,url))",
       "legendFormat": "{{url}} p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(config_store_http_server_requests_seconds_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\"}[$__rate_interval])*60) by (le,url))",
       "legendFormat": "{{url}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(config_store_http_server_requests_seconds_bucket{service =~ \"$service_name\",source_cluster=\"$cluster\", platform=~\"$platform\"}[$__rate_interval])*60) by (le,url))",
       "legendFormat": "{{url}} p50"
      }
     ]
    }
   ]
  },
  {
   "title": "RPM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total RPM",
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service=~\"$service_name\", url!=\"/health\", source_cluster=~\"$cluster\"}[$__rate_interval])*60)"
      }
     ]
    },
    {
     "title": "2xx RPM",
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service=~\"$service_name\",source_cluster=~\"$cluster\", code=~\"2..\", url!=\"/health\"}[$__rate_interval])*60)"
      }
     ]
    },
    {
     "title": "5xx RPM",
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service=~\"$service_name\",source_cluster=~\"$cluster\",code=~\"5..\"}[$__rate_interval])*60)"
      }
     ]
    },
    {
     "title": "4xx RPM",
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(config_store_http_server_requests_seconds_count{service=~\"$service_name\", source_cluster=~\"$cluster\",code=~\"4..\"}[$__rate_interval])*60)"
      }
     ]
    }
   ]
  }
 ]
}