{
 "title": "DP Hercules Jobs",
 "description": "All the alerts related to Data Platform's Hercules Jobs",
 "tags": [ "DP" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(ExecutorAllocationManager_executors_value{application=\"hercules-databricks\"},app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hercules Cluster Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor Count",
     "type": "graph",
     "description": "This panel will show count of Succeeded and Failed Jobs.",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ExecutorAllocationManager_executors_value{app_name=~\"$cluster\",application=\"hercules-databricks\", type_instance=\"numberAllExecutors\"})",
       "legendFormat": "Executors"
      }
     ]
    },
    {
     "title": "EMR Container Status",
     "type": "graph",
     "description": "This panel will show count of Succeeded and Failed Jobs.",
     "gridPos": { "h": 10, "w": 11, "x": 13, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_emr_container_allocated_sum[5m] and on(name) aws_emr_info{tag_Name=~'dp-hercules-v2-sea-x.*'}",
       "legendFormat": "[{{dimension_JobFlowId}}] Running Containers"
      },
      {
       "expr": "aws_emr_container_pending_sum[5m] and on(name) aws_emr_info{tag_Name=~'dp-hercules-v2-sea-x.*'}",
       "legendFormat": "[{{dimension_JobFlowId}}] Pending Containers"
      }
     ]
    }
   ]
  },
  {
   "title": "Hercules App Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": " IN P0 Failed Events",
     "type": "graph",
     "description": "This panel will show P0 events failed during the job processing.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dp.telemetry.hercules.event_app_status{country=\"in\", event=~\"watched_video|failed_playback_api|change_language|logged_in|watch_attempt|app_opened|started_video|failed_retry_video|failed_video|purchased_subscription|viewed_paywall|clicked_paywall|viewed_payment|viewed_content_detail|viewed_home_page|viewed_landing_page|viewed_listing_page|viewed_onboarding_page|viewed_page_payment|viewed_parental_lock_page|viewed_payment_link|viewed_profile_selection_page|viewed_search_page|viewed_watch_page\"}!=4",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": " IN Non-P0 Failed Events",
     "type": "graph",
     "description": "This panel will show Non-P0 events failed during the job processing.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dp.telemetry.hercules.event_app_status{country=\"in\", event!~\"watched_video|failed_playback_api|change_language|logged_in|watch_attempt|app_opened|started_video|failed_retry_video|failed_video|purchased_subscription|viewed_paywall|clicked_paywall|viewed_payment|viewed_content_detail|viewed_home_page|viewed_landing_page|viewed_listing_page|viewed_onboarding_page|viewed_page_payment|viewed_parental_lock_page|viewed_payment_link|viewed_profile_selection_page|viewed_search_page|viewed_watch_page\"}!=4",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Databricks App Status",
     "type": "graph",
     "description": "This panel will show count of Succeeded and Failed Jobs.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(DAGScheduler_job_value{app_name=~\"$cluster\", application=\"hercules-databricks\", type_instance=\"activeJobs\"})",
       "legendFormat": "RunningApplications"
      },
      {
       "expr": "sum(DAGScheduler_job_value{app_name=\"$cluster\", application=\"hercules-databricks\", type_instance=\"allJobs\"})-sum(DAGScheduler_job_value{app_name=\"$cluster\", application=\"hercules-databricks\", type_instance=\"activeJobs\"})",
       "legendFormat": "CompletedApplications"
      },
      {
       "expr": "sum(DAGScheduler_stage_value{app_name=\"$cluster\", application=\"hercules-databricks\", type_instance=\"failedStages\"})",
       "legendFormat": "FailedApplications"
      },
      {
       "expr": "sum(DAGScheduler_stage_value{app_name=\"$cluster\", application=\"hercules-databricks\", type_instance=\"waitingStages\"})",
       "legendFormat": "WaitingApplications"
      }
     ]
    },
    {
     "title": "IN Jobs Status",
     "type": "graph",
     "description": "This panel will show count of Succeeded and Failed Jobs.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(dp.telemetry.hercules.event_app_status{application=\"hercules-databricks\", country=\"in\"}==4)",
       "legendFormat": "Succeeded Jobs"
      },
      {
       "expr": "count(dp.telemetry.hercules.event_app_status{country=\"in\", application=\"hercules-databricks\"}!=4)",
       "legendFormat": "Failed Jobs"
      }
     ]
    },
    {
     "title": "IN Events Info",
     "type": "graph",
     "description": "This panel will show count of Succeeded and Failed Jobs.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dp.telemetry.hercules.event_app_status{country=\"in\", application=\"hercules-databricks\"}",
       "legendFormat": "{{event}}"
      },
      {
       "expr": "count(dp.telemetry.hercules.event_app_status{country=\"in\", application=\"hercules-databricks\"}!=4)",
       "legendFormat": "Failed Jobs"
      }
     ]
    }
   ]
  }
 ]
}