{
 "title": "adtech-reporting",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "ads-reporting" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "adtech-in-dev-aps1,adtech-in-prod-apse1"
   }
  ]
 },
 "panels": [
  {
   "title": "UPDATE_COUNTER_FROM_INFLUX_LATENCY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(SHIFU_REPORTING_UPDATE_COUNTER_FROM_INFLUX_LATENCY_APSE1_bucket[5m])) by (le))",
     "legendFormat": "apse1"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(SHIFU_REPORTING_UPDATE_COUNTER_FROM_INFLUX_LATENCY_EUW1_bucket[5m])) by (le))",
     "legendFormat": "euw1"
    }
   ]
  },
  {
   "title": "RECONCILE_REPORTING_DATA_LATENCY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(SHIFU_REPORTING_RECONCILE_REPORTING_DATA_LATENCY_APSE1_bucket[5m])) by (le))",
     "legendFormat": "apse1"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(SHIFU_REPORTING_RECONCILE_REPORTING_DATA_LATENCY_EUW1_bucket[5m])) by (le))",
     "legendFormat": "euw1"
    }
   ]
  },
  {
   "title": "UPDATE_COUNTER_FROM_INFLUX_SUCCESS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(SHIFU_REPORTING_UPDATE_COUNTER_FROM_INFLUX_SUCCESS_APSE1_total[1m]))",
     "legendFormat": "apse1"
    },
    {
     "expr": "sum(increase(SHIFU_REPORTING_UPDATE_COUNTER_FROM_INFLUX_SUCCESS_EUW1_total[1m]))",
     "legendFormat": "euw1"
    }
   ]
  },
  {
   "title": "RECONCILE_REPORTING_DATA_SUCCESS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(SHIFU_REPORTING_RECONCILE_REPORTING_DATA_SUCCESS_APSE1_total[1m]))",
     "legendFormat": "apse1"
    },
    {
     "expr": "sum(increase(SHIFU_REPORTING_RECONCILE_REPORTING_DATA_SUCCESS_EUW1_total[1m]))",
     "legendFormat": "euw1"
    }
   ]
  },
  {
   "title": "UPDATE_COUNTER_FROM_INFLUX_FAILURE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(SHIFU_REPORTING_UPDATE_COUNTER_FROM_INFLUX_FAILURE_APSE1_total[1m]))",
     "legendFormat": "apse1"
    },
    {
     "expr": "sum(increase(SHIFU_REPORTING_UPDATE_COUNTER_FROM_INFLUX_FAILURE_EUW1[1m]))",
     "legendFormat": "euw1"
    }
   ]
  },
  {
   "title": "RECONCILE_REPORTING_DATA_FAILURE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(SHIFU_REPORTING_RECONCILE_REPORTING_DATA_FAILURE_APSE1[1m]))",
     "legendFormat": "apse1"
    },
    {
     "expr": "sum(increase(SHIFU_REPORTING_RECONCILE_REPORTING_DATA_FAILURE_EUW1[1m]))",
     "legendFormat": "euw1"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } }
 ]
}