{
 "title": "Client release audit",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "release ticket BLOCKED transition alert failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rta_ticket_blocked_transition_id_not_found_total))"
    }
   ]
  },
  {
   "title": "App Metrics Alert Commented on JIRA Successfully",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_metric_jira_alert_success_total))"
    }
   ]
  },
  {
   "title": "hs-productivity-metrics CPU & memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "hs-productivity-metrics (CPU usage main pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-.*\", pod!~\"hs-productivity-metrics-crc-worker.*\", pod!~\"hs-productivity-metrics-rta.*\", pod!~\"hs-productivity-metrics-cad-worker.*\", pod!~\"hs-productivity-metrics-sqs.*\"})) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "hs-productivity-metrics (Memory usage main pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-.*\", pod!~\"hs-productivity-metrics-crc-worker.*\", pod!~\"hs-productivity-metrics-rta.*\", pod!~\"hs-productivity-metrics-cad-worker.*\", pod!~\"hs-productivity-metrics-sqs.*\"}) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "hs-productivity-metrics (CPU usage CRC worker pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-crc-worker.*\"})) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "hs-productivity-metrics (Memory usage CRC worker pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-crc-worker.*\"}) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "hs-productivity-metrics (CPU usage RTA worker pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-rta.*\"})) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "hs-productivity-metrics (Memory usage RTA worker pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-rta-.*\"}) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "hs-productivity-metrics (CPU usage CAD worker pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-cad-worker.*\"})) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "hs-productivity-metrics (Memory usage CAD worker pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-cad-worker.*\"}) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "hs-productivity-metrics (CPU usage SQS worker pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-sqs-.*\"})) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "hs-productivity-metrics (Memory usage SQS worker pod)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"hs-productivity-metrics-sqs.*\"}) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "client release audit CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (final)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"client-release-audit.*\"})) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage (final)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{source_cluster=\"hs-eks-nonprod-api-aps1\", namespace=\"productivity-engg\", pod=~\"client-release-audit.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "K8s Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Restart Pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)(changes(kube_pod_status_ready{condition=\"true\",namespace=\"quality\",source_cluster=\"nonprod-aps1.pp.hotstar-labs.com\",pod=~\"releng-client-.*\"}[1m]))"
      }
     ]
    },
    {
     "title": "Restart Pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)(changes(kube_pod_status_ready{condition=\"true\",namespace=\"quality\",source_cluster=\"nonprod-aps1.pp.hotstar-labs.com\",pod=~\"hs-productivity-.*\"}[1m]))"
      }
     ]
    },
    {
     "title": "Running Pods",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace=\"quality\",source_cluster=\"nonprod-aps1.pp.hotstar-labs.com\",pod=~\"releng-client-.*\"}[1m]) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Frequent Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health checks",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(client_release_audit_health_check_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "health_check_count"
      }
     ]
    },
    {
     "title": "fetch active releases request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(fetch_active_releases_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "fetch active releases request"
      }
     ]
    },
    {
     "title": "Slack message alert",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(duplicate_slack_message_post_request_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "request for duplicate slack message"
      },
      {
       "expr": "sum(increase(request_to_post_message_on_slack_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "request to post slack message"
      },
      {
       "expr": "sum(increase(error_while_posting_slack_message_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "error while posting slack message"
      }
     ]
    },
    {
     "title": "audit record db trasactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(audit_record_create_or_update_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "audit record create or update requests"
      },
      {
       "expr": "sum(increase(audit_record_exist_in_db_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "audit record exist in db"
      },
      {
       "expr": "sum(increase(audit_record_doesnot_exist_in_db_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "audit record not found in db"
      },
      {
       "expr": "sum(increase(audit_record_update_failure_metric_total{serviceName=\"releng-client-release-audit\"} ))",
       "legendFormat": "failure for updating audit record"
      }
     ]
    },
    {
     "title": "retrieve last GitHub commit id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(retrieve_last_github_commit_request_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "retrieve last GitHub commit id"
      },
      {
       "expr": "sum(increase(retrieve_last_commit_request_provied_insuffienct_parameter_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "Insufficient parameters for retrieve last GitHub commit id"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit Record Updates and queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "fetch unique release column values",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(fetch_unique_release_property_counter_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "fetch unique release column values"
      }
     ]
    },
    {
     "title": "retrieve audit records request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(retrieve_all_audit_record_request_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "retrieve all audit records request count"
      },
      {
       "expr": "sum(increase(retrieve_filteed_audit_records_request_metric{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "retrieve filtered audit records request count"
      }
     ]
    },
    {
     "title": "update by pipeline exec. id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(update_by_pipeline_exection_id_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "update by pipeline exec. id requests"
      }
     ]
    },
    {
     "title": "update Jira status by Jira webhook",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(update_jira_status_by_jira_ticket_id_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "update jira status by jira webhook"
      }
     ]
    }
   ]
  },
  {
   "title": "Anomalies ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discrepancy in jira and audit record status",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(different_status_found_forjira_ticket_and_audit_record_metric{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "instances found having different status in jira ticket and release audit"
      }
     ]
    },
    {
     "title": "retrieve latest build requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 4, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(retrieve_latest_build_request_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "retrieve latest build"
      }
     ]
    }
   ]
  },
  {
   "title": "App Store & iOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "create app store review submission request",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(create_app_store_review_submission_request_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "create app store review submission request"
      }
     ]
    },
    {
     "title": "app store api connection API failure",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(app_store_api_connection_failure_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "app store api connection API failure"
      }
     ]
    },
    {
     "title": "verify ios build exists request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 10, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(verify_ios_build_exist_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "verify ios build exists request"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit Configs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "audit configs",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(update_audit_configs_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "update audit configs request"
      },
      {
       "expr": "sum(increase(failure_while_updating_audit_configs_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "failure for updating audit configs"
      },
      {
       "expr": "sum(increase(fetch_audit_configs_metric_total{serviceName=\"releng-client-release-audit\"}))",
       "legendFormat": "fetch audit configs request"
      }
     ]
    }
   ]
  }
 ]
}