{
 "title": "SLO Dashboard",
 "description": "Tracks service's SLO and error budget consumption.",
 "time": { "from": "now-28d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service_requests_error_count",
    "query": "round(sum (rate(envoy_cluster_upstream_rq_5xx{envoy_cluster_name=~'page_compositor_gql_fleet_1_default_hs_core_8080', source_cluster=~'hs-eks-prod-api-apse1'}[1m])*60)) or 0"
   },
   {
    "name": "service_requests_total_count",
    "query": "requests_total_count{service=\"my-service\"}"
   },
   {
    "name": "alerts_filter_criteria",
    "query": "envoy_cluster_name=~'page_compositor_gql_fleet_1_default_hs_core_8080', source_cluster=~'hs-eks-prod-api-apse1'"
   },
   { "name": "service_slo_target", "query": "99.5" },
   { "name": "error_budget", "query": "0.005" }
  ]
 },
 "panels": [
  {
   "title": "SLO Dashboard",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(ALERTS{alertstate=\"firing\",$alerts_filter_criteria}[5m])"
    }
   ]
  },
  {
   "title": "Error Budget Left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * ($error_budget - sum(rate($service_requests_error_count[28d])) by (job) / sum(rate($service_requests_total_count[28d])) by (job))"
    }
   ]
  },
  {
   "title": "Current SLO",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(rate($service_requests_error_count[28d])) by (job) / sum(rate($service_requests_total_count[28d])) by (job)"
    }
   ]
  },
  {
   "title": "28 Day Window SLO",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "$service_slo_target", "legendFormat": "target" },
    {
     "expr": "(1 - sum(rate($service_requests_error_count[28d])) by (job) / sum(rate($service_requests_total_count[28d])) by (job)) * 100",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service_requests_error_count[1m])) by (job) / sum(rate($service_requests_total_count[1m])) by (job)",
     "legendFormat": "error ratio"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service_requests_total_count[1m])) by (job)",
     "legendFormat": "total requests rate"
    },
    {
     "expr": "sum(rate($service_requests_error_count[1m])) by (job)",
     "legendFormat": "error responses rate"
    }
   ]
  }
 ]
}