{
 "title": "Social Adapter Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_created, namespace)"
   },
   { "name": "service", "label": "service", "query": "social-activity-adapter-go" }
  ]
 },
 "panels": [
  {
   "title": "Msg processing latency: kafka read to produce",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(social_activity_adapter_msg_processing_time_bucket{namespace=\"$namespace\", service=\"$service\"}[30m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(social_activity_adapter_msg_processing_time_bucket{namespace=\"$namespace\", service=\"$service\"}[30m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(social_activity_adapter_msg_processing_time_bucket{namespace=\"$namespace\", service=\"$service\"}[30m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Msg Processed Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(social_activity_adapter_kafka_msg_processed_count{namespace=\"$namespace\", service=\"$service\"}[1m])) by (topic)",
     "legendFormat": "receive topic : {{ topic }}"
    },
    {
     "expr": "sum(increase(social_activity_adapter_kafka_produce_success_count{namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "produce"
    }
   ]
  },
  {
   "title": "Kafka Consumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(social_activity_adapter_kafka_read_count{namespace=\"$namespace\", service=\"$service\"}[1m])) by (topic)",
     "legendFormat": "receive topic : {{ topic }}"
    },
    {
     "expr": "sum(increase(social_activity_adapter_kafka_handler_error{namespace=\"$namespace\", service=\"$service\"}[1m])) by (topic)",
     "legendFormat": "handler error: {{ topic }}"
    }
   ]
  },
  {
   "title": "Total Msg Read Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(social_activity_adapter_kafka_read_count{namespace=\"$namespace\", service=\"$service\"}[1m])) by (topic)",
     "legendFormat": "receive topic : {{ topic }}"
    }
   ]
  }
 ]
}