{
 "title": "HES ASG Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Request Per ASG",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\".*airflow\"} * on(pod) group_left(phase) kube_pod_status_phase{phase=\"Running\"} * on(node) group_left(label_kops_k8s_io_instancegroup) kube_node_labels{}) by (label_kops_k8s_io_instancegroup) / sum(kube_node_status_capacity_cpu_cores * on(node) group_left(label_kops_k8s_io_instancegroup) kube_node_labels{}) by (label_kops_k8s_io_instancegroup)"
    }
   ]
  },
  {
   "title": "Memory Request Per ASG",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\".*airflow\"} * on(pod) group_left(phase) kube_pod_status_phase{phase=\"Running\"} * on(node) group_left(label_kops_k8s_io_instancegroup) kube_node_labels{}) by (label_kops_k8s_io_instancegroup) / sum(kube_node_status_capacity_memory_bytes * on(node) group_left(label_kops_k8s_io_instancegroup) kube_node_labels{}) by (label_kops_k8s_io_instancegroup)"
    }
   ]
  },
  {
   "title": "Node Count Per ASG",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_labels{}) by (label_kops_k8s_io_instancegroup)"
    }
   ]
  }
 ]
}