{
 "title": "Kubernetes Master Status (Prometheus)",
 "description": "Kubernetes Master Status (Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_namespace_created, source_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Single Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Servers UP",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(up{job=\"apiserver\", source_cluster=~\"$cluster\"} == 1) / sum(up{job=\"apiserver\", source_cluster=~\"$cluster\"})) * 100"
      }
     ]
    },
    {
     "title": "Kube Controller Manager",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(up{source_cluster=~\"$cluster\", job=\"kube-controller-manager\"} == 1) / sum(up{source_cluster=~\"$cluster\", job=\"kube-controller-manager\"})) * 100"
      }
     ]
    },
    {
     "title": "Schedulers UP",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(up{source_cluster=~\"$cluster\", job=\"kube-scheduler\"} == 1) / sum(up{source_cluster=~\"$cluster\", job=\"kube-scheduler\"})) * 100"
      }
     ]
    },
    {
     "title": "API Server Request Error Rate",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(sum by(instance) (rate(apiserver_request_count{code=~\"5..\", source_cluster=~\"$cluster\"}[5m])) / sum by(instance) (rate(apiserver_request_count{source_cluster=~\"$cluster\"}[5m]))) * 100"
      }
     ]
    },
    {
     "title": "Etcd has a leader?",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(etcd_server_has_leader{source_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Cluster Autoscaler UP",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(up{source_cluster=~\"$cluster\", job=\"cluster-autoscaler-metrics\"} == 1) / sum(up{source_cluster=~\"$cluster\", job=\"cluster-autoscaler-metrics\"})) * 100"
      }
     ]
    },
    {
     "title": "Pending Pods",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_unschedulable_pods_count{source_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Total Nodes Count",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_nodes_count{source_cluster=~\"$cluster\"})\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube Api Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server Request Rates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(instance) (rate(apiserver_request_total{code=~\"5*.\", source_cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "Error Rate ({{ instance}})"
      },
      {
       "expr": "sum by(instance) (rate(apiserver_request_total{source_cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "Request Rate ({{ instance}})"
      }
     ]
    },
    {
     "title": "API Server Request Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{quantile=\"0.99\", source_cluster=~\"$cluster\"} >0) by (verb)"
      }
     ]
    },
    {
     "title": "Current Inflight Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_current_inflight_requests{source_cluster=~\"$cluster\"}) by (requestKind)",
       "legendFormat": "{{requestKind}}"
      }
     ]
    },
    {
     "title": "API Requests by client (kube-*)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_count{client=~\"kubelet.*|kube-scheduler.*|kube-controller.*|kube-apiserver.*|kube-proxy.*\", source_cluster=~\"$cluster\"}[5m])) by (client)>0",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "API Requests by client (non-kube-*)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_count{client!~\"kubelet.*|kube-scheduler.*|kube-controller.*|kube-apiserver.*|kube-proxy.*\", source_cluster=~\"$cluster\"}[5m])) by (client)>0",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "Unavailable Api Services",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "max(rate(aggregator_unavailable_apiservice_count{source_cluster=~\"$cluster\"}[5m])) by ( name, reason)"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler Attempts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(scheduler_schedule_attempts_total{source_cluster=~\"$cluster\"}[1m])) by (result)",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "End to End Scheduling Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(increase(scheduler_e2e_scheduling_latency_microseconds_sum{source_cluster=~\"$cluster\"}[5m]) /1e6)",
       "legendFormat": "latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube Controller Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Manager Queue Depth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(volumes_depth{source_cluster=~\"$cluster\"})\r",
       "legendFormat": "volumes"
      },
      {
       "expr": "sum(deployment_depth{source_cluster=~\"$cluster\"})\r",
       "legendFormat": "deployment"
      },
      {
       "expr": "sum(replicaset_depth{source_cluster=~\"$cluster\"})\r",
       "legendFormat": "replicaset_depth"
      },
      {
       "expr": "sum(service_depth{source_cluster=~\"$cluster\"})\r",
       "legendFormat": "service_depth"
      },
      {
       "expr": "sum(serviceaccount_depth{source_cluster=~\"$cluster\"})\r",
       "legendFormat": "serviceaccount_depth"
      },
      {
       "expr": "sum(endpoint_depth{source_cluster=~\"$cluster\"})\r",
       "legendFormat": "endpoint_depth"
      },
      {
       "expr": "sum(daemonset_depth{source_cluster=~\"$cluster\"})\r",
       "legendFormat": "daemonset_depth"
      },
      {
       "expr": "sum(statefulset_depth{source_cluster=~\"$cluster\"})\r",
       "legendFormat": "statefulset_depth"
      },
      {
       "expr": "sum(replicationmanager_depth{source_cluster=~\"$cluster\"})\r",
       "legendFormat": "replicationmanager_depth"
      },
      {
       "expr": "sum(horizontalpodautoscaler_depth{source_cluster=~\"$cluster\"})",
       "legendFormat": "horizontalpodautoscaler_depth"
      }
     ]
    },
    {
     "title": "Controller Manager Queue Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(volumes_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "volumes"
      },
      {
       "expr": "rate(deployment_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])",
       "legendFormat": "deployment"
      },
      {
       "expr": "rate(replicaset_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "replicaset"
      },
      {
       "expr": "rate(service_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])",
       "legendFormat": "service"
      },
      {
       "expr": "rate(serviceaccount_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "serviceaccount"
      },
      {
       "expr": "rate(endpoint_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "endpoint"
      },
      {
       "expr": "rate(daemonset_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "daemonset"
      },
      {
       "expr": "rate(statefulset_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "statefulset"
      },
      {
       "expr": "rate(replicationmanager_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "replicationmanager"
      },
      {
       "expr": "rate(horizontalpodautoscaler_queue_latency{quantile=\"0.99\", source_cluster=~\"$cluster\"}[5m])",
       "legendFormat": "horizontalpodautoscaler_99_percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{source_cluster=~\"$cluster\"}",
       "legendFormat": "{{instance}} DB Size"
      }
     ]
    },
    {
     "title": "Pending Events",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "etcd_debugging_mvcc_pending_events_total{source_cluster=~\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Sync Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{source_cluster=~\"$cluster\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}} WAL fsync"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{source_cluster=~\"$cluster\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}} DB fsync"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Autoscaler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Function Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(cluster_autoscaler_function_duration_seconds_sum{source_cluster=~\"$cluster\"}[5m]) ",
       "legendFormat": "{{ function }}"
      }
     ]
    },
    {
     "title": "Unschedulable Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cluster_autoscaler_unschedulable_pods_count{source_cluster=~\"$cluster\"}",
       "legendFormat": "Pods"
      }
     ]
    }
   ]
  },
  {
   "title": "CoreDns",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Dns Request Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_proxy_request_duration_seconds_sum{source_cluster=~\"$cluster\"}[1m])) by (to)",
       "legendFormat": "{{ to }}"
      }
     ]
    },
    {
     "title": "CoreDns - Requests (total)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_request_count_total{instance=~\".*\", source_cluster=~\"$cluster\"}[5m])) by (proto)",
       "legendFormat": "{{proto}}"
      },
      {
       "expr": "sum(rate(coredns_dns_request_count_total{instance=~\".*\", source_cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Cache (hitrate)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(coredns_cache_hits_total{instance=~\".*\", source_cluster=~\"$cluster\"}[5m])) by (type)",
       "legendFormat": "hits:{{type}}"
      },
      {
       "expr": "sum(rate(coredns_cache_misses_total{instance=~\".*\", source_cluster=~\"$cluster\"}[5m])) by (type)",
       "legendFormat": "misses"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "instance:node_memory_utilisation:ratio{source_cluster=~\"$cluster\"} * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{fstype=\"ext4\", mountpoint=~\"/.*\", source_cluster=~\"$cluster\"} - node_filesystem_free_bytes{fstype=\"ext4\",mountpoint=~\"/.*\", source_cluster=~\"$cluster\"} ) / node_filesystem_size_bytes{fstype=\"ext4\",mountpoint=~\"/.*\", source_cluster=~\"$cluster\"} * 100",
       "legendFormat": "{{ instance }}({{ mountpoint }})"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "instance:node_cpu_utilisation:rate1m{source_cluster=~\"$cluster\"} * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus CPU Requests/Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"monitoring.*\", pod=~\"prometheus-kube-prometheus.*$\", container!~\"POD\", id!=\"/\", source_cluster=~\"$cluster\"}) by (container)",
       "legendFormat": "real: {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"monitoring.*\", pod=~\"prometheus-kube-prometheus.*$\", source_cluster=~\"$cluster\"}) by (container)",
       "legendFormat": "req: {{ container }}"
      }
     ]
    },
    {
     "title": "Prometheus Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"^prometheus-kube-prometheus.*$\", namespace=~\"monitoring.*\", container!~\"POD\",container!=\"\", id!=\"/\", source_cluster=~\"$cluster\"}) by (container,pod)\n",
       "legendFormat": "{{ container }}/{{pod}}"
      }
     ]
    },
    {
     "title": "Thanos CPU Requests/Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"monitoring.*\", pod=~\"^thanos.*$\", container!~\"POD\", source_cluster=~\"$cluster\"}) by (container)",
       "legendFormat": "real: {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"monitoring.*\", pod=~\"^thanos.*$\", source_cluster=~\"$cluster\"}) by (container)",
       "legendFormat": "req: {{ container }}"
      }
     ]
    },
    {
     "title": "Thanos Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"^thanos.*$\", namespace=~\"monitoring.*\", container!~\"POD\", container!=\"\", source_cluster=~\"$cluster\"}) by (container)",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Volume Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*\", namespace=~\"monitoring.*\", source_cluster=~\"$cluster\"} ",
       "legendFormat": "{{ persistentvolumeclaim }} | {{ node }}"
      }
     ]
    }
   ]
  }
 ]
}