{
 "title": "Kubernetes Control Plane EKS",
 "description": "Kubernetes Control Plane EKS",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "ds", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_namespace_created, source_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Single Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Servers UP",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(up{job=\"apiserver\", source_cluster=~\"$cluster\"} == 1) / sum(up{job=\"apiserver\", source_cluster=~\"$cluster\"})) * 100"
      }
     ]
    },
    {
     "title": "Kube Controller Manager",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(count(apiserver_flowcontrol_request_execution_seconds_count{flow_schema=\"kube-controller-manager\", priority_level=\"workload-high\"}) / count(apiserver_flowcontrol_request_execution_seconds_count{flow_schema=\"kube-controller-manager\", priority_level=\"workload-high\"}) > 0) * 100"
      }
     ]
    },
    {
     "title": "Schedulers UP",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(count(apiserver_flowcontrol_request_execution_seconds_count{flow_schema=\"kube-scheduler\", priority_level=\"workload-high\"}) / count(apiserver_flowcontrol_request_execution_seconds_count{flow_schema=\"kube-scheduler\", priority_level=\"workload-high\"}) > 0) * 100"
      }
     ]
    },
    {
     "title": "API Server Request Error Rate",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(sum by(instance) (rate(apiserver_request_total{code=~\"5..\", source_cluster=~\"$cluster\"}[5m])) / sum by(instance) (rate(apiserver_request_total{source_cluster=~\"$cluster\"}[5m]))) * 100"
      }
     ]
    },
    {
     "title": "Etcd has a leader?",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "etcd_server_has_leader{source_cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Cluster Autoscaler UP",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(up{source_cluster=~\"$cluster\", job=\"cluster-autoscaler-metrics\"} == 1) / sum(up{source_cluster=~\"$cluster\", job=\"cluster-autoscaler-metrics\"})) * 100"
      }
     ]
    },
    {
     "title": "Pending Pods",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_unschedulable_pods_count{source_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Total Nodes Count",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_nodes_count{source_cluster=~\"$cluster\"})\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube Api Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server Request Rates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(instance) (rate(apiserver_request_total{code=~\"5*.\", source_cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "Error Rate ({{ instance}})"
      },
      {
       "expr": "sum by(instance) (rate(apiserver_request_total{source_cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "Request Rate ({{ instance}})"
      }
     ]
    },
    {
     "title": "API Server Request Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{quantile=\"0.99\", source_cluster=~\"$cluster\"} >0) by (verb)"
      }
     ]
    },
    {
     "title": "Current Inflight Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_current_inflight_requests{source_cluster=~\"$cluster\"}) by (requestKind)",
       "legendFormat": "{{requestKind}}"
      }
     ]
    },
    {
     "title": "API Requests by (kube-*)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_flowcontrol_request_execution_seconds_count{flow_schema=~\"kube.*\", source_cluster=~\"$cluster\"}[5m])) by (flow_schema)>0",
       "legendFormat": "{{ flow_schema}}"
      }
     ]
    },
    {
     "title": "API Requests by client (non-kube-*)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_request_total{source_cluster=~\"$cluster\"}[5m]) by (resource, verb)>0"
      }
     ]
    },
    {
     "title": " Number of queued requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_current_inqueue_requests{source_cluster=\"$cluster\"}) by (request_kind)",
       "legendFormat": "{{ request_kind }} "
      }
     ]
    },
    {
     "title": "Unavailable Api Services",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "aggregator_unavailable_apiservice_total{source_cluster=~\"$cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler total request dispatched",
     "type": "graph",
     "description": "Number of requests executed fir kube-scheduler",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(apiserver_flowcontrol_request_queue_length_after_enqueue_sum{ flow_schema=\"kube-scheduler\", source_cluster=~\"$cluster\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Waiting period for the kube-scheduler request",
     "type": "graph",
     "description": "Length of time a request spent waiting in its queue",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(apiserver_flowcontrol_request_wait_duration_seconds_sum{ flow_schema=\"kube-scheduler\", source_cluster=~\"$cluster\"})",
       "legendFormat": "{{ flow_schema }} / {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Queue Depth",
     "type": "graph",
     "description": "Current depth of workqueue",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "workqueue_depth{source_cluster=~\"$cluster\"}\r",
       "legendFormat": "{{ name }} {{ instance }}"
      }
     ]
    },
    {
     "title": "Worker Queue Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(workqueue_queue_duration_seconds_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "rate(deployment_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])",
       "legendFormat": "deployment"
      },
      {
       "expr": "rate(replicaset_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "replicaset"
      },
      {
       "expr": "rate(service_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])",
       "legendFormat": "service"
      },
      {
       "expr": "rate(serviceaccount_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "serviceaccount"
      },
      {
       "expr": "rate(endpoint_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "endpoint"
      },
      {
       "expr": "rate(daemonset_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "daemonset"
      },
      {
       "expr": "rate(statefulset_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "statefulset"
      },
      {
       "expr": "rate(replicationmanager_queue_latency_sum{source_cluster=~\"$cluster\"}[5m])\r",
       "legendFormat": "replicationmanager"
      },
      {
       "expr": "rate(horizontalpodautoscaler_queue_latency{quantile=\"0.99\", source_cluster=~\"$cluster\"}[5m])",
       "legendFormat": "horizontalpodautoscaler_99_percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "apiserver_storage_size_bytes{source_cluster=~\"$cluster\"}",
       "legendFormat": "{{instance}} DB Size"
      }
     ]
    },
    {
     "title": "Number of stored objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_storage_objects{source_cluster=\"$cluster\"}) by (resource)",
       "legendFormat": "{{ resource }}"
      }
     ]
    },
    {
     "title": "Etcd bookmark counts",
     "type": "graph",
     "description": "Number of etcd bookmarks (progress notify events) ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "etcd_bookmark_counts{source_cluster=\"$cluster\", resource!~\".*unstructured.*\"}",
       "legendFormat": "{{ resource }}"
      }
     ]
    }
   ]
  }
 ]
}