{
 "title": "[Shifu] [ME] Display AdServer Overview",
 "tags": [ "shifu-me" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pods Total Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{pod=~\"adtech-shifu-display-ad-decision-me-prod.*\"})"
    }
   ]
  },
  {
   "title": "Pod Avg Cpu",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"adtech-shifu-display-ad-decision-me-prod.*\"}[1m])/4)"
    }
   ]
  },
  {
   "title": "Cloud Watch: Request Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\", source_cluster=\"hs-eks-prod-api-euw1\"}[1m])*60) by (envoy_cluster_name)",
     "legendFormat": "total request"
    }
   ]
  },
  {
   "title": "Cloud Watch: Mean Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\", source_cluster=\"hs-eks-prod-api-euw1\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\", source_cluster=\"hs-eks-prod-api-euw1\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\", source_cluster=\"hs-eks-prod-api-euw1\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Ambassador 4XX & 5XX RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_5xx_total{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\",source_cluster=\"hs-eks-prod-api-euw1\"}[1m]))",
     "legendFormat": "Backend 5XX RPS"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_4xx_total{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\",source_cluster=\"hs-eks-prod-api-euw1\"}[1m]))",
     "legendFormat": "Backend 4XX RPS"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_5xx_total{envoy_http_conn_manager_prefix=\"ingress_http\",source_cluster=\"hs-eks-prod-api-apse1\"}[1m]))",
     "legendFormat": "Ambassador 5XX RPS"
    }
   ]
  },
  {
   "title": "Ambassador Backend Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\", source_cluster=\"hs-eks-prod-api-euw1\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\", source_cluster=\"hs-eks-prod-api-euw1\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\", source_cluster=\"hs-eks-prod-api-euw1\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Ambassador Backend Request Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "req/min" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sum(rate(envoy_cluster_upstream_rq_timeout_total{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\", source_cluster=\"hs-eks-prod-api-euw1\"}[5m])*60) by (envoy_cluster_name))[5m:1m]",
     "legendFormat": "Backend Request Timeout Count"
    },
    {
     "expr": "avg_over_time(sum(rate(envoy_cluster_upstream_rq_pending_failure_eject_total{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\", source_cluster=\"hs-eks-prod-api-euw1\"}[5m])*60) by (envoy_cluster_name))[5m:1m]",
     "legendFormat": "Backend Request Pending Failure Count"
    }
   ]
  },
  {
   "title": "Ambassador Backend Connection Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "req/min" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq_total{envoy_cluster_name=~\"cluster_adtech_shifu_display_ad_decision.*\"}[5m])*60) by (envoy_cluster_name))[5m:1m]",
     "legendFormat": "Connections Destroyed with Active Requests"
    }
   ]
  },
  {
   "title": "Requests count (RPM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"adtech-shifu-display-ad-decision-me-prod\",uri=~\"/shifu/hs-in/v1/group/.*\"}[1m]))",
     "legendFormat": "total request"
    }
   ]
  },
  {
   "title": "Latency P99/P95/Mean",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(rate(http_server_requests_seconds_bucket{job=\"adtech-shifu-display-ad-decision-me-prod\",uri=~\"/shifu/hs-in/v1/group/.*\"}[1m])) by (le, uri))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(http_server_requests_seconds_bucket{job=\"adtech-shifu-display-ad-decision-me-prod\",uri=~\"/shifu/hs-in/v1/group/.*\"}[1m])) by (le, uri))",
     "legendFormat": "P95"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"adtech-shifu-display-ad-decision-me-prod\",uri=~\"/shifu/hs-in/v1/group/.*\"}[1m])) / sum(rate(http_server_requests_seconds_count{job=\"adtech-shifu-display-ad-decision-me-prod\",uri=~\"/shifu/hs-in/v1/group/.*\"}[1m]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Response code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"adtech-shifu-display-ad-decision-me-prod\",uri=~\"/shifu/hs-in/v1/group/.*\"}[1m])) by (status, uri)",
     "legendFormat": "{{uri}}: {{status}}"
    }
   ]
  },
  {
   "title": "Admodel Load Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "shifu_decision_service_load_ad_model_version{job=\"adtech-shifu-display-ad-decision-me-prod\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pacing Load Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "shifu_decision_service_load_pacing_version{job=\"adtech-shifu-display-ad-decision-me-prod\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Country Code & Group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_valid_country_code_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "valid country code"
    },
    {
     "expr": "sum(increase(shifu_decision_service_valid_country_code_but_no_cg_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "valid country code but no cg"
    },
    {
     "expr": "sum(increase(shifu_decision_service_invalid_country_code_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "invalid country code"
    },
    {
     "expr": "sum(increase(shifu_decision_service_log_country_code_failed_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "log country code failed"
    }
   ]
  },
  {
   "title": "Count: selection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "selection",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SELECTION_COUNT",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "placementType", "operator": "!=", "value": "MIDROLL" },
      { "condition": "AND", "key": "placementType", "operator": "!=", "value": "PREROLL" }
     ]
    }
   ]
  },
  {
   "title": "Count: impression",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "impression",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IMPRESSION_COUNT",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "placementType", "operator": "!=", "value": "MIDROLL" },
      { "condition": "AND", "key": "placementType", "operator": "!=", "value": "PREROLL" }
     ]
    }
   ]
  },
  {
   "title": "Count: view",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "view",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VIEW_COUNT",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "placementType", "operator": "!=", "value": "MIDROLL" },
      { "condition": "AND", "key": "placementType", "operator": "!=", "value": "PREROLL" }
     ]
    }
   ]
  },
  {
   "title": "Fcap try times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "legendFormat": "fcap try times" },
    {
     "expr": "sum(increase(shifu_decision_service_fcap_pull_history_exception_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "fcap pull exception"
    },
    {
     "expr": "sum(increase(shifu_decision_service_fcap_pull_history_short_circuited_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "fcap pull circuit break"
    }
   ]
  },
  {
   "title": "Fcap timer metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_get_time_seconds_sum{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m])) / sum(increase(shifu_decision_service_get_time_seconds_count{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "redis get time"
    },
    {
     "expr": "sum(increase(shifu_decision_service_decode_time_seconds_sum{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m])) / sum(increase(shifu_decision_service_decode_time_seconds_count{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "decode time"
    },
    { "legendFormat": "redis get time max" }
   ]
  },
  {
   "title": "Failure: Fcap History",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_get_failure_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "redis get failure"
    },
    {
     "expr": "sum(increase(shifu_decision_service_decode_failure_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "decode failure"
    },
    {
     "expr": "sum(increase(shifu_decision_service_fcap_update_exception_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "update exception"
    },
    {
     "expr": "sum(increase(shifu_decision_service_serialize_error_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "serialize_error"
    },
    {
     "expr": "sum(increase(shifu_decision_service_deserialize_error_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "deserialize_error"
    },
    {
     "expr": "sum(increase(shifu_decision_service_json_parse_error_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "json_parse_error"
    },
    {
     "expr": "sum(increase(shifu_decision_service_unknown_decode_error_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "unknown_decode_error"
    },
    {
     "expr": "sum(increase(shifu_decision_service_unknown_encode_error_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "unknown_encode_error"
    }
   ]
  },
  {
   "title": "inventory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_inventory_tracker_start_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "send"
    },
    {
     "expr": "sum(increase(shifu_decision_service_inventory_tracker_callback_total{job=\"adtech-shifu-display-ad-decision-me-prod\", http_return_code != \"200\"}[1m])) by (type, http_return_code)",
     "legendFormat": "callback {{type}}: {{http_return_code}}"
    },
    {
     "expr": "sum(increase(shifu_decision_service_inventory_tracker_callback_total{job=\"adtech-shifu-display-ad-decision-me-prod\", http_return_code = \"200\"}[1m])) by (type, http_return_code)",
     "legendFormat": "callback {{type}}: {{http_return_code}}"
    },
    {
     "expr": "sum(increase(shifu_decision_service_preroll_request_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m])) by (type)",
     "legendFormat": "request {{type}}"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"adtech-shifu-display-ad-decision-me-prod\",uri=~\"/shifu/hs-in/v1/preroll\"}[1m]))",
     "legendFormat": "preroll request"
    }
   ]
  },
  {
   "title": "No qualified cause",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_qualification_empty_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "no qualification"
    },
    {
     "expr": "sum(increase(shifu_decision_service_not_feasible_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m])) by (not_feasible_type, id)",
     "legendFormat": "no feasible {{not_feasible_type}} = {{id}}"
    }
   ]
  },
  {
   "title": "Wrapper Fill Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_wrapper_fill_result_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m])) by (passback_ad_count, wrapper_ad_count)"
    }
   ]
  },
  {
   "title": "Slot Fill Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_selection_result_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m])) by (max_slot, selected_slot)"
    }
   ]
  },
  {
   "title": "Loading ad counter info",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(increase(shifu_decision_service_load_counter_fail_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[10m])) by (instance))",
     "legendFormat": "loading ad counter info failure"
    },
    {
     "expr": "avg(sum(increase(shifu_decision_service_load_counter_success_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[10m])) by (instance))",
     "legendFormat": "load ad counter info sucess"
    },
    {
     "expr": "sum(increase(shifu_counter_service_update_current_day_count_failed_total[10m])) by (ad_consumption_type)",
     "legendFormat": "update current day count failure: {{ad_consumption_type}}"
    },
    {
     "expr": "sum(increase(shifu_counter_service_update_moving_count_failed_total[10m])) by (ad_consumption_type)",
     "legendFormat": "update moving day count failure: {{ad_consumption_type}}"
    },
    {
     "expr": "sum(increase(shifu_counter_service_update_lifetime_count_failed_total[10m])) by (ad_consumption_type)",
     "legendFormat": "update lifetime count failure: {{ad_consumption_type}}"
    }
   ]
  },
  {
   "title": "Loading pacing info",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_load_pacing_fail_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[10m]))",
     "legendFormat": "load pacing failed"
    },
    {
     "expr": "avg(increase(shifu_decision_service_load_pacing_success_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[10m]))",
     "legendFormat": "load pacing sucess"
    }
   ]
  },
  {
   "title": "Loading ad model info",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_load_ad_model_fail_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[10m]))",
     "legendFormat": "loading ad model failure"
    },
    {
     "expr": "avg(increase(shifu_decision_service_load_ad_model_success_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[10m]))",
     "legendFormat": "load ad model sucess"
    }
   ]
  },
  {
   "title": "Unsupported Placement",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(shifu_decision_service_unsupported_placement_total{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory: heap usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jvm_memory_used_bytes{job=\"adtech-shifu-display-ad-decision-me-prod\"}) by (instance))",
     "legendFormat": "avg mem"
    }
   ]
  },
  {
   "title": "Memory: usage by region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jvm_memory_used_bytes{job=\"adtech-shifu-display-ad-decision-me-prod\"}) by (instance, id)) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "GC: count by cause",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{job=\"adtech-shifu-display-ad-decision-me-prod\"}[1m])) by (cause)",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "GC: pause time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(jvm_gc_pause_seconds_sum{service=\"adtech-shifu-display-ad-decision-me-prod\"}[1m]))",
     "legendFormat": "avg gc pause "
    }
   ]
  },
  {
   "title": "CPU: usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"adtech-shifu-display-ad-decision-me-prod.*\"}[1m])/sum(kube_pod_container_info{pod=~\"adtech-shifu-display-ad-decision-me-prod.*\"}))",
     "legendFormat": "avg cpu"
    }
   ]
  },
  {
   "title": "CPU: load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(sum(system_load_average_1m{job=\"adtech-shifu-display-ad-decision-me-prod\"}) by (instance))",
     "legendFormat": "avg cpu load"
    }
   ]
  }
 ]
}