{
 "title": "AP Zazu",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(http_zazu_req_count{service=\"$service_name\"}, pod)"
   },
   { "name": "service_name", "query": "ap-zazu" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Total Count",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_labels{label_app=\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Pod Avg Cpu",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"$service_name\"}[1m]))"
      }
     ]
    },
    {
     "title": "Push Message Speed/m",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(emq_cli_zazu_push_count{service=\"$service_name\"}[1m]))"
      }
     ]
    },
    {
     "title": "Push RPM",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_zazu_req_count{service=\"$service_name\", req=\"/api/v1/push-async\", pod=~\"$pod\", code=\"200\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Push message/m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(emq_cli_zazu_push_count{service=\"$service_name\"}[1m])) by (tag)",
       "legendFormat": "push_count-{{tag}}"
      }
     ]
    },
    {
     "title": "Push RPM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_zazu_req_count{service=\"$service_name\", req=\"/api/v1/push-async\", pod=~\"$pod\"}[1m])) by (code)",
       "legendFormat": "ap-zazu-response-{{code}}"
      }
     ]
    },
    {
     "title": "Internal resp time p99",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "int_zazu_resp_time_summary{pod=~\"$pod\", service=\"$service_name\", quantile=\"0.99\"}",
       "legendFormat": "zazu_internal_resp_time-{{pod}}-{{req}}"
      }
     ]
    },
    {
     "title": "Response time p99",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "http_zazu_req_time_summary{pod=~\"$pod\", service=\"$service_name\", quantile=\"0.99\"}",
       "legendFormat": "zazu_req_time-{{pod}}-{{req}}"
      }
     ]
    },
    {
     "title": "Queue size sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(emq_cli_zazu_queue_size{pod=~\"$pod\", service=\"$service_name\"})",
       "legendFormat": "queue_size"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Online Listener/m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kafka_zazu_online_status{service=\"$service_name\"}[1m]))",
       "legendFormat": "online_rate"
      }
     ]
    },
    {
     "title": "Push Delay Time P99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_zazu_delay_summary{service=\"$service_name\", quantile=\"0.99\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "process cpu usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{service=\"$service_name\", pod=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{service=\"$service_name\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "open file descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{service=\"$service_name\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{service=\"$service_name\", pod=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "OS threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{service=\"$service_name\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "memory alloc",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes_total{pod=~\"$pod\",service=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "heap in use memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{service=\"$service_name\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "GC cpu fraction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{service=\"$service_name\", pod=~\"$pod\"}"
      }
     ]
    }
   ]
  }
 ]
}