{
 "title": "Subs and Pay Integrated(Prod1+Prod2)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "NAMESPACE",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, namespace)"
    }
   },
   {
    "name": "SERVICE",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, job)"
    }
   },
   {
    "name": "API_STATUS",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\",deployment=\"subscription-service\"})",
       "legendFormat": "subs pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\",deployment=\"payment-service\"})",
       "legendFormat": "pay pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\",deployment=\"subscription-service-read\"})",
       "legendFormat": "subs read pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\", source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\",deployment=\"subscription-service-worker\"})",
       "legendFormat": "subs worker pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_deployment_status_replicas_available{namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\", deployment=\"payment-service-worker\"})",
       "legendFormat": "pay worker pods",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Subs - 2XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (api_name, response_code, http_status) (delta(hspay_subscriptions_api_response_metrics_total{http_status=~\"2.*\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "{{api_name}}, {{response_code}}, {{http_status}}"
      }
     ]
    },
    {
     "title": "Subs - Overall response throughput by codes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (http_status) (delta(hspay_subscriptions_api_response_metrics_total{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "{{http_status}}"
      }
     ]
    },
    {
     "title": "Subs API Level Metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$NAMESPACE\", service=~\"$SERVICE\", status=~\"$API_STATUS\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (uri, status) > 0 ",
       "legendFormat": "{{uri}} {{status}}"
      }
     ]
    },
    {
     "title": "Pay - 2XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (api_name, response_code, http_status) (delta(hspay_payments_api_response_metrics_total{http_status=~\"2.*\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "{{api_name}}, {{response_code}}, {{http_status}}"
      }
     ]
    },
    {
     "title": "Subs - 4XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (api_name, response_code, http_status) (delta(hspay_subscriptions_api_response_metrics_total{http_status=~\"4.*\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "{{api_name}}, {{response_code}}, {{http_status}}"
      }
     ]
    },
    {
     "title": "Initiate 5XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_5XX_counter[1m]))",
       "legendFormat": "Subs"
      },
      {
       "expr": "sum(increase(http_custom_server_requests_seconds_count{namespace=\"hspay-in-prod-apse1\", service=~\"payment-service.*\", source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\",uri=\"/payments/{apiVersion:v1|v2|v3}/{countryCode:in|us|ca|gb|fr|de|it|nl|sa|ae|qa|bh|om|kw|sg|my|lk|np|za|mu|au|nz|zz|id}/charge\", status=~\"5..\"}[1m]))",
       "legendFormat": "Pay"
      }
     ]
    },
    {
     "title": "Pay - 4XX",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (api_name, response_code, http_status) (delta(hspay_payments_api_response_metrics_total{http_status=~\"4.*\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "{{api_name}}, {{response_code}}, {{http_status}}"
      }
     ]
    },
    {
     "title": "Subs - Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name, method) (increase(hspay_subscriptions_error_metrics_total{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[30s]))",
       "legendFormat": "Errors: {{service_name}}, {{method}}"
      }
     ]
    },
    {
     "title": "Subs Redis metrics | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_redis_metrics_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le, method))"
      }
     ]
    },
    {
     "title": "Ratelimit block TPS Initiate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ratelimit_api_v1_ratelimit_blocked_config_key_total{config_key=~\"ambassador.host_gringotts-in-prod.hotstar.com.generic_key_payment_init_Api\"}[1m]))"
      }
     ]
    },
    {
     "title": "Pay/Kafka - Producer metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(hspay_payments_service_kafka_producer_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_payments_service_kafka_producer_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_service_kafka_producer_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "sum(delta(hspay_payments_service_kafka_producer_bucket{le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "Throughput"
      }
     ]
    }
   ]
  },
  {
   "title": "Major APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Initiate throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_bucket{le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (source_cluster)",
       "legendFormat": "Subs {{source_cluster}}"
      },
      {
       "expr": "sum(delta(hspay_payments_service_ChargeService_initiate_bucket{le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (source_cluster)",
       "legendFormat": "Pay {{source_cluster}}"
      }
     ]
    },
    {
     "title": "Subs - Initiate latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_api_SubscriptionGatewayController_addPayment_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Get subs throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"0\", le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "verbose 0"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"1\", le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "verbose 1"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"2\", le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "verbose 2"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"3\", le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "verbose 3"
      }
     ]
    },
    {
     "title": "Get Subs Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Get subs latency | verbose 0",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"0\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"0\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"0\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Payment client - Initiate latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(hspay_subscriptions_http_client_metrics_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_http_client_metrics_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_http_client_metrics_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "max(rate(hspay_subscriptions_http_client_metrics_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Get subs latency | verbose 1",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"1\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"1\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"1\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Get subs latency | verbose 2",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"2\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"2\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"2\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Get subs latency | verbose 3",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"3\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"3\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_SubscriptionService_getSubscriptions_bucket{verbosity=\"3\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "PayU - Initiate latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(hspay_payments_service_PayUGateway_initiateCharge_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_payments_service_PayUGateway_initiateCharge_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_service_PayUGateway_initiateCharge_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p75"
      }
     ]
    },
    {
     "title": "Partner - Create Subs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_PartnerService_createSubscription_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_PartnerService_createSubscription_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_PartnerService_createSubscription_bucket{le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "Partner - Update Subs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_api_PartnerService_updateSubscription_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_subscriptions_api_PartnerService_updateSubscription_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_api_PartnerService_updateSubscription_bucket{le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "Redis Cache Hit Rate Metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_redis_cache_interactions{redis_cache_name = \"hid_cache\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (cache_hit_result)",
       "legendFormat": "HID Cache - {{cache_hit_result}}"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_redis_cache_interactions{redis_cache_name = \"subs_cache\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (cache_hit_result)",
       "legendFormat": "Subs Cache - {{cache_hit_result}}"
      }
     ]
    },
    {
     "title": "Tax Client - Response code throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (delta(hspay_subscriptions_tax_service_response_total{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "CalculateTax - {{response_code}}"
      }
     ]
    },
    {
     "title": "Payment Client - Response code throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (delta(hspay_subscriptions_init_response_total{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "{{response_code}}"
      },
      {
       "expr": "sum by (response_code) (delta(hspay_subscriptions_refund_response_total{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m]))",
       "legendFormat": "REFUND - {{response_code}}"
      }
     ]
    },
    {
     "title": "Tax client - calculate tax latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_external_service_metrics_bucket{service_name=\"tax_service\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "CalculateTax - p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(hspay_subscriptions_external_service_metrics_bucket{service_name=\"tax_service\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "CalculateTax - p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_external_service_metrics_bucket{service_name=\"tax_service\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "CalculateTax - p75"
      }
     ]
    },
    {
     "title": "UM Client - get user info by hid latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_external_service_metrics_bucket{service_name=\"um_service\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99 "
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(hspay_subscriptions_external_service_metrics_bucket{service_name=\"um_service\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p90 "
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_external_service_metrics_bucket{service_name=\"um_service\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p75 "
      }
     ]
    }
   ]
  },
  {
   "title": "Worker metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Consumer Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_worker_metrics_bucket{le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (queue_name)",
       "legendFormat": "{{queue_name}}"
      },
      {
       "expr": "sum(delta(hspay_subscriptions_consumer_metrics_bucket{le=\"+Inf\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (consumer)",
       "legendFormat": "{{consumer}}"
      }
     ]
    },
    {
     "title": "Group wise lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_topic",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(lag) as total_lag FROM (SELECT last(\"lag\") as lag FROM burrow.autogen.burrow_partition WHERE \"group\" =~ /prod.hspay.subscription./ GROUP BY time($__interval), \"group\",topic,partition fill(null)) WHERE $timeFilter GROUP BY time($__interval),\"group\", topic",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Partner worker recur events success count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hspay_subscriptions_partner_worker_metrics_total{is_success=\"true\"})) by (partner)",
       "legendFormat": "success count - {{partner}}"
      },
      {
       "expr": "sum(increase(hspay_subscriptions_partner_worker_metrics_total{is_success=\"false\"})) by (partner)",
       "legendFormat": "failure count - {{partner}}"
      },
      {
       "expr": "sum(increase(hspay_subscriptions_partner_worker_metrics_total{is_success=\"false\"}))",
       "legendFormat": "failure count - total"
      }
     ]
    },
    {
     "title": "Worker Consumer Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_worker_metrics_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (queue_name,le))",
       "legendFormat": "{{queue_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_consumer_metrics_bucket{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (consumer,le))",
       "legendFormat": "{{consumer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Partner Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "OK",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"OK\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (api_name)",
       "legendFormat": "{{api_name}}"
      }
     ]
    },
    {
     "title": "Traffic by partner",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (partner)",
       "legendFormat": "{{partner}}"
      }
     ]
    },
    {
     "title": "USER_SUBSCRIPTION_SUBSCRIPTION_NOT_FOUND",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"USER_SUBSCRIPTION_SUBSCRIPTION_NOT_FOUND\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (api_name)",
       "legendFormat": "{{api_name}}"
      }
     ]
    },
    {
     "title": "INTERNAL_SERVER_ERROR",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"INTERNAL_SERVER_ERROR\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (api_name)",
       "legendFormat": "{{api_name}}"
      }
     ]
    },
    {
     "title": "PARTNER_SUBSCRIPTION_CONFLICT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"PARTNER_SUBSCRIPTION_CONFLICT\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (partner)",
       "legendFormat": "{{partner}}"
      }
     ]
    },
    {
     "title": "EVENT_NOT_ACCEPTABLE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_partner_metrics{response_code=\"EVENT_NOT_ACCEPTABLE\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"}[1m])) by (api_name)",
       "legendFormat": "{{api_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat server metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat busy threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(tomcat_threads_busy_threads{job=\"subscription-service\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"})",
       "legendFormat": "Subs busy threads"
      },
      {
       "expr": "sum(tomcat_threads_busy_threads{job =~ \"payment-service.*\",source_cluster=~\"apicluster-apse1.prod2.hotstar-prod.com|prod-apse1.k8s.hotstar-labs.com\"})",
       "legendFormat": "Pay busy threads"
      },
      {
       "expr": "sum(tomcat_threads_busy_threads{job=\"subscription-service-read\"})",
       "legendFormat": "Subs read busy threads"
      }
     ]
    }
   ]
  },
  {
   "title": "Database metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pay - Charges | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_db_metrics_bucket{entity=\"charge\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Pay - Webhook notification Log | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_db_metrics_bucket{entity=\"webhook_notification_log\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Pay - PayU Charges | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_payments_db_metrics_bucket{entity=\"payu_charge\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Subscription Table | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_db_metrics_bucket{entity=\"subscription\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Subscription Logs Table | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_db_metrics_bucket{entity=\"subscription_log\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Orders Table | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_db_metrics_bucket{entity=\"order\"}[1m])) by (le, entity, method))"
      }
     ]
    },
    {
     "title": "Subs Redis metrics | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(hspay_subscriptions_redis_metrics_bucket[1m])) by (le, method))"
      }
     ]
    },
    {
     "title": "Switch transition Logs Table | p75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_subscriptions_db_metrics_bucket{entity=\"switch_transition_meta\"}[1m])) by (le, entity, method))"
      }
     ]
    }
   ]
  }
 ]
}