{
 "title": "Akamai-Datastream-Stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Hotstar API stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "2XX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "datastream_2xx * 60", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "4XX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "datastream_4xx * 60", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "5XX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "datastream_5xx * 60", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "Cache Miss",
   "type": "graph",
   "description": "The total number of requests that received the required data from the origin for this time interval.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "datastream_numCacheMiss * 60", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "description": "The total number of requests that received the required data from the cache",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "datastream_numCacheHit * 60", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "Avg Edge-ResponseTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "datastream_edgeResponseTime", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "Avg Origin-ResponseTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "datastream_originResponseTime", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "description": "The average number of requestsPerSecond for this time interval.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "datastream_requestsPerSecond", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "OffLoad Rate",
   "type": "graph",
   "description": "The percentage value of cache hit requests divided by the total number of requests for this time interval",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "datastream_offloadRate", "legendFormat": "{{ path }}" }
   ]
  },
  {
   "title": "Datastream API stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  },
  {
   "title": "Datastream api errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(datastream_api_errors) by(errorType)",
     "legendFormat": "{{ errorType }}"
    }
   ]
  },
  {
   "title": "Datastream api response time(avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(datastream_api_response_time)"
    }
   ]
  }
 ]
}