{
 "title": "Rated Capacity Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Platform concurrency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "current infra ladder",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      { "expr": "min(current_ladder)" }
     ]
    },
    {
     "title": "vod users",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      { "expr": "max(platform_vod_concurrency)" }
     ]
    },
    {
     "title": "live users",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      { "expr": "max(platform_live_concurrency)" }
     ]
    },
    {
     "title": "Total Users akamai",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "max(platform_live_concurrency{}) + max(platform_vod_concurrency{})"
      }
     ]
    },
    {
     "title": "Total Users Heartbeat",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      { "expr": "max(heart_beat_concurrency)" }
     ]
    },
    {
     "title": "Concurrency scaling buffer",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "platform_concurrency_buffer:traffic_based"
      }
     ]
    },
    {
     "title": "standby infra",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "format": "percentunit",
     "valueName": "total",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"monitoring\", pod=~\"overprovisioning-.*\"}) / sum(kube_node_status_capacity_cpu_cores{namespace=\"monitoring\"})"
      }
     ]
    },
    {
     "title": "Audience Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "platform_concurrency:with_akamai_and_heartbeat + platform_concurrency_buffer:traffic_based",
       "legendFormat": "Concurrency for Scaling"
      },
      { "expr": "max(bifrost_hb_alb_request)", "legendFormat": "Hearbeat ALB Concurrency" },
      { "expr": "max(heart_beat_concurrency{})", "legendFormat": "Heartbeat Concurrency" },
      {
       "expr": "max(platform_live_concurrency{})",
       "legendFormat": "Akamai Live Concurrency"
      },
      {
       "expr": "max(platform_vod_concurrency{})",
       "legendFormat": "Akamai VOD Concurrency"
      },
      { "expr": "current_ladder", "legendFormat": "Infra Ladder" },
      {
       "expr": "platform_concurrency_buffer:traffic_based",
       "legendFormat": "Concurrency Buffer"
      }
     ]
    },
    {
     "title": "hs-um",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "aws_elb_request_count_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\".*hs-um*\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "{{ tag_kubernetes_io_service_name }}"
      }
     ]
    },
    {
     "title": "cms-multi-get-new",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "aws_elb_request_count_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\".*cms-multi-get-new*\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "{{ tag_kubernetes_io_service_name }}"
      }
     ]
    },
    {
     "title": "cms-geccomp",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "aws_elb_request_count_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\".*cms-geccomp*\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "{{ tag_kubernetes_io_service_name }}"
      }
     ]
    },
    {
     "title": "bifrost",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(aws_alb_tg_request_count_sum and on (name) aws_alb_info{tag_prometheus_monitoring_svc_name=\"bifrost\"})"
      }
     ]
    },
    {
     "title": "cms-rocky",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "aws_elb_request_count_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\".*cms-rocky*\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "{{ tag_kubernetes_io_service_name }}"
      }
     ]
    },
    {
     "title": "persona-service",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "aws_alb_request_count_sum + on (name)  group_left(tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_ingress_name=~\"persona-service-1-ingress\",tag_kubernetes_io_namespace=~\"personalisation-in-prod-apse1\"}) by(name,tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace)",
       "legendFormat": "{{ tag_kubernetes_io_service_name }}"
      }
     ]
    },
    {
     "title": "um-concurrency",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "aws_elb_request_count_sum + on (name)  group_left(tag_kubernetes_io_service_name) topk(1,aws_elb_info{tag_kubernetes_io_service_name!~\"kube-system.*|monitoring.*|book-info.*|logging.*\",tag_kubernetes_io_service_name=~\"umsp-in-prod-apse1/ums-concurrency-int\"}) by(name,tag_kubernetes_io_service_name)",
       "legendFormat": "{{ tag_kubernetes_io_service_name }}"
      }
     ]
    },
    {
     "title": "bifrost-hb",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(aws_alb_tg_request_count_sum and on (name) aws_alb_info{tag_prometheus_monitoring_svc_name=\"bifrost-hb\"})"
      }
     ]
    }
   ]
  }
 ]
}