{
 "title": "Google Integrations",
 "time": { "from": "now-10m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_created, namespace)"
   },
   { "name": "service", "label": "service", "query": "google-integrations" }
  ]
 },
 "panels": [
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "CMS Consumer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cms_consumer_messages_success_count_total)",
     "legendFormat": "Messages read success total"
    },
    {
     "expr": "sum(cms_consumer_messages_error_count_total)",
     "legendFormat": "Messages read error total"
    },
    {
     "expr": "sum(cms_consumer_updates_error_count_total)",
     "legendFormat": "Update errors total"
    }
   ]
  },
  {
   "title": "Indexing Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(content_indexing_update_success_count_total)",
     "legendFormat": "Total URL update success count"
    },
    {
     "expr": "sum(content_indexing_update_error_count_total)",
     "legendFormat": "Total URL update error count"
    },
    {
     "expr": "sum(content_indexing_delete_success_count_total)",
     "legendFormat": "Total URL Delete success count"
    },
    {
     "expr": "sum(content_indexing_delete_error_count_total)",
     "legendFormat": "Total URL Delete error count"
    },
    {
     "expr": "sum(content_indexing_other_error_count_total)",
     "legendFormat": "Total other error count"
    },
    {
     "expr": "sum(content_indexing_skipped_count_total)",
     "legendFormat": "Total skipped count"
    }
   ]
  },
  {
   "title": "Kafka Broker State",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "First",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(kafka_broker_state) by (kafka_broker_state)",
     "legendFormat": "{{kafka_broker_state}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Kafka Connection Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_conn_error_count_total)",
     "legendFormat": "Initial error count"
    },
    {
     "expr": "sum(kafka_consumer_cb_error_count_total)",
     "legendFormat": "Total error count"
    }
   ]
  },
  {
   "title": "Pod Level Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Pods Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"$service\"}) by (deployment, namespace)",
     "legendFormat": "Desired"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$service\"}) by (deployment, namespace)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", deployment=\"$service\"}) by (deployment, namespace)",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=~\"$service.*\", container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container_name=\"$service\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=~\"$service.*\", container_name!=\"POD\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$service.*\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=~\"$service.*\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$service.*\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$service.*\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=~\"$service.*\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$service.*\"}) by (container)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", pod_name=~\"$service.*\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}} (RSS)"
    },
    {
     "expr": "sum by (container_name) (container_resources_memory_cache_bytes{container_name!=\"\",container_name!=\"POD\",namespace=\"$namespace\",pod_name=~\"$service.*\"})",
     "legendFormat": "{{container_name}} (Cache)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\", pod_name=~\"$service.*\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}} (Swap)"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", container_name=\"$service\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / avg(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\"$service.*\", container_name!=\"POD\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$service.*\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\"$service.*\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$service.*\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$service.*\", container!=\"\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\"$service.*\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$service.*\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_rss{namespace=\"$namespace\", pod_name=~\"$service.*\", container_name != \"\", container_name != \"POD\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum by (container) (label_replace(container_resources_memory_cache_bytes{container_name!=\"\",container_name!=\"POD\",namespace=\"$namespace\",pod_name=~\"$service.*\"}, \"container\", \"$1\", \"container_name\", \"(.*)\"))"
    },
    {
     "expr": "sum(label_replace(container_memory_swap{namespace=\"$namespace\", pod_name=~\"$service.*\", container_name != \"\", container_name != \"POD\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
    }
   ]
  },
  {
   "title": "ALB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_tg_request_count_sum and on (name) aws_alb_info{tag_kubernetes_io_service_name=\"$service\", tag_kubernetes_io_namespace=\"$namespace\"})",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "ALB Error Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_tg_httpcode_elb_5_xx_count_sum and on (name) aws_alb_info{tag_kubernetes_io_service_name=\"$service\", tag_kubernetes_io_namespace=\"$namespace\"})",
     "legendFormat": "ALB 5xx Count"
    },
    {
     "expr": "sum(aws_alb_tg_httpcode_backend_4_xx_sum and on (name) aws_alb_info{tag_kubernetes_io_service_name=\"$service\", tag_kubernetes_io_namespace=\"$namespace\"})",
     "legendFormat": "Backend 4xx Count"
    },
    {
     "expr": "sum(aws_alb_tg_httpcode_backend_5_xx_sum and on (name) aws_alb_info{tag_kubernetes_io_service_name=\"$service\", tag_kubernetes_io_namespace=\"$namespace\"})",
     "legendFormat": "Backend 5xx Count"
    }
   ]
  },
  {
   "title": "ALB Spill Over Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_tg_spillover_count_sum and on (name) aws_alb_info{tag_kubernetes_io_service_name=\"$service-alb\"})",
     "legendFormat": "$service"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(aws_alb_target_response_time_average and on (name) aws_alb_info{tag_kubernetes_io_ingress_name=\"$service-ingress\"})",
     "legendFormat": "$service"
    }
   ]
  }
 ]
}