{
 "title": "Topic Level Metrics - ISC",
 "description": "All information about topics within Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": "show tag values from BrokerTopicMetrics with key = \"topic\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total Messages ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "BrokerTopicMetrics",
     "query": "SELECT sum(\"OneMinuteRate\") FROM \"BrokerTopicMetrics\" WHERE (\"typeName\" =~ /type=BrokerTopicMetrics,name=MessagesInPerSec,topic=$topic/) AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "MessagesInPerSec" },
      { "condition": "AND", "key": "topic", "operator": "=~", "value": "/^$topic$/" }
     ]
    }
   ]
  },
  {
   "title": "MessagesInPerSec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "BrokerTopicMetrics",
     "query": "SELECT mean(\"OneMinuteRate\") FROM \"BrokerTopicMetrics\" WHERE (\"name\" = 'MessagesInPerSec' AND \"topic\" =~ /^$topic$/) AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "MessagesInPerSec" },
      { "condition": "AND", "key": "topic", "operator": "=~", "value": "/^$topic$/" }
     ]
    }
   ]
  },
  {
   "title": "BytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "BrokerTopicMetrics",
     "query": "SELECT sum(\"OneMinuteRate\") FROM \"BrokerTopicMetrics\" WHERE (\"typeName\" =~ /type=BrokerTopicMetrics,name=BytesInPerSec,topic=$topic/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesInPerSec" },
      { "condition": "AND", "key": "topic", "operator": "=~", "value": "/^$topic$/" }
     ]
    }
   ]
  },
  {
   "title": "TotalProduceRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "BrokerTopicMetrics",
     "query": "SELECT sum(\"OneMinuteRate\") FROM \"BrokerTopicMetrics\" WHERE (\"typeName\" =~ /type=BrokerTopicMetrics,name=TotalProduceRequestsPerSec,topic=$topic/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "TotalProduceRequestsPerSec" },
      { "condition": "AND", "key": "topic", "operator": "=~", "value": "/^$topic$/" }
     ]
    }
   ]
  },
  {
   "title": "BytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "BrokerTopicMetrics",
     "query": "SELECT percentile(\"OneMinuteRate\",90) FROM \"BrokerTopicMetrics\" WHERE (\"typeName\" =~ /type=BrokerTopicMetrics,name=BytesOutPerSec,topic=$topic/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "BytesOutPerSec" },
      { "condition": "AND", "key": "topic", "operator": "=~", "value": "/^$topic$/" }
     ]
    }
   ]
  },
  {
   "title": "FailedProduceRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "BrokerTopicMetrics",
     "query": "SELECT sum(\"OneMinuteRate\") FROM \"BrokerTopicMetrics\" WHERE (\"typeName\" =~ /type=BrokerTopicMetrics,name=FailedProduceRequestsPerSec,topic=$topic/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "FailedProduceRequestsPerSec" },
      { "condition": "AND", "key": "topic", "operator": "=~", "value": "/^$topic$/" }
     ]
    }
   ]
  }
 ]
}