{
 "title": "Kubernetes cluster namespace utilisation",
 "description": "Monitors Kubernetes cluster CPU AND Memory",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(node_boot_time_seconds{cluster=\"$cluster\", job=\"node-exporter\"}, instance)"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_namespace_created, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_created{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "container",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, container)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(\n  sum(\n    count(container_memory_working_set_bytes{id=\"/\"}) by (instance)\n    * on (instance) \n    sum(avg_over_time(container_memory_working_set_bytes{id=\"/\"}[1d])) by (instance)\n  )\n  /\n  sum(kube_node_status_allocatable_memory_bytes)\n) * 100"
      }
     ]
    },
    {
     "title": "Cluster CPU usage avg",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 11, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(\n  sum(\n    count(irate(container_cpu_usage_seconds_total{id=\"/\"}[1d])) by (instance)\n    * on (instance) \n    sum(irate(container_cpu_usage_seconds_total{id=\"/\"}[1d])) by (instance)\n  ) \n  / \n  (sum (kube_node_status_allocatable_cpu_cores))\n) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 5, "y": 6 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 11, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[1m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 17, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Cluster Node Utilisation by CPU and RAM requests",
     "type": "table",
     "description": "This table shows the comparison of CPU and RAM requests by applications, vs the capacity of the node",
     "gridPos": { "h": 7, "w": 21, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "( \n  sum(kube_pod_container_resource_requests_memory_bytes) by (node) \n  /\n  sum(kube_node_status_allocatable_memory_bytes) by (node)\n) * 100",
       "legendFormat": "{{ node }}"
      },
      {
       "expr": "( \n  sum(kube_pod_container_resource_requests_cpu_cores) by (node) \n  /\n  sum(kube_node_status_allocatable_cpu_cores) by (node)\n) * 100",
       "legendFormat": "{{ node }}"
      },
      {
       "expr": "# CPU Usage / cpu requested\nsum by (namespace) (\n  # Filter out no-longer-existing pods\n  label_replace(\n    (kube_pod_status_phase{namespace=~\".*wiremind.*\", phase=\"Running\"}),\n    \"pod_name\",\"$1\",\"pod\",\"(.*)\"\n  )\n  * on (pod_name, namespace) group_right\n  rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\"}[1d])\n)\n\n/ on (namespace)\nsum by (namespace) (\n  kube_pod_container_resource_requests_cpu_cores\n) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace / Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "Namespace CPU resource requested",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by(namespace)",
     "legendFormat": "{{ namespace}}"
    }
   ]
  },
  {
   "title": "Namespace CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\", namespace =~\"$namespace\"}[1m])) by (pod_name)\n",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods CPU requested",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Namespace / Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace Memory  requested ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes / (1024 * 1024 * 1024)) by (namespace)",
       "legendFormat": "{{ namespace }} "
      }
     ]
    },
    {
     "title": "Namespace Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container_name!=\"\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Pods memory request",
     "type": "graph",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"} / (1024 * 1024 * 1024)) by (pod)\n",
       "legendFormat": "{{pod }}"
      }
     ]
    },
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_usage_bytes{image!=\"\",name=~\"^k8s_.*\",namespace= \"$namespace\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace / Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{node=~\"^$Node$\"}[1m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\"^$Node$\"}[1m]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Pods network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}[1m])) by (pod_name)",
       "legendFormat": "-> {{ pod_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\"}[1m])) by (pod_name)",
       "legendFormat": "<- {{ pod_name }}"
      }
     ]
    }
   ]
  }
 ]
}