{
 "title": "Beats Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_namespace_created, source_cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(filebeat_filebeat_harvester{namespace=\"logging\", source_cluster=~\"$cluster\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "filebeat_uptime_seconds_total{pod=\"$pod\", source_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Filebeat Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_filebeat_events{pod=\"$pod\", source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Harvester Info",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_filebeat_harvester{pod=\"$pod\", source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ harvester }}"
    }
   ]
  },
  {
   "title": "Registrar states",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_registrar_states{pod=\"$pod\", source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Filebeat input logs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_filebeat_input_log{pod=\"$pod\", source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ files }}"
    }
   ]
  },
  {
   "title": "Output read errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_libbeat_output_read_errors_total{pod=\"$pod\",source_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Output write errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_libbeat_output_write_errors_total{pod=\"$pod\",source_cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Registrar writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_registrar_writes{pod=\"$pod\", source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ writes }}"
    }
   ]
  },
  {
   "title": "Output Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_libbeat_output_events{pod=\"$pod\", source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Pipeline Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filebeat_libbeat_pipeline_events{pod=\"$pod\", source_cluster=~\"$cluster\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}