{
 "title": "Social Chat Infra Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "North Star ( Private/ Received ）",
   "type": "graph",
   "description": "EMQ messages stats not available in this grafana. So we use Private messages / User published messages as the north star here. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(MessageUnicastToFriend{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"}) + sum(MessageSentToFriend{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"}))/ sum(MessageOverall{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"})",
     "legendFormat": "North Star"
    },
    {
     "expr": "(sum(MessageUnicastToFriend{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"}) by (subtype) + sum(MessageSentToFriend{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"}) by (subtype))/ sum(MessageOverall{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"}) by (subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "5xx",
     "type": "graph",
     "description": "5xx from elb and alb, we won't add alerts since it have already added in deployment-portal.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(aws_alb_httpcode_elb_5_xx_count_sum[1m]) + on (name)  group_left(tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name=~\"social-(chat|common|media-labs|signal)-.*\"}) by(name,tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace)) by (tag_kubernetes_io_ingress_name)",
       "legendFormat": "{{ tag_kubernetes_io_namespace }}/{{ tag_kubernetes_io_ingress_name }}"
      },
      {
       "expr": "sum(delta(aws_alb_tg_httpcode_target_5_xx_count_sum[1m]) + on (name)  group_left(tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name=~\"social-(chat|common|media-labs|signal)-.*\"}) by(name,tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace)) by (tag_kubernetes_io_ingress_name)",
       "legendFormat": "{{ tag_kubernetes_io_namespace }}/{{ tag_kubernetes_io_ingress_name }}"
      }
     ]
    },
    {
     "title": "4xx",
     "type": "graph",
     "description": "4xx from elb and alb, we won't add alerts since it have already added in deployment-portal.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(aws_alb_httpcode_elb_4_xx_count_sum[1m]) + on (name)  group_left(tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name=~\"social-(chat|common|media-labs|signal)-.*\"}) by(name,tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace)) by (tag_kubernetes_io_ingress_name)",
       "legendFormat": "{{ tag_kubernetes_io_namespace }}/{{ tag_kubernetes_io_ingress_name }}"
      },
      {
       "expr": "sum(delta(aws_alb_tg_httpcode_target_4_xx_count_sum[1m]) + on (name)  group_left(tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace) topk(1,aws_alb_info{tag_kubernetes_io_ingress_name=~\"social-(chat|common|media-labs|signal)-.*\"}) by(name,tag_kubernetes_io_ingress_name,tag_kubernetes_io_namespace)) by (tag_kubernetes_io_ingress_name)",
       "legendFormat": "{{ tag_kubernetes_io_namespace }}/{{ tag_kubernetes_io_ingress_name }}"
      }
     ]
    },
    {
     "title": "Pubapi Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg by (path) (http_server_requests_latency_seconds_total{quantile=\"Avg\",service=~\"social-chat-pubapi\"})",
       "legendFormat": "avg {{path}}"
      },
      {
       "expr": "avg by (path) (http_server_requests_latency_seconds_total{quantile=\"p90\",service=~\"social-chat-pubapi\"})",
       "legendFormat": "p90 {{path}}"
      }
     ]
    },
    {
     "title": "Subapi Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg by (path) (http_server_requests_latency_seconds_total{quantile=\"Avg\",service=~\"social-chat-subapi\"})",
       "legendFormat": "avg {{path}}"
      },
      {
       "expr": "avg by (path) (http_server_requests_latency_seconds_total{quantile=\"p90\",service=~\"social-chat-subapi\"})",
       "legendFormat": "p90 {{path}}"
      },
      {}
     ]
    },
    {
     "title": "Gateway Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg by (path) (http_server_requests_latency_seconds_total{quantile=\"Avg\",service=~\"social-chat-gateway\"})",
       "legendFormat": "avg {{path}}"
      },
      {
       "expr": "avg by (path) (http_server_requests_latency_seconds_total{quantile=\"p90\",service=~\"social-chat-gateway\"})",
       "legendFormat": "p90 {{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Received RPS",
     "type": "graph",
     "description": "Messages published by clients",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(MessageOverall{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"}[1m])) by (namespace, subtype)",
       "legendFormat": "{{subtype}} "
      }
     ]
    },
    {
     "title": "Comment ",
     "type": "singlestat",
     "description": "total text comment received today",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(avg(MessageOverall{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\", subtype=\"text\"}) by (namespace))"
      }
     ]
    },
    {
     "title": "Public Feed Messages",
     "type": "graph",
     "description": "Messages sent to clients via EMQ public topic",
     "gridPos": { "h": 6, "w": 10, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(MessageSentToPublic{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"}[1m])) by (namespace, subtype)",
       "legendFormat": "{{subtype}}"
      }
     ]
    },
    {
     "title": "Comment ",
     "type": "singlestat",
     "description": "total text comment sent to public feed today",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(avg(MessageSentToPublic{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\", subtype=\"text\"}) by (namespace))"
      }
     ]
    },
    {
     "title": "Hotshot",
     "type": "singlestat",
     "description": "total hotshot received today",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 12 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(avg(MessageOverall{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\", subtype=\"hotshot\"}) by (namespace))"
      }
     ]
    },
    {
     "title": "Hotshot",
     "type": "singlestat",
     "description": "total hotshot sent to public feed today",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 12 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(avg(MessageSentToPublic{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\", subtype=\"hotshot\"}) by (namespace))"
      }
     ]
    },
    {
     "title": "Video",
     "type": "singlestat",
     "description": "total video received today",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(avg(MessageOverall{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\", subtype=\"video\"}) by (namespace))"
      }
     ]
    },
    {
     "title": "Video",
     "type": "singlestat",
     "description": "total video sent to public today",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(avg(MessageSentToPublic{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\", subtype=\"video\"}) by (namespace))"
      }
     ]
    },
    {
     "title": "Live Friend messages",
     "type": "graph",
     "description": "Messages sent to clients via EMQ private topic",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(MessageUnicastToFriend{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"}) by (namespace, subtype)",
       "legendFormat": "{{subtype}}"
      }
     ]
    },
    {
     "title": "History Friend messages",
     "type": "graph",
     "description": "Messages sent to client via http request in subapi.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(MessageSentToFriend{target=~\"^d/.*\", namespace=~\"^$Namespace.*$\"}) by (namespace, subtype)",
       "legendFormat": "{{subtype}}"
      }
     ]
    },
    {
     "title": "PubAPI (RPS)",
     "type": "graph",
     "description": "Publish api total received, denied, profane \nRaise alert when denied rqs is high",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pubapi_request_overall[1m]))",
       "legendFormat": "overall"
      },
      {
       "expr": "sum(rate(pubapi_message_dential_of_service[1m]))",
       "legendFormat": "dential of service"
      },
      {
       "expr": "sum(rate(pubapi_message_public_profane[1m]))",
       "legendFormat": "profane"
      },
      {
       "expr": "sum(rate(pubapi_request_failed[1m])) by (name)",
       "legendFormat": "failed {{name}}"
      }
     ]
    },
    {
     "title": "SubAPI (RPS)",
     "type": "graph",
     "description": "History api rqs",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(subapi_request_overall[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Moderation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Moderation (RPM)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(MessageOverall{target=~\"d/.*\"}[1m])",
       "legendFormat": "Income {{subtype}}"
      },
      {
       "expr": "delta(MessageAccepted{target=~\"d/.*\"}[1m])",
       "legendFormat": "Accept {{subtype}}"
      },
      {
       "expr": "delta(MessageRejected{target=~\"d/.*\"}[1m])",
       "legendFormat": "Rejected {{ subtype}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Media labs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Image NSFW Health",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(image_nsfw_ping_time) * 1000",
       "legendFormat": "ping time"
      }
     ]
    },
    {
     "title": "Text Eval Health",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(text_eval_ping_time) * 1000",
       "legendFormat": "ping time"
      }
     ]
    },
    {
     "title": "Text Eval RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(requests_total{service=\"social-media-labs-text-eval\"}[5m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg(rate(requests_total{service=\"social-media-labs-text-eval\"}[5m])>0)",
       "legendFormat": "Average (per pod)"
      }
     ]
    },
    {
     "title": "Text Eval Latency (Processing Time)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_duration_seconds_sum{service=\"social-media-labs-text-eval\"}[5m])) / sum(rate(request_duration_seconds_count{service=\"social-media-labs-text-eval\"}[5m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(request_duration_seconds_bucket{service=\"social-media-labs-text-eval\"}[5m])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(request_duration_seconds_bucket{service=\"social-media-labs-text-eval\"}[5m])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(request_duration_seconds_bucket{service=\"social-media-labs-text-eval\"}[5m])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Image Eval RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(requests_total{service=\"social-media-labs-image-eval\"}[5m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg(rate(requests_total{service=\"social-media-labs-image-eval\"}[5m])>0)",
       "legendFormat": "Average (per pod)"
      }
     ]
    },
    {
     "title": "Image Eval Latency (Processing Time)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_duration_seconds_sum{service=\"social-media-labs-image-eval\"}[5m])) / sum(rate(request_duration_seconds_count{service=\"social-media-labs-image-eval\"}[5m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(request_duration_seconds_bucket{service=\"social-media-labs-image-eval\"}[5m])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(request_duration_seconds_bucket{service=\"social-media-labs-image-eval\"}[5m])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(request_duration_seconds_bucket{service=\"social-media-labs-image-eval\"}[5m])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Video Eval RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(requests_total{service=\"social-media-labs-video-eval\"}[5m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg(rate(requests_total{service=\"social-media-labs-video-eval\"}[5m])>0)",
       "legendFormat": "Average (per pod)"
      }
     ]
    },
    {
     "title": "Video Eval Latency (Processing Time)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_duration_seconds_sum{service=\"social-media-labs-video-eval\"}[5m])) / sum(rate(request_duration_seconds_count{service=\"social-media-labs-video-eval\"}[5m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(request_duration_seconds_bucket{service=\"social-media-labs-video-eval\"}[5m])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(request_duration_seconds_bucket{service=\"social-media-labs-video-eval\"}[5m])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(request_duration_seconds_bucket{service=\"social-media-labs-video-eval\"}[5m])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Processor Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(processed_messages_total{service=\"social-media-labs-processor\"}[1m])) by (channel) > 0",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "Active Channels Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(active_channels_count{service=\"social-media-labs-processor\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Processor Regular Sync Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(regular_sync_duration_seconds_sum{service=\"social-media-labs-processor\"}>0[5m])) / sum(rate(regular_sync_duration_seconds_count{service=\"social-media-labs-processor\"}>0[5m]))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Processor Update ClusterMap Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(update_single_pass_duration_seconds_sum{service=\"social-media-labs-processor\"}>0[5m])) by (channel) / sum(rate(update_single_pass_duration_seconds_count{service=\"social-media-labs-processor\"}>0[5m])) by (channel)",
       "legendFormat": "{{channel}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Social Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Social Graph",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(FriendAPIRequestOverall{target=~\"d/.*\"})",
       "legendFormat": "Overall"
      },
      {
       "expr": "avg(FriendAPIRequestFailure{target=~\"d/.*\"})",
       "legendFormat": "Failure"
      },
      {
       "expr": "avg(GraphFiveOrMoreFriends{target=~\"d/.*\"}) + avg(GraphLessThanFiveFriends{target=~\"d/.*\"})",
       "legendFormat": "Not Empty "
      },
      {
       "expr": "avg(GraphNoFriend{target=~\"d/.*\"})",
       "legendFormat": "Empty "
      },
      {
       "expr": "sum(delta(FriendAPIRequestFailure{target=~\"d/.*\"}[5m]))/(sum(delta(FriendAPIRequestOverall{target=~\"d/.*\"}[5m])) + 0.00001) ",
       "legendFormat": "ErrorRate"
      }
     ]
    },
    {
     "title": "Social Graph API Health",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(social_graph_ping_time) * 1000",
       "legendFormat": "ping time"
      }
     ]
    }
   ]
  },
  {
   "title": "Social Signals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Social Signals",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(SocialSignalOverall{target=~\"d/.*\"})",
       "legendFormat": "Income"
      },
      {
       "expr": "sum(SocialSignalExpired{target=~\"d/.*\"})",
       "legendFormat": "Expired"
      },
      {
       "expr": "sum(SocialSignalBadFormat{target=~\"d/.*\"}) ",
       "legendFormat": "BadFormat"
      },
      {
       "expr": "sum(SocialSignalSentSuccess{target=~\"d/.*\"})",
       "legendFormat": "SentOut"
      },
      {
       "expr": "sum(SocialSignalSentSuccess{target=~\"d/.*\", subtype=~\".*history\"}) / (sum(SocialSignalSentSuccess{target=~\"d/.*\"}) + 0.00001) * 100",
       "legendFormat": "History %"
      }
     ]
    },
    {
     "title": "Social Signal  Types (RPM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(SocialSignalReceived{target=~\"d/.*\"}[1m])",
       "legendFormat": "Income {{subtype}}"
      },
      {
       "expr": "delta(SocialSignalSentSuccess{target=~\"d/.*\"}[1m])",
       "legendFormat": "SentOut {{subtype}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Social Signal Aggregator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Social Signal Error Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(delta(social_signal_aggregator_event_expired[5m])) + sum(delta(social_signal_aggregator_event_badformat[5m]))) / (sum(delta(social_signal_aggregator_event_receive[5m]))+0.0001)",
       "legendFormat": "error rate "
      }
     ]
    },
    {
     "title": "Social Signal Throughput (RPS)",
     "type": "graph",
     "description": "Comparison between the #sent signals and #received signals",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(social_signal_aggregator_signal_sentout[5m]))",
       "legendFormat": "Sent out"
      },
      {
       "expr": "sum(rate(social_signal_aggregator_event_by_type[5m]))",
       "legendFormat": "Received"
      }
     ]
    }
   ]
  },
  {
   "title": "Common FileStore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Request  Stats",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filestore_get_request_overall_count[1m]))",
       "legendFormat": "Get"
      },
      {
       "expr": "sum(rate(filestore_get_request_local_hit_count[1m]))",
       "legendFormat": "Raw data from local"
      },
      {
       "expr": "sum(rate(filestore_get_request_neighbor_hit_count[1m]))",
       "legendFormat": "Raw data from neighbor"
      },
      {
       "expr": "sum(rate(filestore_get_request_miss_count[1m]))",
       "legendFormat": "Raw data from s3"
      }
     ]
    },
    {
     "title": "Get RPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filestore_get_request_overall_count[1m]) ",
       "legendFormat": "Get {{pod}}"
      }
     ]
    },
    {
     "title": "POST RPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(filestore_post_request_overall_count[1m]) ",
       "legendFormat": "Get {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Say Hi",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(SayHiOverall{target=~\"d/.*\"}) by (namespace)",
       "legendFormat": "Say Hi {{namespace}}"
      }
     ]
    },
    {
     "title": "Mention",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(MentionOverall{target=~\"d/.*\"}) by (namespace)",
       "legendFormat": "Mention {{namespace}}"
      }
     ]
    },
    {
     "title": "Messages Stats (# / minute)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(router_broker_message_total[1m]))",
       "legendFormat": "message_total"
      },
      {
       "expr": "sum(delta(router_broker_message_failure[1m]))",
       "legendFormat": "message_failure"
      },
      {
       "expr": "sum(delta(router_broker_message_retry[1m]))",
       "legendFormat": "message_retry"
      }
     ]
    },
    {
     "title": "Feedback Requests (# / minute)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(router_broker_feedback_request[1m]))",
       "legendFormat": "failure_requests_from_broker"
      },
      {
       "expr": "sum(delta(router_broker_report_request[1m]))",
       "legendFormat": "report_requests_to_broker"
      }
     ]
    },
    {
     "title": "User Actions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(subapi_request_action_submit)",
       "legendFormat": "#Like"
      },
      {
       "expr": "sum(subapi_request_action_cancel)",
       "legendFormat": "#Cancel Like"
      }
     ]
    }
   ]
  }
 ]
}