{
 "title": "P13N Reco Offline Training",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "country", "query": "in,id,sg,my,th" }
  ]
 },
 "panels": [
  {
   "title": "Masthead",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Masthead Training NDCG",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_masthead_tf_train_ndcg{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "Masthead Training MAP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_masthead_tf_train_map{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "Masthead Training AUC",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_masthead_tf_train_auc{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "Masthead Training Mean Score",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_masthead_tf_train_mean_score{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "Masthead Training Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_masthead_tf_train_training_time{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "masthead dataset sample number",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_masthead_tf_train_sample_num{country=\"$country\"}",
       "legendFormat": "{{country}}-{{sampler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TPFY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPFY Training AUC",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_tpfy_train_auc{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "TPFY Training NDCG",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_tpfy_train_ndcg{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "TPFY Training MAP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_tpfy_train_map{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Content Similarity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Content Similarity Evaluation Score",
     "type": "graph",
     "description": "evaluation score on test cases",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_content_similarity_train_train_eval_scores{country=\"$country\"}",
       "legendFormat": "train-{{country}}-{{variant_name}}-{{ctype}}-{{key}}"
      },
      {
       "expr": "p13n_reco_offline_content_similarity_pre_prediction_pre_prediction_eval_scores{country=\"$country\"}",
       "legendFormat": "pre_prediction-{{country}}-{{variant_name}}-{{ctype}}-{{key}}"
      }
     ]
    },
    {
     "title": "Content Similarity Guardrail Flag",
     "type": "graph",
     "description": "Guardrail flag status",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_content_similarity_train_train_guardrail_flag{country=\"$country\"}",
       "legendFormat": "train-{{country}}-{{variant_name}}-{{ctype}}"
      },
      {
       "expr": "p13n_reco_offline_content_similarity_pre_prediction_pre_prediction_guardrail_flag{country=\"$country\"}",
       "legendFormat": "pre_prediction-{{country}}-{{variant_name}}-{{ctype}}"
      }
     ]
    },
    {
     "title": "Content Similarity Training Metrics",
     "type": "graph",
     "description": "Training metrics",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_content_similarity_train_training_metrics{country=\"$country\"}",
       "legendFormat": "{{metric}}-{{country}}-{{variant_name}}-{{ctype}}-{{key}}"
      }
     ]
    },
    {
     "title": "Content Similarity Training Dataset",
     "type": "graph",
     "description": "Numbers around training dataset",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_content_similarity_train_dataset{country=\"$country\"}",
       "legendFormat": "{{variant_name}}-{{ctype}}-{{metrics_type}}-{{source}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ent Recall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "ent_recall Training recall@10",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_ent_recall_train_recall_10{country=\"$country\"}",
       "legendFormat": "{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "ent_recall Training recall@50",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_ent_recall_train_recall_50{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "ent_recall Training recall@100",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_ent_recall_train_recall_100{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    },
    {
     "title": "ent_recall Training avg rank",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "p13n_reco_offline_ent_recall_train_avg_rank{country=\"$country\"}",
       "legendFormat": "{{country}}-{{model}}-{{eval_name}}"
      }
     ]
    }
   ]
  }
 ]
}