{
 "title": "S3 File Operations Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace=\"video\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"video\", pod=\"$pod\", container!=\"POD\"}) by (container)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{ namespace=\"video\", pod=\"$pod\", container!=\"POD\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}} (RSS)"
    },
    {
     "expr": "sum by (container) (container_resources_memory_cache_bytes{container!=\"\",container!=\"POD\",namespace=\"video\",pod=\"$pod\"})",
     "legendFormat": "{{container}} (Cache)"
    },
    {
     "expr": "sum(container_memory_swap{ namespace=\"video\", pod=\"$pod\", container!=\"POD\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}} (Swap)"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"video\", pod=\"$pod\", container!=\"POD\"}, \"container\", \"$1\", \"container\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{ namespace=\"video\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"video\", pod=\"$pod\"}, \"container\", \"$1\", \"container\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{ namespace=\"video\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{ namespace=\"video\", pod=\"$pod\"}) by (container)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"video\", pod=\"$pod\", container!=\"POD\", container!=\"\"}, \"container\", \"$1\", \"container\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{ namespace=\"video\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"video\", pod=\"$pod\"}, \"container\", \"$1\", \"container\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"video\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{ namespace=\"video\", pod=\"$pod\", container!=\"\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{ namespace=\"video\", pod=\"$pod\", container!=\"\"}, \"container\", \"$1\", \"container\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}) by (container)"
    },
    {
     "expr": "sum(label_replace(container_memory_rss{namespace=\"video\", pod=\"$pod\", container != \"\", container != \"POD\"}, \"container\", \"$1\", \"container\", \"(.*)\")) by (container)"
    },
    {
     "expr": "sum by (container) (label_replace(container_resources_memory_cache_bytes{container!=\"\",container!=\"POD\",namespace=\"video\",pod=\"$pod\"}, \"container\", \"$1\", \"container\", \"(.*)\"))"
    },
    {
     "expr": "sum(label_replace(container_memory_swap{namespace=\"video\", pod=\"$pod\", container != \"\", container != \"POD\"}, \"container\", \"$1\", \"container\", \"(.*)\")) by (container)"
    }
   ]
  },
  {
   "title": "Request Latency  Per Endpoint",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(hes_s3_file_operations_http_handler_latency_sum{namespace=\"video\",job=\"hes-s3-file-operations\"}[1m])/rate(hes_s3_file_operations_http_handler_latency_count{namespace=\"video\",job=\"hes-s3-file-operations\"}[1m])) by (path)"
    }
   ]
  },
  {
   "title": "Request Per Minute",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hes_s3_file_operations_http_handler_latency_count{namespace=\"video\",job=\"hes-s3-file-operations\"}[1m])) by (path)"
    }
   ]
  },
  {
   "title": "Http Error Per Minute",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path, code) (rate(hes_s3_file_operations_http_status_code_total{code!=\"200\",job=\"hes-s3-file-operations\",namespace=\"video\"}[1m]))"
    }
   ]
  },
  {
   "title": "Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Time in Second" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(hes_s3_file_operations_http_handler_latency_bucket{namespace=\"video\",job=\"hes-s3-file-operations\"}[1m])) by (le))",
     "legendFormat": "99 Percentile Latency"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(hes_s3_file_operations_http_handler_latency_bucket{namespace=\"video\",job=\"hes-s3-file-operations\"}[1m])) by (le))",
     "legendFormat": "95 Percentile Latency"
    }
   ]
  }
 ]
}