{
 "title": "[Blaze] Campaign Manager Service",
 "tags": [
  "blaze",
  "migrated-to-last9"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "adtech-in-dev-aps1,adtech-in-pp-aps1,adtech-in-qa-aps1,adtech-in-prod-apse1"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods count",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{container=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}) by (container)"
      }
     ]
    },
    {
     "title": "Pods Avg RPM",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(sum(increase(http_server_requests_seconds_count{service=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}[1m])) by  (instance))"
      }
     ]
    },
    {
     "title": "Pod Avg Cpu",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"adtech-blaze-campaign-manager-service.*\"}[1m])/4)"
      }
     ]
    },
    {
     "title": "cpu usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"adtech-blaze-campaign-manager-service.*\", namespace=\"$namespace\"}[1m]) / sum(kube_pod_container_info{pod=~\"adtech-blaze-campaign-manager-service.*\", namespace=\"$namespace\"}))",
       "legendFormat": "avg cpu usage"
      },
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"adtech-blaze-campaign-manager-service.*\"}[1m]) / sum(kube_pod_container_info{pod=~\"adtech-blaze-campaign-manager-service.*\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC: pause cause",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(sum(increase(jvm_gc_pause_seconds_count{job=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}[1m])) by (instance, cause)) by (cause)",
       "legendFormat": "{{cause}}"
      }
     ]
    },
    {
     "title": "GC: pause time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(jvm_gc_pause_seconds_sum{job=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "avg gc pause"
      }
     ]
    },
    {
     "title": "Memory: heap usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg(sum(jvm_memory_used_bytes{job=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}) by (instance))",
       "legendFormat": "avg_memory"
      }
     ]
    },
    {
     "title": "Memory: usage by region",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(sum(jvm_memory_used_bytes{job=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}) by (instance, id)) by (id)",
       "legendFormat": "{{id}} avg usage"
      }
     ]
    },
    {
     "title": "load average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(system_load_average_1m{service=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}[1m])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg(avg_over_time(system_load_average_1m{service=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "avg cpu load"
      }
     ]
    },
    {
     "title": "Cloud Watch: request count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_alb_tg_request_count_sum and on (name) aws_alb_info{tag_Name=\"AdTechBlazeCampaignManagerService\"})",
       "legendFormat": "total request"
      }
     ]
    },
    {
     "title": "Cloud Watch: response time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(aws_alb_target_response_time_average and on (name) aws_alb_info{tag_Name=\"AdTechBlazeCampaignManagerService\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "Cloud Watch: 5XX & 4XX",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_alb_httpcode_elb_5_xx_count_sum and on (name) aws_alb_info{tag_Name=\"AdTechBlazeCampaignManagerService\"})",
       "legendFormat": "alb_5XX"
      },
      {
       "expr": "sum(aws_alb_httpcode_target_5_xx_count_sum and on (name) aws_alb_info{tag_Name=\"AdTechBlazeCampaignManagerService\"})",
       "legendFormat": "backend_5XX"
      },
      {
       "expr": "sum(aws_alb_httpcode_target_4_xx_count_sum and on (name) aws_alb_info{tag_Name=\"AdTechBlazeCampaignManagerService\"})",
       "legendFormat": "backend_4XX"
      }
     ]
    },
    {
     "title": "request count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{service=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}[1m])) by (uri)",
       "legendFormat": "{{uri}}"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{service=\"adtech-blaze-campaign-manager-service\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{service=\"adtech-blaze-campaign-manager-service\", namespace=\"adtech-in-prod-apse1\"}[1m])) by (le, uri))",
       "legendFormat": "P99-{{uri}}"
      }
     ]
    }
   ]
  }
 ]
}