{
 "title": "Pre Launch",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(source_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Pre Launch - Login by Phone OTP",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(um_rest_counter_pre_launch_login_by_phone_otp_api_seconds_bucket{source_cluster=~'$Cluster'}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(um_rest_counter_pre_launch_login_by_phone_otp_api_seconds_bucket{source_cluster=~'$Cluster'}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(um_rest_counter_pre_launch_login_by_phone_otp_api_seconds_bucket{source_cluster=~'$Cluster'}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "sum(delta(um_rest_counter_pre_launch_login_by_phone_otp_api_seconds_count{source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "throughput"
    }
   ]
  },
  {
   "title": "Pre Launch - Login by Phone OTP  response codes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(delta(um_rest_counter_pre_launch_login_by_phone_otp_api_seconds_count{source_cluster=~'$Cluster'}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pre Launch - Login by Phone IVR response codes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(delta(um_rest_counter_login_by_phone_ivr_api_seconds_count{source_cluster=~'$Cluster'}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pre Launch - Login by IVR OTP",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(um_rest_counter_login_by_phone_ivr_api_seconds_bucket{source_cluster=~'$Cluster'}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(um_rest_counter_login_by_phone_ivr_api_seconds_bucket{source_cluster=~'$Cluster'}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(um_rest_counter_login_by_phone_ivr_api_seconds_bucket{source_cluster=~'$Cluster'}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "sum(delta(um_rest_counter_login_by_phone_ivr_api_seconds_count{source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "throughput"
    }
   ]
  },
  {
   "title": "Binders error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(page_comp_binder_error_total{id=~\"Prelaunch.*\",service=~\"hs-core-page-compositor-prod-mena\"}[1m]))",
     "legendFormat": "Prelaunch errors"
    },
    {
     "expr": "sum(increase(page_comp_binder_error_total{id=~\"PreRegistration.*\",service=~\"hs-core-page-compositor-prod-mena\"}[1m]))",
     "legendFormat": "PreRegistration errors"
    }
   ]
  }
 ]
}