{
 "title": "DP Cruise CDC Jobs",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": "in,my" },
   {
    "name": "cdc_type",
    "query": "hspay_subscriptions,hspay_payments,hspay_coupon"
   },
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {
     "query": "label_values(cruise_cdc_job.allJobs, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "P0 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Absolute Consumer Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-${region}_${cdc_type}.*\",group!=\"delta_cdc-in_hspay_subscriptions_subscriptions_s3_kafka_key\"})by(group,topic)",
       "legendFormat": "{{group}}-{{topic}}"
      }
     ]
    },
    {
     "title": "Max Time Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "m" }
     ],
     "targets": [
      {
       "expr": "((time() * 1000) - avg(dp.cruise.cdc.event_high_water_mark{application=\"cruise_cdc\",table_name=~\"${region}_${cdc_type}.*\"}) by (table_name)) / 60000",
       "legendFormat": "{{table_name}}"
      }
     ]
    },
    {
     "title": "Cluster CPU Usage - P50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(cpu_usage_user_050{application=\"cruise_cdc\",cpu=\"cpu-total\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'})by(application, env, cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Host CPU Usage - P50",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_user_050{application=\"cruise_cdc\",cpu=\"cpu-total\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'}",
       "legendFormat": "{{cluster_name}}-{{host}}"
      }
     ]
    },
    {
     "title": "Cluster CPU Usage - P90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(cpu_usage_user_090{application=\"cruise_cdc\",cpu=\"cpu-total\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'})by(application, env, cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Host CPU Usage - P90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_user_090{application=\"cruise_cdc\",cpu=\"cpu-total\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'}",
       "legendFormat": "{{cluster_name}}-{{host}}"
      }
     ]
    },
    {
     "title": "Cluster Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(mem_used_percent{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'})by(application, cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Host Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "mem_used_percent{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'}",
       "legendFormat": "{{cluster_name}}-{{host}}"
      }
     ]
    },
    {
     "title": "Num of Executors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cruise_cdc_executors.numberAllExecutors{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'})by(application, env, cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "P1 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of Records Written",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cruise_cdc_recordsWritten.count{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Spark Failed Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cruise_cdc_tasks.failedTasks.count{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Spark Succeeded Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cruise_cdc_succeededTasks.count{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Spark Killed Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cruise_cdc_tasks.killedTasks.count{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name'}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Driver Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(cpu_usage_user_050{application=\"cruise_cdc\",cpu=\"cpu-total\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name',host_type='Driver'}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}-P50"
      },
      {
       "expr": "avg(cpu_usage_user_090{application=\"cruise_cdc\",cpu=\"cpu-total\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name',host_type='Driver'}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}-P90"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(mem_used_percent{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name', host_type=\"Driver\"}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(disk_used_percent{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name', host_type=\"Driver\"}) by (application,cluster_name,path)",
       "legendFormat": "{{cluster_name}}-{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(cpu_usage_user_050{application=\"cruise_cdc\",cpu=\"cpu-total\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name',host_type='Executor'}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}-P50"
      },
      {
       "expr": "avg(cpu_usage_user_090{application=\"cruise_cdc\",cpu=\"cpu-total\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name',host_type='Executor'}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}-P90"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(mem_used_percent{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name', host_type=\"Executor\"}) by (application,cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(disk_used_percent{application=\"cruise_cdc\",region=~'$region',cdc_type=~'$cdc_type',cluster_name=~'$cluster_name', host_type=\"Executor\"}) by (application,cluster_name,path)",
       "legendFormat": "{{cluster_name}}-{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Row Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dp.cruise.cdc.event_input_count{application=\"cruise_cdc\",table_name=~\"${region}_${cdc_type}.*\"}) by (application,table_name)",
       "legendFormat": "Input count - {{table_name}}"
      }
     ]
    },
    {
     "title": "Batch Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(dp.cruise.cdc.event_batch_duration{application=\"cruise_cdc\",table_name=~\"${region}_${cdc_type}.*\"}) by (application,table_name)",
       "legendFormat": "Batch duration - {{table_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CDC HSPAY Jobs Consumer Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Absolute Consumer Lag - HSPAY Subscriptions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-in_hspay_subscriptions_apple_partner_subscriptions_s3|delta_cdc-in_hspay_subscriptions_bsnl_partner_subscriptions_s3|delta_cdc-in_hspay_subscriptions_pack_specific_coupons_s3|delta_cdc-in_hspay_subscriptions_invoice_s3|delta_cdc-in_hspay_subscriptions_jio_partner_subscriptions_s3|delta_cdc-in_hspay_subscriptions_subscription_instruments_s3|delta_cdc-in_hspay_subscriptions_subscription_params_s3|delta_cdc-in_hspay_subscriptions_partner_subscriptions_s3|delta_cdc-in_hspay_subscriptions_billing_attempts_s3|\"})by(group,topic)",
       "legendFormat": "{{group}}"
      },
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-in_hspay_subscriptions_discounts_s3|delta_cdc-in_hspay_subscriptions_payments_s3|delta_cdc-in_hspay_subscriptions_tax_details_s3|delta_cdc-in_hspay_subscriptions_orders_meta_s3|delta_cdc-in_hspay_subscriptions_refund_orders_s3|delta_cdc-in_hspay_subscriptions_coupons_s3|delta_cdc-in_hspay_subscriptions_pricing_plans_s3|delta_cdc-in_hspay_subscriptions_cancel_orders_s3|delta_cdc-in_hspay_subscriptions_grandfathering_renewal_mapping_s3\"})by(group,topic)",
       "legendFormat": "{{group}}"
      },
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-in_hspay_subscriptions_subscription_logs_s3|delta_cdc-in_hspay_subscriptions_oms_orders_s3|delta_cdc-in_hspay_subscriptions_order_items_s3|delta_cdc-in_hspay_subscriptions_orders_s3|delta_cdc-in_hspay_subscriptions_subscription_types_s3|delta_cdc-in_hspay_subscriptions_renew_subscription_s3|delta_cdc-in_hspay_subscriptions_switch_transitions_s3|delta_cdc-in_hspay_subscriptions_tata_sky_partner_subscriptions_s3|delta_cdc-in_hspay_subscriptions_deferred_subscriptions_s3|delta_cdc-in_hspay_subscriptions_oms_refund_orders_s3|delta_cdc-in_hspay_subscriptions_coupons_meta_s3|delta_cdc-in_hspay_subscriptions_move_subscription_log_s3|delta_cdc-in_hspay_subscriptions_subscription_types_s3|\"})by(group,topic)\n",
       "legendFormat": "{{group}}"
      },
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-in_hspay_subscriptions_subscriptions_s3\"})by(group,topic)",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Absolute Consumer Lag - HSPAY Coupons",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-in_hspay_coupon_offers_s3|delta_cdc-in_hspay_coupon_offers_meta_s3|delta_cdc-in_hspay_coupon_offers_usage_s3|delta_cdc-in_hspay_coupon_child_coupon_s3\"})by(group,topic)",
       "legendFormat": "{{group}}"
      },
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-in_hspay_coupon_orders_s3\"})by(group,topic)",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Absolute Consumer Lag - HSPAY Payments",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-in_hspay_payments_paytm_instruments_s3|delta_cdc-in_hspay_payments_payu_charges_s3|delta_cdc-in_hspay_payments_payu_customers_s3|delta_cdc-in_hspay_payments_payu_instruments_s3|delta_cdc-in_hspay_payments_razorpay_charges_s3\"})by(group,topic)",
       "legendFormat": "{{group}}"
      },
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-in_hspay_payments_adyen_charges_s3|delta_cdc-in_hspay_payments_instruments_s3|delta_cdc-in_hspay_payments_adyen_instruments_s3|delta_cdc-in_hspay_payments_customers_s3|delta_cdc-in_hspay_payments_refunds_s3|delta_cdc-in_hspay_payments_phonepe_instruments_s3|delta_cdc-in_hspay_payments_razorpay_instruments_s3|delta_cdc-in_hspay_payments_phonepe_charges_s3|delta_cdc-in_hspay_payments_charges_meta_s3\"})by(group,topic)",
       "legendFormat": "{{group}}"
      },
      {
       "expr": "sum(burrow_partition_lag{group=~\"delta_cdc-in_hspay_payments_charges_s3|delta_cdc-in_hspay_payments_adyen_refunds_s3|delta_cdc-in_hspay_payments_customer_instruments_s3|delta_cdc-in_hspay_payments_billdesk_charges_s3|delta_cdc-in_hspay_payments_billdesk_customers_s3|delta_cdc-in_hspay_payments_paytm_charges_s3\"})by(group,topic)",
       "legendFormat": "{{group}}"
      }
     ]
    }
   ]
  }
 ]
}