{
 "title": "CMS CDC Connectors",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Task Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": " Source Task Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_connector",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "connector_task_metrics",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "connector", "operator": "=", "value": "cms.prod.p13n.za" }
     ]
    },
    {
     "alias": "$tag_connector",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "connector-task-metrics",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "connector", "operator": "=", "value": "cms.prod_mena.p13n.za" }
     ]
    }
   ]
  },
  {
   "title": " Sink Task Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_connector",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "connector_task_metrics",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "connector", "operator": "=", "value": "cms.prod.p13n.za" }
     ]
    },
    {
     "alias": "$tag_connector",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "connector-task-metrics",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "connector", "operator": "=", "value": "cms.prod_mena.p13n.za" }
     ]
    }
   ]
  },
  {
   "title": " Source Poll Batch Avg Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_connector",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "connector-task-metrics",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "connector", "operator": "=", "value": "s3" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "source-task-metrics",
     "select": [
      [
       { "params": [ "poll-batch-avg-time-ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "cms-connect" }
     ]
    }
   ]
  },
  {
   "title": " Sink Put Batch Avg Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_connector",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sink-task-metrics",
     "select": [
      [
       { "params": [ "sink-record-active-count-avg" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "cms-connect" }
     ]
    }
   ]
  },
  {
   "title": " Sink Put Batch Avg Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_connector",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sink-task-metrics",
     "select": [
      [
       { "params": [ "put-batch-avg-time-ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "cms-connect" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "source-task-metrics",
     "select": [
      [
       { "params": [ "poll-batch-avg-time-ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "cms-connect" }
     ]
    }
   ]
  },
  {
   "title": " Source Record Active Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "connector" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "source-task-metrics",
     "select": [
      [
       { "params": [ "source-record-active-count-avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "cms-connect" }
     ]
    }
   ]
  },
  {
   "title": "System metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": " Cpu usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"usage_user\") AS \"usage_user\" FROM \"cpu\" WHERE (\"application\" = 'cdc-connect') AND $timeFilter GROUP BY time($__interval), \"application\"",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=", "value": "cdc-connect" }
       ]
      }
     ]
    },
    {
     "title": " Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"usage_user\") AS \"usage_user\" FROM \"cpu\" WHERE (\"application\" = 'cdc-connect') AND $timeFilter GROUP BY time($__interval), \"application\"",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=", "value": "cdc-connect" }
       ]
      }
     ]
    },
    {
     "title": " Network IO rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"bytes_recv\"), 1s) AS \"bytes_recv\", derivative(max(\"bytes_sent\"), 1s) AS \"bytes_sent\" FROM \"net\" WHERE (\"application\" = 'cdc-connect') AND $timeFilter GROUP BY time(10s), \"application\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Root volume usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "disk",
       "query": "SELECT mean(\"usage_user\") AS \"usage_user\" FROM \"cpu\" WHERE (\"application\" = 'cdc-connect') AND $timeFilter GROUP BY time($__interval), \"application\"",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=", "value": "cdc-connect" },
        { "condition": "AND", "key": "device", "operator": "=", "value": "xvda1" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": " Garbage Collection Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "application" ], "type": "tag" }
       ],
       "measurement": "GarbageCollector",
       "select": [
        [
         { "params": [ "LastGcInfo_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=", "value": "cdc-connect" }
       ]
      }
     ]
    },
    {
     "title": " Heap usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "HeapMemoryUsage",
       "select": [
        [
         { "params": [ "HeapMemoryUsage_used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=", "value": "cdc-connect" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "HeapMemoryUsage",
       "select": [
        [
         { "params": [ "HeapMemoryUsage_max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=", "value": "cdc-connect" }
       ]
      }
     ]
    },
    {
     "title": " Thread Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ThreadCount",
       "groupBy": [
        { "params": [ "application" ], "type": "tag" }
       ],
       "measurement": "ThreadCount",
       "select": [
        [
         { "params": [ "ThreadCount" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=", "value": "cdc-connect" }
       ]
      }
     ]
    }
   ]
  }
 ]
}