{
 "title": "Launch Darkly Relay Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SOURCE_CLUSTER",
    "label": "SOURCE_CLUSTER",
    "query": {
     "query": "label_values(kube_namespace_created, source_cluster)"
    }
   },
   {
    "name": "NAMESPACE",
    "label": "NAMESPACE",
    "query": "growth,growth-pp,growth-qa,growth-dev"
   },
   {
    "name": "TABLE_NAME",
    "label": "TABLE_NAME",
    "query": {
     "query": "label_values(amazonaws_com_AWS_DynamoDB_ConsumedReadCapacityUnits_sum,TableName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LD Dynamo DB metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read capacity units consumed per period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_ConsumedReadCapacityUnits_sum{TableName=\"$TABLE_NAME\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write capacity units consumed per period(india)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_ConsumedWriteCapacityUnits_sum{TableName=\"$TABLE_NAME\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisioned Write Capacity Units(india)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_ProvisionedWriteCapacityUnits_sum{TableName=\"$TABLE_NAME\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provisioned Read Capacity Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_ProvisionedReadCapacityUnits_sum{TableName=\"$TABLE_NAME\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Throttle Events(india)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_ReadThrottleEvents_sum{TableName=\"growth-launch-darkly-dynamodb-prod-ap-southeast-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Throttle Events(Mena)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_ReadThrottleEvents_sum{TableName=\"growth-launch-darkly-dynamodb-mena-prod-eu-west-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Throttle Events(Mena)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_WriteThrottleEvents_sum{TableName=\"growth-launch-darkly-dynamodb-mena-prod-eu-west-1\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Throttle Events(India)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_WriteThrottleEvents_sum{TableName=\"growth-launch-darkly-dynamodb-prod-ap-southeast-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Returned Item Count(India)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_ReturnedItemCount_sum{TableName=\"growth-launch-darkly-dynamodb-prod-ap-southeast-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Returned Item Count(Mena)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_ReturnedItemCount_sum{TableName=\"growth-launch-darkly-dynamodb-mena-prod-eu-west-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Request Latency (ms)(India)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(amazonaws_com_AWS_DynamoDB_SuccessfulRequestLatency_sum{TableName=\"growth-launch-darkly-dynamodb-prod-ap-southeast-1\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Request Latency (ms)(Mena)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(amazonaws_com_AWS_DynamoDB_SuccessfulRequestLatency_sum{TableName=\"growth-launch-darkly-dynamodb-mena-prod-eu-west-1\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Errors (HTTP 500)(India)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_SystemErrors_sum{TableName=\"growth-launch-darkly-dynamodb-prod-ap-southeast-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Errors (HTTP 500)(Mena)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_SystemErrors_sum{TableName=\"growth-launch-darkly-dynamodb-mena-prod-eu-west-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Capacity Utilization (%)(mena)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "(\n  rate(amazonaws_com_AWS_DynamoDB_ConsumedWriteCapacityUnits_sum{TableName=\"growth-launch-darkly-dynamodb-mena-prod-eu-west-1\"}[5m])\n  / on(TableName)\n  amazonaws_com_AWS_DynamoDB_ProvisionedWriteCapacityUnits_sum{TableName=\"growth-launch-darkly-dynamodb-mena-prod-eu-west-1\"}\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Capacity Utilization (%)(mena)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "(\n  rate(amazonaws_com_AWS_DynamoDB_ConsumedWriteCapacityUnits_sum{TableName=\"growth-launch-darkly-dynamodb-prod-ap-southeast-1\"}[5m])\n  / on(TableName)\n  amazonaws_com_AWS_DynamoDB_ProvisionedWriteCapacityUnits_sum{TableName=\"growth-launch-darkly-dynamodb-prod-ap-southeast-1\"}\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throttle Rate (% of consumed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "(\n  rate(amazonaws_com_AWS_DynamoDB_WriteThrottleEvents_sum{TableName=\"$TABLE_NAME\"}[5m])\n  / on(TableName)\n  amazonaws_com_AWS_DynamoDB_ConsumedWriteCapacityUnits_sum{TableName=\"$TABLE_NAME\"}\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Capacity Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "(\n  rate(amazonaws_com_AWS_DynamoDB_ConsumedReadCapacityUnits_sum{TableName=\"$TABLE_NAME\"}[5m])\n  / on(TableName)\n  amazonaws_com_AWS_DynamoDB_ProvisionedReadCapacityUnits_sum{TableName=\"$TABLE_NAME\"}\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Errors (HTTP 400)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "amazonaws_com_AWS_DynamoDB_UserErrors_sum{TableName=\"$TABLE_NAME\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Infra metrics - Old DC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total pods",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pods" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{source_cluster=\"$SOURCE_CLUSTER\", namespace=\"$NAMESPACE\", container=\"launch-darkly-relay\"})",
       "legendFormat": "Old Cluster"
      }
     ]
    },
    {
     "title": "Total cores allocated to Relay",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 5, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{source_cluster=\"$SOURCE_CLUSTER\", namespace=\"$NAMESPACE\", container=\"launch-darkly-relay\"})",
       "legendFormat": "Old Cluster"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "stat",
     "gridPos": { "h": 10, "w": 7, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"launch-darkly-relay\",source_cluster=\"$SOURCE_CLUSTER\",namespace=\"$NAMESPACE\"}[1m])) / count(rate(container_cpu_usage_seconds_total{container=\"launch-darkly-relay\",source_cluster=\"$SOURCE_CLUSTER\",namespace=\"$NAMESPACE\"}[1m]))",
       "legendFormat": "Old Cluster"
      }
     ]
    },
    {
     "title": "Service Memory Usage",
     "type": "stat",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container=\"launch-darkly-relay\",namespace=\"$NAMESPACE\", source_cluster=\"$SOURCE_CLUSTER\"}) / avg(kube_pod_container_resource_requests_memory_bytes{container=\"launch-darkly-relay\",namespace=\"$NAMESPACE\", source_cluster=\"$SOURCE_CLUSTER\"})",
       "legendFormat": "Old Cluster Memory usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra metrics - New DC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total pods",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pods" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{source_cluster=\"$SOURCE_CLUSTER\", namespace=\"$NAMESPACE\", container=\"main\", pod=~\"launch-darkly-relay-service.*\"})"
      }
     ]
    },
    {
     "title": "Total cores allocated to Relay",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{source_cluster=\"$SOURCE_CLUSTER\", namespace=\"$NAMESPACE\", container=\"main\", pod=~\"launch-darkly-relay-service.*\"})",
       "legendFormat": "New Cluster"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "stat",
     "gridPos": { "h": 10, "w": 7, "x": 10, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"main\" , pod=~\"launch-darkly-relay-service.*\",source_cluster=\"$SOURCE_CLUSTER\",namespace=\"$NAMESPACE\"}[1m])) / count(rate(container_cpu_usage_seconds_total{container=\"main\" , pod=~\"launch-darkly-relay-service.*\",source_cluster=\"$SOURCE_CLUSTER\",namespace=\"$NAMESPACE\"}[1m]))",
       "legendFormat": "New Cluster"
      }
     ]
    },
    {
     "title": "Service Memory Usage",
     "type": "stat",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{container = \"main\", pod=~\"launch-darkly-relay-service.*\",namespace=\"$NAMESPACE\", source_cluster=\"$SOURCE_CLUSTER\"}) / avg(kube_pod_container_resource_requests_memory_bytes{container = \"main\", pod=~\"launch-darkly-relay-service.*\",namespace=\"$NAMESPACE\", source_cluster=\"$SOURCE_CLUSTER\"})",
       "legendFormat": "New Cluster Memory usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total connections to Relay from services",
     "type": "stat",
     "gridPos": { "h": 13, "w": 5, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "conns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ld_relay_metrics_connections_total{namespace=\"$NAMESPACE\", source_cluster=\"$SOURCE_CLUSTER\"}[1m])",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Total connections to Relay from services by project",
     "type": "graph",
     "gridPos": { "h": 13, "w": 19, "x": 5, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(ld_relay_metrics_connections_total{source_cluster=\"$SOURCE_CLUSTER\", namespace=\"$NAMESPACE\"}[1m]) by (env)",
       "legendFormat": "{{env}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "New connections to Relay from services",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum by (env, platformCategory) (delta(ld_relay_metrics_newconnections_total{namespace=\"$NAMESPACE\",source_cluster=\"$SOURCE_CLUSTER\"}[1m]))",
       "legendFormat": "{{env}} / {{platformCategory}}-side integration"
      }
     ]
    }
   ]
  },
  {
   "title": "Request to Relay metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total throughput from services",
     "type": "graph",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ld_relay_metrics_requests_total{namespace=\"$NAMESPACE\",source_cluster=\"$SOURCE_CLUSTER\"}[1m])) * 100",
       "legendFormat": "throughput"
      }
     ]
    },
    {
     "title": "/all API throughput from services by project",
     "type": "graph",
     "gridPos": { "h": 11, "w": 17, "x": 7, "y": 12 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum by (env, route) (rate(ld_relay_metrics_requests_total{namespace=\"$NAMESPACE\",source_cluster=\"$SOURCE_CLUSTER\"}[1m]) * 100)",
       "legendFormat": "{{env}} - API path /{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts - Old DC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total connections per pod - APSE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(ld_relay_metrics_connections_total{namespace=\"growth\", source_cluster=\"prod-apse1.k8s.hotstar-labs.com\"}[1m])/sum(kube_pod_container_status_ready{source_cluster=\"prod-apse1.k8s.hotstar-labs.com\", namespace=\"growth\", container=\"launch-darkly-relay\"}[1m])",
       "legendFormat": "Avg connections per pod"
      }
     ]
    },
    {
     "title": "Total connections per pod - MENA",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(ld_relay_metrics_connections_total{namespace=\"growth\", source_cluster=\"hs-eks-prod-api-euw1\"}[1m])/sum(kube_pod_container_status_ready{source_cluster=\"hs-eks-prod-api-euw1\", namespace=\"growth\", container=\"launch-darkly-relay\"}[1m])",
       "legendFormat": "Avg connections per pod"
      }
     ]
    },
    {
     "title": "Total connections per pod - USE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(ld_relay_metrics_connections_total{namespace=\"growth\", source_cluster=\"prod-use1.k8s.hotstar-labs.com\"}[1m])/sum(kube_pod_container_status_ready{source_cluster=\"prod-use1.k8s.hotstar-labs.com\", namespace=\"growth\", container=\"launch-darkly-relay\"}[1m])",
       "legendFormat": "Avg connections per pod"
      }
     ]
    },
    {
     "title": "Total connections per pod - EUW1",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(ld_relay_metrics_connections_total{namespace=\"growth\", source_cluster=\"prod-euw1.eu.hotstar-labs.com\"}[1m])/sum(kube_pod_container_status_ready{source_cluster=\"prod-euw1.eu.hotstar-labs.com\", namespace=\"growth\", container=\"launch-darkly-relay\"}[1m])",
       "legendFormat": "Avg connections per pod"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts - New DC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total connections per pod - APSE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(ld_relay_metrics_connections_total{namespace=\"growth\" , source_cluster=\"hs-eks-prod-api-apse1\" }[1m])/sum(kube_pod_container_status_ready{namespace=\"growth\", source_cluster=\"hs-eks-prod-api-apse1\", container=\"main\", pod=~\"launch-darkly-relay-service.*\"}[1m])",
       "legendFormat": "Avg connections per pod"
      }
     ]
    },
    {
     "title": "Total connections per pod - MENA",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(ld_relay_metrics_connections_total{namespace=\"growth\", source_cluster=\"hs-eks-prod-api-euw1\" }[1m])/sum(kube_pod_container_status_ready{namespace=\"growth\", source_cluster=\"hs-eks-prod-api-euw1\", container=\"main\", pod=~\"launch-darkly-relay-service.*\"}[1m])",
       "legendFormat": "Avg connections per pod"
      }
     ]
    }
   ]
  }
 ]
}