{
 "title": "SecEng - Embargo Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_cluster",
    "label": "source_cluster",
    "query": {
     "query": "label_values(embargo_request_count, source_cluster)"
    }
   },
   {
    "name": "ingress",
    "label": "ingress",
    "query": "seceng-entity-embargo-service-prod3-ingress, seceng-entity-embargo-service-prodme-ingress"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "seceng-entity-embargo-service.*"
   },
   {
    "name": "container",
    "label": "container",
    "query": "seceng-entity-embargo-service-prod3, seceng-entity-embargo-service-prodme"
   },
   { "name": "namespace", "label": "namespace", "query": "seceng" },
   {
    "name": "dimension_CacheClusterId",
    "label": "dimension_CacheClusterId",
    "query": "seceng-embargo-prod3.*, seceng-embargo-prodme.*"
   }
  ]
 },
 "panels": [
  {
   "title": "API Level Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (increase(embargo_request_count_total{namespace=\"$namespace\",source_cluster=~\"$source_cluster\"}[1m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Avg POD CPU Utilization ",
   "type": "stat",
   "description": "curr/ total cpu",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((100*sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\",source_cluster=~\"$source_cluster\",namespace=\"$namespace\"}[1m])) by (pod)) / avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\",source_cluster=~\"$source_cluster\",namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "avg cpu"
    }
   ]
  },
  {
   "title": "Avg POD  Memory Usage ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(container_memory_working_set_bytes{container=\"$container\",source_cluster=~\"$source_cluster\"}[1m]) by (pod))",
     "legendFormat": "Avg Pod memory"
    }
   ]
  },
  {
   "title": "Embargo Service Response Time - API Level (ms)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*(avg(histogram_quantile(0.5, sum by (le, exported_endpoint)(delta(embargo_request_duration_bucket{source_cluster=~\"$source_cluster\",namespace=\"$namespace\"}[1m])))))",
     "legendFormat": "P50"
    },
    {
     "expr": "1000*avg(histogram_quantile(0.9, sum by (le, exported_endpoint) (delta(embargo_request_duration_bucket{source_cluster=~\"$source_cluster\",namespace=\"$namespace\"}[1m]))))",
     "legendFormat": "P90"
    },
    {
     "expr": "1000*avg(histogram_quantile(0.99, sum by (le, exported_endpoint) (delta(embargo_request_duration_bucket{source_cluster=~\"$source_cluster\",namespace=\"$namespace\"}[1m]))))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Backend Success Rate",
   "type": "gauge",
   "description": "(Current RPM -  Redis failures - Middleware timeouts) / Current RPM",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 * sum(increase(embargo_request_count_total{source_cluster=~\"$source_cluster\"}[1m])) - sum(increase(embargo_cache_failures_total{source_cluster=~\"$source_cluster\"}[1m]))) / sum(increase(embargo_request_count_total{source_cluster=~\"$source_cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "POD count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=~\"$pod\", source_cluster=~\"$source_cluster\", namespace=\"$namespace\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "Redis Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Engine CPU Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ec_engine_cpuutilization_average{dimension_CacheClusterId=~\"$dimension_CacheClusterId\",source_cluster=~\"$source_cluster\"}",
     "legendFormat": "cpu {{ dimension_CacheClusterId }}"
    },
    {
     "expr": "avg(aws_ec_engine_cpuutilization_average{dimension_CacheClusterId=~\"$dimension_CacheClusterId\",source_cluster=~\"$source_cluster\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Free-able Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(aws_ec_freeable_memory_average{dimension_CacheClusterId=~\"$dimension_CacheClusterId\",source_cluster=~\"$source_cluster\"}) by (dimension_CacheClusterId)",
     "legendFormat": "{{ dimension_CacheClusterId }} "
    },
    {
     "expr": "avg(aws_ec_freeable_memory_average{dimension_CacheClusterId=~\"$dimension_CacheClusterId\",source_cluster=~\"$source_cluster\"})",
     "legendFormat": "Avg"
    },
    { "expr": "1000000000", "legendFormat": "Alert" }
   ]
  },
  {
   "title": "Redis Response Time (P99)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(embargo_cache_request_time_bucket{source_cluster=~\"$source_cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Redis Response Time (P90)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(embargo_cache_request_time_bucket{source_cluster=~\"$source_cluster\", namespace=\"$namespace\"}[1m])) by (le))\n\n",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Redis Response Time (P50)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(embargo_cache_request_time_bucket{source_cluster=~\"$source_cluster\", namespace=\"$namespace\"}[1m])) by (le))\n",
     "legendFormat": "{{cdn}} P50"
    }
   ]
  },
  {
   "title": "Redis Lock Acquired",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 1, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(embargo_cache_lock_total{namespace=\"$namespace\",source_cluster=\"$source_cluster\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Redis Failures",
   "type": "timeseries",
   "description": "Redis Failures",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(embargo_cache_failures_total{namespace=\"$namespace\",source_cluster=~\"$source_cluster\"}[1m]))",
     "legendFormat": "Embargo Redis failures"
    }
   ]
  },
  {
   "title": "Connections per Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aws_ec_curr_connections_average{dimension_CacheClusterId=~\"$dimension_CacheClusterId\",source_cluster=~\"$source_cluster\"}) by (dimension_CacheClusterId)",
     "legendFormat": "{{ dimension_CacheClusterId }} "
    },
    {
     "expr": "avg(aws_ec_curr_connections_average{dimension_CacheClusterId=~\"$dimension_CacheClusterId\",source_cluster=~\"$source_cluster\"}) ",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Resource Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"$pod\",source_cluster=~\"$source_cluster\", namespace=\"$namespace\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage per pod {%}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(100*sum(rate(container_cpu_usage_seconds_total{name=~\"^k8s_.*\",pod=~\"$pod\",source_cluster=~\"$source_cluster\", namespace=\"$namespace\"}[1m])) by (pod)) / avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\",source_cluster=~\"$source_cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg((100*sum(rate(container_cpu_usage_seconds_total{name=~\"^k8s_.*\",pod=~\"$pod\",source_cluster=~\"$source_cluster\", namespace=\"$namespace\"}[1m])) by (pod)) / avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\",source_cluster=~\"$source_cluster\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Memory Usage per POD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name=~\"^k8s_.*\",container=\"$container\",source_cluster=~\"$source_cluster\"}[1m]) by (pod) ",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{name=~\"^k8s_.*\",container=\"$container\",source_cluster=~\"$source_cluster\"}[1m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Business Metrics (RPM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true
  },
  {
   "title": "API Response Code  ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint, status) (increase(embargo_request_count_total{namespace=\"$namespace\",source_cluster=~\"$source_cluster\"}[1m]))",
     "legendFormat": "{{exported_endpoint}} {{status}}"
    },
    {
     "expr": "sum by (pod) (increase(embargo_request_count_total{exported_endpoint=\"/fnf\",namespace=\"$namespace\",source_cluster=~\"$source_cluster\",status=\"400\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Consumer count",
   "type": "timeseries",
   "description": "Total number of received enforce messages",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (updateType, status) (increase(embargo_service_kafka_consume_count_total{namespace=\"$namespace\",source_cluster=~\"$source_cluster\"}[1m]))",
     "legendFormat": "{{updateType}} {{status}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Kafka Producer count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (topic, status) (increase(embargo_service_kafka_produce_count_total{namespace=\"$namespace\",source_cluster=~\"$source_cluster\"}[1m]))",
     "legendFormat": "{{topic}} {{status}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Invalid API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(embargo_invalid_api_request_count{source_cluster=\"$source_cluster\", namespace=\"$namespace\"}[1m])) by (exported_endpoint)",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Invalid REX Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(embargo_invalid_rex_request_count{source_cluster=\"$source_cluster\", namespace=\"$namespace\"}[1m])) by (updateType)",
     "legendFormat": "{{updateType}}"
    }
   ]
  },
  {
   "title": "Expiry Cron Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(embargo_expiry_cron_count_total{namespace=\"$namespace\",source_cluster=\"$source_cluster\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Application Quality Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true
  },
  {
   "title": "API Level Response Time (P99)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_endpoint) (delta(embargo_request_duration_bucket{source_cluster=~\"$source_cluster\",namespace=\"$namespace\"}[1m])))",
     "legendFormat": "P99 {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Service Unavailability (5XX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_alb_httpcode_elb_5_xx_count_sum{source_cluster=~\"$source_cluster\"})",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Message Marshalling Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(embargo_serialization_failures{source_cluster=~\"$source_cluster\", namespace=\"$namespace\"}[1m])) by (conversionType)",
     "legendFormat": "{{conversionType}}"
    }
   ]
  }
 ]
}