{
 "title": "HES-Stream-Store",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "method", "query": "GET,POST" },
   {
    "name": "path",
    "query": "/stream-store/api/v1/packaged-artifacts,/stream-store/api/v1/encoded-artifacts,/stream-store/api/v1/playback-urls,/stream-store/api/v1/drm-key,/stream-store/api/v1/packaging-metadata,/stream-store/api/v1/manifest-storage,/stream-store/api/v1/content-config"
   },
   {
    "name": "collection",
    "query": "content_config_store,manifest_storage,packaging_metadata,drm_keys,packaged_artifacts,playback_urls,encoded_artifacts"
   },
   {
    "name": "db_query_type",
    "query": "Count,CreateOne,Create,Find,FindOne,UpdateOne,DeleteOne"
   }
  ]
 },
 "panels": [
  {
   "title": "Database Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "Pods Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"vp-in-prod-apse1\", container=\"hes-stream-store-prod\"}) by (container)"
    }
   ]
  },
  {
   "title": "MemoryUtilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"stream-store.*\"})\n/\nsum(kube_pod_container_resource_requests_memory_bytes{pod=~\"stream-store.*\"})"
    }
   ]
  },
  {
   "title": "Avg RPM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(increase(hes_http_handler_latency_count{service=\"hes-stream-store-prod\", namespace=\"vp-in-prod-apse1\"}[1m])) by (instance))"
    }
   ]
  },
  {
   "title": "CPU-Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{datacenter=\"sgp\", pod=~\"stream-store.*\"}[5m]))\n/\nsum(kube_pod_container_resource_requests_cpu_cores{datacenter=\"sgp\", pod=~\"stream-store.*\"})\n* 100"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hes_http_handler_latency_sum{service=\"hes-stream-store-prod\", namespace=\"vp-in-prod-apse1\", method=\"$method\", path=\"$path\"}[1m]) / sum(hes_http_handler_latency_count{service=\"hes-stream-store-prod\", namespace=\"vp-in-prod-apse1\", method=\"$method\", path=\"$path\"}[1m])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "API Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(hes_http_status_code_total[1m]))",
     "legendFormat": "throughput"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hes_http_status_code_total{code=~\"4..\"}[1m])) * 100 / sum(rate(hes_http_status_code_total[1m]))"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hes_http_status_code_total{code=~\"5..\"}[1m])) * 100 / sum(rate(hes_http_status_code_total[1m]))"
    }
   ]
  }
 ]
}