{
 "title": "TF Serving TPFY I18N",
 "tags": [
  "P13N",
  "RECO"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   { "name": "tenant", "query": "apse1-0,euw1-0" },
   {
    "name": "cluster",
    "query": "hs-eks-prod-api-apse1,hs-eks-prod-api-euw1, hs-eks-nonprod-api-aps1, hs-eks-dev-api-aps1, hs-eks-qa-api-aps1, hs-eks-load4-api-apse1, hs-eks-prod6-api-apse1"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(kube_pod_container_status_restarts_total{namespace=\"personalisation\", pod=~\"discovery-tf-serving.*\", datacenter=\"sgp\", source_cluster=\"hs-eks-prod6-api-apse1\"}[15m])))",
     "legendFormat": "restart"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"personalisation\", pod=~\"discovery-tf-serving.*\", pod!~\"discovery-tf-serving-masthead.*\", pod!~\"discovery-tf-serving-anchor.*\",source_cluster=\"hs-eks-prod6-api-apse1\"}) by (source_cluster)",
     "legendFormat": "pod count"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"$namespace\", container=\"discovery-tf-serving\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(container_cpu_user_seconds_total{namespace=\"$namespace\",container=\"discovery-tf-serving\", source_cluster=\"$cluster\"}[2m]) / 120",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Model Load Attempt",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": ":tensorflow:cc:saved_model:load_attempt_count{namespace=\"$namespace\"}",
     "legendFormat": "{{model_path}}"
    }
   ]
  }
 ]
}