{
 "title": "Client Performance - Hotstar Web",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kpiName",
    "label": "kpiName",
    "query": "appLaunchTimeKPI, timeToLoadHomePageKPI, timeToLoadSearchPageKPI, searchResultTimeKPI, timeToLoadDetailsPageKPI, playStartTimeKPI, paywallPageLoadTimeKPI, paymentPageLoadTimeKPI, timeToLoadMySpacePageKPI"
   },
   { "name": "browser", "label": "browser", "query": "chrome, firefox, safari, edge" }
  ]
 },
 "panels": [
  {
   "title": "No of Samples",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(${kpiName}{projectId=\"1\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "Rocky"
    },
    {
     "expr": "count(${kpiName}{projectId=\"0\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,IN"
    },
    {
     "expr": "count(${kpiName}{projectId=\"3\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,IN Cache"
    },
    {
     "expr": "count(${kpiName}{projectId=\"2\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,ZA"
    },
    {
     "expr": "count(${kpiName}{projectId=\"4\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,ZA Cache"
    }
   ]
  },
  {
   "title": "${kpiName}-p90, p50",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 16, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.50, ${kpiName}{projectId=\"1\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "Rocky p50"
    },
    {
     "expr": "quantile(0.50, ${kpiName}{projectId=\"0\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,IN p50"
    },
    {
     "expr": "quantile(0.50, ${kpiName}{projectId=\"3\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,IN Cache p50"
    },
    {
     "expr": "quantile(0.50, ${kpiName}{projectId=\"2\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,ZA p50"
    },
    {
     "expr": "quantile(0.50, ${kpiName}{projectId=\"4\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,ZA Cache p50"
    },
    {
     "expr": "quantile(0.90, ${kpiName}{projectId=\"1\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "Rocky p90"
    },
    {
     "expr": "quantile(0.90, ${kpiName}{projectId=\"0\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,IN p90"
    },
    {
     "expr": "quantile(0.90, ${kpiName}{projectId=\"3\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,IN Cache p90"
    },
    {
     "expr": "quantile(0.90, ${kpiName}{projectId=\"2\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,ZA p90"
    },
    {
     "expr": "quantile(0.90, ${kpiName}{projectId=\"4\", deviceId=~\"$browser\"}[$__range])",
     "legendFormat": "X,ZA Cache p90"
    }
   ]
  },
  {
   "title": "${kpiName} - Rocky",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${kpiName}{projectId=\"1\", deviceId=~\"$browser\"})>0) by (testCaseName, deviceId)"
    }
   ]
  },
  {
   "title": "${kpiName} - X, IN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${kpiName}{projectId=\"0\", deviceId=~\"$browser\"})>0) by (testCaseName, deviceId)"
    }
   ]
  },
  {
   "title": "${kpiName} - X, ZA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${kpiName}{projectId=\"2\", deviceId=~\"$browser\"})>0) by (testCaseName, deviceId)"
    }
   ]
  },
  {
   "title": "${kpiName} - X, IN (Cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${kpiName}{projectId=\"3\", deviceId=~\"$browser\"})>0) by (testCaseName, deviceId)"
    }
   ]
  },
  {
   "title": "${kpiName} - X, ZA (Cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(${kpiName}{projectId=\"4\", deviceId=~\"$browser\"})>0) by (testCaseName, deviceId)"
    }
   ]
  }
 ]
}