{
 "title": "Post Transaction timeout webhook feature dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "First level metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Post transaction timeout throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum by (gateway_name, payment_mode, payment_processor) (delta(hspay_payments_post_timeout_webhook_count_total{acquisition_type=\"renewal\"}[1m]))",
       "legendFormat": "{{gateway_name}}-{{payment_mode}}-{{payment_processor}}"
      }
     ]
    },
    {
     "title": "Post Transacation timeout SQS throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_payments_service_post_timeout_webhook_SQS_bucket{le=\"+Inf\"}[$__rate_interval])) by (source_cluster)",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Post Transacation timeout SQS latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,sum(rate(hspay_payments_service_post_timeout_webhook_SQS_bucket{source_cluster=\"nonprod-aps1.pp.hotstar-labs.com\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Second level metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Post Transacation timeout consumer throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_consumer_metrics_bucket{le=\"+Inf\",consumer=\"post_timeout_webhook_event_consumer\"}[$__rate_interval])) by (source_cluster)",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Post Transacation timeout consumer latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,sum(rate(hspay_subscriptions_consumer_metrics_bucket{le=\"+Inf\",consumer=\"post_timeout_webhook_event_consumer\"}[$__rate_interval])) by (source_cluster))",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Post Transacation timeout instant charge throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_post_timeout_webhook_metrics{api_name=\"instant_charge\"}[$__rate_interval])) by (source_cluster)",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Post Transacation timeout instant charge latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,sum(delta(hspay_subscriptions_post_timeout_webhook_metrics{api_name=\"instant_charge\"}[$__rate_interval])) by (source_cluster))",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Post Transacation timeout instant charge response code",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_post_timeout_webhook_metrics{api_name=\"instant_charge\"}[$__rate_interval])) by (http_status, response_code)",
       "legendFormat": "{{http_status}}-{{response_code}}"
      }
     ]
    },
    {
     "title": "Post Transacation timeout refund throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_post_timeout_webhook_metrics{api_name=\"hspay_subscriptions_payment_refund_api\"}[$__rate_interval])) by (source_cluster)",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Post Transacation timeout refund latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,sum(delta(hspay_subscriptions_post_timeout_webhook_metrics{api_name=\"hspay_subscriptions_payment_refund_api\"}[$__rate_interval])) by (source_cluster))",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Post Transacation timeout refund response code",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(hspay_subscriptions_post_timeout_webhook_metrics{api_name=\"hspay_subscriptions_payment_refund_api\"}[$__rate_interval])) by (http_status, response_code)",
       "legendFormat": "{{http_status}}-{{response_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Third level metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Post Transacation timeout payment successful throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum by (gateway_name, payment_mode, payment_processor) (delta(hspay_payments_post_timeout_webhook_processing_success_total{acquisition_type=\"renewal\"}[1m]))",
       "legendFormat": "{{gateway_name}}-{{payment_mode}}-{{payment_processor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Delayed Post transaction webhook",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delayed Post Transacation timeout webhook throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(delta(delayed_post_transaction_webhook_count{acquisition_type=\"renewal\"}[$__rate_interval])) by (gateway_name, payment_mode, payment_processor)",
       "legendFormat": "{{gateway_name}}-{{payment_mode}}-{{payment_processor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Delayed Post transaction webhook recon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delayed webhook recon publish count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum by (provider) ((delta(create_update_schedule_publish_total{acquisition_type=\"renewal\"}[10m])))",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "Delayed failed webhook recon publish count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum((delta(failed_create_update_schedule_publish{acquisition_type=\"renewal\"}[10m]))) by (provider)",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "delayed timeout scheduler recon publisher latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_payments_external_service_metrics_bucket{service_name=\"aws_event_scheduler\", api_name=\"aws_create_update_scheduler\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_payments_external_service_metrics_bucket{service_name=\"aws_event_scheduler\", api_name=\"aws_create_update_scheduler\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(hspay_payments_external_service_metrics_bucket{service_name=\"aws_event_scheduler\", api_name=\"aws_create_update_scheduler\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "delayed timeout scheduler recon consumer latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hspay_payments_consumer_metrics_bucket{consumer_name=\"scheduled_post_transaction_timeout_consumer\"}[1m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hspay_payments_consumer_metrics_bucket{consumer_name=\"scheduled_post_transaction_timeout_consumer\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(hspay_payments_consumer_metrics_bucket{consumer_name=\"scheduled_post_transaction_timeout_consumer\"}[1m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Delayed failed webhook recon consumed count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hspay_payments_consumer_metrics_count{consumer_name=\"scheduled_post_transaction_timeout_consumer\"}[1m]) * 60)",
       "legendFormat": "{{provider}}"
      }
     ]
    }
   ]
  }
 ]
}