{
 "title": "Mutation webhook",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(mutation_requests_total,source_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mutation_http_response_time_seconds_bucket{path=\"/mutate\",source_cluster=~\"$cluster\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mutation_http_response_time_seconds_bucket{path=\"/mutate\",source_cluster=~\"$cluster\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mutation_http_response_time_seconds_bucket{path=\"/mutate\",source_cluster=~\"$cluster\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "server RPM",
   "type": "graph",
   "description": "total number of mutation request",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sum(mutation_requests_total{source_cluster=~\"$cluster\"})[1m])"
    }
   ]
  },
  {
   "title": "successful mutation",
   "type": "graph",
   "description": "number of successful mutation",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name, namespace) (mutation_success_total{source_cluster=~\"$cluster\"})",
     "legendFormat": "{{ name }}  - {{ namespace }}"
    }
   ]
  },
  {
   "title": "skipped mutation",
   "type": "graph",
   "description": "number of mutation skipped",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name, namespace) (mutation_skipped_total{source_cluster=~\"$cluster\"})",
     "legendFormat": "{{ name }} - {{ namespace }}"
    }
   ]
  },
  {
   "title": "rate of mutation error",
   "type": "graph",
   "description": "rate of mutation error",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mutation_error{source_cluster=~\"$cluster\"}[5m])"
    }
   ]
  },
  {
   "title": "rejection error per 2m",
   "type": "graph",
   "description": "rate of mutation error",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_admission_webhook_rejection_count_total{name=\"mutate-k8s-admission-controller.hotstar.com\",source_cluster=~\"$cluster\"}[2m])"
    }
   ]
  }
 ]
}