{
 "title": "Gamepad Recommendation Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_namespace_created, source_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_requests_total{namespace=\"productivity-engg\",source_cluster=\"$cluster\"}[5m])) by (handler, method, status)",
       "legendFormat": "{{method}} [{{status}}] - {{handler}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_request_duration_seconds_sum{source_cluster=\"$cluster\", namespace=\"productivity-engg\", service=~\"gamepad-recommendation.*\"}[5m]) / irate(http_request_duration_seconds_count{source_cluster=\"$cluster\", namespace=\"productivity-engg\",service=~\"gamepad-recommendation.*\"}[5m])",
       "legendFormat": "{{method}} - {{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Collection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(python_gc_collections_total)) by (generation)",
       "legendFormat": "Generation - {{generation}}"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_open_fds{source_cluster=\"$cluster\",pod=~\"gamepad-recommendation.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Incorrect Prediction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(incorrect_prediction_counter_total{source_cluster=\"$cluster\"})) by (service,dc,ladder)",
       "legendFormat": "{{service}}-{{dc}} : {{ladder}}"
      }
     ]
    },
    {
     "title": "Reommendation Not Available",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(recommendation_not_available_total{source_cluster=\"$cluster\"})) by (service,dc)",
       "legendFormat": "{{service}}-{{dc}}"
      }
     ]
    },
    {
     "title": "Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(irate(process_cpu_seconds_total{source_cluster=\"$cluster\",service=~\"gamepad-recommendation.*\"}) *100) /0.5",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra k8s Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(100*sum(rate(container_cpu_usage_seconds_total{pod=~\"gamepad-recommendation.*\", container!=\"\", image!=\"\", source_cluster=\"$cluster\", namespace=\"productivity-engg\", pod=~\"gamepad-recommendation.*\"}[5m])) by (pod) / on(pod) sum(kube_pod_container_resource_requests_cpu_cores{source_cluster=\"$cluster\", namespace=\"productivity-engg\"}) by (pod)) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Avg Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(100*sum(rate(container_memory_usage_bytes{pod=~\"gamepad-recommendation.*\", container!=\"\", image!=\"\", source_cluster=\"$cluster\", namespace=\"productivity-engg\", pod=~\"gamepad-recommendation.*\"}[5m])) by (pod) / on(pod) sum(kube_pod_container_resource_requests_memory_bytes{source_cluster=\"$cluster\", namespace=\"productivity-engg\"}) by (pod)) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_spec_replicas{source_cluster=\"$cluster\",deployment=~\"gamepad-recommendation.*\"})",
       "legendFormat": "Pod Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Service List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Applications With Performance Recommendation",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT  a.name, a.namespace, o.value FROM applications as a INNER JOIN application_overrides as o ON o.application_id = a.id and o.override = 'performance_recommendation'"
      }
     ]
    }
   ]
  }
 ]
}