{
 "title": "[Shifu] Ad Dds Nonprod",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "adtech-shifu-display-ad-dds-pp,adtech-shifu-display-ad-dds-dev,adtech-shifu-display-ad-dds-qa"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "cluster_adtech_shifu_display_ad_dds_pp,cluster_adtech_shifu_display_ad_dds_qa,cluster_adtech_shifu_display_ad_dds_dev"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "adtech-in-dev-aps1,adtech-in-qa-aps1,adtech-in-pp-aps1"
   }
  ]
 },
 "panels": [
  {
   "title": "Dds Service Container CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=~\"${service}.*\", namespace=\"${namespace}\"}[1m])) / 1"
    }
   ]
  },
  {
   "title": "Dds Service Pods Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{pod=~\"${service}.*\", namespace=\"${namespace}\"})"
    }
   ]
  },
  {
   "title": "Cloud Watch: Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"${cluster}.*\"}[1m])*60) by (envoy_cluster_name)",
     "legendFormat": "total request"
    }
   ]
  },
  {
   "title": "Cloud Watch: Mean Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"${cluster}.*\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"${cluster}.*\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"${cluster}.*\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Ambassador 4XX & 5XX RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_5xx_total{envoy_cluster_name=~\"${cluster}.*\"}[1m]))",
     "legendFormat": "Backend 5XX RPS"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_5xx_total{envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "Ambassador 5XX RPS"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_4xx_total{envoy_cluster_name=~\"${cluster}.*\"}[1m]))",
     "legendFormat": "Backend 4XX RPS"
    }
   ]
  },
  {
   "title": "Ambassador Backend Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"${cluster}.*\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"${cluster}.*\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"${cluster}.*\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Ambassador Backend Request Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "req/min" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sum(rate(envoy_cluster_upstream_rq_timeout_total{envoy_cluster_name=~\"${cluster}.*\"}[5m])*60) by (envoy_cluster_name))[5m:1m]",
     "legendFormat": "Backend Request Timeout Count"
    },
    {
     "expr": "avg_over_time(sum(rate(envoy_cluster_upstream_rq_pending_failure_eject_total{envoy_cluster_name=~\"${cluster}.*\"}[5m])*60) by (envoy_cluster_name))[5m:1m]",
     "legendFormat": "Backend Request Pending Failure Count"
    }
   ]
  },
  {
   "title": "Ambassador Backend Connection Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "req/min" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq_total{envoy_cluster_name=~\"${cluster}.*\"}[5m])*60) by (envoy_cluster_name))[5m:1m]",
     "legendFormat": "Connections Destroyed with Active Requests"
    }
   ]
  },
  {
   "title": "Requests count (RPM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=~\"${service}.*\",namespace=\"${namespace}\",uri=~\"/shifu/hs-in/v1/graphql.*\"}[1m]))",
     "legendFormat": "total request"
    }
   ]
  },
  {
   "title": "Latency P99/P95/Mean",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, avg(rate(adtech_shifu_ad_dds_get_ad_http_response_time_seconds_bucket{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.95, avg(rate(adtech_shifu_ad_dds_get_ad_http_response_time_seconds_bucket{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_ad_http_response_time_seconds_sum{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m])) / sum(increase(adtech_shifu_ad_dds_get_ad_http_response_time_seconds_count{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Response code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=~\"${service}.*\",namespace=\"${namespace}\",uri=~\"/shifu/hs-in/v1/graphql.*\"}[1m])) by (status, uri)",
     "legendFormat": "{{uri}}: {{status}}"
    }
   ]
  },
  {
   "title": "Ad Response Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_ad_http_response_complete_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))by(http_return_code)",
     "legendFormat": "http_return_code: {{http_return_code}}"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_ad_http_response_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "http response exception"
    }
   ]
  },
  {
   "title": "Ad Data Time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_ad_data_time_seconds_sum{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m])) / sum(increase(adtech_shifu_ad_dds_get_ad_data_time_seconds_count {job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "get ad data time"
    }
   ]
  },
  {
   "title": "Ad Exception",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_ad_short_circuited_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "ad short circuited"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_ad_short_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "ad short exception"
    },
    {
     "expr": "sum(adtech_shifu_ad_dds_ad_circuit_breaker_thread_pool_is_full_count{job=~\"${service}.*\",namespace=\"${namespace}\"})",
     "legendFormat": "thread pool is full"
    }
   ]
  },
  {
   "title": "Subs Response Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_subs_http_response_complete_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))by(http_return_code)",
     "legendFormat": "http return code: {{http_return_code}}"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_subs_http_response_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "http response exception"
    }
   ]
  },
  {
   "title": "Sbus Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_subs_http_response_time_seconds_sum{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m])) / sum(increase(adtech_shifu_ad_dds_get_subs_http_response_time_seconds_count{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "mean latency"
    }
   ]
  },
  {
   "title": "Subs Exception",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_subs_short_circuited_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "subs short circuited"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_subs_short_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "subs short exception"
    },
    {
     "expr": "sum(adtech_shifu_ad_dds_subs_circuit_breaker_thread_pool_is_full_count{job=~\"${service}.*\",namespace=\"${namespace}\"})",
     "legendFormat": "thread pool is full"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_empty_subs_response_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "empty subs response"
    }
   ]
  },
  {
   "title": "Usm Response Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_usm_http_response_complete_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))by(http_return_code)",
     "legendFormat": "http return code: {{http_return_code}}"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_usm_http_response_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "http response exception"
    }
   ]
  },
  {
   "title": "Usm Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_usm_http_response_time_seconds_sum{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m])) / sum(increase(adtech_shifu_ad_dds_get_usm_http_response_time_seconds_count{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "mean latency"
    }
   ]
  },
  {
   "title": "Usm Exception",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_usm_short_circuited_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "usm short circuited"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_usm_short_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "usm short exception"
    },
    {
     "expr": "sum(adtech_shifu_ad_dds_usm_circuit_breaker_thread_pool_is_full_count{job=~\"${service}.*\",namespace=\"${namespace}\"})",
     "legendFormat": "thread pool is full"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_empty_usm_response_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "empty usm response"
    }
   ]
  },
  {
   "title": "Cms Response Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_cms_http_response_complete_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))by(http_return_code)",
     "legendFormat": "http return code: {{http_return_code}}"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_cms_http_response_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "http response exception"
    }
   ]
  },
  {
   "title": "Cms Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_cms_http_response_time_seconds_sum{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m])) / sum(increase(adtech_shifu_ad_dds_get_cms_http_response_time_seconds_count{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "mean latency"
    }
   ]
  },
  {
   "title": "Cms Exception",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_usm_short_circuited_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))\n",
     "legendFormat": "usm short circuited"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_cms_short_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "cms short exception"
    },
    {
     "expr": "sum(adtech_shifu_ad_dds_cms_circuit_breaker_thread_pool_is_full_count{job=~\"${service}.*\",namespace=\"${namespace}\"})",
     "legendFormat": "thread pool is full"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_empty_cms_response_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "empty cms response"
    }
   ]
  },
  {
   "title": "Media Response Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_media_http_response_complete_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))by(http_return_code)",
     "legendFormat": "http return code: {{http_return_code}}"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_media_http_response_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "http response exception"
    }
   ]
  },
  {
   "title": "Media Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_media_http_response_time_seconds_sum{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m])) / sum(increase(adtech_shifu_ad_dds_get_media_http_response_time_seconds_count{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "mean latency"
    }
   ]
  },
  {
   "title": "Media Exception",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_media_short_circuited_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "media short circuited"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_get_media_short_exception_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "media short exception"
    },
    {
     "expr": "sum(adtech_shifu_ad_dds_media_circuit_breaker_thread_pool_is_full_count{job=~\"${service}.*\",namespace=\"${namespace}\"})",
     "legendFormat": "thread pool is full"
    },
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_empty_media_response_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "empty media response"
    }
   ]
  },
  {
   "title": "Missing Content Id",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_missing_content_id_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "missing content_id"
    }
   ]
  },
  {
   "title": "Invalid Content Id",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_invalid_content_id_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "invalid content_id"
    }
   ]
  },
  {
   "title": "Unsupported Platform",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_unsupported_platform_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "unsupported platform"
    }
   ]
  },
  {
   "title": "Unsupported Country",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(adtech_shifu_ad_dds_unsupported_country_code_total{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "unsupported country code"
    }
   ]
  },
  {
   "title": "Memory: usage by region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jvm_memory_used_bytes{job=~\"${service}.*\",namespace=\"${namespace}\"}) by (instance, id)) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory: heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jvm_memory_used_bytes{job=~\"${service}.*\",namespace=\"${namespace}\"}) by (instance))",
     "legendFormat": "avg mem"
    }
   ]
  },
  {
   "title": "GC: count by cause",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{job=~\"${service}.*\",namespace=\"${namespace}\"}[1m])) by (cause)",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "CPU: load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(system_load_average_1m{job=~\"${service}.*\",namespace=\"${namespace}\"}) by (instance))",
     "legendFormat": "avg cpu load"
    }
   ]
  },
  {
   "title": "GC: pause time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(jvm_gc_pause_seconds_sum{service=~\"${service}.*\",namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "avg gc pause "
    }
   ]
  },
  {
   "title": "CPU: usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"${service}.*\",namespace=\"${namespace}\"}[1m])/sum(kube_pod_container_info{pod=~\"${service}.*\",namespace=\"${namespace}\"}))",
     "legendFormat": "avg cpu"
    }
   ]
  }
 ]
}