{
 "title": "Personalisation / Collections",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "service", "label": "service", "query": "discovery-persona-collections" },
   { "name": "datacenter", "label": "datacenter", "query": { "query": "" } },
   {
    "name": "source_cluster",
    "query": "hs-eks-prod-api-apse1,hs-eks-prod-api-euw1,load-apse1.ld.hotstar-labs.com, nonprod-aps1.pp.hotstar-labs.com, hs-eks-nonprod-api-aps1, hs-eks-dev-api-aps1, hs-eks-qa-api-aps1, hs-eks-load4-api-apse1, hs-eks-prod6-api-apse1"
   }
  ]
 },
 "panels": [
  {
   "title": "Collections Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_requests_total{namespace=\"$namespace\", method=\"GET\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\", status_code=\"200\", url=\"/v1/collection/id/items\"}[1m]))",
       "legendFormat": "GET 200"
      },
      {
       "expr": "sum(increase(http_requests_total{namespace=\"$namespace\", method=\"GET\", status_code=~\"5..\", url=\"/v1/collection/id/items\"}[1m]))",
       "legendFormat": "GET 5xx"
      },
      {
       "expr": "sum(increase(http_requests_total{namespace=\"$namespace\", method=\"GET\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  status_code=~\"4..\", url=\"/v1/collection/id/items\"}[1m]))",
       "legendFormat": "GET 4xx"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  url=\"/v1/collection/id/items\"}[1m])) by (le))",
       "legendFormat": "Tray GET P50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  url=\"/v1/collection/id/items\"}[1m])) by (le))",
       "legendFormat": "Tray GET P90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  url=\"/v1/collection/id/items\"}[1m])) by (le))",
       "legendFormat": "Tray GET P99"
      }
     ]
    },
    {
     "title": "Volume per collection ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_requests_total{namespace=\"$namespace\", method=\"GET\", status_code=\"200\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  url=\"/v1/collection/id/items\"}[1m])) by (id)",
       "legendFormat": "2xx {{ id }}"
      },
      {
       "expr": "sum(increase(http_requests_total{namespace=\"$namespace\", method=\"GET\", status_code=~\"5..\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\", url=\"/v1/collection/id/items\"}[1m])) by (id)",
       "legendFormat": "5xx {{ id }}"
      },
      {
       "expr": "sum(increase(http_requests_total{namespace=\"$namespace\", method=\"GET\", status_code=~\"4..\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  url=\"/v1/collection/id/items\"}[1m])) by (id)",
       "legendFormat": "4xx {{ id }}"
      }
     ]
    },
    {
     "title": "Latency per collection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  url=\"/v1/collection/id/items\"}[1m])) by (le, id))",
       "legendFormat": "P99 {{ id }}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  url=\"/v1/collection/id/items\"}[1m])) by (le, id))",
       "legendFormat": "P90 {{ id }}"
      }
     ]
    },
    {
     "title": "Latency per collection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"4c1847b4-4250-445d-a491-5bb9643ba973\"}[1m])) by (le))",
       "legendFormat": "New on HS"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"3a63b9a9-5e87-4af7-adbd-187f32f132db\"}[1m])) by (le))",
       "legendFormat": "Live News"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"8b85db6c-8b58-45c1-bb03-cf1ae05cd948\"}[1m])) by (le))",
       "legendFormat": "New short movies"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"1a3f0c85-b882-44e1-b44c-d2d35455e6ea\"}[1m])) by (le))",
       "legendFormat": "Latest from celebs"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"84734de6-35a2-4433-8925-e8aed4351480\"}[1m])) by (le))",
       "legendFormat": "Headlines"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"d658fadd-8ddb-4f84-b622-0a9883db56f9\"}[1m])) by (le))",
       "legendFormat": "Politics"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"5f2a5e1c-5580-49da-bae3-b3c874cc2cae\"}[1m])) by (le))",
       "legendFormat": "Corona"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"4f2ef679-f7af-4fc2-9cbf-3e64eade5f38\"}[1m])) by (le))",
       "legendFormat": "Ent"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"8c45774c-c255-4c84-8b96-136540959e9e\"}[1m])) by (le))",
       "legendFormat": "Sports"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"a7520cd4-c13e-4a75-9674-5758795ba248\"}[1m])) by (le))",
       "legendFormat": "News roundup"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"4b5a02c9-6ccd-4bdb-9086-09cc6490693a\"}[1m])) by (le))",
       "legendFormat": "National"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"94fde8cb-a976-48c5-b0ee-3001edbaa6f7\"}[1m])) by (le))",
       "legendFormat": "Business"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"8bd8aa19-82de-4754-aff9-fe649a9e3beb\"}[1m])) by (le))",
       "legendFormat": "World"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"692f47a4-8772-4f5c-bf42-d32662a0eebb\"}[1m])) by (le))",
       "legendFormat": "Science"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"a1342546-9ea1-412d-b1ba-363539ac62fb\"}[1m])) by (le))",
       "legendFormat": "Religion"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"260f6f5a-9743-4a69-81fe-0566adbb7946\"}[1m])) by (le))",
       "legendFormat": "Health"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"7ecd4c7f-b3af-4f09-ae69-c7da4e9707f3\"}[1m])) by (le))",
       "legendFormat": "Crime"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"269af69b-d0a8-4fc8-8c4b-4fe76194a036\"}[1m])) by (le))",
       "legendFormat": "Lifestyle"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"d5d59f5e-61af-4136-b478-45cbe8fa529e\"}[1m])) by (le))",
       "legendFormat": "Misc"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_requests_time_bucket{namespace=\"$namespace\", url=\"/v1/collection/id/items\", id=\"8a626686-6119-4a2f-8cb4-a086b192cdc4\"}[1m])) by (le))",
       "legendFormat": "Local"
      }
     ]
    },
    {
     "title": "DDB GET latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_dynamodb_getitem_time_bucket{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  table=\"persona-collection-prod\"}[1m])) by (le))",
       "legendFormat": "P99 collections"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_dynamodb_getitem_time_bucket{namespace=\"$namespace\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\", table=\"persona-collection-index-prod\"}[1m])) by (le))",
       "legendFormat": "P99 index"
      }
     ]
    },
    {
     "title": "DDB GET count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(collections_dynamodb_getitem_time_count{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\", }[1m]))",
       "legendFormat": "DDB Get count"
      }
     ]
    },
    {
     "title": "Local cache lookup time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_cache_lookup_time_bucket{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  hit=\"true\"}[1m])) by (le))",
       "legendFormat": "Cache lookup hit p99"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_cache_lookup_time_bucket{namespace=\"$namespace\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  hit=\"false\"}[1m])) by (le))",
       "legendFormat": "Cache lookup miss p99"
      }
     ]
    },
    {
     "title": "Items refreshed in cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(collections_cache_itemsrefreshed_count_total{datacenter=\"$datacenter\",namespace=\"$namespace\",source_cluster=\"$source_cluster\"}[1m]))",
       "legendFormat": "Items refreshed"
      }
     ]
    },
    {
     "title": "Cache refresh time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_cache_refresh_time_bucket{namespace=\"$namespace\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\"}[1m])) by (le))",
       "legendFormat": "cache refresh time p99"
      }
     ]
    },
    {
     "title": "Local cache add new key time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(increase(collections_cache_update_time_sum{namespace=\"$namespace\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\"}[1m]))",
       "legendFormat": "Cache update"
      }
     ]
    },
    {
     "title": "Kafka reads ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kafka_read_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Kafka reads"
      }
     ]
    },
    {
     "title": "Cache key creation time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_cache_keycreation_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Index decrement time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_index_decrement_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Index deletion time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_index_deletion_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Index creation time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_index_creation_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P99 index creation time"
      }
     ]
    },
    {
     "title": "Index increment time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collections_index_increment_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Available Pod count",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace!~\"default|kube-system|monitoring|logging|infrastructure|istio-system|book-info|kong\",namespace=\"$namespace\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\"}) by (deployment, namespace)",
       "legendFormat": "Available Replica count"
      }
     ]
    },
    {
     "title": "Pods availability",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=~\"$service\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\"}) by (deployment, namespace)",
       "legendFormat": "Desired"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  deployment=~\"$service\"}) by (deployment, namespace)",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  deployment=~\"$service\"}) by (deployment, namespace)",
       "legendFormat": "Unavailable"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod=~\".*persona-collection.*\"}[1m])) / avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod=~\".*persona-collection.*\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=~\"$service.*\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\", container_name!=\"POD\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod=~\"$service.*\"}) by (container)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod_name=~\"$service.*\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod=~\"$service.*\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod=~\"$service.*\"}) by (container)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod_name=~\"$service.*\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod=~\"$service.*\"}) by (container)"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\", container =~ \".*main.*\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\", container =~ \".*main.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table-old",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\"$service.*\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  container_name!=\"POD\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\", pod=~\"$service.*\"}) by (container)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod_name=~\"$service.*\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",  source_cluster=\"$source_cluster\", datacenter=\"$datacenter\", pod=~\"$service.*\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod=~\"$service.*\", container!=\"\"}) by (container)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod_name=~\"$service.*\", container_name!=\"\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod=~\"$service.*\"}) by (container)"
      },
      {
       "expr": "sum(label_replace(container_memory_rss{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod_name=~\"$service.*\", container_name != \"\", container_name != \"POD\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
      },
      {
       "expr": "sum by (container) (label_replace(container_resources_memory_cache_bytes{container_name!=\"\",container_name!=\"POD\",datacenter=\"$datacenter\",namespace=\"$namespace\",pod_name=~\"$service.*\",source_cluster=\"$source_cluster\"}, \"container\", \"$1\", \"container_name\", \"(.*)\"))"
      },
      {
       "expr": "sum(label_replace(container_memory_swap{namespace=\"$namespace\", source_cluster=\"$source_cluster\", datacenter=\"$datacenter\",  pod_name=~\"$service.*\", container_name != \"\", container_name != \"POD\"}, \"container\", \"$1\", \"container_name\", \"(.*)\")) by (container)"
      }
     ]
    }
   ]
  }
 ]
}