{
 "title": "Kubernetes Cluster Cost",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "EKSCluster",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas, source_cluster)"
    }
   },
   { "name": "CostFactor", "query": "26,28,30,60,62,68,70,72,74" },
   {
    "name": "Team",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas{namespace!~\"ambassador.*|kube-system|monitoring|logging|velero|victoria-metrics|victoria-metrics-scaling|apps|auth\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$EKSCluster  Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$EKSCluster Overall Cost",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(avg_over_time(kube_node_status_allocatable_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor"
      }
     ]
    },
    {
     "title": "$EKSCluster Utilisation Cost",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor",
       "legendFormat": "EKS Utilisation Cost"
      }
     ]
    },
    {
     "title": "$EKSCluster Wastage Cost",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(avg_over_time(kube_node_status_allocatable_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor) - (sum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor)",
       "legendFormat": "EKS Wastage Cost"
      }
     ]
    },
    {
     "title": "Namespace Utilisation Cost",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor",
       "legendFormat": "{{namespace }}"
      }
     ]
    },
    {
     "title": "Namespace Utilisation Cost(Including Wastage)",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) ((((((sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor) * 100 )/ (sum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor)) * ((sum(avg_over_time(kube_node_status_allocatable_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor) - (sum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor)))/100) + (sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{source_cluster=~\"$EKSCluster\"})) * .067 * ($__range_s / 3600) * .$CostFactor))",
       "legendFormat": "{{namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ALL Team Cost",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ALL Team Utilisation Cost",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{})) * .067 * ($__range_s / 3600) * .$CostFactor",
       "legendFormat": "{{namespace }}"
      }
     ]
    },
    {
     "title": "ALL Team Overall Cost(Including Wastage)",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) ((((((sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{})) * .067 * ($__range_s / 3600) * .$CostFactor) * 100 )/ (sum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{})) * .067 * ($__range_s / 3600) * .$CostFactor)) * ((sum(avg_over_time(kube_node_status_allocatable_cpu_cores{})) * .067 * ($__range_s / 3600) * .$CostFactor) - (sum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{})) * .067 * ($__range_s / 3600) * .$CostFactor)))/100) + (sum by (namespace) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{})) * .067 * ($__range_s / 3600) * .$CostFactor))",
       "legendFormat": "{{namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Team $Team Cost Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Team Utilisation Cost(Excluding Wastage)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$Team\"})) * .067 * ($__range_s / 3600) * .$CostFactor",
       "legendFormat": "$Team"
      }
     ]
    },
    {
     "title": "$Team Overall Cost(Including Wastage)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (\n  (\n    (\n      (\n        (\n          (\n            sum by (namespace) (\n              avg_over_time(kube_pod_container_resource_limits_cpu_cores{namespace=\"$Team\"})\n            ) \n            * .067 \n            * ($__range_s / 3600) \n            * .$CostFactor\n          ) \n          * 100 \n        ) \n        / \n        (\n          sum(\n            avg_over_time(kube_pod_container_resource_limits_cpu_cores{})\n          ) \n          * .067 \n          * ($__range_s / 3600) \n          * .$CostFactor\n        )\n      ) \n      * \n      (\n        (\n          sum(\n            avg_over_time(kube_node_status_allocatable_cpu_cores{})\n          ) \n          * .067 \n          * ($__range_s / 3600) \n          * .$CostFactor\n        ) \n        - \n        (\n          sum(\n            avg_over_time(kube_pod_container_resource_limits_cpu_cores{})\n          ) \n          * .067 \n          * ($__range_s / 3600) \n          * .$CostFactor\n        )\n      )\n    ) \n    / 100\n  ) \n  + \n  (\n    sum(\n      avg_over_time(kube_pod_container_resource_limits_cpu_cores{namespace=\"$Team\"})\n    ) \n    * .067 \n    * ($__range_s / 3600) \n    * .$CostFactor\n  )\n)",
       "legendFormat": "$Team"
      }
     ]
    },
    {
     "title": "$Team Cost by EKS Cluster(Excluding Wastage)",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (source_cluster) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$Team\"})) * .067 * ($__range_s / 3600) * .$CostFactor",
       "legendFormat": "{{$source_cluster}}"
      }
     ]
    },
    {
     "title": "$Team Cost by EKS Cluster(Excluding Wastage)",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (source_cluster) (avg_over_time(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$Team\"})) * .067 * ($__range_s / 3600) * .$CostFactor",
       "legendFormat": "{{$source_cluster}}"
      }
     ]
    }
   ]
  }
 ]
}