{
 "title": "UM Ratelimit Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "rule", "label": "rule", "query": "label_values(config_key)" },
   { "name": "Cluster", "label": "Cluster", "query": "label_values(source_cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Guest Signup @ Origin",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(um_rest_counter_create_user_seconds_count{source_cluster=~'$Cluster'}[$__range]))"
    }
   ]
  },
  {
   "title": "Refresh token @ Origin",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(um_rest_counter_refresh_token_api_seconds_count{source_cluster=~'$Cluster'}[$__range]))"
    }
   ]
  },
  {
   "title": "Refresh token Weak token given",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(um_um_counter_refresh_token_guest_weak_token_not_expired_total{source_cluster=~'$Cluster'}[$__range]) + increase(um_um_counter_refresh_token_guest_token_rate_limited_total{source_cluster=~'$Cluster'}[$__range]))"
    }
   ]
  },
  {
   "title": "Guest user Weak token given",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(ratelimit_api_v1_ratelimit_blocked_config_key_total{config_key=\"ambassador.service_ums-ap-southeast-1.api_guest_signup.ip\",source_cluster=~'$Cluster'}[$__range]))"
    }
   ]
  },
  {
   "title": "Rule Requests in selected time range",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(ratelimit_api_v1_ratelimit_config_key_total{config_key=\"$rule\",source_cluster=~'$Cluster'}[$__range]))"
    }
   ]
  },
  {
   "title": "Rule Blocked in selected time range",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 6 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(ratelimit_api_v1_ratelimit_blocked_config_key_total{config_key=\"$rule\",source_cluster=~'$Cluster'}[$__range]))"
    }
   ]
  },
  {
   "title": "Refresh Token API (RPM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(um_um_counter_refresh_token_guest_weak_token_not_expired_total{source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Weak Token bounce back"
    },
    {
     "expr": "sum(increase(um_um_counter_refresh_token_guest_token_rate_limited_total{source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Refresh Token RateLimited"
    },
    {
     "expr": "sum(increase(um_rest_counter_create_user_seconds_count{source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Total refresh token"
    }
   ]
  },
  {
   "title": "Guest Jwt token Created(UM Origin)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(um_um_counter_guest_signup_dummy_token_created_total[$__range]))"
    }
   ]
  },
  {
   "title": "RL Service Load & Blocked Rate (RPS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"ambassador-in-prod-apse1\",job=\"ratelimit\",source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Total Request Coming from Clients"
    },
    {
     "expr": "sum by (config_key) (rate(ratelimit_api_v1_ratelimit_blocked_config_key_total{source_cluster=~\"$Cluster\"}[1m]))",
     "legendFormat": "{{ config_key }} rps"
    }
   ]
  },
  {
   "title": "Weak token other activities in UM (RPM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(um_ums_rate_limit_guest_toke_seen_total{source_cluster=~'$Cluster'}[1m])) by (api)",
     "legendFormat": "{{ api }} api"
    }
   ]
  },
  {
   "title": "Guest Token Supplied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(um_um_counter_guest_signup_dummy_token_created_total{source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Total PC Blocked For Free timer",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(um_auth_counter_invalid_session_jwt_rate_limited{source_cluster=~'$Cluster'}[$__range]))"
    }
   ]
  },
  {
   "title": "Playback Failure due to Weak Token(RPM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(um_auth_counter_invalid_session_jwt_rate_limited{source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Playback Failure Due to Weak Token"
    }
   ]
  }
 ]
}