{
 "title": "Personalisation / Flink / Associative Aggregation",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(flink_jobmanager_job_numRestarts{host=~\"reco.*_flink_jobmanager\"}, job_name)"
    }
   },
   {
    "name": "event_name",
    "query": "WatchedVideoEvent,ParsedTrayViewedEvent,TrayViewedEvent,ContentClickedEvent,AddedToWatchlistEvent,RemovedFromWatchlistEvent,PaywallClickEvent,PaywallClickEvent,UserIdentifyEvent,GetInstalledAppsEvent,ParsedGetInstalledAppsEvent"
   }
  ]
 },
 "panels": [
  {
   "title": "Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event Parsing Success",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "increase(flink_taskmanager_job_task_operator_deserializer_parsingSuccessCounter_MinervaDeserializationSchema_$event_name{namespace=\"$namespace\", job_name=\"$job_name\"}[1m])",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_deserializer_parsingSuccessCounter_MinervaDeserializationSchema_$event_name{namespace=\"$namespace\", job_name=\"$job_name\"}[1m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Event Parsing Failure",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "increase(flink_taskmanager_job_task_operator_deserializer_parsingFailureCounter_MinervaDeserializationSchema_$event_name{namespace=\"$namespace\", job_name=\"$job_name\"}[1m])",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_deserializer_parsingFailureCounter_MinervaDeserializationSchema_$event_name{namespace=\"$namespace\", job_name=\"$job_name\"}[1m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Event Timestamp (Local)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "dateTimeAsLocal" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(flink_taskmanager_job_task_operator_SentinelTimestamp{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Sentinel.*\", operator_name=~\".*Sentinel.*\"}[2m] > 0)",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    },
    {
     "title": "Event Timestamp Lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(time() * 1000 - avg_over_time(flink_taskmanager_job_task_operator_SentinelTimestamp{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Sentinel.*\", operator_name=~\".*Sentinel.*\"}[2m] > 0)) > 0",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source Total Volume",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Source.*\", operator_name=~\".*Source.*\"}[1m])",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Source.*\", operator_name=~\".*Source.*\"}[1m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Source Watermark Lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(time() * 1000 - (flink_taskmanager_job_task_operator_currentOutputWatermark{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Source:_X.*\", operator_name=~\".*Source.*\"} > 0)) > 0",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    },
    {
     "title": "Sentinel Total Volume",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Sentinel.*\", operator_name=~\".*Sentinel.*\"}[1m])",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Sentinel.*\", operator_name=~\".*Sentinel.*\"}[1m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Sentinel Watermark Lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(time() * 1000 - (flink_taskmanager_job_task_operator_currentOutputWatermark{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Sentinel.*\", operator_name=~\".*Sentinel.*\"} > 0)) > 0",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    },
    {
     "title": "StateReader Total Volume",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*StateReader.*\", operator_name=~\".*StateReader.*\"}[1m])",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*StateReader.*\", operator_name=~\".*StateReader.*\"}[1m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "StateReader Watermark Lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(time() * 1000 - (flink_taskmanager_job_task_operator_currentOutputWatermark{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*StateReader.*\", operator_name=~\".*StateReader.*\"} > 0)) > 0",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    },
    {
     "title": "Aggregator Total Volume",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Aggregator.*\", operator_name=~\".*Aggregator.*\"}[1m])",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Aggregator.*\", operator_name=~\".*Aggregator.*\"}[1m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Aggregator Watermark Lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(time() * 1000 - (flink_taskmanager_job_task_operator_currentOutputWatermark{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*Aggregator.*\", operator_name=~\".*Aggregator.*\"} > 0)) > 0",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    },
    {
     "title": "FeatureWriter Total Volume",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*FeatureWriter.*\", operator_name=~\".*FeatureWriter.*\"}[1m])",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*FeatureWriter.*\", operator_name=~\".*FeatureWriter.*\"}[1m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "FeatureWriter Watermark Lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(time() * 1000 - (flink_taskmanager_job_task_operator_currentOutputWatermark{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*FeatureWriter.*\", operator_name=~\".*FeatureWriter.*\"} > 0)) > 0",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    },
    {
     "title": "StateWriter Total Volume",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*StateWriter.*\", operator_name=~\".*StateWriter.*\"}[1m])",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_numRecordsIn{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*StateWriter.*\", operator_name=~\".*StateWriter.*\"}[1m]))",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "StateWriter Watermark Lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(time() * 1000 - (flink_taskmanager_job_task_operator_currentOutputWatermark{namespace=\"$namespace\", job_name=\"$job_name\", task_name=~\".*StateWriter.*\", operator_name=~\".*StateWriter.*\"} > 0)) > 0",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "External IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "FeatureWriter Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_FeatureWriter_count{namespace=\"$namespace\", job_name=\"$job_name\"}[1m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_circuitBreakerFailureLatencyMilliseconds_FeatureWriter_count{namespace=\"$namespace\", job_name=\"$job_name\"}[1m]))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "FeatureWriter Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_FeatureWriter{namespace=\"$namespace\", job_name=\"$job_name\", quantile=\"0.75\"}[1m])",
       "legendFormat": "success-p75"
      },
      {
       "expr": "avg(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_FeatureWriter{namespace=\"$namespace\", job_name=\"$job_name\", quantile=\"0.95\"}[1m])",
       "legendFormat": "success-p95"
      },
      {
       "expr": "avg(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_FeatureWriter{namespace=\"$namespace\", job_name=\"$job_name\", quantile=\"0.99\"}[1m])",
       "legendFormat": "success-p99"
      }
     ]
    },
    {
     "title": "StateReader Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_StateReader_count{namespace=\"$namespace\", job_name=\"$job_name\"}[1m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_circuitBreakerFailureLatencyMilliseconds_StateReader_count{namespace=\"$namespace\", job_name=\"$job_name\"}[1m]))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "StateReader Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_StateReader{namespace=\"$namespace\", job_name=\"$job_name\", quantile=\"0.75\"}[1m])",
       "legendFormat": "success-p75"
      },
      {
       "expr": "avg(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_StateReader{namespace=\"$namespace\", job_name=\"$job_name\", quantile=\"0.95\"}[1m])",
       "legendFormat": "success-p95"
      },
      {
       "expr": "avg(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_StateReader{namespace=\"$namespace\", job_name=\"$job_name\", quantile=\"0.99\"}[1m])",
       "legendFormat": "success-p99"
      }
     ]
    },
    {
     "title": "StateWriter Volume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_StateWriter_count{namespace=\"$namespace\", job_name=\"$job_name\"}[1m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_circuitBreakerFailureLatencyMilliseconds_StateWriter_count{namespace=\"$namespace\", job_name=\"$job_name\"}[1m]))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "StateWriter Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_StateWriter{namespace=\"$namespace\", job_name=\"$job_name\", quantile=\"0.75\"}[1m])",
       "legendFormat": "success-p75"
      },
      {
       "expr": "avg(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_StateWriter{namespace=\"$namespace\", job_name=\"$job_name\", quantile=\"0.95\"}[1m])",
       "legendFormat": "success-p95"
      },
      {
       "expr": "avg(flink_taskmanager_job_task_operator_circuitBreakerSuccessLatencyMilliseconds_StateWriter{namespace=\"$namespace\", job_name=\"$job_name\", quantile=\"0.99\"}[1m])",
       "legendFormat": "success-p99"
      }
     ]
    }
   ]
  }
 ]
}