{
 "title": "UM Concurrency Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Country", "label": "country", "query": "in,id,us,ca,sg,my,th,gb" },
   { "name": "Cluster", "label": "Cluster", "query": "label_values(source_cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Concurrency API Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(um_concurrency_check_requests_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Concurrency API Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(um_concurrency_check_concurrency_api_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "999th "
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(um_concurrency_check_concurrency_api_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(um_concurrency_check_concurrency_api_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Concurrency device limit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(um_concurrency_max_concurrent_limit_reached_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Device Limit Count"
    }
   ]
  },
  {
   "title": "User Token Validation Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(um_concurrency_user_token_validation_service_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "999th "
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(um_concurrency_user_token_validation_service_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(um_concurrency_user_token_validation_service_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Concurrency Check Hystrix Circuit Open Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_check_concurrency_hystrix_circuit_open_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Concurrency Check Fallback response",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_check_concurrency_api_fallback_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Password Reset Suggested Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_max_concurrent_limit_password_reset_suggested_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "User Token Redis Cache  Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(um_concurrency_user_token_redis_cache_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "999th "
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(um_concurrency_user_token_redis_cache_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(um_concurrency_user_token_redis_cache_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Invalid token",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_user_token_expired_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Verify Token Exception",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_verify_token_exception_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Expired JWT",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_jwt_token_expired_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Redis/Aerospike Put",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_onlyRedisPut_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Only Redis Put"
    },
    {
     "expr": "sum(increase(um_concurrency_aeroRedisPut_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Both Redis Aerospike Put"
    }
   ]
  },
  {
   "title": "Failed Audit Event Push Success",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_audit_event_push_success_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Failed Audit Event Push Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_audit_event_push_failed_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Hystrix Circuit Open Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_kafka_hystrix_circuit_open_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Redis/Aerospike Get",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_onlyRedisGet_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Only Redis Get"
    },
    {
     "expr": "sum(increase(um_concurrency_onlyAeroGet_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Only Aerospike Get"
    },
    {
     "expr": "sum(increase(um_concurrency_aeroRedisKeyPresentSameState_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Aerospike Redis Present in same state"
    },
    {
     "expr": "sum(increase(um_concurrency_aeroRedisKeyPresentDiffState_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Aerospike Redis Present in different state"
    }
   ]
  },
  {
   "title": "Redis Hystrix Circuit Open Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_redis_hystrix_circuit_open_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Service Panic Mode Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_service_panic_mode_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Redis Fallback Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_redis_fallback_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Redis/Aerospike Removes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_aeroRemove_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Aerospike Removes"
    },
    {
     "expr": "sum(increase(um_concurrency_redisRemove_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Redis Removes"
    }
   ]
  },
  {
   "title": "User Event Parse Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_user_event_parse_failed_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Serialization Exception",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_kafka_serialization_exception_count_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))"
    }
   ]
  },
  {
   "title": "Subs based concurrency.",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(um_concurrency_subs_based_concurrency_configured_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Set limit for configure pack from dynamo"
    },
    {
     "expr": "sum(increase(um_concurrency_subs_based_concurrency_default_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Set limit to default from dynamo"
    },
    {
     "expr": "sum(increase(um_concurrency_subs_based_concurrency_vault_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Set limit default limit from vault"
    },
    {
     "expr": "sum(increase(um_concurrency_subs_based_concurrency_update_failed_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Internal subs limit update failed"
    },
    {
     "expr": "sum(increase(um_concurrency_subs_based_concurrency_update_success_total{country=~'$Country',source_cluster=~'$Cluster'}[1m]))",
     "legendFormat": "Internal subs limit update success"
    }
   ]
  },
  {
   "title": "Check Concurrency Service Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(um_concurrency_check_concurrency_service_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "999th "
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(um_concurrency_check_concurrency_service_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(um_concurrency_check_concurrency_service_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Concurrency Delete API Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(um_concurrency_delete_concurrency_api_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "999th "
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(um_concurrency_delete_concurrency_api_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(um_concurrency_delete_concurrency_api_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "99th "
    }
   ]
  },
  {
   "title": "Kafka Ingestion Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(um_concurrency_kafka_ingestion_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "999th "
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(um_concurrency_kafka_ingestion_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(um_concurrency_kafka_ingestion_latency_bucket{country=~'$Country',source_cluster=~'$Cluster'}[1m])) by (le)) * 1000",
     "legendFormat": "99th "
    }
   ]
  }
 ]
}