{
 "title": "HES Cluster Utilisation",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "4k DAGs Resource Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "4k-hdr-dv Packaging CPU Utilisation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"4k-hdr-dv-packaging.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"4k-hdr-dv-packaging.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "4k-hdr-dv Packaging Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"4k-hdr-dv-packaging.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"4k-hdr-dv-packaging.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "4k-sdr Packaging CPU utilisation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"4k-sdr-packaging.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"4k-sdr-packaging.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "4k-sdr Packaging Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"4k-sdr-packaging.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"4k-sdr-packaging.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "4k-hdr-dv  Encoding CPU Utilisation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"4k-hdr-dv-encode.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"4k-hdr-dv-encode.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "4k-hdr-dv Encoding Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"4k-hdr-dv-encode.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"4k-hdr-dv-encode.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "4k-sdr Encoding CPU utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"4k-sdr-encode.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"4k-sdr-encode.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "4k-sdr Encoding Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"4k-sdr-encode.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"4k-sdr-encode.*\", container=\"base\"}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "FHD AVC DAGs Resource Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVC Chunk Encoding CPU utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"scle.p-chunk-encode.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"scle.p-chunk-encode.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "AVC Chunk Encoding Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"scle.p-chunk-encode.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"scle.p-chunk-encode.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "AVC Packaging CPU utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"scle.p-packaging.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"scle.p-packaging.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "AVC Packaging Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"scle.p-packaging.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"scle.p-packaging.*\", container=\"base\"}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "FHD HEVC DAGs Resource Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "HEVC Chunk Encoding CPU utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\".*aev5-hevc-chunk-encode-.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\".*aev5-hevc-chunk-encode-.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "HEVC Chunk Encoding Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\".*aev5-hevc-chunk-encode-.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\".*aev5-hevc-chunk-encode-.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "HEVC Chunk Packaging CPU utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\".*aev5-hevc-chunk-packaging.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\".*aev5-hevc-chunk-packaging.*\", container=\"base\"}) by (pod)"
      }
     ]
    },
    {
     "title": "HEVC Packaging Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\".*aev5-hevc-chunk-packaging.*\", container=\"base\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\".*aev5-hevc-chunk-packaging.*\", container=\"base\"}) by (pod)"
      }
     ]
    }
   ]
  }
 ]
}