{
 "title": "Game Marshall SOP Orchestration Health",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "source cluster",
    "query": "hs-eks-dev-api-aps1,hs-eks-nonprod-api-aps1"
   }
  ]
 },
 "panels": [
  {
   "title": "Orchestrator P0 health heartbeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orchestrator Start",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(orchestrator_script_start_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Orchestrator Start"
      }
     ]
    },
    {
     "title": "Orchestrator Complete",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(orchestrator_script_complete_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Orchestrator Complete"
      }
     ]
    },
    {
     "title": "Orchestrator Flask App Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(start_orchestrator_request_count_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Request to start the Orchestrator schedule"
      },
      {
       "expr": "sum(increase(stop_orchestrator_request_count_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Request to Stop the Orchestrator schedule"
      }
     ]
    },
    {
     "title": "Exceptions in Orchestration script",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(excecption_in_orhestration_script_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Exceptions in Orchestration script"
      }
     ]
    }
   ]
  },
  {
   "title": "Anomalies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "No action for orchestrator for step ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(action_missing_in_orchestration_column_in_sheet_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "No action mentioned for step"
      }
     ]
    },
    {
     "title": "Sheet Cell Status TODO But Pipeline INPROGRESS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pipeline_non_terminated_but_cell_status_todo_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Sheet Cell Status TODO But Pipeline INPROGRESS"
      }
     ]
    }
   ]
  },
  {
   "title": "Google Sheet health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Google Sheet Read Credential initialisation success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(google_sheet_process_total)) by (source_cluster)\n",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "No Executable step found to run on google sheet",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(executable_steps_found_zero_from_sheet_total)) by (source_cluster)",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Google Sheet Read Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(google_sheet_read_requests_total)) by (source_cluster)",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Google Sheet Update Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(google_sheet_update_success_total)) by (source_cluster)",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "RATE LIMIT HIT FOR GOOGLE SHEET",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(rate_limit_hit_for_google_sheet_api_token_total)) by (source_cluster)",
       "legendFormat": "{{source_cluster}}"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(google_sheet_get_step_details_exception_total)) by (source_cluster)",
       "legendFormat": "Getting step details exception {{source_cluster}}"
      },
      {
       "expr": "sum(increase(google_sheet_update_step_status_exception_total)) by (source_cluster)",
       "legendFormat": "Update step status in gsheet exception {{source_cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Slack API health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slack Message Publish Success & Failure",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(slack_message_published_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(increase(slack_message_published_error_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Failure"
      }
     ]
    },
    {
     "title": "Slack Message Publish Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(slack_message_published_exception_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Overall Exception while publishing message"
      },
      {
       "expr": "sum(increase(notify_onlyslack_message_publish_exception_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Exception while notify only message publish"
      },
      {
       "expr": "sum(increase(notify_and_execute_slack_message_publish_exception_total))",
       "legendFormat": "Exception while notify and execute message publish"
      }
     ]
    }
   ]
  },
  {
   "title": "GoCD Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "GoCD API Response Audit View",
     "type": "graph",
     "description": "API response for GET call pipeline history & POST call to Trigger pipeline",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gocd_api_requests_count_by_status_total{source_cluster=\"$cluster\"})) by (method, row, status_code)"
      }
     ]
    },
    {
     "title": "GoCD Pipeline Schedule Success and Failure",
     "type": "graph",
     "description": "Success, Failure while orchestrator is triggering step GoCD pipelines",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gocd_pipline_schedule_api_success_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Schedule Success"
      },
      {
       "expr": "sum(increase(gocd_pipline_schedule_api_failure_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Schedule Failure"
      }
     ]
    },
    {
     "title": "GoCD Pipeline Schedule Exceptions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(exception_while_schduling_gocd_pipeline_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Exception while Schduling"
      },
      {
       "expr": "sum(increase(exception_while_checking_eligibiity_for_gocd_pipeline_trigger_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "Exception while checking eligibility to trigger pipeline"
      },
      {
       "expr": "sum(increase(exception_while_checking_status_of_gocd_pipeline_total))",
       "legendFormat": "exception while checking status of pipeline"
      }
     ]
    }
   ]
  },
  {
   "title": "Pagerduty Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pagerduty API requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(increase(pd_api_requests_count_by_status_total{source_cluster=\"$cluster\"})) by (method, endpoint, status_code)"
      }
     ]
    },
    {
     "title": "successful PD creation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(successful_to_create_pd_incident_total{source_cluster=\"$cluster\"}))",
       "legendFormat": "successful PD creation"
      }
     ]
    },
    {
     "title": "Errors while creating PD",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(unable_to_create_pd_incident_total{source_cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Unable to create PD"
      },
      {
       "expr": "sum(increase(exception_while_creating_pd_incident_total{source_cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Exceptions while creating PD"
      }
     ]
    }
   ]
  },
  {
   "title": "K8s health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{source_cluster=\"$cluster\", namespace=\"productivity-engg\", pod=~\"hspay-payment-service-scripts-.*\"})) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{source_cluster=\"$cluster\", namespace=\"productivity-engg\", pod=~\"hspay-payment-service-scripts-.*\"}) by (pod) ",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}