{
 "title": "CMS popularity pipeline",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flink Task Manager Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"flink-in-prod-apse1\", container=\"cms-flink-taskmanager\"}/(1073741824)"
      }
     ]
    },
    {
     "title": "Flink job memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"flink-in-prod-apse1\", container=\"cms-flink-jobmanager\"}/(1073741824)"
      }
     ]
    },
    {
     "title": "CPU Usage Flink JOB Manager",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"flink-in-prod-apse1\", container=\"cms-flink-jobmanager\"}[1m])) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"flink-in-prod-apse1\", container=~\"cms-flink-jobmanager\"}) by (container) "
      }
     ]
    },
    {
     "title": "CPU Usage flink task managers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"flink-in-prod-apse1\", container=\"cms-flink-taskmanager\"}[1m])) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"flink-in-prod-apse1\", container=~\"cms-flink-taskmanager\"}) by (container) "
      }
     ]
    }
   ]
  }
 ]
}