{
 "title": "Amplitude Connect",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(connector_custom_metrics.amplitude.event.sent_value{application=~\".*connect\"},application)"
    }
   },
   {
    "name": "connector",
    "query": {
     "query": "label_values(connector_custom_metrics.amplitude.event.sent_value{connector=~\".*amp.*\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "P0 Client Side Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bad Request Error",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.amplitude.bad.request.error_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      },
      {
       "expr": "sum(connector_custom_metrics.amplitude.bad.request.error_value{application=~\".*connect\",connector=\".*amp.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "Obfuscator Payload Error",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_obfuscator_metrics.event_payload_error_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      },
      {
       "expr": "sum(connector_custom_obfuscator_metrics.event_payload_error_value{application=~\".*connect\",connector=\".*amp.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "Sample Rate missing ",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.amplitude.sample.rate.missing_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      },
      {
       "expr": "sum(connector_custom_metrics.amplitude.sample.rate.missing_value{application=~\".*connect\",connector=\".*amp.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "Invalid Event Error",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.amplitude.invalid.event.error_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      },
      {
       "expr": "sum(connector_custom_metrics.amplitude.invalid.event.error_value{application=~\".*connect\",connector=\".*amp.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "Invalid Message Error",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.amplitude.invalid.message.error_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      },
      {
       "expr": "sum(connector_custom_metrics.amplitude.invalid.message.error_value{application=~\".*connect\",connector=\".*amp.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "P0 Server Side Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate Limit Error/ Throttling ",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.amplitude.too.many.requests.error_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      },
      {
       "expr": "sum(connector_custom_metrics.amplitude.too.many.requests.error_value{application=~\".*connect\",connector=\".*amp.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "Throttled after retry",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.amplitude.throttled.after.retry_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      },
      {
       "expr": "sum(connector_custom_metrics.amplitude.throttled.after.retry_value{application=~\".*connect\",connector=\".*amp.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "Throttled messages rejected",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.amplitude.throttled.messages.rejected_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      },
      {
       "expr": "sum(connector_custom_metrics.amplitude.throttled.messages.rejected_value{application=~\".*connect\",connector=\".*amp.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "API Error",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.amplitude.api.error_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      },
      {
       "expr": "sum(connector_custom_metrics.amplitude.api.error_value{application=~\".*connect\",connector=\".*amp.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "Invalid PID Header",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.sampling.invalid.pid_header.error_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"}[1m])by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    }
   ]
  },
  {
   "title": "P1 Observational metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Sent ",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "expr": "sum(connector_custom_metrics.amplitude.event.sent_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"}[1m])by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "Sink Connector - Read/Send Rate",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "avg(sink_task_metrics_sink_record_read_rate{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"}[1m])by(application,connector)",
       "legendFormat": "read_rate.{{application}}.{{connector}}"
      },
      {
       "expr": "avg(sink_task_metrics_sink_record_send_rate{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"}[1m])by(application,connector)",
       "legendFormat": "send_rate.{{application}}.{{connector}}"
      },
      {
       "expr": "avg(sink_task_metrics_sink_record_active_count{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"}[1m])by(application,connector)",
       "legendFormat": "active_count.{{application}}.{{connector}}"
      },
      {
       "expr": "avg(sink_task_metrics_offset_commit_completion_rate{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"}[1m])by(application,connector)",
       "legendFormat": "offset_commit_completion_rate.{{application}}.{{connector}}"
      }
     ]
    },
    {
     "title": "Transform timers breakup",
     "type": "graph",
     "description": "Time taken by \"serialization\", \"deserialization\" & business logic of amplitude connector transforms per record. ",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "avg(connector_custom_metrics.sampling.sampling_transform_time.serialize_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "sampling_transform_time.serialize_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.sampling.sampling_transform_time.deserialize_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "sampling_transform_time.deserialize_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.sampling.sampling_transform_time.transform_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "sampling_transform_time.transform_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.obfuscator.obfuscation_transform_time.serialize_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "obfuscation_transform_time.serialize_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.obfuscator.obfuscation_transform_time.deserialize_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "obfuscation_transform_time.deserialize_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.obfuscator.obfuscation_transform_time.transform_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "obfuscation_transform_time.transform_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.protoToPayload.protoToJsonTransformTime.serialize_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "protoToJsonTransformTime.serialize_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.protoToPayload.protoToJsonTransformTime.deserialize_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "protoToJsonTransformTime.deserialize_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.protoToPayload.protoToJsonTransformTime.transform_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "protoToJsonTransformTime.transform_p95"
      }
     ]
    },
    {
     "title": "Transform timers breakup",
     "type": "graph",
     "description": "Total Time taken by amplitude connector transforms per record. ",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "avg(connector_custom_metrics.sampling.sampling_transform_time.total_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "sampling_transform_time.total_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.obfuscator.obfuscation_transform_time.total_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "obfuscation_transform_time.total_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.protoToPayload.protoToJsonTransformTime.total_95_percentile{application=~\".*$cluster_name.*\"})by(cluster)",
       "legendFormat": "protoToJsonTransformTime.total_p95"
      }
     ]
    },
    {
     "title": "API Flush Time vs Batch Send Time",
     "type": "graph",
     "description": "API Flush Time : Time taken taken by amplitude connector to send a batch of records via the Amplitude API. \nBatch Send Time : Time taken taken by amplitude connector to process & send a batch of records via the Amplitude API. ",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(connector_custom_metrics.amplitude.flush.time_95_percentile{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}.flushTime_p95"
      },
      {
       "expr": "avg(connector_custom_metrics.amplitude.put.time.total_95_percentile{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}.batchSendTime_p95"
      }
     ]
    },
    {
     "title": "API Flush Size vs Batch Size",
     "type": "graph",
     "description": "API Flush Size : Number of records sent by amplitude connector in a batch to Amplitude API.\n \nBatch Size : Number of records available post sampling to be sent by amplitude connector after a single poll call from a Kafka partition.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(connector_custom_metrics.amplitude.put.records.count_value{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}.batchSize_mean"
      },
      {
       "expr": "avg(connector_custom_metrics.amplitude.flush.size_mean{application=~\".*$cluster_name.*\",connector=~\".*$connector.*\"})by(application,connector)",
       "legendFormat": "{{application}}.{{connector}}.flushSize__mean"
      }
     ]
    }
   ]
  }
 ]
}