{
 "title": "Play Portal Backend - Prod",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "PD Alert list ",
   "type": "alertlist",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "No Of Unique Contents Tested",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(content_id)) as \"Total Unique Contents\" from ipl_test where $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "No Of Unique Contents Tested Per Platform",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "select platform as \"Platform\", count(distinct(content_id)) as \"Total Unique Contents\" from ipl_test where $__timeFilter(created_at) group by platform;"
    }
   ]
  },
  {
   "title": "Total No Of Hours Tests Ran Per Platform",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 7 },
   "targets": [
    {
     "rawSql": "select platform as \"Platform\",\nsum(\n  DATE_PART('day', updated_at::timestamp-created_at::timestamp)*24 +\n\tDATE_PART('hour', updated_at::timestamp-created_at::timestamp) +\n\tDATE_PART('minute', updated_at::timestamp-created_at::timestamp)/60 +\n\tDATE_PART('second', updated_at::timestamp-created_at::timestamp)/36600\n) as \"No Of Hrs\" from ipl_test where $__timeFilter(created_at) group by platform order by \"No Of Hrs\" desc;"
    }
   ]
  },
  {
   "title": "Total No Of Tests Executed Per Platform",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "rawSql": "select platform as \"Platform\", count(*) as \"No Of Tests\" from ipl_test where $__timeFilter(created_at) group by platform;"
    }
   ]
  },
  {
   "title": "PlayPortalX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "No Of Unique Contents Tested - X",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(DISTINCT(temp_table.contents)) FROM (\nSELECT unnest(string_to_array(content_ids, ',')) AS contents FROM content_validation_x WHERE $__timeFilter(created_at)\n) AS temp_table;"
      }
     ]
    },
    {
     "title": "No Of Unique Contents Tested Per Platform - X",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "rawSql": "SELECT temp_table.platform AS \"Platform\", COUNT(DISTINCT(temp_table.contents)) FROM (\nSELECT platform, unnest(string_to_array(content_ids, ',')) AS contents FROM content_validation_x WHERE $__timeFilter(created_at)\n) AS temp_table GROUP BY temp_table.platform;"
      }
     ]
    },
    {
     "title": "Total No Of Hours Tests Ran Per Platform - X",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "select platform as \"Platform\",\nsum(\n  DATE_PART('day', updated_at::timestamp-created_at::timestamp)*24 +\n\tDATE_PART('hour', updated_at::timestamp-created_at::timestamp) +\n\tDATE_PART('minute', updated_at::timestamp-created_at::timestamp)/60 +\n\tDATE_PART('second', updated_at::timestamp-created_at::timestamp)/36600\n) as \"No Of Hrs\" from content_validation_x where $__timeFilter(created_at) group by platform order by \"No Of Hrs\" desc;"
      }
     ]
    },
    {
     "title": "Total No Of Tests Executed Per Platform - X",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "rawSql": "select platform as \"Platform\", count(*) as \"No Of Tests\" from content_validation_x where $__timeFilter(created_at) group by platform;"
      }
     ]
    }
   ]
  },
  {
   "title": "API Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "5XX Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(\n  http_request_duration_seconds_count{service=\"qe-portal\",status_code=~\"5..\"}[1m]\n)) by (method,path)",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "4XX Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(\n  http_request_duration_seconds_count{service=\"qe-portal\",status_code=~\"4..\"}[1m]\n)) by (method,path)",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "90% Latency Bucket",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s", "label": "Response Time" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_request_duration_seconds{quantile=\"0.9\",service=\"qe-portal\"}[1m])) by (path)",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_request_duration_seconds_count{service=~\"qe-portal\"}[1m])) by (path)",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Total Requests Throughput (rpm)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_request_duration_seconds_count{service=\"qe-portal\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Success Response Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_request_duration_seconds_count{service=\"qe-portal\",status_code=~\"2..\"}[1m]))",
       "legendFormat": "response"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(kube_pod_container_info{container=\"qe-portal\"}[10s])",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Mean Cpu Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 5, "y": 17 },
     "yaxes": [
      { "format": "percent", "label": "Cpu load in %" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cpu_load{service=\"qe-portal\"}[1m])) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Used (Heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
     "yaxes": [
      { "format": "decbits", "label": "Memory in Mb" }
     ],
     "targets": [
      {
       "expr": "sum(increase(process_memory_heapUsed{service=\"qe-portal\"}[1m])) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Pod Restart Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "No. Of Restarts" }
     ],
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"qe-portal\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Test Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Tests Triggered In A Day",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(runtest_success_metric_total{service=\"qe-portal\"}[1d])) + sum(increase(runtest_failure_metric_total{service=\"qe-portal\"}[1d]))",
       "legendFormat": "Tests Triggered"
      }
     ]
    },
    {
     "title": "Test Status In Last 1 Minute",
     "type": "graph",
     "description": "Test count per status for tests running in devicelab",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "No of jobs aborted" }
     ],
     "targets": [
      {
       "expr": "sum(increase(robustest_testInProgress_metric_total{service=\"qe-portal\"}[1m]))",
       "legendFormat": "In Progress"
      },
      {
       "expr": "sum(increase(robustest_testpaused_metric_total{service=\"qe-portal\"}[1m]))",
       "legendFormat": "Paused"
      },
      {
       "expr": "sum(increase(robustest_testAbort_metric_total{service=\"qe-portal\"}[1m]))",
       "legendFormat": "Aborted"
      },
      {
       "expr": "sum(increase(robustest_testFail_metric_total{service=\"qe-portal\"}[1m]))",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(increase(robustest_testSuccess_metric_total{service=\"qe-portal\"}[1m]))",
       "legendFormat": "Passed"
      }
     ]
    },
    {
     "title": "Tests Triggered Successfully In A Day",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(runtest_success_metric_total{service=\"qe-portal\"}[1d]))",
       "legendFormat": "Tests Triggered"
      }
     ]
    },
    {
     "title": "Failed To Trigger Tests In A Day",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(runtest_failure_metric_total{service=\"qe-portal\"}[1d]))",
       "legendFormat": "Tests Triggered"
      }
     ]
    },
    {
     "title": "Go-Cd Abort  Job count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "No of jobs aborted" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gocd_abortTest_metric_total{service=\"qe-portal\"}[1d]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Go-Cd Failed To Trigger Job Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(gocd_triggerTestFail_metric_total{service=\"qe-portal\"}[1d]))"
      }
     ]
    },
    {
     "title": "Go-Cd Jobs Successfully Triggered",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(gocd_triggerTest_metric_total{service=\"qe-portal\"}[1d]))"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Deadlocks Count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_deadlocks{service=\"qe-portal\"}[1m])"
      }
     ]
    },
    {
     "title": "Transaction Rollbacks",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_stat_database_xact_rollback{service=\"qe-portal\"}"
      }
     ]
    },
    {
     "title": "Committed Transactions",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_stat_database_xact_commit{service=\"qe-portal\"}"
      }
     ]
    },
    {
     "title": "Total Records inserted",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{service=\"qe-portal\"}"
      }
     ]
    },
    {
     "title": "Total Records Updated",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{service=\"qe-portal\"}"
      }
     ]
    },
    {
     "title": "Total Records Deleted",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{service=\"qe-portal\"}"
      }
     ]
    },
    {
     "title": "Transaction Rollback Count In A Minute",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(increase(pg_stat_database_xact_rollback{service=\"qe-portal\"}[1m]))",
       "legendFormat": "No Of Transactions Rollback"
      }
     ]
    },
    {
     "title": "Current Configuration",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "rawSql": "select js.key as \"Config Key\", js.value as \"Value\"\nfrom config, json_each(config.data::json) as js"
      }
     ]
    }
   ]
  }
 ]
}