{
 "title": "Pulse Flink Cluster",
 "description": "Pulse Flink Metrics",
 "tags": [ "pulse" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jobName",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime{host=\"$host_name\"},job_name)"
    }
   },
   { "name": "cluster", "label": "cluster", "query": "hs-eks-prod7-api-apse1" },
   { "name": "namespace", "label": "adtech", "query": "adtech" },
   { "name": "host_name", "query": "pulse_flink_jobmanager" }
  ]
 },
 "panels": [
  {
   "title": "Kafka Client metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Average consumer max lag ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max{job_name=\"$jobName\"}) by (operator_name)",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Current avg consumer lag ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_currentEmitEventTimeLag{job_name=\"$jobName\"}) by (operator_name)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Sum commit failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_commitsFailed{namespace=\"$namespace\",job_name=\"$jobName\"}) by (operator)",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Avg checkpoint delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_checkpointStartDelayNanos{namespace=\"$namespace\",job_name=\"$jobName\"})"
    }
   ]
  },
  {
   "title": "Avg commit rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_commit_rate{namespace=\"$namespace\",job_name=\"$jobName\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Avg commit Latency max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_commit_latency_max{namespace=\"$namespace\",job_name=\"$jobName\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Assigned partition / operator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_assigned_partitions{job_name=\"$jobName\"})",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "backPressuredTimeMsPerSecond",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(flink_taskmanager_job_task_backPressuredTimeMsPerSecond{job_name=\"$jobName\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Flink Cluster Indicators ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Slots",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsAvailable{job=~\"pulse-flink-jobmanager\", namespace=\"$namespace\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "flink_jobmanager_taskSlotsTotal{job=~\"pulse-flink-jobmanager\", namespace=\"$namespace\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Running Jobs Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRunningJobs{job=\"pulse-flink-jobmanager\", namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flink Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU Usage",
     "type": "graph",
     "description": "Container CPU Usage Percent",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"pulse-.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Memory Usage Percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",pod=~\"pulse-.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"pulse-.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "JM/TM CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "100 * flink_jobmanager_Status_JVM_CPU_Load{namespace=\"$namespace\", pod=~\"pulse-flink-.*\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "100 * flink_taskmanager_Status_JVM_CPU_Load{namespace=\"$namespace\", pod=~\"pulse-flink-.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "TM/JM Heap Memory",
     "type": "graph",
     "description": "TaskManager and JobManager JVM Memory Usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "displayType": "Regular",
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Used{pod=~\"pulse-flink-.*\"}) by (pod) / sum(flink_taskmanager_Status_JVM_Memory_Heap_Max{pod=~\"pulse-flink-.*\"}) by (pod)",
       "legendFormat": "{{pod}}",
       "valueHandler": "Number Threshold"
      },
      {
       "displayType": "Regular",
       "expr": "sum(flink_jobmanager_Status_JVM_Memory_Heap_Used{pod=~\"pulse-flink-.*\"}) by (pod) / sum(flink_jobmanager_Status_JVM_Memory_Heap_Max{pod=~\"pulse-flink-.*\"}) by (pod)",
       "legendFormat": "{{pod}}",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Task Manager Non Heap Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_NonHeap_Used{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod) / sum(flink_taskmanager_Status_JVM_Memory_NonHeap_Max{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Task Manager Direct Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod) / \nsum(flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Details for all Pods",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Details for all Pods",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",pod=~\"pulse-flink-.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",pod=~\"pulse-flink-.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",pod=~\"pulse-flink-.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_rss{namespace=\"$namespace\",container!=\"\",pod=~\"pulse-flink-.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum by (pod) (label_replace(container_resources_memory_cache_bytes{container!=\"\",namespace=\"$namespace\",pod=~\"pulse-flink-.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\"))"
      }
     ]
    }
   ]
  },
  {
   "title": "Ads Flink Job Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of restarts",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_numRestarts{job_name=\"$jobName\"}"
      }
     ]
    },
    {
     "title": "Job Downtime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 7, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "flink_jobmanager_job_downtime{job_name=\"$jobName\"}"
      }
     ]
    },
    {
     "title": "Job Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 15, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "flink_jobmanager_job_uptime{job_name=\"$jobName\"}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{namespace=\"$namespace\",job_name=\"$jobName\"}",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{namespace=\"$namespace\",job_name=\"$jobName\"}",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Number of Failed Completed and Checkpoints",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{namespace=\"$namespace\",job_name=\"$jobName\"}",
       "legendFormat": "failed: {{job_name}}"
      },
      {
       "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints{job_name=\"$jobName\"}",
       "legendFormat": "completed: {{job_name}}"
      }
     ]
    },
    {
     "title": "TM Load Distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsIn{job_name=\"$jobName\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_total_records{job_name=\"$jobName\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Operator Records In Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_name=\"$jobName\"}) by (operator_name)",
       "legendFormat": "{{operator_name}}"
      }
     ]
    },
    {
     "title": "Operator Records Out Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=\"$jobName\"}) by (operator_name)",
       "legendFormat": "{{operator_name}}"
      }
     ]
    },
    {
     "title": "Cohort Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_streamType_platform_lang_cohorts_total{job_name=\"$jobName\"}[1m]))",
       "legendFormat": "Cohort Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Metrics in Flink ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Sink Producer Record Send Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaProducer_record_send_rate{job_name=\"$jobName\"})",
       "legendFormat": "Producer record send rate"
      }
     ]
    },
    {
     "title": "Kafka Consumer Record Consumed Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job_name=\"$jobName\"})",
       "legendFormat": "Consumer records consumed rate"
      }
     ]
    },
    {
     "title": "Kafka Consumer/Producer Bytes Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_bytes_consumed_rate{job_name=\"$jobName\"})",
       "legendFormat": "Bytes Consumed Rate"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaProducer_outgoing_byte_rate{job_name=\"$jobName\"})",
       "legendFormat": "Bytes Produced Rate"
      }
     ]
    },
    {
     "title": "Kafka Producer Batch Size Avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_KafkaProducer_batch_size_avg{job_name=\"$jobName\"}",
       "legendFormat": "{{job_name}}-{{subtask_index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cohort Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSAI Cohort Count By Lang",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_streamType_platform_lang_cohorts_total{job_name=\"$jobName\", streamType=\"ssai\"}[1m])) by (lang)",
       "legendFormat": "{{lang}}"
      }
     ]
    },
    {
     "title": "SSAI Cohort Count By Platform",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_streamType_platform_lang_cohorts_total{job_name=\"$jobName\", streamType=\"ssai\"}[1m])) by (platform)",
       "legendFormat": "{{platform}}"
      }
     ]
    },
    {
     "title": "Cohort Count By StreamType",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_streamType_platform_lang_cohorts_total{job_name=\"$jobName\"}[1m])) by (streamType)",
       "legendFormat": "{{streamType}}"
      }
     ]
    },
    {
     "title": "Cohort Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(flink_taskmanager_job_task_operator_streamType_platform_lang_cohorts_total{job_name=\"$jobName\"}[1m]))",
       "legendFormat": "Cohort Count"
      }
     ]
    }
   ]
  }
 ]
}