{
 "title": "Blaze Flink Cluster",
 "description": "Blaze Flink Metrics",
 "tags": [ "blaze" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jobName",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime,job_name)"
    }
   },
   { "name": "cluster", "label": "cluster", "query": "flink-in-prod-apse1" },
   { "name": "namespace", "query": "adtech" },
   { "name": "deployment", "query": "blaze-flink" }
  ]
 },
 "panels": [
  {
   "title": "Flink Cluster Indicators ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Slots",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsAvailable{job=~\"blaze-flink-jobmanager\", namespace=\"$namespace\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "flink_jobmanager_taskSlotsTotal{job=~\"blaze-flink-jobmanager\", namespace=\"$namespace\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Running Jobs Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRunningJobs{job=\"blaze-flink-jobmanager\", namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flink Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operator Records Out Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=\"$jobName\"}) by (operator_name)",
       "legendFormat": "{{operator_name}}"
      }
     ]
    },
    {
     "title": "Operator Records In Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_name=\"$jobName\"}) by (operator_name)",
       "legendFormat": "{{operator_name}}"
      }
     ]
    },
    {
     "title": "kafka Records In Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_by_label_numeric(increase(flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_name=\"$jobName\",operator_name=~\".*Source.*\"}),\"operator_name\",\"subtask_index\")",
       "legendFormat": "{{operator_name}}_{{subtask_index}} "
      }
     ]
    },
    {
     "title": "Task Bytes In ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numBytesInPerSecond{job_name=\"$jobName\"}) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "task bakcpressure time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_backPressuredTimeMsPerSecond{job_name=\"$jobName\"}) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "task busy time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_busyTimeMsPerSecond{job_name=\"$jobName\"}) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Reach Processor watermark lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(time() * 1000 - (flink_taskmanager_job_task_operator_currentOutputWatermark{job_name=\"$jobName\", task_name=~\".*Timestamps.*\", operator_name=~\".*Timestamps.*\"} > 0)) > 0",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    },
    {
     "title": "redis sink watermark lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(time() * 1000 - (flink_taskmanager_job_task_operator_currentOutputWatermark{job_name=\"$jobName\", task_name=~\".*Sink:_write_reach_to_redis.*\", operator_name=~\".*Sink:_write_reach_to_redis.*\"} > 0)) > 0",
       "legendFormat": "{{operator_name}}_{{subtask_index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flink Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Task Manager Non Heap Memory Used",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_NonHeap_Used{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod) / sum(flink_taskmanager_Status_JVM_Memory_NonHeap_Max{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Task Manager Direct Memory Used",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod) / \nsum(flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "TM/JM Heap Memory",
     "type": "bargauge",
     "description": "TaskManager and JobManager JVM Memory Usage",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "displayType": "Regular",
       "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Used{pod=~\"$deployment.*\"}) by (pod) / sum(flink_taskmanager_Status_JVM_Memory_Heap_Max{pod=~\"$deployment.*\"}) by (pod)",
       "legendFormat": "{{pod}}",
       "valueHandler": "Number Threshold"
      },
      {
       "displayType": "Regular",
       "expr": "sum(flink_jobmanager_Status_JVM_Memory_Heap_Used{pod=~\"$deployment.*\"}) by (pod) / sum(flink_jobmanager_Status_JVM_Memory_Heap_Max{pod=~\"$deployment.*\"}) by (pod)",
       "legendFormat": "{{pod}}",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "CPU Details for all Pods",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Details for all Pods",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$deployment.*\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_rss{namespace=\"$namespace\",container!=\"\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum by (pod) (label_replace(container_resources_memory_cache_bytes{container!=\"\",namespace=\"$namespace\",pod=~\"$deployment.*\"}, \"pod\", \"$1\", \"pod\", \"(.*)\"))"
      }
     ]
    }
   ]
  },
  {
   "title": "Ads Flink Job Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of restarts",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_numRestarts{job_name=\"$jobName\"}"
      }
     ]
    },
    {
     "title": "Job Downtime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "flink_jobmanager_job_downtime{job_name=\"$jobName\"}"
      }
     ]
    },
    {
     "title": "Job Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "flink_jobmanager_job_uptime{job_name=\"$jobName\"}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{namespace=\"$namespace\",job_name=\"$jobName\"}",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{namespace=\"$namespace\",job_name=\"$jobName\"}",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Number of Failed Completed and Checkpoints",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{namespace=\"$namespace\",job_name=\"$jobName\"}",
       "legendFormat": "failed: {{job_name}}"
      },
      {
       "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints{job_name=\"$jobName\"}",
       "legendFormat": "completed: {{job_name}}"
      }
     ]
    },
    {
     "title": "TM Load Distribution",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "displayType": "Regular",
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsIn{job_name=\"$jobName\"}) by(pod)",
       "legendFormat": "{{pod}}",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Metrics in Flink ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Proto Consumer Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(burrow_partition_lag{cluster=\"kafka_hb\" , group = \"prod-apse1-c-blaze_reach_flink-proto_heartbeat\"}) by (group, topic, partition)",
       "legendFormat": "{{group}}-{{topic}}-{{partition}}"
      }
     ]
    },
    {
     "title": "Kafka Proto Consumer Status Code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(burrow_partition_status_code{cluster=\"kafka_hb\" , group = \"prod-apse1-c-blaze_reach_flink-proto_heartbeat\"}) by (group, topic, partition)",
       "legendFormat": "{{group}}-{{topic}}-{{partition}}"
      }
     ]
    },
    {
     "title": "Kafka tracker Consumer Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(burrow_partition_lag{cluster=\"kafka_ct\" , group = \"prod-apse1-c-blaze_reach_flink-impression\"}) by (group, topic, partition)",
       "legendFormat": "{{group}}-{{topic}}-{{partition}}"
      }
     ]
    },
    {
     "title": "Kafka tracker Consumer Status Code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(burrow_partition_status_code{cluster=\"kafka_ct\" , group = \"prod-apse1-c-blaze_reach_flink-impression\"}) by (group, topic, partition)",
       "legendFormat": "{{group}}-{{topic}}-{{partition}}"
      }
     ]
    }
   ]
  }
 ]
}