{
 "title": "DP - Airflow Dashboard (Kops)",
 "tags": [
  "dp",
  "airflow"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   { "name": "environment", "query": "airflow-pp,airflow-prod" }
  ]
 },
 "panels": [
  {
   "title": "InfraMetrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage: Scheduler",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n# This query returns current used memory for a pod\ncontainer_memory_working_set_bytes{source_cluster=\"prod-use1.data.k8s.hotstar-labs.com\", namespace=\"$namespace\", pod=~\"airflow-scheduler.*\", container != \"POD\", container != \"\"} \n)\n/ on(pod,container) # This means that two series values are divided if the value of pod lavel matches. \n(\n# This query returns total allocated memory for a pod\nkube_pod_container_resource_requests_memory_bytes{source_cluster=\"prod-use1.data.k8s.hotstar-labs.com\", namespace=\"$namespace\",pod=~\"airflow-scheduler.*\", container != \"POD\", container != \"\"}\n)",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage:  Webserver",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(\n# This query returns current used memory for a pod\ncontainer_memory_working_set_bytes{source_cluster=\"prod-use1.data.k8s.hotstar-labs.com\", namespace=\"$namespace\", pod=~\"airflow-.*\", pod!~\"airflow-scheduler.*\",  container != \"POD\", container != \"\"} \n)\n/ on(pod) # This means that two series values are divided if the value of pod lavel matches. \n(\n# This query returns total allocated memory for a pod\nkube_pod_container_resource_requests_memory_bytes{source_cluster=\"prod-use1.data.k8s.hotstar-labs.com\", namespace=\"$namespace\",pod=~\"airflow-.*\", pod!~\"airflow-scheduler.*\", container != \"POD\", container != \"\"}\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Throttling - Scheduler",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(container_cpu_cfs_throttled_periods_total{ namespace=\"$namespace\", pod=~\"airflow-scheduler.*\", container != \"\"} *100)  / on(pod,container) (container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"airflow-scheduler.*\", container != \"\"})",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "CPU Throttling - Webserver",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(container_cpu_cfs_throttled_periods_total{ namespace=\"$namespace\", pod=~\"airflow-.*\", pod!~\"airflow-scheduler.*\", container != \"\"} *100)  / on(pod,container) (container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"airflow-.*\",  pod!~\"airflow-scheduler.*\", container != \"\"})",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "CPU Utilisation: Scheduler",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "\n(\n# This query gives CPU usage for containers in absolute numbers\n namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"airflow-scheduler.*\", container != \"POD\", container != \"\"}\n) \n/ on (pod,container)\n\n(\n# This query gives total CPU usage for containers in absolute numbers\nkube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"airflow-scheduler.*\", container != \"POD\", container != \"\"}\n)",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "CPU Utilisation: Webserver",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "\n(\n# This query gives CPU usage for containers in absolute numbers\n namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"airflow-.*\", pod!~\"airflow-scheduler.*\", container != \"POD\", container != \"\"}\n) \n/ on (pod,container)\n\n(\n# This query gives total CPU usage for containers in absolute numbers\nkube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",  pod=~\"airflow-.*\",  pod!~\"airflow-scheduler.*\", container != \"POD\", container != \"\"}\n)",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Airflow Scheduler Status",
     "type": "singlestat",
     "description": "Whether the scheduler is UP or DOWN",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
     "format": "short",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"airflow-scheduler\"})"
      }
     ]
    },
    {
     "title": "Airflow Web servers",
     "type": "singlestat",
     "description": "No. of airflow web servers",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
     "format": "short",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"airflow\"})"
      }
     ]
    },
    {
     "title": "Connection Pools",
     "type": "graph",
     "description": "Connection Pools",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(aiflow_connection_pool_open_slots{environment=\"$environment\"}) by (pool_name)",
       "legendFormat": "{{ pool_name }} -open"
      },
      {
       "expr": "max(aiflow_connection_pool_used_slots{environment=\"$environment\"}) by (pool_name)",
       "legendFormat": "{{ pool_name }} -used"
      },
      {
       "expr": "max(aiflow_connection_pool_starving_tasks{environment=\"$environment\"}) by (pool_name)",
       "legendFormat": "{{ pool_name }} -starving"
      }
     ]
    },
    {
     "title": "Executor Metrics",
     "type": "graph",
     "description": "Executor Metrics",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(aiflow_executor_open_slots{environment=\"$environment\"})",
       "legendFormat": "OpenSlots"
      },
      {
       "expr": "avg(aiflow_executor_running_tasks{environment=\"$environment\"})",
       "legendFormat": "RunningTasks"
      },
      {
       "expr": "avg(aiflow_executor_queued_tasks{environment=\"$environment\"})",
       "legendFormat": "QueuedTasks"
      }
     ]
    }
   ]
  }
 ]
}