{
 "title": "K8S Kubeletstats",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_time_s_total{}, k8s_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU Usage",
   "type": "gauge",
   "description": "This metric measures the average CPU utilization across all the containers in a given Pod. It represents the overall CPU utilization of the Pod, including all the containers running within it.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_cpu_utilization_1{k8s_pod_name=\"$pod\"}",
     "legendFormat": "{{k8s_pod_name}} CPU Usage"
    }
   ]
  },
  {
   "title": "Pod Used RAM",
   "type": "piechart",
   "description": "This metric measures the memory utilization across all the containers in a given Pod. It represents the overall memory utilization of the Pod, including all the containers running within it.",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_memory_available_By{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Available RAM {{k8s_pod_name}}"
    },
    {
     "expr": "k8s_pod_memory_usage_By{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Used RAM {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_container_restarts_1{k8s_pod_name=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources - CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "container_cpu_utilization_1{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Used CPU (ratio) for container {{k8s_container_name}} running on {{instance}}"
    },
    {
     "expr": "k8s_container_cpu_limit{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Limit for {{k8s_container_name}} from {{k8s_pod_name}}"
    },
    {
     "expr": "k8s_container_cpu_request{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Request for {{k8s_container_name}} from {{k8s_pod_name}}"
    },
    {
     "expr": "rate(container_cpu_time_s_total{k8s_pod_name=\"$pod\"}[1m])",
     "legendFormat": "Usage for {{k8s_container_name}} from {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_cpu_utilization_1{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Container {{k8s_container_name}} used CPU"
    },
    {
     "expr": "k8s_pod_cpu_utilization_1{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Pod {{k8s_pod_name}} running on {{instance}}"
    }
   ]
  },
  { "title": "Resources - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_By{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Container {{k8s_container_name}} Used RAM"
    },
    {
     "expr": "k8s_container_memory_limit{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Limit for {{k8s_container_name}} from {{k8s_pod_name}}"
    },
    {
     "expr": "k8s_container_memory_request{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Request for {{k8s_container_name}} from {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k8s_pod_memory_usage_By{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Pod {{k8s_pod_name}} Used RAM"
    },
    {
     "expr": "k8s_pod_memory_available_By{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Pod {{k8s_pod_name}} Available RAM"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true
  },
  {
   "title": "Filesystem stats (containers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_filesystem_capacity_By{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Filesystem Capacity for {{k8s_container_name}}"
    },
    {
     "expr": "container_filesystem_available_By{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Available storage for {{k8s_container_name}}"
    },
    {
     "expr": "container_filesystem_usage_By{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Used storage for {{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "Network IO ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(k8s_pod_network_io_By_total{k8s_pod_name=\"$pod\", direction=\"receive\"}[1m])",
     "legendFormat": "Received {{k8s_pod_name}}"
    },
    {
     "expr": "- rate(k8s_pod_network_io_By_total{k8s_pod_name=\"$pod\", direction=\"transmit\"}[1m])",
     "legendFormat": "Sent {{k8s_pod_name}}"
    }
   ]
  }
 ]
}