{
 "title": "AWS ALB - L2M - Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "alb_status_code", "label": "ALB Status Code", "query": { "query": "label_values(alb_status_code)" } },
   {
    "name": "alb_target_status_code",
    "label": "Target Status Code",
    "query": {
     "query": "label_values(alb_target_status_code)"
    }
   },
   { "name": "alb_request_verb", "label": "Request Verb", "query": { "query": "label_values(alb_request_verb)" } }
  ]
 },
 "panels": [
  {
   "title": "Distribution of ALB HTTP Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (alb_status_code) (alb_l2m_cx_docs_total{alb_status_code=~\"$alb_status_code\"})",
     "legendFormat": "{{alb_status_code}}"
    }
   ]
  },
  {
   "title": "Distribution of HTTP Request Verbs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (alb_request_verb) (alb_l2m_cx_docs_total{alb_request_verb=~\"$alb_request_verb\"})",
     "legendFormat": "{{alb_status_code}}"
    }
   ]
  },
  {
   "title": "Distribution of ALB Target HTTP Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (alb_target_status_code) (alb_l2m_cx_docs_total{alb_target_status_code=~\"$alb_target_status_code\"})",
     "legendFormat": "{{alb_status_code}}"
    }
   ]
  },
  {
   "title": "Distribution of HTTP Status Code - Succes vs. Error",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (alb_l2m_cx_docs_total{alb_status_code=~\"[23]..\",alb_request_verb=~\"$alb_request_verb\"}) ",
     "legendFormat": "HTTP Success Codes "
    },
    {
     "expr": "sum (alb_l2m_cx_docs_total{alb_status_code=~\"[45]..\",alb_request_verb=~\"$alb_request_verb\"})",
     "legendFormat": "HTTP Error Codes "
    }
   ]
  },
  {
   "title": "Distribution of HTTP Status Error Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (alb_status_code) (alb_l2m_cx_docs_total{alb_status_code=~\"$alb_status_code\"})",
     "legendFormat": "{{alb_status_code}}"
    }
   ]
  },
  {
   "title": "Total Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (alb_received_bytes_cx_max)",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum (alb_sent_bytes_cx_max)", "legendFormat": "Bytes" }
   ]
  },
  {
   "title": "Average Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max (alb_request_processing_time_cx_avg)",
     "legendFormat": "Average Processing Time"
    }
   ]
  },
  {
   "title": "Average Target Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (alb_target_processing_time_cx_avg)",
     "legendFormat": "Average Processing Time"
    }
   ]
  },
  {
   "title": "Average Response Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max (alb_response_processing_time_cx_avg)",
     "legendFormat": "Average Processing Time"
    }
   ]
  },
  {
   "title": "Backend HTTP Success Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "Responses",
     "bucketAggs": [
      { "field": "coralogix.timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_: \"target_status_code\" AND target_status_code:[200 TO 399]",
     "timeField": "coralogix.timestamp"
    }
   ]
  },
  {
   "title": "Backend 4XX error codes. by ALB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "alb.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "coralogix.timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_: \"alb\" AND target_status_code:[400 TO 499]",
     "timeField": "coralogix.timestamp"
    }
   ]
  },
  {
   "title": "Backend 5XX error codes. by ALB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "alb.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "coralogix.timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_: \"alb\" AND target_status_code:[500 TO 599]",
     "timeField": "coralogix.timestamp"
    }
   ]
  }
 ]
}