{
 "title": "k8s Container/Pod/Node Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_time_s_total, k8s_namespace_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_time_s_total{k8s_namespace_name=\"$namespace\"}, k8s_container_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_time_s_total{k8s_namespace_name=\"$namespace\",k8s_container_name=~\"$container\"}, k8s_pod_name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(container_cpu_time_s_total{k8s_namespace_name=\"$namespace\"}, k8s_node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_time_s_total{k8s_namespace_name=\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
     "legendFormat": "{{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_utilization_1{k8s_namespace_name=~\"$namespace\", k8s_container_name=~\"$container\"}) by (k8s_container_name)",
     "legendFormat": "{{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_By{k8s_namespace_name=\"$namespace\", k8s_container_name=~\"$container\"}) by (k8s_container_name)",
     "legendFormat": "{{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "Memory Major Page faults",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(increase(container_memory_major_page_faults_1{k8s_namespace_name=\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
     "legendFormat": "{{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_filesystem_capacity_By{k8s_namespace_name=\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
     "legendFormat": "Capacity: {{k8s_container_name}}"
    },
    {
     "expr": "sum(rate(container_filesystem_available_By{k8s_namespace_name=\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
     "legendFormat": "Available: {{k8s_container_name}}"
    },
    {
     "expr": "sum(rate(container_filesystem_usage_By{k8s_namespace_name=\"$namespace\", k8s_container_name=~\"$container\"}[$__rate_interval])) by (k8s_container_name)",
     "legendFormat": "Usage: {{k8s_container_name}}"
    }
   ]
  },
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_cpu_time_total{k8s_namespace_name=\"$namespace\", k8s_pod_name=~\"$pod\"}[$__rate_interval])) by (k8s_pod_name)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(k8s_pod_cpu_utilization_1{k8s_namespace_name=~\"$namespace\", k8s_pod_name=~\"$pod\"}) by (k8s_pod_name)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(k8s_pod_memory_usage_By{k8s_namespace_name=\"$namespace\", k8s_pod_name=~\"$pod\"}) by (k8s_pod_name)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_network_errors_1_total{k8s_namespace_name=\"$namespace\",k8s_pod_name=~\"$pod\"}[$__rate_interval])) by (k8s_pod_name,direction)",
     "legendFormat": "{{k8s_pod_name}} => {{direction}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_network_io_By_total{k8s_namespace_name=\"$namespace\", k8s_pod_name=~\"$pod\"}[$__rate_interval])) by (k8s_pod_name,direction)",
     "legendFormat": "{{k8s_pod_name}} => {{direction}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_filesystem_capacity_By{k8s_namespace_name=\"$namespace\", k8s_pod_name=~\"$pod\"}[$__rate_interval])) by (k8s_pod_name)",
     "legendFormat": "Capacity: {{k8s_pod_name}}"
    },
    {
     "expr": "sum(rate(k8s_pod_filesystem_available_By{k8s_namespace_name=\"$namespace\", k8s_pod_name=~\"$pod\"}[$__rate_interval])) by (k8s_pod_name)",
     "legendFormat": "Available: {{k8s_pod_name}}"
    },
    {
     "expr": "sum(rate(k8s_pod_filesystem_usage_By{k8s_namespace_name=\"$namespace\", k8s_pod_name=~\"$pod\"}[$__rate_interval])) by (k8s_pod_name)",
     "legendFormat": "Usage: {{k8s_pod_name}}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_cpu_time_total{k8s_node_name=~\"$node\"}[$__rate_interval])) by (k8s_node_name)",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(k8s_node_cpu_utilization_1{k8s_node_name=~\"$node\"}) by (k8s_node_name)",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(k8s_node_filesystem_usage_By{k8s_node_name=~\"$node\"}) by (k8s_node_name)",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_node_network_io_By_total{k8s_node_name=~\"$node\"}[$__rate_interval])) by (k8s_node_name)",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  }
 ]
}