{
 "title": "APM - RED",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service_name", "label": "Service Name", "query": { "query": "label_values(service_name)" } },
   { "name": "percentile", "label": "Latency Percentile", "query": "50, 75, 90, 95, 99" }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request (Throughput)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req/m" } },
   "targets": [
    {
     "expr": "sum(rate(calls_total_total{service_name=~\"$service_name\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "Error Request (Throughput)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req/m" } },
   "targets": [
    {
     "expr": "sum(rate(calls_total_total{service_name=~\"$service_name\",status_code=\"STATUS_CODE_ERROR\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "Total Request (Throughput)",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req/m" } },
   "targets": [
    {
     "expr": "60 * sum(rate(calls_total_total{}[1m])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(calls_total_total{service_name=~\"$service_name\",status_code=\"STATUS_CODE_ERROR\"}[1m])) / sum(rate(calls_total_total{service_name=~\"$service_name\"}[1m])))"
    }
   ]
  },
  {
   "title": "Duration (Latency) - p$percentile",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentile,\nsum(rate(latency_ms_bucket{service_name=~\"$service_name\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(calls_total_total{service_name=~\"$service_name\",status_code=\"STATUS_CODE_ERROR\"}[1m])) / sum(rate(calls_total_total{service_name=~\"$service_name\"}[1m])))",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Duration (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\nsum(rate(latency_ms_bucket{service_name=~\"$service_name\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95,\nsum(rate(latency_ms_bucket{service_name=~\"$service_name\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90,\nsum(rate(latency_ms_bucket{service_name=~\"$service_name\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50,\nsum(rate(latency_ms_bucket{service_name=~\"$service_name\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75,\nsum(rate(latency_ms_bucket{service_name=~\"$service_name\"}[1m])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Request (Throughput)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "calls_total_total{service_name=~\"$service_name\"}"
    }
   ]
  },
  { "title": "Service and Operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Req/m by Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "60 * sum(rate(calls_total_total{service_name=~\"$service_name\",operation!=\"\"}[1m])) by (service_name,operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Error Percentage by Operation",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(100 * (sum(calls_total_total{service_name=~\"$service_name\",operation!=\"\",status_code=\"STATUS_CODE_ERROR\"}) by (operation) / sum(calls_total_total{service_name=~\"$service_name\",operation!=\"\"}) by (operation))) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Duration (Latency) - p$percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentile,\nsum(rate(latency_ms_bucket{service_name=~\"$service_name\", operation!=\"\"}[1m])) by (le,operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Service, Operation and Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Total Request (Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "60 * sum(rate(calls_total_total{service_name=~\"$service_name\",operation!=\"\",status_code!=\"\"}[1m])) by (service_name,operation,status_code)",
     "legendFormat": "{{operation}}=>{{status_code}}"
    }
   ]
  },
  {
   "title": "Duration (Latency) - p$percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentile,\nsum(rate(latency_ms_bucket{service_name=~\"$service_name\", operation!=\"\"}[1m])) by (le,operation,status_code))",
     "legendFormat": "{{operation}}=>{{status_code}}"
    }
   ]
  }
 ]
}