{
 "title": "HS-Core log size distribution",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Log size per day per binder_id",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "widget_type_instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "query": "binder_id!=\"\"",
     "timeField": "coralogix.timestamp"
    }
   ]
  },
  {
   "title": "Log size per day per binder_id",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "binder_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "query": "binder_id!=\"\"",
     "timeField": "coralogix.timestamp"
    }
   ]
  },
  {
   "title": "binder vs other logs",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "page/space binder logs",
     "bucketAggs": [
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "query": "_exists_:binder_id",
     "timeField": "coralogix.timestamp"
    },
    {
     "alias": "other logs",
     "bucketAggs": [
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "query": "!(_exists_:binder_id) && !(_exists_:widget_type_instance)",
     "timeField": "coralogix.timestamp"
    },
    {
     "alias": "total",
     "bucketAggs": [
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "timeField": "coralogix.timestamp"
    },
    {
     "alias": "widget binder logs",
     "bucketAggs": [
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "query": "_exists_:widget_type_instance",
     "timeField": "coralogix.timestamp"
    }
   ]
  },
  {
   "title": "Logs per API",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "api_path.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "timeField": "coralogix.timestamp"
    }
   ]
  },
  {
   "title": "Top Error recurring logs",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "error.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "7" },
       "type": "terms"
      },
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "timeField": "coralogix.timestamp"
    }
   ]
  },
  {
   "title": "Log size per day per app ",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "coralogix.metadata.subsystemName",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "timeField": "coralogix.timestamp"
    }
   ]
  },
  {
   "title": "binder logs per api",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "api_path.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "query": "_exists_:binder_id",
     "timeField": "coralogix.timestamp"
    }
   ]
  },
  {
   "title": "non binder logs per api",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "api_path.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "coralogix.timestamp", "id": "3", "settings": { "interval": "1d", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "_size", "id": "1", "type": "sum" }
     ],
     "query": "!(_exists_:binder_id)",
     "timeField": "coralogix.timestamp"
    }
   ]
  }
 ]
}