{
 "title": "Gradle Enterprise K8s Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_cluster",
    "label": "source_cluster",
    "query": "prod-use1-cmd.k8s.hotstar-labs.com,hs-eks-cmd-prod-api-aps1"
   }
  ]
 },
 "panels": [
  { "title": "Health Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"productivity-engg\",  source_cluster=\"$source_cluster\",pod=~\"gradle-enterprise-app-.*\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Restarted Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace)(changes(kube_pod_status_ready{condition=\"true\",namespace=\"productivity-engg\", source_cluster=\"$source_cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pod Not Ready",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_status_ready{condition=\"false\",namespace=\"productivity-engg\",source_cluster=\"$source_cluster\",pod=~\"gradle-enterprise-app-.*\"})"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",namespace=\"productivity-engg\",source_cluster=\"$source_cluster\",pod=~\"gradle-enterprise-app-.*\"}[30m]) - on (namespace,pod,container) group_left avg by (namespace, pod, container)(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"productivity-engg\",source_cluster=\"$source_cluster\",pod=~\"gradle-enterprise-app-.*\"})) * -1 >0)",
     "legendFormat": "Memory-Idle"
    }
   ]
  },
  {
   "title": "CPU Usage (Request - 4, Max-N/A)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{source_cluster=\"$source_cluster\", namespace=\"productivity-engg\", pod=~\"gradle-enterprise-app-.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{container!=\"POD\",container!=\"\",namespace=\"productivity-engg\",source_cluster=\"$source_cluster\",pod=~\"gradle-enterprise-app-.*\"} - on (namespace,pod,container) avg by (namespace, pod, container)(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"productivity-engg\",source_cluster=\"$source_cluster\",pod=~\"gradle-enterprise-app-.*\"})) * -1 >0 ) / (1024*1024*1024)",
     "legendFormat": "Memory-Idle"
    }
   ]
  },
  {
   "title": "Average Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(container_memory_usage_bytes{source_cluster=\"$source_cluster\",namespace=\"productivity-engg\", pod=~\"gradle-enterprise-app-.*\",  container!=\"POD\", container!=\"\"}) by (pod)/sum(kube_pod_container_resource_requests_memory_bytes{source_cluster=\"$source_cluster\", namespace=\"productivity-engg\", pod=~\"gradle-enterprise-app-.*\",  container!=\"POD\", container!=\"\"}) by (pod)) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Max 20Gi)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{source_cluster=\"$source_cluster\", namespace=\"productivity-engg\", pod=~\"gradle-enterprise-app-.*\",  container!=\"POD\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}-(Total)"
    },
    {
     "expr": "sum(container_memory_rss{source_cluster=\"$source_cluster\", namespace=\"productivity-engg\", pod=~\"gradle-enterprise-app-.*\", container!=\"POD\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}-(RSS)"
    },
    {
     "expr": "sum(container_memory_cache{source_cluster=\"$source_cluster\", namespace=\"productivity-engg\", pod=~\"gradle-enterprise-app-.*\", container!=\"POD\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}-(cache)"
    },
    {
     "expr": "sum(container_memory_swap{source_cluster=\"$source_cluster\", namespace=\"productivity-engg\", pod=~\"gradle-enterprise-app-.*\", container!=\"POD\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}-(swap)"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"productivity-engg\", source_cluster=\"$source_cluster\", pod=~\"gradle-enterprise-app-.*\"}[5m])) by (name, pod)",
     "legendFormat": "Network Bytes Received-{{ pod }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"productivity-engg\", source_cluster=\"prod-use1-cmd.k8s.hotstar-labs.com\", pod=~\"gradle-enterprise-app-.*\"}[5m])) by (name, pod)",
     "legendFormat": "Network Bytes Transmitted-{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"productivity-engg\", source_cluster=\"$source_cluster\"}[5m])) by (container_name, device, pod)",
     "legendFormat": "Bytes Written-{{pod}}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"productivity-engg\", source_cluster=\"prod-use1-cmd.k8s.hotstar-labs.com\"}[5m])) by (container_name, device, pod)",
     "legendFormat": "Bytes Read-{{pod}}"
    }
   ]
  },
  {
   "title": "K8s Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes ready per cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}==1)"
      }
     ]
    }
   ]
  }
 ]
}